/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import Mathlib

#print "file: DkMath.CosmicFormula.ThreeElement.Basic"

/-!
# Three-element cosmic-formula algebra

This module separates the quadratic state attached to two base values `x` and
`u` into three exact terms:

* `coreTerm x = x^2`;
* `interactionBeam x u = 2*x*u`;
* `gapTerm u = u^2`.

The second coordinate named `beam` in CF2D is not the same object as
`interactionBeam`. The latter is the cross term generated by the two base
values.

The module is pure algebra. It contains no topology, limit theorem, RH-specific
assumption, complex phase, or trigonometric construction.
-/

namespace DkMath
namespace CosmicFormula
namespace ThreeElement

variable {R : Type*}

/-- The quadratic Core term `x^2`. -/
def coreTerm [Semiring R] (x : R) : R :=
  x ^ 2

/-- The interaction Beam, namely the quadratic cross term `2*x*u`. -/
def interactionBeam [Semiring R] (x u : R) : R :=
  2 * x * u

/-- The quadratic Gap term `u^2`. -/
def gapTerm [Semiring R] (u : R) : R :=
  u ^ 2

/-- The unsigned square mass `Core + Gap`. -/
def squareMass [Semiring R] (x u : R) : R :=
  coreTerm x + gapTerm u

/-- The plus observation whole `(x+u)^2`. -/
def plusWhole [Semiring R] (x u : R) : R :=
  (x + u) ^ 2

/-- The minus observation whole `(x-u)^2`. -/
def minusWhole [Ring R] (x u : R) : R :=
  (x - u) ^ 2

/-- The plus whole is the exact sum of Core, interaction Beam, and Gap. -/
theorem plusWhole_eq_core_add_beam_add_gap
    [CommSemiring R] (x u : R) :
    plusWhole x u =
      coreTerm x + interactionBeam x u + gapTerm u := by
  simp only [plusWhole, coreTerm, interactionBeam, gapTerm]
  ring

/-- The minus whole flips only the sign of the interaction Beam. -/
theorem minusWhole_eq_core_sub_beam_add_gap
    [CommRing R] (x u : R) :
    minusWhole x u =
      coreTerm x - interactionBeam x u + gapTerm u := by
  simp only [minusWhole, coreTerm, interactionBeam, gapTerm]
  ring

/-- Subtracting the two wholes extracts twice the interaction Beam. -/
theorem plusWhole_sub_minusWhole_eq_two_mul_interactionBeam
    [CommRing R] (x u : R) :
    plusWhole x u - minusWhole x u =
      2 * interactionBeam x u := by
  simp only [plusWhole, minusWhole, interactionBeam]
  ring

/-- Adding the two wholes extracts twice the unsigned square mass. -/
theorem plusWhole_add_minusWhole_eq_two_mul_squareMass
    [CommRing R] (x u : R) :
    plusWhole x u + minusWhole x u =
      2 * squareMass x u := by
  simp only [plusWhole, minusWhole, squareMass, coreTerm, gapTerm]
  ring

/-- Swapping the two base values preserves the unsigned square mass. -/
theorem squareMass_swap
    [CommSemiring R] (x u : R) :
    squareMass x u = squareMass u x := by
  simp only [squareMass, coreTerm, gapTerm]
  ring

/-- Swapping the two base values preserves the interaction Beam. -/
theorem interactionBeam_swap
    [CommSemiring R] (x u : R) :
    interactionBeam x u = interactionBeam u x := by
  simp only [interactionBeam]
  ring

/--
Core and Gap have the same polynomial form when supplied the same value.

This theorem does not identify their semantic roles or their states.
-/
theorem coreTerm_eq_gapTerm_same_input
    [Semiring R] (x : R) :
    coreTerm x = gapTerm x :=
  rfl

end ThreeElement
end CosmicFormula
end DkMath
