#!/usr/bin/env bash
set -euo pipefail

tts_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$tts_dir/../../../../../../" && pwd)"
kokoro="$project_root/venv/bin/kokoro-tts"
model="$tts_dir/models/kokoro-v1.0.onnx"
voices="$tts_dir/models/voices-v1.0.bin"
raw_dir="$tts_dir/output/raw"
timed_dir="$tts_dir/output/timed"
concat_file="$tts_dir/output/concat.txt"
timing_file="$tts_dir/output/timing.tsv"
combined_timed_wav="$tts_dir/output/dkmath-final-narration-timed.wav"
normalized_wav="$tts_dir/output/dkmath-final-narration-normalized.wav"

test -x "$kokoro"
test -f "$model"
test -f "$voices"

mkdir -p "$raw_dir" "$timed_dir"
printf 'cue\tstart\tend\ttarget_seconds\traw_seconds\tatempo\n' > "$timing_file"
printf '%s\n' '# generated by build_final_narration.sh' > "$concat_file"

while IFS='|' read -r cue start end text_file; do
  case "$cue" in
    ''|'#'*) continue ;;
  esac

  text_path="$tts_dir/$text_file"
  raw_wav="$raw_dir/cue_${cue}.wav"
  cue_timed_wav="$timed_dir/cue_${cue}.wav"
  target_seconds=$((end - start))

  "$kokoro" "$text_path" "$raw_wav" \
    --lang en-us \
    --voice af_sarah \
    --model "$model" \
    --voices "$voices"

  raw_seconds="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$raw_wav")"
  atempo="$(awk -v raw="$raw_seconds" -v target="$target_seconds" 'BEGIN {
    if (raw > target) printf "%.6f", raw / target; else print "1.000000"
  }')"

  ffmpeg -nostdin -y -v error -i "$raw_wav" \
    -filter:a "atempo=$atempo,apad=pad_dur=$target_seconds,atrim=duration=$target_seconds" \
    -ar 48000 -ac 1 -c:a pcm_s16le "$cue_timed_wav"

  printf "file '%s'\n" "$cue_timed_wav" >> "$concat_file"
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$cue" "$start" "$end" "$target_seconds" "$raw_seconds" "$atempo" >> "$timing_file"
done < "$tts_dir/cues.tsv"

ffmpeg -nostdin -y -v error -f concat -safe 0 -i "$concat_file" \
  -ar 48000 -ac 1 -c:a pcm_s16le "$combined_timed_wav"

ffmpeg -nostdin -y -v error -i "$combined_timed_wav" \
  -filter:a "loudnorm=I=-16:TP=-1.5:LRA=11" \
  -ar 48000 -ac 1 -c:a pcm_s16le "$normalized_wav"

ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1 \
  "$normalized_wav"
