/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.TraceOneDiscriminantAxis
import Mathlib.RingTheory.DedekindDomain.Basic

#print "file: DkMath.NumberTheory.TraceOneConjugateCoprime"

namespace DkMath.NumberTheory.TraceOneQuadratic

/-! ## Generic prime-axis and conjugate-coprime kernel -/

theorem discrAxis_ne_zero_of_packet
    (P : PrimeDiscriminantPacket p s) : discrAxis s ≠ 0 := by
  intro hzero
  have hnorm := P.natAbs_norm_discrAxis
  rw [hzero] at hnorm
  have hpzero : p = 0 := by
    simpa [norm] using hnorm.symm
  exact P.prime.ne_zero hpzero

/-- Under the domain hypothesis, the discriminant axis is a prime element.

The proof uses only the packet's norm-divisibility equivalence and norm
multiplicativity; it does not install a global domain instance for every
quadratic parameter. -/
theorem PrimeDiscriminantPacket.prime_discrAxis
    (P : PrimeDiscriminantPacket p s) [IsDomain (TraceOneInt s)] :
    Prime (discrAxis s) := by
  refine ⟨discrAxis_ne_zero_of_packet P, ?_, ?_⟩
  · intro hunit
    have haxis_one : discrAxis s ∣ (1 : TraceOneInt s) :=
      (isUnit_iff_dvd_one.mp hunit)
    have hp_one : p ∣ 1 := by
      simpa [norm] using
        (P.discrAxis_dvd_iff_prime_dvd_natAbs_norm (1 : TraceOneInt s)).mp
          haxis_one
    exact P.prime.not_dvd_one hp_one
  · intro x y hxy
    have hnorm : p ∣ Int.natAbs (norm (x * y)) :=
      (P.discrAxis_dvd_iff_prime_dvd_natAbs_norm (x * y)).mp hxy
    rw [traceOne_norm_mul, Int.natAbs_mul] at hnorm
    rcases P.prime.dvd_mul.mp hnorm with hx | hy
    · exact Or.inl (P.discrAxis_dvd_iff_prime_dvd_natAbs_norm x |>.mpr hx)
    · exact Or.inr (P.discrAxis_dvd_iff_prime_dvd_natAbs_norm y |>.mpr hy)

/-- The principal axis ideal is maximal in a one-dimensional domain. -/
theorem PrimeDiscriminantPacket.discrAxis_span_isMaximal
    (P : PrimeDiscriminantPacket p s) [IsDomain (TraceOneInt s)]
    [Ring.DimensionLEOne (TraceOneInt s)] :
    (Ideal.span ({discrAxis s} : Set (TraceOneInt s))).IsMaximal := by
  have hprime : Prime (discrAxis s) := P.prime_discrAxis
  have hspan_ne_bot :
      Ideal.span ({discrAxis s} : Set (TraceOneInt s)) ≠ ⊥ := by
    intro hbot
    have hmem : discrAxis s ∈ (⊥ : Ideal (TraceOneInt s)) := by
      rw [← hbot]
      exact Ideal.mem_span_singleton_self _
    exact discrAxis_ne_zero_of_packet P (by simpa using hmem)
  exact (Ideal.isPrime_span_singleton_of_prime hprime).isMaximal hspan_ne_bot

/-- Coordinate Bézout forces the discriminant axis into the sum of the two
principal ideals generated by an element and its conjugate. -/
theorem discrAxis_mem_span_sup_conj
    {w : TraceOneInt s} (hcoords : IsCoprime w.fst w.snd) :
    discrAxis s ∈
      Ideal.span ({w} : Set (TraceOneInt s)) ⊔
        Ideal.span ({conj w} : Set (TraceOneInt s)) := by
  let I : Ideal (TraceOneInt s) := Ideal.span ({w} : Set (TraceOneInt s))
  let J : Ideal (TraceOneInt s) := Ideal.span ({conj w} : Set (TraceOneInt s))
  change discrAxis s ∈ I ⊔ J
  have hw : w ∈ I ⊔ J := Ideal.mem_sup_left (Ideal.mem_span_singleton_self _)
  have hconj : conj w ∈ I ⊔ J :=
    Ideal.mem_sup_right (Ideal.mem_span_singleton_self _)
  have hdiff : w - conj w ∈ I ⊔ J := sub_mem hw hconj
  have hdsnd : (w.snd : TraceOneInt s) * discrAxis s ∈ I ⊔ J := by
    rw [← sub_conj_eq_snd_mul_discrAxis]
    exact hdiff
  have haxisw : discrAxis s * w ∈ I ⊔ J :=
    Ideal.mul_mem_left _ (discrAxis s) hw
  have hfst : (w.fst : TraceOneInt s) * discrAxis s ∈ I ⊔ J := by
    rw [← discrAxis_mul_sub_tau_mul_sub_conj]
    exact sub_mem haxisw (Ideal.mul_mem_left _ (tau s) hdiff)
  rcases hcoords with ⟨m, n, hbezout⟩
  have hcast : ((m * w.fst + n * w.snd : ℤ) : TraceOneInt s) = 1 := by
    rw [hbezout]
    norm_num
  have hcomb :
      (m : TraceOneInt s) * ((w.fst : TraceOneInt s) * discrAxis s) +
        (n : TraceOneInt s) * ((w.snd : TraceOneInt s) * discrAxis s) ∈ I ⊔ J :=
    add_mem (Ideal.mul_mem_left _ (m : TraceOneInt s) hfst)
      (Ideal.mul_mem_left _ (n : TraceOneInt s) hdsnd)
  have heq : discrAxis s =
      (m : TraceOneInt s) * ((w.fst : TraceOneInt s) * discrAxis s) +
        (n : TraceOneInt s) * ((w.snd : TraceOneInt s) * discrAxis s) := by
    calc
      discrAxis s = ((m * w.fst + n * w.snd : ℤ) : TraceOneInt s) *
          discrAxis s := by rw [hcast, one_mul]
      _ = (m : TraceOneInt s) * ((w.fst : TraceOneInt s) * discrAxis s) +
          (n : TraceOneInt s) * ((w.snd : TraceOneInt s) * discrAxis s) := by
        push_cast
        ring
  exact heq ▸ hcomb

/-- The TraceOne conjugate pair is ideal-coprime once the coordinate pair is
coprime and the discriminant axis is terminal for the element. -/
theorem ideal_isCoprime_span_conj_of_coordinate_coprime_of_axis_terminal
    (P : PrimeDiscriminantPacket p s) [IsDomain (TraceOneInt s)]
    [Ring.DimensionLEOne (TraceOneInt s)]
    {w : TraceOneInt s} (hcoords : IsCoprime w.fst w.snd)
    (hterminal : ¬ discrAxis s ∣ w) :
    IsCoprime (Ideal.span ({w} : Set (TraceOneInt s)))
      (Ideal.span ({conj w} : Set (TraceOneInt s))) := by
  rw [Ideal.isCoprime_iff_sup_eq]
  by_contra hne
  have haxis_le :
      Ideal.span ({discrAxis s} : Set (TraceOneInt s)) ≤
        Ideal.span ({w} : Set (TraceOneInt s)) ⊔
          Ideal.span ({conj w} : Set (TraceOneInt s)) := by
    rw [Ideal.span_le]
    intro x hx
    simp only [Set.mem_singleton_iff] at hx
    subst x
    exact discrAxis_mem_span_sup_conj hcoords
  have heq :
      Ideal.span ({discrAxis s} : Set (TraceOneInt s)) =
        Ideal.span ({w} : Set (TraceOneInt s)) ⊔
          Ideal.span ({conj w} : Set (TraceOneInt s)) :=
    P.discrAxis_span_isMaximal.eq_of_le hne haxis_le
  have hw : w ∈ Ideal.span ({discrAxis s} : Set (TraceOneInt s)) := by
    rw [heq]
    exact Ideal.mem_sup_left (Ideal.mem_span_singleton_self _)
  exact hterminal (Ideal.mem_span_singleton.mp hw)

/-- A one-layer axis strip for a norm of the form `p * c^p`.

This is the exponent-independent normalization endpoint used by the later
Phase-1/13 bridge.  The theorem deliberately takes the norm equality as an
input; it does not assert that a cyclotomic coordinate realization exists. -/
theorem PrimeDiscriminantPacket.exists_terminal_discrAxis_mul_of_natAbs_norm_eq_prime_mul_pow
    (P : PrimeDiscriminantPacket p s) {x : TraceOneInt s}
    (hx : norm x ≠ 0) {c : ℕ}
    (hNorm : Int.natAbs (norm x) = p * c ^ p)
    (hc : ¬ p ∣ c) :
    ∃ y : TraceOneInt s,
      x = discrAxis s * y ∧
      norm y ≠ 0 ∧
      ¬ discrAxis s ∣ y ∧
      ∃ k : ℤ, norm y = k ^ p := by
  have haxis : discrAxis s ∣ x := by
    apply (P.discrAxis_dvd_iff_prime_dvd_natAbs_norm x).mpr
    exact ⟨c ^ p, hNorm⟩
  have hnotAxisSq : ¬ discrAxis s ^ 2 ∣ x := by
    intro hsq
    have hpSq : p ^ 2 ∣ Int.natAbs (norm x) :=
      (P.discrAxis_pow_dvd_iff_pow_prime_dvd_natAbs_norm 2 x).mp hsq
    rcases hpSq with ⟨k, hk⟩
    have hEq : p * c ^ p = p * (p * k) := by
      calc
        p * c ^ p = Int.natAbs (norm x) := hNorm.symm
        _ = p ^ 2 * k := hk
        _ = p * (p * k) := by ring
    have hcPow : c ^ p = p * k :=
      Nat.eq_of_mul_eq_mul_left P.prime.pos hEq
    exact hc (P.prime.dvd_of_dvd_pow ⟨k, hcPow⟩)
  have hdepth : discrAxisDepth p x = 1 := by
    have haxis1 : discrAxis s ^ 1 ∣ x := by simpa using haxis
    have hle : 1 ≤ discrAxisDepth p x :=
      (P.discrAxis_pow_dvd_iff_le_depth hx 1).mp haxis1
    have hnot : ¬ 2 ≤ discrAxisDepth p x := by
      intro hle2
      apply hnotAxisSq
      exact (P.discrAxis_pow_dvd_iff_le_depth hx 2).mpr hle2
    omega
  rcases P.exists_terminal_discrAxis_core hx with
    ⟨y, hxy, hyNorm, hyAxis, _hyPrime, hNormCore, _hyOne⟩
  have hxy' : x = discrAxis s * y := by
    simpa [hdepth] using hxy
  have hyAbs : Int.natAbs (norm y) = c ^ p := by
    have hEq : p * c ^ p = p * Int.natAbs (norm y) := by
      calc
        p * c ^ p = Int.natAbs (norm x) := hNorm.symm
        _ = p ^ discrAxisDepth p x * Int.natAbs (norm y) := hNormCore
        _ = p * Int.natAbs (norm y) := by rw [hdepth]; simp
    exact Nat.eq_of_mul_eq_mul_left P.prime.pos hEq.symm
  have hpOdd : Odd p := by
    exact P.prime.odd_of_ne_two P.prime_ne_two
  have hpow : ∃ k : ℤ, norm y = k ^ p := by
    rcases Int.natAbs_eq (norm y) with hpos | hneg
    · refine ⟨(c : ℤ), ?_⟩
      rw [hpos, hyAbs]
      norm_cast
    · refine ⟨-(c : ℤ), ?_⟩
      rw [hneg, hyAbs, hpOdd.neg_pow]
      norm_cast
  exact ⟨y, hxy', hyNorm, hyAxis, hpow⟩

/-! ## Coordinate primitivity under one axis strip -/

/-- A single discriminant-axis multiplication cannot create a common integer
divisor in the coordinates. -/
theorem coordinate_isCoprime_of_eq_discrAxis_mul
    {s : ℤ} {x y : TraceOneInt s}
    (hxy : x = discrAxis s * y)
    (hx : IsCoprime x.fst x.snd) :
    IsCoprime y.fst y.snd := by
  rcases hx with ⟨m, n, hbezout⟩
  refine ⟨-m + 2 * n, 2 * s * m + n, ?_⟩
  rw [hxy, discrAxis_eq] at hbezout
  simp only [TraceOneQuadratic.fst_mul, TraceOneQuadratic.snd_mul] at hbezout
  linear_combination hbezout

end DkMath.NumberTheory.TraceOneQuadratic
