/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
-/

import DkMath.NumberTheory.TraceOneQuadratic
import Mathlib.RingTheory.Ideal.Operations

#print "file: DkMath.NumberTheory.TraceOneIdealPower"

namespace DkMath.NumberTheory.TraceOneQuadratic

/-! ## Principal ideals attached to a norm power -/

/-- The conjugate principal-ideal product of a TraceOne element is the
principal ideal generated by its norm. -/
theorem span_mul_span_conj_eq_span_norm
    {s : ℤ} {r : TraceOneInt s} :
    Ideal.span ({r} : Set (TraceOneInt s)) *
        Ideal.span ({conj r} : Set (TraceOneInt s)) =
      Ideal.span ({(norm r : TraceOneInt s)} : Set (TraceOneInt s)) := by
  rw [Ideal.span_singleton_mul_span_singleton]
  rw [traceOne_mul_conj]
  rfl

/-- A norm `p`-th power gives the principal-ideal product required by the
coprime ideal-power extraction theorem. -/
theorem span_mul_span_conj_eq_pow_of_norm_eq_pow
    {s : ℤ} {r : TraceOneInt s} {k : ℤ} {p : ℕ}
    (hNorm : norm r = k ^ p) :
    Ideal.span ({r} : Set (TraceOneInt s)) *
        Ideal.span ({conj r} : Set (TraceOneInt s)) =
      (Ideal.span ({(k : TraceOneInt s)} : Set (TraceOneInt s))) ^ p := by
  rw [span_mul_span_conj_eq_span_norm, hNorm]
  rw [show ((k ^ p : ℤ) : TraceOneInt s) =
      (k : TraceOneInt s) ^ p by norm_num]
  rw [Ideal.span_singleton_pow]

end DkMath.NumberTheory.TraceOneQuadratic
