/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreAdaptiveClassification

#print "file: DkMathTest.NumberTheory.LegendreAdaptiveCertificateAxiomAudit"

#check DkMath.NumberTheory.exists_pos_modEq_le_period
#print axioms DkMath.NumberTheory.exists_pos_modEq_le_period
#check DkMath.NumberTheory.exists_pos_modEq_le_window
#print axioms DkMath.NumberTheory.exists_pos_modEq_le_window
#check DkMath.NumberTheory.modEq_add_complement_zero
#print axioms DkMath.NumberTheory.modEq_add_complement_zero
#check DkMath.NumberTheory.exists_parity_offset_le_two_mul_period
#print axioms DkMath.NumberTheory.exists_parity_offset_le_two_mul_period
#check DkMath.NumberTheory.Legendre.activeSupport_contains_of_point_modEq
#print axioms DkMath.NumberTheory.Legendre.activeSupport_contains_of_point_modEq
#check DkMath.NumberTheory.Legendre.activeSupport_contains_of_product_dvd
#print axioms DkMath.NumberTheory.Legendre.activeSupport_contains_of_product_dvd
#check DkMath.NumberTheory.Legendre.local_excess_ge_of_point_modEq
#print axioms DkMath.NumberTheory.Legendre.local_excess_ge_of_point_modEq
#check DkMath.NumberTheory.Legendre.candidate_of_window_coprime_odd
#print axioms DkMath.NumberTheory.Legendre.candidate_of_window_coprime_odd
#check DkMath.NumberTheory.Legendre.exists_windowed_odd_support_of_product_le
#print axioms DkMath.NumberTheory.Legendre.exists_windowed_odd_support_of_product_le
#check DkMath.NumberTheory.Legendre.coprime_prime_anchor_of_strict_window_odd
#print axioms DkMath.NumberTheory.Legendre.coprime_prime_anchor_of_strict_window_odd
#check DkMath.NumberTheory.Legendre.exists_candidate_support_of_prime_product_lt
#print axioms DkMath.NumberTheory.Legendre.exists_candidate_support_of_prime_product_lt
#check DkMath.NumberTheory.Legendre.witness_charge_le_supportExcess_of_prime_product_lt
#print axioms DkMath.NumberTheory.Legendre.witness_charge_le_supportExcess_of_prime_product_lt
#check DkMath.NumberTheory.Legendre.supportExcess_ge_two_of_prime_gt_105
#print axioms DkMath.NumberTheory.Legendre.supportExcess_ge_two_of_prime_gt_105
#check DkMath.NumberTheory.Legendre.seat_ne_of_distinct_modEq_classes
#print axioms DkMath.NumberTheory.Legendre.seat_ne_of_distinct_modEq_classes
#check DkMath.NumberTheory.Legendre.sum_indexed_modEq_charge_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.sum_indexed_modEq_charge_le_supportExcess
#check DkMath.NumberTheory.Legendre.uncovered_nonempty_of_indexed_modEq_certificates
#print axioms DkMath.NumberTheory.Legendre.uncovered_nonempty_of_indexed_modEq_certificates
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_indexed_modEq_certificates
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_indexed_modEq_certificates
#check DkMath.NumberTheory.Legendre.prime_anchor_period_family_charge_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.prime_anchor_period_family_charge_le_supportExcess
#check DkMath.NumberTheory.Legendre.prime_squareCell_of_prime_period_family_gap
#print axioms DkMath.NumberTheory.Legendre.prime_squareCell_of_prime_period_family_gap
#check DkMathTest.LegendreAdaptiveCertificate.shell41Seats
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41Seats
#check DkMathTest.LegendreAdaptiveCertificate.shell41Witness
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41Witness
#check DkMathTest.LegendreAdaptiveCertificate.shell91Seats
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91Seats
#check DkMathTest.LegendreAdaptiveCertificate.shell91Witness
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91Witness
#check DkMathTest.LegendreAdaptiveCertificate.shell41_candidate_seats
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_candidate_seats
#check DkMathTest.LegendreAdaptiveCertificate.shell41_support_witnesses
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_support_witnesses
#check DkMathTest.LegendreAdaptiveCertificate.shell41_witness_charge
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_witness_charge
#check DkMathTest.LegendreAdaptiveCertificate.shell41_supportExcess_ge_six
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_supportExcess_ge_six
#check DkMathTest.LegendreAdaptiveCertificate.shell41_cap_and_candidate
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_cap_and_candidate
#check DkMathTest.LegendreAdaptiveCertificate.shell41_uncovered_ge_two
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_uncovered_ge_two
#check DkMathTest.LegendreAdaptiveCertificate.shell41_uncovered_nonempty
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_uncovered_nonempty
#check DkMathTest.LegendreAdaptiveCertificate.shell41_prime
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell41_prime
#check DkMathTest.LegendreAdaptiveCertificate.shell91_candidate_seats
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_candidate_seats
#check DkMathTest.LegendreAdaptiveCertificate.shell91_support_witnesses
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_support_witnesses
#check DkMathTest.LegendreAdaptiveCertificate.shell91_witness_charge
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_witness_charge
#check DkMathTest.LegendreAdaptiveCertificate.shell91_supportExcess_ge_six
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_supportExcess_ge_six
#check DkMathTest.LegendreAdaptiveCertificate.shell91_cap_and_candidate
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_cap_and_candidate
#check DkMathTest.LegendreAdaptiveCertificate.shell91_uncovered_ge_two
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_uncovered_ge_two
#check DkMathTest.LegendreAdaptiveCertificate.shell91_uncovered_nonempty
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_uncovered_nonempty
#check DkMathTest.LegendreAdaptiveCertificate.shell91_prime
#print axioms DkMathTest.LegendreAdaptiveCertificate.shell91_prime
#check DkMathTest.LegendreCRTSeat.zero_residue_positive_endpoint
#print axioms DkMathTest.LegendreCRTSeat.zero_residue_positive_endpoint
#check DkMathTest.LegendreCRTSeat.raw_period_does_not_guarantee_parity
#print axioms DkMathTest.LegendreCRTSeat.raw_period_does_not_guarantee_parity
#check DkMathTest.LegendreCRTSeat.parity_period_does_not_guarantee_candidate
#print axioms DkMathTest.LegendreCRTSeat.parity_period_does_not_guarantee_candidate
#check DkMathTest.LegendreCRTSeat.distinct_witness_sets_do_not_separate_seats
#print axioms DkMathTest.LegendreCRTSeat.distinct_witness_sets_do_not_separate_seats
#check DkMathTest.LegendreCRTSeat.prime107_short_period_candidate
#print axioms DkMathTest.LegendreCRTSeat.prime107_short_period_candidate
#check DkMathTest.LegendreCRTSeat.prime107_structural_charge
#print axioms DkMathTest.LegendreCRTSeat.prime107_structural_charge
#check DkMathTest.LegendreCRTSeat.prime211_period_lift_seats
#print axioms DkMathTest.LegendreCRTSeat.prime211_period_lift_seats
#check DkMathTest.LegendreCRTSeat.prime211_structural_family_charge
#print axioms DkMathTest.LegendreCRTSeat.prime211_structural_family_charge
#check DkMathTest.LegendreCRTSeat.prime107_provider_needs_more_charge
#print axioms DkMathTest.LegendreCRTSeat.prime107_provider_needs_more_charge
#check DkMathTest.LegendreCRTSeat.shell41_indexed_CRT_prime
#print axioms DkMathTest.LegendreCRTSeat.shell41_indexed_CRT_prime
#check DkMathTest.LegendreAdaptiveClassification.diagnosticData
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnosticData
#check DkMathTest.LegendreAdaptiveClassification.diagnosticWitnessData
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnosticWitnessData
#check DkMathTest.LegendreAdaptiveClassification.solvedUpToFive
#print axioms DkMathTest.LegendreAdaptiveClassification.solvedUpToFive
#check DkMathTest.LegendreAdaptiveClassification.solvedAtSix
#print axioms DkMathTest.LegendreAdaptiveClassification.solvedAtSix
#check DkMathTest.LegendreAdaptiveClassification.unresolvedShells
#print axioms DkMathTest.LegendreAdaptiveClassification.unresolvedShells
#check DkMathTest.LegendreAdaptiveClassification.diagnosticSeats
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnosticSeats
#check DkMathTest.LegendreAdaptiveClassification.diagnosticWitness
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnosticWitness
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_partition_checked
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_partition_checked
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_certificates_checked
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_certificates_checked
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_caps_match_prior
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_caps_match_prior
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_charge_le_excess
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_charge_le_excess
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_success_condition_checked
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_success_condition_checked
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_solved_uncovered
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_solved_uncovered
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_solved_prime
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_solved_prime
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_survivor_budget_obstruction
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_survivor_budget_obstruction
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_survivor_charge_ge_six
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_survivor_charge_ge_six
#check DkMathTest.LegendreAdaptiveClassification.diagnostic_survivors_have_few_odd_anchor_factors
#print axioms DkMathTest.LegendreAdaptiveClassification.diagnostic_survivors_have_few_odd_anchor_factors
