/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre

#print "file: DkMathTest.NumberTheory.LegendreBlockLocalizationInventory"

open DkMath.NumberTheory.Legendre

#check paritySafeSupportExcess
#check paritySafePrimePairOverlapCount
#check paritySafePairOverlapOutsideDepthCollision
#check paritySafeDepthCollisionPairOverlapMass
#check paritySafeDepthCollisionLocalSupportCost
#check paritySafeRechargeExactDepthFiberCollisionSeats
#check paritySafeRechargeExactDepthFiveDirectionCollisionSeats
#check paritySafeLowCostResidualCapacity
#check paritySafeRechargeExactDepthResidualPairCapacityExcess
#check lowerParitySafeFreshSupport
#check lowerFreshSupportExcessChargeCount
#check lowerParitySafeFreshPairs
#check paritySafePrimePairOverlapCount_eq_supportExcess_add_residual
#check paritySafeSupportExcess_eq_outsideCollision_add_collisionSupportCost
#check paritySafePairOverlapOutsideDepthCollision_eq_outsideSupport_add_outsideResidual
#check paritySafePrimePairOverlapCount_eq_outsideCollision_add_collisionMass
#check paritySafeDepthCollisionPairOverlapMass_eq_supportCost_add_collision_add_depthResidualCapacity
#check three_mul_collision_add_fiveDirection_card_le_depthCollisionLocalSupportCost
#check paritySafeSecondCancellationFrontier_iff_reducedSupportCharge
#check paritySafeFullCoverSecondCancellationFrontier_iff_reducedSupportCharge
#check paritySafeLowCostResidualCapacity_eq_mass_add_slack
#check paritySafeCandidate_card_add_supportExcess_eq_incidence_of_fullyCovered
#check sum_lowerCandidates_sub_parityCap_sub_firstSlots_le_excess
#check sum_fullCandidate_add_freshChargeBound_le_incidence
#check not_squareOffsetsFullyCovered_iff_escaping_nonempty
#check prime_of_squareAnchoredSupportEscape
#check squareCell_iff_exists_squareOffset
