import DkMath.NumberTheory.Legendre
import DkMath.NumberTheory.GapFocusing.HomogeneousAddress
import DkMath.NumberTheory.GapFocusing.CyclotomicBoundary
open DkMath.NumberTheory.Legendre DkMath.NumberTheory.GapFocusing
#check mem_reindexed_primeSupport_inter_lower_iff
#check reindexed_primeSupport_inter_lower_eq_filter
#check mem_reindexed_primeSupport_inter_upper_imp_eq_two
#check paritySafeIncidenceCount_eq_candidate_support_sum
#check paritySafeCandidate_card_add_supportExcess_eq_incidence_of_fullyCovered
#check two_mul_pairOverlap_add_threeCollision_add_threeCandidate_le_fullCoverCapacity
#check paritySafeLowCostResidualCapacity_eq_mass_add_slack
#check paritySafeFullCoverRequiredLowCostSlack_le_two_capacitySlack
#check paritySafePrimePairOverlapCount_eq_outsideCollision_add_collisionMass
#check two_mul_outsideCollisionPairOverlap_add_nineCollision_add_threeFiveDirection_add_twoResidualSlack_add_threeCandidate_le_fullCoverActualMass
#check legendreConjecture_iff_squareOffsets_not_fully_covered
#check dvd_cyclotomicShiftedEval_iff_primeOrder_eq_of_not_dvd
#check DkMath.CFBRC.cyclotomicShiftedEval

#check mem_reindexed_primeSupport_inter_lower_petalMul_iff
#check common_lower_dvd_gnomonPetalTransition_numerator_of_not_dvd_first
#check paritySafeSupportExcess
#check paritySafePrimePairOverlapCount
#check paritySafeLowCostResidualCapacity
#check paritySafeRechargeExactDepthResidualPairCapacityExcess
#check isRoot_cyclotomic_iff_prime_pow_mul_orderOf
#check dvd_cyclotomicShiftedEval_iff_dvd_first_of_dvd_second
#check primeOrder
#check primeRatio
