/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreRetained297Calibration
import DkMathTest.NumberTheory.LegendreRetained1031Calibration
import DkMathTest.NumberTheory.LegendreHandoffRegression

#print "file: DkMathTest.NumberTheory.LegendreRetainedAxiomAudit"

#check DkMath.Combinatorics.supportedSeats
#print axioms DkMath.Combinatorics.supportedSeats
#check DkMath.Combinatorics.representedDirections
#print axioms DkMath.Combinatorics.representedDirections
#check DkMath.Combinatorics.retainedExcess
#print axioms DkMath.Combinatorics.retainedExcess
#check DkMath.Combinatorics.emptySupportSeats
#print axioms DkMath.Combinatorics.emptySupportSeats
#check DkMath.Combinatorics.emptySupportSeats_union_supported
#print axioms DkMath.Combinatorics.emptySupportSeats_union_supported
#check DkMath.Combinatorics.disjoint_emptySupportSeats_supported
#print axioms DkMath.Combinatorics.disjoint_emptySupportSeats_supported
#check DkMath.Combinatorics.card_support_split
#print axioms DkMath.Combinatorics.card_support_split
#check DkMath.Combinatorics.card_support_sum
#print axioms DkMath.Combinatorics.card_support_sum
#check DkMath.Combinatorics.card_representedDirections
#print axioms DkMath.Combinatorics.card_representedDirections
#check DkMath.Combinatorics.representedDirections_unique
#print axioms DkMath.Combinatorics.representedDirections_unique
#check DkMath.Combinatorics.card_nonmaximum_add_indicator
#print axioms DkMath.Combinatorics.card_nonmaximum_add_indicator
#check DkMath.Combinatorics.sum_witness_cards
#print axioms DkMath.Combinatorics.sum_witness_cards
#check DkMath.Combinatorics.mem_supportPackingRemainder_iff_maxima
#print axioms DkMath.Combinatorics.mem_supportPackingRemainder_iff_maxima
#check DkMath.Combinatorics.mem_supportPackingRightRemainder_iff_minima
#print axioms DkMath.Combinatorics.mem_supportPackingRightRemainder_iff_minima
#check DkMath.NumberTheory.Legendre.coarseTownRetainedSupportedSeats
#print axioms DkMath.NumberTheory.Legendre.coarseTownRetainedSupportedSeats
#check DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes
#print axioms DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes
#check DkMath.NumberTheory.Legendre.coarseTownUnrepresentedActivePrimes
#print axioms DkMath.NumberTheory.Legendre.coarseTownUnrepresentedActivePrimes
#check DkMath.NumberTheory.Legendre.coarseTownRetainedSupportExcess
#print axioms DkMath.NumberTheory.Legendre.coarseTownRetainedSupportExcess
#check DkMath.NumberTheory.Legendre.mem_coarseTownRetainedSupportedSeats
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownRetainedSupportedSeats
#check DkMath.NumberTheory.Legendre.coarseTown_retained_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_retained_partition
#check DkMath.NumberTheory.Legendre.coarseTown_card_retained_split
#print axioms DkMath.NumberTheory.Legendre.coarseTown_card_retained_split
#check DkMath.NumberTheory.Legendre.coarseTown_represented_subset_active
#print axioms DkMath.NumberTheory.Legendre.coarseTown_represented_subset_active
#check DkMath.NumberTheory.Legendre.coarseTown_retained_loss_decomposition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_retained_loss_decomposition
#check DkMath.NumberTheory.Legendre.coarseTownFiberMaximumAt
#print axioms DkMath.NumberTheory.Legendre.coarseTownFiberMaximumAt
#check DkMath.NumberTheory.Legendre.coarseTownFiberMinimumAt
#print axioms DkMath.NumberTheory.Legendre.coarseTownFiberMinimumAt
#check DkMath.NumberTheory.Legendre.mem_coarseTownPackingRemainder_iff_maxima
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownPackingRemainder_iff_maxima
#check DkMath.NumberTheory.Legendre.mem_coarseTownRightPackingRemainder_iff_minima
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownRightPackingRemainder_iff_minima
#check DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats_subset_remainder
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats_subset_remainder
#check DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats_subset_rightRemainder
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats_subset_rightRemainder
#check DkMath.NumberTheory.Legendre.coarseTown_remainder_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_remainder_partition
#check DkMath.NumberTheory.Legendre.coarseTown_remainder_card_split
#print axioms DkMath.NumberTheory.Legendre.coarseTown_remainder_card_split
#check DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes_subset_active
#print axioms DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes_subset_active
#check DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes_subset_outside
#print axioms DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes_subset_outside
#check DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes_unique
#print axioms DkMath.NumberTheory.Legendre.coarseTownRepresentedPrimes_unique
#check DkMath.NumberTheory.Legendre.coarseTown_active_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_active_partition
#check DkMath.NumberTheory.Legendre.coarseTown_active_partition_disjoint
#print axioms DkMath.NumberTheory.Legendre.coarseTown_active_partition_disjoint
#check DkMath.NumberTheory.Legendre.coarseTown_active_card_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_active_card_partition
#check DkMath.NumberTheory.Legendre.coarseTown_represented_card_split
#print axioms DkMath.NumberTheory.Legendre.coarseTown_represented_card_split
#check DkMath.NumberTheory.Legendre.coarseTown_loss_decomposition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_loss_decomposition
#check DkMath.NumberTheory.Legendre.mem_coarseTownRightPackingRemainder
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownRightPackingRemainder
#check DkMath.NumberTheory.Legendre.coarseTownNonminimumFiberSeats
#print axioms DkMath.NumberTheory.Legendre.coarseTownNonminimumFiberSeats
#check DkMath.NumberTheory.Legendre.mem_coarseTownNonminimumFiberSeats
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownNonminimumFiberSeats
#check DkMath.NumberTheory.Legendre.card_coarseTownNonminimumFiberSeats_add_indicator
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownNonminimumFiberSeats_add_indicator
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionWitnessPrimes
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionWitnessPrimes
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionMultiplicity
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionMultiplicity
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionOverlap
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionOverlap
#check DkMath.NumberTheory.Legendre.coarseTownRightSupportLoss
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightSupportLoss
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionWitnessPrimes_subset_support
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionWitnessPrimes_subset_support
#check DkMath.NumberTheory.Legendre.mem_coarseTownRightDeletionVertices_iff_multiplicity_pos
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownRightDeletionVertices_iff_multiplicity_pos
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass_eq_nonminimum_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass_eq_nonminimum_sum
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass_eq_left
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass_eq_left
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass_add_active_eq_incidence
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionMass_add_active_eq_incidence
#check DkMath.NumberTheory.Legendre.card_rightDeletion_add_overlap_eq_mass
#print axioms DkMath.NumberTheory.Legendre.card_rightDeletion_add_overlap_eq_mass
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionOverlap_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionOverlap_le_supportExcess
#check DkMath.NumberTheory.Legendre.coarseTownRight_remainder_conservation
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_remainder_conservation
#check DkMath.NumberTheory.Legendre.coarseTownRight_remainder_add_loss
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_remainder_add_loss
#check DkMath.NumberTheory.Legendre.coarseTownRightRetainedSupportedSeats
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightRetainedSupportedSeats
#check DkMath.NumberTheory.Legendre.coarseTownRightRepresentedPrimes
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightRepresentedPrimes
#check DkMath.NumberTheory.Legendre.coarseTownRightUnrepresentedActivePrimes
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightUnrepresentedActivePrimes
#check DkMath.NumberTheory.Legendre.coarseTownRightRetainedSupportExcess
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightRetainedSupportExcess
#check DkMath.NumberTheory.Legendre.mem_coarseTownRightRetainedSupportedSeats
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownRightRetainedSupportedSeats
#check DkMath.NumberTheory.Legendre.coarseTownRightRepresentedPrimes_subset_active
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightRepresentedPrimes_subset_active
#check DkMath.NumberTheory.Legendre.coarseTownRightRepresentedPrimes_unique
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightRepresentedPrimes_unique
#check DkMath.NumberTheory.Legendre.coarseTownRight_remainder_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_remainder_partition
#check DkMath.NumberTheory.Legendre.coarseTownRight_remainder_card_split
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_remainder_card_split
#check DkMath.NumberTheory.Legendre.coarseTownRight_active_card_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_active_card_partition
#check DkMath.NumberTheory.Legendre.coarseTownRight_represented_card_split
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_represented_card_split
#check DkMath.NumberTheory.Legendre.coarseTownRight_loss_decomposition
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_loss_decomposition
#check DkMath.NumberTheory.Legendre.coarseTown_orientation_loss_identity
#print axioms DkMath.NumberTheory.Legendre.coarseTown_orientation_loss_identity
#check DkMath.NumberTheory.Legendre.coarseTown_orientation_overlap_identity
#print axioms DkMath.NumberTheory.Legendre.coarseTown_orientation_overlap_identity
#check DkMath.NumberTheory.Legendre.coarseTownBetterRemainder
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetterRemainder
#check DkMath.NumberTheory.Legendre.coarseTownBetterLoss
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetterLoss
#check DkMath.NumberTheory.Legendre.coarseTownBetterRemainder_subset
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetterRemainder_subset
#check DkMath.NumberTheory.Legendre.coarseTownBetterRemainder_family
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetterRemainder_family
#check DkMath.NumberTheory.Legendre.card_coarseTownBetterRemainder
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownBetterRemainder
#check DkMath.NumberTheory.Legendre.coarseTownBetter_remainder_add_loss
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetter_remainder_add_loss
#check DkMath.NumberTheory.Legendre.card_coarseTownBetterRemainder_le_outside_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownBetterRemainder_le_outside_of_fullyCovered
#check DkMath.NumberTheory.Legendre.coarseTownBetter_deficit_iff_loss_frontier
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetter_deficit_iff_loss_frontier
#check DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTownBetter_deficit
#print axioms DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTownBetter_deficit
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTownBetter_deficit
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTownBetter_deficit
#check DkMath.NumberTheory.Legendre.coarseTownBetterLoss_eq_min
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetterLoss_eq_min
#check DkMath.NumberTheory.Legendre.coarseTownRight_active_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_active_partition
#check DkMath.NumberTheory.Legendre.coarseTownRight_active_partition_disjoint
#print axioms DkMath.NumberTheory.Legendre.coarseTownRight_active_partition_disjoint
#check DkMath.NumberTheory.Legendre.coarseTownFiberMaximumAt_eq_max'
#print axioms DkMath.NumberTheory.Legendre.coarseTownFiberMaximumAt_eq_max'
#check DkMath.NumberTheory.Legendre.existsUnique_coarseTownFiberMaximumAt
#print axioms DkMath.NumberTheory.Legendre.existsUnique_coarseTownFiberMaximumAt
#check DkMath.NumberTheory.Legendre.coarseTownMax_represented_iff_retained
#print axioms DkMath.NumberTheory.Legendre.coarseTownMax_represented_iff_retained
#check DkMath.NumberTheory.Legendre.coarseTownMax_unrepresented_iff_deleted
#print axioms DkMath.NumberTheory.Legendre.coarseTownMax_unrepresented_iff_deleted
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_active
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_active
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_rank
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_rank
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_ne
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_ne
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_no_two_cycle
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_no_two_cycle
#check DkMath.NumberTheory.Legendre.coarseTownMax_unrepresented_iff_outgoing
#print axioms DkMath.NumberTheory.Legendre.coarseTownMax_unrepresented_iff_outgoing
#check DkMath.NumberTheory.Legendre.coarseTownMax_represented_iff_terminal
#print axioms DkMath.NumberTheory.Legendre.coarseTownMax_represented_iff_terminal
#check DkMath.NumberTheory.Legendre.coarseTownFiberMinimumAt_eq_min'
#print axioms DkMath.NumberTheory.Legendre.coarseTownFiberMinimumAt_eq_min'
#check DkMath.NumberTheory.Legendre.existsUnique_coarseTownFiberMinimumAt
#print axioms DkMath.NumberTheory.Legendre.existsUnique_coarseTownFiberMinimumAt
#check DkMath.NumberTheory.Legendre.coarseTownMin_represented_iff_retained
#print axioms DkMath.NumberTheory.Legendre.coarseTownMin_represented_iff_retained
#check DkMath.NumberTheory.Legendre.coarseTownMin_unrepresented_iff_deleted
#print axioms DkMath.NumberTheory.Legendre.coarseTownMin_unrepresented_iff_deleted
#check DkMath.NumberTheory.Legendre.coarseTownMinHandoff
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinHandoff
#check DkMath.NumberTheory.Legendre.coarseTownMinHandoff_active
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinHandoff_active
#check DkMath.NumberTheory.Legendre.coarseTownMinHandoff_rank
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinHandoff_rank
#check DkMath.NumberTheory.Legendre.coarseTownMinHandoff_ne
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinHandoff_ne
#check DkMath.NumberTheory.Legendre.coarseTownMinHandoff_no_two_cycle
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinHandoff_no_two_cycle
#check DkMath.NumberTheory.Legendre.coarseTownMin_unrepresented_iff_outgoing
#print axioms DkMath.NumberTheory.Legendre.coarseTownMin_unrepresented_iff_outgoing
#check DkMath.NumberTheory.Legendre.coarseTownMin_represented_iff_terminal
#print axioms DkMath.NumberTheory.Legendre.coarseTownMin_represented_iff_terminal
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_gap_arithmetic
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_gap_arithmetic
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_grid
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_grid
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_different_columns
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_different_columns
#check DkMath.NumberTheory.Legendre.coarseTownHandoff_destination_unique
#print axioms DkMath.NumberTheory.Legendre.coarseTownHandoff_destination_unique
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_product_not_dvd_gap
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_product_not_dvd_gap
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_chain_rank
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_chain_rank
#check DkMath.NumberTheory.Legendre.coarseTownMinHandoff_chain_rank
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinHandoff_chain_rank
#check DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_no_cycle
#print axioms DkMath.NumberTheory.Legendre.coarseTownMaxHandoff_no_cycle
#check DkMath.NumberTheory.Legendre.coarseTownMinHandoff_no_cycle
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinHandoff_no_cycle
#check DkMath.NumberTheory.Legendre.coarseTownBetter_deficit_implies_uncovered_nonempty
#print axioms DkMath.NumberTheory.Legendre.coarseTownBetter_deficit_implies_uncovered_nonempty
#check DkMathTest.LegendreRetained297Calibration.left_carrier_checked
#print axioms DkMathTest.LegendreRetained297Calibration.left_carrier_checked
#check DkMathTest.LegendreRetained297Calibration.left_represented_checked
#print axioms DkMathTest.LegendreRetained297Calibration.left_represented_checked
#check DkMathTest.LegendreRetained297Calibration.right_carrier_checked
#print axioms DkMathTest.LegendreRetained297Calibration.right_carrier_checked
#check DkMathTest.LegendreRetained297Calibration.right_represented_checked
#print axioms DkMathTest.LegendreRetained297Calibration.right_represented_checked
#check DkMathTest.LegendreRetained297Calibration.left_loss_decomposition_checked
#print axioms DkMathTest.LegendreRetained297Calibration.left_loss_decomposition_checked
#check DkMathTest.LegendreRetained297Calibration.right_loss_decomposition_checked
#print axioms DkMathTest.LegendreRetained297Calibration.right_loss_decomposition_checked
#check DkMathTest.LegendreRetained297Calibration.better_orientation_checked
#print axioms DkMathTest.LegendreRetained297Calibration.better_orientation_checked
#check DkMathTest.LegendreRetained297Calibration.better_cards_checked
#print axioms DkMathTest.LegendreRetained297Calibration.better_cards_checked
#check DkMathTest.LegendreRetained297Calibration.exists_prime_squareCell_297_of_better_selector
#print axioms DkMathTest.LegendreRetained297Calibration.exists_prime_squareCell_297_of_better_selector
#check DkMathTest.LegendreRetained1031Calibration.left_carrier_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.left_carrier_checked
#check DkMathTest.LegendreRetained1031Calibration.left_represented_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.left_represented_checked
#check DkMathTest.LegendreRetained1031Calibration.right_carrier_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.right_carrier_checked
#check DkMathTest.LegendreRetained1031Calibration.right_represented_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.right_represented_checked
#check DkMathTest.LegendreRetained1031Calibration.right_remainder_card_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.right_remainder_card_checked
#check DkMathTest.LegendreRetained1031Calibration.left_loss_decomposition_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.left_loss_decomposition_checked
#check DkMathTest.LegendreRetained1031Calibration.right_loss_decomposition_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.right_loss_decomposition_checked
#check DkMathTest.LegendreRetained1031Calibration.better_orientation_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.better_orientation_checked
#check DkMathTest.LegendreRetained1031Calibration.better_cards_checked
#print axioms DkMathTest.LegendreRetained1031Calibration.better_cards_checked
#check DkMathTest.LegendreRetained1031Calibration.exists_prime_squareCell_1031_of_better_selector
#print axioms DkMathTest.LegendreRetained1031Calibration.exists_prime_squareCell_1031_of_better_selector
#check DkMathTest.LegendreHandoffRegression.six_handoff
#print axioms DkMathTest.LegendreHandoffRegression.six_handoff
#check DkMathTest.LegendreHandoffRegression.eight_branching
#print axioms DkMathTest.LegendreHandoffRegression.eight_branching
#check DkMathTest.LegendreHandoffRegression.six_gap_counterexample
#print axioms DkMathTest.LegendreHandoffRegression.six_gap_counterexample
#check DkMathTest.LegendreHandoffRegression.seven_shared_minimum
#print axioms DkMathTest.LegendreHandoffRegression.seven_shared_minimum
#check DkMathTest.LegendreHandoffRegression.seven_distinct_terminal_directions
#print axioms DkMathTest.LegendreHandoffRegression.seven_distinct_terminal_directions
#check DkMathTest.LegendreHandoffRegression.empty_fibers_have_no_extrema
#print axioms DkMathTest.LegendreHandoffRegression.empty_fibers_have_no_extrema
#check DkMathTest.LegendreHandoffRegression.uniform_branching_297
#print axioms DkMathTest.LegendreHandoffRegression.uniform_branching_297
#check DkMathTest.LegendreSurvivor297Calibration.exists_prime_squareCell_297_of_right_survivor_deletion
#print axioms DkMathTest.LegendreSurvivor297Calibration.exists_prime_squareCell_297_of_right_survivor_deletion
#check DkMathTest.LegendreSurvivor1031Calibration.exists_prime_squareCell_1031_of_survivor_deletion
#print axioms DkMathTest.LegendreSurvivor1031Calibration.exists_prime_squareCell_1031_of_survivor_deletion
