/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreSqrtQuotientCalibration
import DkMathTest.NumberTheory.LegendreSqrtQuotientRegression

#print "file: DkMathTest.NumberTheory.LegendreSqrtQuotientAxiomAudit"

#check DkMath.NumberTheory.Legendre.sqrtRoughQuotientFiber
#print axioms DkMath.NumberTheory.Legendre.sqrtRoughQuotientFiber
#check DkMath.NumberTheory.Legendre.sqrtRoughCompositeFiber
#print axioms DkMath.NumberTheory.Legendre.sqrtRoughCompositeFiber
#check DkMath.NumberTheory.Legendre.sqrtRoughRoutedFiber
#print axioms DkMath.NumberTheory.Legendre.sqrtRoughRoutedFiber
#check DkMath.NumberTheory.Legendre.sqrtRoughRejectedFiber
#print axioms DkMath.NumberTheory.Legendre.sqrtRoughRejectedFiber
#check DkMath.NumberTheory.Legendre.sqrt_quotient_gt_anchor
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_gt_anchor
#check DkMath.NumberTheory.Legendre.mem_sqrtRoughQuotientFiber
#print axioms DkMath.NumberTheory.Legendre.mem_sqrtRoughQuotientFiber
#check DkMath.NumberTheory.Legendre.sqrt_quotient_ne_zero_ne_one
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_ne_zero_ne_one
#check DkMath.NumberTheory.Legendre.sqrt_cross_fiber_eq_quotient_prime_filter
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_fiber_eq_quotient_prime_filter
#check DkMath.NumberTheory.Legendre.sqrt_quotient_prime_composite_partition
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_prime_composite_partition
#check DkMath.NumberTheory.Legendre.sqrt_quotient_seat_packet
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_seat_packet
#check DkMath.NumberTheory.Legendre.sqrt_quotient_seat_rough_iff
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_seat_rough_iff
#check DkMath.NumberTheory.Legendre.sqrt_quotient_rejected_iff_small_prime
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_rejected_iff_small_prime
#check DkMath.NumberTheory.Legendre.sqrt_quotient_below_empty_above_eq
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_below_empty_above_eq
#check DkMath.NumberTheory.Legendre.primeAnchor_quotient_fiber_card_eq_floor
#print axioms DkMath.NumberTheory.Legendre.primeAnchor_quotient_fiber_card_eq_floor
#check DkMath.NumberTheory.Legendre.sqrt_supported_quotient_packet
#print axioms DkMath.NumberTheory.Legendre.sqrt_supported_quotient_packet
#check DkMath.NumberTheory.Legendre.sqrt_quotient_owners_eq_support
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_owners_eq_support
#check DkMath.NumberTheory.Legendre.sqrt_routed_fiber_card_eq_rough_wave
#print axioms DkMath.NumberTheory.Legendre.sqrt_routed_fiber_card_eq_rough_wave
#check DkMath.NumberTheory.Legendre.sqrt_three_factor_owner_quotients
#print axioms DkMath.NumberTheory.Legendre.sqrt_three_factor_owner_quotients
#check DkMath.NumberTheory.Legendre.sqrt_cube_owner_quotient
#print axioms DkMath.NumberTheory.Legendre.sqrt_cube_owner_quotient
#check DkMath.NumberTheory.Legendre.sqrt_repeated_owner_quotients
#print axioms DkMath.NumberTheory.Legendre.sqrt_repeated_owner_quotients
#check DkMath.NumberTheory.Legendre.sqrt_triple_owner_quotients
#print axioms DkMath.NumberTheory.Legendre.sqrt_triple_owner_quotients
#check DkMath.NumberTheory.Legendre.sqrt_cube_quotient_owner_multiplicity
#print axioms DkMath.NumberTheory.Legendre.sqrt_cube_quotient_owner_multiplicity
#check DkMath.NumberTheory.Legendre.sqrt_repeated_quotient_owner_multiplicity
#print axioms DkMath.NumberTheory.Legendre.sqrt_repeated_quotient_owner_multiplicity
#check DkMath.NumberTheory.Legendre.sqrt_triple_quotient_owner_multiplicity
#print axioms DkMath.NumberTheory.Legendre.sqrt_triple_quotient_owner_multiplicity
#check DkMath.NumberTheory.Legendre.sqrt_composite_quotient_routes_to_census
#print axioms DkMath.NumberTheory.Legendre.sqrt_composite_quotient_routes_to_census
#check DkMath.NumberTheory.Legendre.sqrt_quotient_owners_above_eq_support
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_owners_above_eq_support
#check DkMath.NumberTheory.Legendre.sqrt_composite_quotient_normal_forms
#print axioms DkMath.NumberTheory.Legendre.sqrt_composite_quotient_normal_forms
#check DkMath.NumberTheory.Legendre.sqrt_routed_composite_factor_packet
#print axioms DkMath.NumberTheory.Legendre.sqrt_routed_composite_factor_packet
#check DkMath.NumberTheory.Legendre.sqrt_cross_fiber_eq_routed_prime_filter
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_fiber_eq_routed_prime_filter
#check DkMath.NumberTheory.Legendre.sqrt_rejected_quotient_not_prime
#print axioms DkMath.NumberTheory.Legendre.sqrt_rejected_quotient_not_prime
#check DkMath.NumberTheory.Legendre.sqrt_quotient_routed_rejected_partition
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_routed_rejected_partition
#check DkMath.NumberTheory.Legendre.sqrt_composite_fiber_corrected_partition
#print axioms DkMath.NumberTheory.Legendre.sqrt_composite_fiber_corrected_partition
#check DkMath.NumberTheory.Legendre.sqrt_routed_quotient_sum_eq_rough_incidence
#print axioms DkMath.NumberTheory.Legendre.sqrt_routed_quotient_sum_eq_rough_incidence
#check DkMath.NumberTheory.Legendre.sqrt_quotient_conservation
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_conservation
#check DkMath.NumberTheory.Legendre.sqrt_routed_composite_sum
#print axioms DkMath.NumberTheory.Legendre.sqrt_routed_composite_sum
#check DkMath.NumberTheory.Legendre.sqrt_cross_add_composite_eq_total
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_add_composite_eq_total
#check DkMath.NumberTheory.Legendre.sqrt_composite_sum_corrected
#print axioms DkMath.NumberTheory.Legendre.sqrt_composite_sum_corrected
#check DkMath.NumberTheory.Legendre.sqrt_cross_eq_total_sub_routing
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_eq_total_sub_routing
#check DkMath.NumberTheory.Legendre.sqrt_cross_bound_of_composite_lower
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_bound_of_composite_lower
#check DkMath.NumberTheory.Legendre.sqrt_cross_bound_of_rejected_lower
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_bound_of_rejected_lower
#check DkMath.NumberTheory.Legendre.sqrt_rejected_card_lower_of_small_primes
#print axioms DkMath.NumberTheory.Legendre.sqrt_rejected_card_lower_of_small_primes
#check DkMath.NumberTheory.Legendre.sqrt_cross_le_total
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_le_total
#check DkMath.NumberTheory.Legendre.sqrt_cross_card_le_capacity_sub_routing
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_card_le_capacity_sub_routing
#check DkMath.NumberTheory.Legendre.prime_squareCell_of_quotient_routing_budget
#print axioms DkMath.NumberTheory.Legendre.prime_squareCell_of_quotient_routing_budget
#check DkMath.NumberTheory.Legendre.sqrt_quotient_sum_split_owner_range
#print axioms DkMath.NumberTheory.Legendre.sqrt_quotient_sum_split_owner_range
#check DkMath.NumberTheory.Legendre.primeAnchor_quotient_range_eq_floor
#print axioms DkMath.NumberTheory.Legendre.primeAnchor_quotient_range_eq_floor
#check DkMath.NumberTheory.Legendre.sqrt_cross_fiber_card_le_odd_span
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_fiber_card_le_odd_span
#check DkMathTest.LegendreSqrtQuotientCalibration.quotientNumbers
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotientNumbers
#check DkMathTest.LegendreSqrtQuotientCalibration.rejectedThreeCalc
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.rejectedThreeCalc
#check DkMathTest.LegendreSqrtQuotientCalibration.rejectedThree_normal_form
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.rejectedThree_normal_form
#check DkMathTest.LegendreSqrtQuotientCalibration.rejectedThree_card_le
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.rejectedThree_card_le
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient_floor_inputs_checked
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient_floor_inputs_checked
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient_row_arithmetic
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient_row_arithmetic
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient_total_checked
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient_total_checked
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient_rejected_lower_checked
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient_rejected_lower_checked
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient_full_calibration
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient_full_calibration
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient_structural_calibration_endpoints
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient_structural_calibration_endpoints
#check DkMathTest.LegendreSqrtQuotientCalibration.active1031
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.active1031
#check DkMathTest.LegendreSqrtQuotientCalibration.active1031_checked
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.active1031_checked
#check DkMathTest.LegendreSqrtQuotientCalibration.rough1031
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.rough1031
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_inputs_checked
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_inputs_checked
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_structural_inputs
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_structural_inputs
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_structural_endpoint
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_structural_endpoint
#check DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_uncovered_lower
#print axioms DkMathTest.LegendreSqrtQuotientCalibration.quotient1031_uncovered_lower
#check DkMathTest.LegendreSqrtQuotientRegression.rejected_eleven_packet
#print axioms DkMathTest.LegendreSqrtQuotientRegression.rejected_eleven_packet
#check DkMathTest.LegendreSqrtQuotientRegression.rejected_eleven
#print axioms DkMathTest.LegendreSqrtQuotientRegression.rejected_eleven
#check DkMathTest.LegendreSqrtQuotientRegression.uncorrected_conservation_eleven_false
#print axioms DkMathTest.LegendreSqrtQuotientRegression.uncorrected_conservation_eleven_false
#check DkMathTest.LegendreSqrtQuotientRegression.repeated_eight_key
#print axioms DkMathTest.LegendreSqrtQuotientRegression.repeated_eight_key
#check DkMathTest.LegendreSqrtQuotientRegression.repeated_eight_quotients
#print axioms DkMathTest.LegendreSqrtQuotientRegression.repeated_eight_quotients
#check DkMathTest.LegendreSqrtQuotientRegression.repeated_thirteen_quotients
#print axioms DkMathTest.LegendreSqrtQuotientRegression.repeated_thirteen_quotients
#check DkMathTest.LegendreSqrtQuotientRegression.repeated_thirteen_owner_count
#print axioms DkMathTest.LegendreSqrtQuotientRegression.repeated_thirteen_owner_count
#check DkMathTest.LegendreSqrtQuotientRegression.triple_nineteen_quotients
#print axioms DkMathTest.LegendreSqrtQuotientRegression.triple_nineteen_quotients
#check DkMathTest.LegendreSqrtQuotientRegression.empty_zero_quotient_sum
#print axioms DkMathTest.LegendreSqrtQuotientRegression.empty_zero_quotient_sum
#check DkMathTest.LegendreSqrtQuotientRegression.no_small_prime_rejection_before_eleven
#print axioms DkMathTest.LegendreSqrtQuotientRegression.no_small_prime_rejection_before_eleven
#check DkMathTest.LegendreSqrtQuotientRegression.rejected_eleven_is_minimal
#print axioms DkMathTest.LegendreSqrtQuotientRegression.rejected_eleven_is_minimal
#check DkMathTest.LegendreSqrtQuotientRegression.no_multiple_owners_before_eight
#print axioms DkMathTest.LegendreSqrtQuotientRegression.no_multiple_owners_before_eight
#check DkMathTest.LegendreSqrtQuotientRegression.no_prime_multiple_owners_before_thirteen
#print axioms DkMathTest.LegendreSqrtQuotientRegression.no_prime_multiple_owners_before_thirteen
