/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreConservationRegression
import DkMathTest.NumberTheory.LegendreSurvivor297Calibration
import DkMathTest.NumberTheory.LegendreSurvivor1031Calibration
import DkMathTest.NumberTheory.LegendreCapacity297Calibration

#print "file: DkMathTest.NumberTheory.LegendreConservationAxiomAudit"

#check DkMath.Combinatorics.card_le_supportUniverse
#print axioms DkMath.Combinatorics.card_le_supportUniverse
#check DkMath.Combinatorics.supportCollisionEdges
#print axioms DkMath.Combinatorics.supportCollisionEdges
#check DkMath.Combinatorics.mem_supportCollisionEdges
#print axioms DkMath.Combinatorics.mem_supportCollisionEdges
#check DkMath.Combinatorics.supportCollisionDeletionVertices
#print axioms DkMath.Combinatorics.supportCollisionDeletionVertices
#check DkMath.Combinatorics.supportPackingRemainder
#print axioms DkMath.Combinatorics.supportPackingRemainder
#check DkMath.Combinatorics.mem_supportCollisionDeletionVertices
#print axioms DkMath.Combinatorics.mem_supportCollisionDeletionVertices
#check DkMath.Combinatorics.mem_supportPackingRemainder
#print axioms DkMath.Combinatorics.mem_supportPackingRemainder
#check DkMath.Combinatorics.supportCollisionDeletionVertices_subset
#print axioms DkMath.Combinatorics.supportCollisionDeletionVertices_subset
#check DkMath.Combinatorics.supportPackingRemainder_subset
#print axioms DkMath.Combinatorics.supportPackingRemainder_subset
#check DkMath.Combinatorics.disjoint_supportPackingRemainder_deletion
#print axioms DkMath.Combinatorics.disjoint_supportPackingRemainder_deletion
#check DkMath.Combinatorics.supportPackingRemainder_union_deletion
#print axioms DkMath.Combinatorics.supportPackingRemainder_union_deletion
#check DkMath.Combinatorics.card_supportPacking_partition
#print axioms DkMath.Combinatorics.card_supportPacking_partition
#check DkMath.Combinatorics.card_supportCollisionDeletionVertices_le_edges
#print axioms DkMath.Combinatorics.card_supportCollisionDeletionVertices_le_edges
#check DkMath.Combinatorics.supportPackingRemainder_pairwiseDisjoint
#print axioms DkMath.Combinatorics.supportPackingRemainder_pairwiseDisjoint
#check DkMath.Combinatorics.supportPacking_exact_packet
#print axioms DkMath.Combinatorics.supportPacking_exact_packet
#check DkMath.Combinatorics.supportCollisionRightDeletionVertices
#print axioms DkMath.Combinatorics.supportCollisionRightDeletionVertices
#check DkMath.Combinatorics.supportPackingRightRemainder
#print axioms DkMath.Combinatorics.supportPackingRightRemainder
#check DkMath.Combinatorics.mem_supportCollisionRightDeletionVertices
#print axioms DkMath.Combinatorics.mem_supportCollisionRightDeletionVertices
#check DkMath.Combinatorics.supportCollisionRightDeletionVertices_subset
#print axioms DkMath.Combinatorics.supportCollisionRightDeletionVertices_subset
#check DkMath.Combinatorics.card_supportPackingRight_partition
#print axioms DkMath.Combinatorics.card_supportPackingRight_partition
#check DkMath.Combinatorics.supportPackingRightRemainder_pairwiseDisjoint
#print axioms DkMath.Combinatorics.supportPackingRightRemainder_pairwiseDisjoint
#check DkMath.Combinatorics.exists_supportPacking
#print axioms DkMath.Combinatorics.exists_supportPacking
#check DkMath.NumberTheory.Legendre.card_fullTown_pairwiseOldSupportDisjoint_le_outsidePrimes_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.card_fullTown_pairwiseOldSupportDisjoint_le_outsidePrimes_of_fullyCovered
#check DkMath.NumberTheory.Legendre.not_fullyCovered_of_fullTown_survivor_capacity
#print axioms DkMath.NumberTheory.Legendre.not_fullyCovered_of_fullTown_survivor_capacity
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_not_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_not_fullyCovered
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_fullTown_survivor_capacity
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_fullTown_survivor_capacity
#check DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_outside_deletion_deficit
#print axioms DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_outside_deletion_deficit
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_outside_deletion_deficit
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_outside_deletion_deficit
#check DkMath.NumberTheory.Legendre.coarseTown_outside_deletion_deficit_of_old_deficit
#print axioms DkMath.NumberTheory.Legendre.coarseTown_outside_deletion_deficit_of_old_deficit
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionVertices
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionVertices
#check DkMath.NumberTheory.Legendre.coarseTownRightPackingRemainder
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightPackingRemainder
#check DkMath.NumberTheory.Legendre.coarseTownRightPackingRemainder_subset
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightPackingRemainder_subset
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionVertices_subset
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionVertices_subset
#check DkMath.NumberTheory.Legendre.coarseTownRightPackingRemainder_family
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightPackingRemainder_family
#check DkMath.NumberTheory.Legendre.card_coarseTownRightDeletion_partition
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownRightDeletion_partition
#check DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_outside_right_deletion_deficit
#print axioms DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_outside_right_deletion_deficit
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_outside_right_deletion_deficit
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_outside_right_deletion_deficit
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionByFibers
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionByFibers
#check DkMath.NumberTheory.Legendre.coarseTownRightDeletionVertices_eq_fibers
#print axioms DkMath.NumberTheory.Legendre.coarseTownRightDeletionVertices_eq_fibers
#check DkMath.NumberTheory.Legendre.coarseFullTownActivePrimes
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownActivePrimes
#check DkMath.NumberTheory.Legendre.mem_coarseFullTownActivePrimes
#print axioms DkMath.NumberTheory.Legendre.mem_coarseFullTownActivePrimes
#check DkMath.NumberTheory.Legendre.coarseFullTownActivePrimes_subset
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownActivePrimes_subset
#check DkMath.NumberTheory.Legendre.card_coarseFullTownActivePrimes_le
#print axioms DkMath.NumberTheory.Legendre.card_coarseFullTownActivePrimes_le
#check DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats
#check DkMath.NumberTheory.Legendre.mem_coarseFullTownUncoveredSeats
#print axioms DkMath.NumberTheory.Legendre.mem_coarseFullTownUncoveredSeats
#check DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats_eq_empty_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownUncoveredSeats_eq_empty_of_fullyCovered
#check DkMath.NumberTheory.Legendre.coarseFullTownSupportExcess
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownSupportExcess
#check DkMath.NumberTheory.Legendre.coarseFullTownIncidence_add_uncovered_eq_card_add_excess
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownIncidence_add_uncovered_eq_card_add_excess
#check DkMath.NumberTheory.Legendre.coarseTownNonmaximumFiberSeats
#print axioms DkMath.NumberTheory.Legendre.coarseTownNonmaximumFiberSeats
#check DkMath.NumberTheory.Legendre.mem_coarseTownNonmaximumFiberSeats
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownNonmaximumFiberSeats
#check DkMath.NumberTheory.Legendre.card_coarseTownNonmaximumFiberSeats_add_indicator
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownNonmaximumFiberSeats_add_indicator
#check DkMath.NumberTheory.Legendre.coarseTownDeletionWitnessPrimes
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionWitnessPrimes
#check DkMath.NumberTheory.Legendre.coarseTownDeletionMultiplicity
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionMultiplicity
#check DkMath.NumberTheory.Legendre.coarseTownDeletionWitnessPrimes_subset_support
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionWitnessPrimes_subset_support
#check DkMath.NumberTheory.Legendre.mem_coarseTownDeletionVertices_iff_multiplicity_pos
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownDeletionVertices_iff_multiplicity_pos
#check DkMath.NumberTheory.Legendre.mem_coarseTownDeletionByFibers_iff_multiplicity_pos
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownDeletionByFibers_iff_multiplicity_pos
#check DkMath.NumberTheory.Legendre.coarseTownDeletionMass
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionMass
#check DkMath.NumberTheory.Legendre.coarseTownDeletionMass_eq_nonmaximum_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionMass_eq_nonmaximum_sum
#check DkMath.NumberTheory.Legendre.coarseTownDeletionMass_add_active_eq_incidence
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionMass_add_active_eq_incidence
#check DkMath.NumberTheory.Legendre.coarseTownDeletionOverlap
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionOverlap
#check DkMath.NumberTheory.Legendre.card_deletion_add_overlap_eq_mass
#print axioms DkMath.NumberTheory.Legendre.card_deletion_add_overlap_eq_mass
#check DkMath.NumberTheory.Legendre.coarseTownDeletion_primeFiber_conservation
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletion_primeFiber_conservation
#check DkMath.NumberTheory.Legendre.coarseTown_remainder_conservation
#print axioms DkMath.NumberTheory.Legendre.coarseTown_remainder_conservation
#check DkMath.NumberTheory.Legendre.coarseTown_remainder_conservation_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.coarseTown_remainder_conservation_of_fullyCovered
#check DkMath.NumberTheory.Legendre.coarseTown_fullCover_conservation_frontier
#print axioms DkMath.NumberTheory.Legendre.coarseTown_fullCover_conservation_frontier
#check DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_conservation_deficit
#print axioms DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_conservation_deficit
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_conservation_deficit
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_conservation_deficit
#check DkMath.NumberTheory.Legendre.coarseTown_outside_deficit_iff_conservation_with_uncovered
#print axioms DkMath.NumberTheory.Legendre.coarseTown_outside_deficit_iff_conservation_with_uncovered
#check DkMath.NumberTheory.Legendre.coarseTown_outside_deficit_iff_conservation_of_uncovered_empty
#print axioms DkMath.NumberTheory.Legendre.coarseTown_outside_deficit_iff_conservation_of_uncovered_empty
#check DkMath.NumberTheory.Legendre.coarseTownDeletionOverlap_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionOverlap_le_supportExcess
#check DkMath.NumberTheory.Legendre.coarseTown_conservation_frontier_unconditional
#print axioms DkMath.NumberTheory.Legendre.coarseTown_conservation_frontier_unconditional
#check DkMath.NumberTheory.Legendre.coarseFullTownPrimeFiber_eq_divisibility_of_mem
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownPrimeFiber_eq_divisibility_of_mem
#check DkMath.NumberTheory.Legendre.coarseFullTownIncidence_eq_divisibility_sum
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownIncidence_eq_divisibility_sum
#check DkMath.NumberTheory.Legendre.coarseFullTownActivePrimes_eq_divisibility_filter
#print axioms DkMath.NumberTheory.Legendre.coarseFullTownActivePrimes_eq_divisibility_filter
#check DkMath.NumberTheory.Legendre.card_coarseTownNonmaximumFiberSeats_of_nonempty
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownNonmaximumFiberSeats_of_nonempty
#check DkMath.NumberTheory.Legendre.coarseTownNonmaximumFiberSeats_eq_empty_of_empty
#print axioms DkMath.NumberTheory.Legendre.coarseTownNonmaximumFiberSeats_eq_empty_of_empty
#check DkMath.NumberTheory.Legendre.mem_coarseTownDeletionWitnessPrimes
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownDeletionWitnessPrimes
#check DkMath.NumberTheory.Legendre.coarseTownSupportLoss
#print axioms DkMath.NumberTheory.Legendre.coarseTownSupportLoss
#check DkMath.NumberTheory.Legendre.coarseTown_overlap_add_loss_eq_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_overlap_add_loss_eq_excess
#check DkMath.NumberTheory.Legendre.coarseTown_remainder_add_loss_eq_uncovered_add_active
#print axioms DkMath.NumberTheory.Legendre.coarseTown_remainder_add_loss_eq_uncovered_add_active
#check DkMath.NumberTheory.Legendre.coarseTown_outside_deficit_iff_loss_add_inactive_lt_uncovered
#print axioms DkMath.NumberTheory.Legendre.coarseTown_outside_deficit_iff_loss_add_inactive_lt_uncovered
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_loss_frontier
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_loss_frontier
#check DkMathTest.LegendreConservationRegression.one_base_coordinates
#print axioms DkMathTest.LegendreConservationRegression.one_base_coordinates
#check DkMathTest.LegendreConservationRegression.one_conservation_coordinates
#print axioms DkMathTest.LegendreConservationRegression.one_conservation_coordinates
#check DkMathTest.LegendreConservationRegression.one_master_checked
#print axioms DkMathTest.LegendreConservationRegression.one_master_checked
#check DkMathTest.LegendreConservationRegression.five_base_coordinates
#print axioms DkMathTest.LegendreConservationRegression.five_base_coordinates
#check DkMathTest.LegendreConservationRegression.five_conservation_coordinates
#print axioms DkMathTest.LegendreConservationRegression.five_conservation_coordinates
#check DkMathTest.LegendreConservationRegression.five_master_checked
#print axioms DkMathTest.LegendreConservationRegression.five_master_checked
#check DkMathTest.LegendreConservationRegression.eleven_base_coordinates
#print axioms DkMathTest.LegendreConservationRegression.eleven_base_coordinates
#check DkMathTest.LegendreConservationRegression.eleven_conservation_coordinates
#print axioms DkMathTest.LegendreConservationRegression.eleven_conservation_coordinates
#check DkMathTest.LegendreConservationRegression.eleven_master_checked
#print axioms DkMathTest.LegendreConservationRegression.eleven_master_checked
#check DkMathTest.LegendreConservationRegression.elevenOdd_base_coordinates
#print axioms DkMathTest.LegendreConservationRegression.elevenOdd_base_coordinates
#check DkMathTest.LegendreConservationRegression.elevenOdd_conservation_coordinates
#print axioms DkMathTest.LegendreConservationRegression.elevenOdd_conservation_coordinates
#check DkMathTest.LegendreConservationRegression.elevenOdd_master_checked
#print axioms DkMathTest.LegendreConservationRegression.elevenOdd_master_checked
#check DkMathTest.LegendreConservationRegression.nineteen_base_coordinates
#print axioms DkMathTest.LegendreConservationRegression.nineteen_base_coordinates
#check DkMathTest.LegendreConservationRegression.nineteen_conservation_coordinates
#print axioms DkMathTest.LegendreConservationRegression.nineteen_conservation_coordinates
#check DkMathTest.LegendreConservationRegression.nineteen_master_checked
#print axioms DkMathTest.LegendreConservationRegression.nineteen_master_checked
#check DkMathTest.LegendreConservationRegression.twentynine_base_coordinates
#print axioms DkMathTest.LegendreConservationRegression.twentynine_base_coordinates
#check DkMathTest.LegendreConservationRegression.twentynine_conservation_coordinates
#print axioms DkMathTest.LegendreConservationRegression.twentynine_conservation_coordinates
#check DkMathTest.LegendreConservationRegression.twentynine_master_checked
#print axioms DkMathTest.LegendreConservationRegression.twentynine_master_checked
#check DkMathTest.LegendreConservationRegression.smallest_false_equivalence
#print axioms DkMathTest.LegendreConservationRegression.smallest_false_equivalence
#check DkMathTest.LegendreConservationRegression.five_false_equivalence
#print axioms DkMathTest.LegendreConservationRegression.five_false_equivalence
#check DkMathTest.LegendreSurvivor297Calibration.town297Seats
#print axioms DkMathTest.LegendreSurvivor297Calibration.town297Seats
#check DkMathTest.LegendreSurvivor297Calibration.oldPrimes297
#print axioms DkMathTest.LegendreSurvivor297Calibration.oldPrimes297
#check DkMathTest.LegendreSurvivor297Calibration.town297Seats_eq_production
#print axioms DkMathTest.LegendreSurvivor297Calibration.town297Seats_eq_production
#check DkMathTest.LegendreSurvivor297Calibration.oldPrimes297_eq_production
#print axioms DkMathTest.LegendreSurvivor297Calibration.oldPrimes297_eq_production
#check DkMathTest.LegendreSurvivor297Calibration.geometry297_checked
#print axioms DkMathTest.LegendreSurvivor297Calibration.geometry297_checked
#check DkMathTest.LegendreSurvivor297Calibration.deletion297_cards_checked
#print axioms DkMathTest.LegendreSurvivor297Calibration.deletion297_cards_checked
#check DkMathTest.LegendreSurvivor297Calibration.remainder297_cards
#print axioms DkMathTest.LegendreSurvivor297Calibration.remainder297_cards
#check DkMathTest.LegendreSurvivor297Calibration.survivor297_right_strictness
#print axioms DkMathTest.LegendreSurvivor297Calibration.survivor297_right_strictness
#check DkMathTest.LegendreSurvivor297Calibration.exists_prime_squareCell_297_of_right_survivor_deletion
#print axioms DkMathTest.LegendreSurvivor297Calibration.exists_prime_squareCell_297_of_right_survivor_deletion
#check DkMathTest.LegendreSurvivor297Calibration.incidence297_checked
#print axioms DkMathTest.LegendreSurvivor297Calibration.incidence297_checked
#check DkMathTest.LegendreSurvivor297Calibration.active297_checked
#print axioms DkMathTest.LegendreSurvivor297Calibration.active297_checked
#check DkMathTest.LegendreSurvivor297Calibration.uncovered297_checked
#print axioms DkMathTest.LegendreSurvivor297Calibration.uncovered297_checked
#check DkMathTest.LegendreSurvivor297Calibration.conservation297_coordinates
#print axioms DkMathTest.LegendreSurvivor297Calibration.conservation297_coordinates
#check DkMathTest.LegendreSurvivor297Calibration.master297_checked
#print axioms DkMathTest.LegendreSurvivor297Calibration.master297_checked
#check DkMathTest.LegendreSurvivor1031Calibration.outside1031_card_checked
#print axioms DkMathTest.LegendreSurvivor1031Calibration.outside1031_card_checked
#check DkMathTest.LegendreSurvivor1031Calibration.exists_prime_squareCell_1031_of_survivor_deletion
#print axioms DkMathTest.LegendreSurvivor1031Calibration.exists_prime_squareCell_1031_of_survivor_deletion
#check DkMathTest.LegendreSurvivor1031Calibration.incidence1031_checked
#print axioms DkMathTest.LegendreSurvivor1031Calibration.incidence1031_checked
#check DkMathTest.LegendreSurvivor1031Calibration.active1031_checked
#print axioms DkMathTest.LegendreSurvivor1031Calibration.active1031_checked
#check DkMathTest.LegendreSurvivor1031Calibration.uncovered1031_checked
#print axioms DkMathTest.LegendreSurvivor1031Calibration.uncovered1031_checked
#check DkMathTest.LegendreSurvivor1031Calibration.conservation1031_coordinates
#print axioms DkMathTest.LegendreSurvivor1031Calibration.conservation1031_coordinates
#check DkMathTest.LegendreSurvivor1031Calibration.master1031_checked
#print axioms DkMathTest.LegendreSurvivor1031Calibration.master1031_checked
#check DkMathTest.LegendreCapacity297Calibration.exists_prime_squareCell_297_of_explicitCapacityCertificate
#print axioms DkMathTest.LegendreCapacity297Calibration.exists_prime_squareCell_297_of_explicitCapacityCertificate
#check DkMathTest.LegendreDeletion1031Calibration.exists_prime_squareCell_1031_of_coarseTownDeletion
#print axioms DkMathTest.LegendreDeletion1031Calibration.exists_prime_squareCell_1031_of_coarseTownDeletion
