/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreTerminalProductCalibration

#print "file: DkMathTest.NumberTheory.LegendreTerminalProductAxiomAudit"

#check DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt
#print axioms DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt
#check DkMath.NumberTheory.Legendre.coarseTownMinimumTerminalPrimesAt
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinimumTerminalPrimesAt
#check DkMath.NumberTheory.Legendre.mem_coarseTownTerminalPrimesAt
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownTerminalPrimesAt
#check DkMath.NumberTheory.Legendre.mem_coarseTownMinimumTerminalPrimesAt
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownMinimumTerminalPrimesAt
#check DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt_subset_support
#print axioms DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt_subset_support
#check DkMath.NumberTheory.Legendre.coarseTownMinimumTerminalPrimesAt_subset_support
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinimumTerminalPrimesAt_subset_support
#check DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt_subset_active
#print axioms DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt_subset_active
#check DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt_subset_outside
#print axioms DkMath.NumberTheory.Legendre.coarseTownTerminalPrimesAt_subset_outside
#check DkMath.NumberTheory.Legendre.coarseTownMinimumTerminalPrimesAt_subset_active
#print axioms DkMath.NumberTheory.Legendre.coarseTownMinimumTerminalPrimesAt_subset_active
#check DkMath.NumberTheory.Legendre.coarseTown_terminal_continuing_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_terminal_continuing_partition
#check DkMath.NumberTheory.Legendre.coarseTown_minimum_continuing_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_minimum_continuing_partition
#check DkMath.NumberTheory.Legendre.coarseTown_terminal_continuing_cards
#print axioms DkMath.NumberTheory.Legendre.coarseTown_terminal_continuing_cards
#check DkMath.NumberTheory.Legendre.coarseTown_minimum_continuing_cards
#print axioms DkMath.NumberTheory.Legendre.coarseTown_minimum_continuing_cards
#check DkMath.NumberTheory.Legendre.mem_coarseTownDeletionVertices_iff_continuing_nonempty
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownDeletionVertices_iff_continuing_nonempty
#check DkMath.NumberTheory.Legendre.mem_coarseTownRightDeletionVertices_iff_continuing_nonempty
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownRightDeletionVertices_iff_continuing_nonempty
#check DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_isFinitePrimeBasis
#print axioms DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_isFinitePrimeBasis
#check DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_product_dvd
#print axioms DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_product_dvd
#check DkMath.NumberTheory.Legendre.squareOffset_completePoint_bounds
#print axioms DkMath.NumberTheory.Legendre.squareOffset_completePoint_bounds
#check DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_product_bounds
#print axioms DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_product_bounds
#check DkMath.NumberTheory.Legendre.coarseTown_initial_support_gt_cutoff
#print axioms DkMath.NumberTheory.Legendre.coarseTown_initial_support_gt_cutoff
#check DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_power_bounds
#print axioms DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_power_bounds
#check DkMath.NumberTheory.Legendre.coarseTown_initial_support_power_bounds
#print axioms DkMath.NumberTheory.Legendre.coarseTown_initial_support_power_bounds
#check DkMath.NumberTheory.Legendre.coarseTown_terminal_continuing_product_dvd
#print axioms DkMath.NumberTheory.Legendre.coarseTown_terminal_continuing_product_dvd
#check DkMath.NumberTheory.Legendre.coarseTown_minimum_continuing_product_dvd
#print axioms DkMath.NumberTheory.Legendre.coarseTown_minimum_continuing_product_dvd
#check DkMath.NumberTheory.Legendre.coarseTown_continuing_mul_terminal_product_dvd
#print axioms DkMath.NumberTheory.Legendre.coarseTown_continuing_mul_terminal_product_dvd
#check DkMath.NumberTheory.Legendre.coarseTown_initial_terminal_continuing_power
#print axioms DkMath.NumberTheory.Legendre.coarseTown_initial_terminal_continuing_power
#check DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_power
#print axioms DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_power
#check DkMath.NumberTheory.Legendre.coarseTown_rightDeleted_terminal_power
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightDeleted_terminal_power
#check DkMath.NumberTheory.Legendre.coarseTown_initial_deleted_terminal_power
#print axioms DkMath.NumberTheory.Legendre.coarseTown_initial_deleted_terminal_power
#check DkMath.NumberTheory.Legendre.coarseTown_initial_continuing_mul_terminal_power
#print axioms DkMath.NumberTheory.Legendre.coarseTown_initial_continuing_mul_terminal_power
#check DkMath.NumberTheory.Legendre.terminal_card_lt_of_power_threshold
#print axioms DkMath.NumberTheory.Legendre.terminal_card_lt_of_power_threshold
#check DkMath.NumberTheory.Legendre.support_card_le_of_power_threshold
#print axioms DkMath.NumberTheory.Legendre.support_card_le_of_power_threshold
#check DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_threshold
#print axioms DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_threshold
#check DkMath.NumberTheory.Legendre.coarseTown_rightDeleted_terminal_threshold
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightDeleted_terminal_threshold
#check DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_le_support_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_le_support_excess
#check DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_subset_missing
#print axioms DkMath.NumberTheory.Legendre.coarseTown_deleted_terminal_subset_missing
#check DkMath.NumberTheory.Legendre.coarseTown_rightDeleted_terminal_subset_missing
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightDeleted_terminal_subset_missing
#check DkMath.NumberTheory.Legendre.coarseTown_missing_unique_terminal
#print axioms DkMath.NumberTheory.Legendre.coarseTown_missing_unique_terminal
#check DkMath.NumberTheory.Legendre.coarseTown_rightMissing_unique_terminal
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightMissing_unique_terminal
#check DkMath.NumberTheory.Legendre.coarseTown_terminal_fibers_pairwiseDisjoint
#print axioms DkMath.NumberTheory.Legendre.coarseTown_terminal_fibers_pairwiseDisjoint
#check DkMath.NumberTheory.Legendre.coarseTown_minimum_terminal_fibers_pairwiseDisjoint
#print axioms DkMath.NumberTheory.Legendre.coarseTown_minimum_terminal_fibers_pairwiseDisjoint
#check DkMath.NumberTheory.Legendre.coarseTown_terminal_biUnion_eq_missing
#print axioms DkMath.NumberTheory.Legendre.coarseTown_terminal_biUnion_eq_missing
#check DkMath.NumberTheory.Legendre.coarseTown_minimum_terminal_biUnion_eq_missing
#print axioms DkMath.NumberTheory.Legendre.coarseTown_minimum_terminal_biUnion_eq_missing
#check DkMath.NumberTheory.Legendre.coarseTown_missing_card_eq_terminal_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTown_missing_card_eq_terminal_sum
#check DkMath.NumberTheory.Legendre.coarseTown_rightMissing_card_eq_terminal_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightMissing_card_eq_terminal_sum
#check DkMath.NumberTheory.Legendre.coarseTown_missing_le_capacity_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTown_missing_le_capacity_sum
#check DkMath.NumberTheory.Legendre.coarseTown_rightMissing_le_capacity_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightMissing_le_capacity_sum
#check DkMath.NumberTheory.Legendre.coarseTown_missing_le_uniform_capacity
#print axioms DkMath.NumberTheory.Legendre.coarseTown_missing_le_uniform_capacity
#check DkMath.NumberTheory.Legendre.coarseTown_rightMissing_le_uniform_capacity
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightMissing_le_uniform_capacity
#check DkMath.NumberTheory.Legendre.coarseTown_loss_le_capacity_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTown_loss_le_capacity_sum
#check DkMath.NumberTheory.Legendre.coarseTown_rightLoss_le_capacity_sum
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightLoss_le_capacity_sum
#check DkMath.NumberTheory.Legendre.coarseTown_betterLoss_le_capacity_sums
#print axioms DkMath.NumberTheory.Legendre.coarseTown_betterLoss_le_capacity_sums
#check DkMath.NumberTheory.Legendre.coarseTown_missing_le_deleted_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_missing_le_deleted_excess
#check DkMath.NumberTheory.Legendre.coarseTown_support_excess_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_support_excess_partition
#check DkMath.NumberTheory.Legendre.coarseTown_capacity_loss_upper_ge_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_capacity_loss_upper_ge_excess
#check DkMath.NumberTheory.Legendre.coarseTown_right_support_excess_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTown_right_support_excess_partition
#check DkMath.NumberTheory.Legendre.coarseTown_right_capacity_loss_upper_ge_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_right_capacity_loss_upper_ge_excess
#check DkMath.NumberTheory.Legendre.coarseTown_product_threshold_capacity_ge_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_product_threshold_capacity_ge_excess
#check DkMath.NumberTheory.Legendre.coarseTown_missing_le_product_threshold
#print axioms DkMath.NumberTheory.Legendre.coarseTown_missing_le_product_threshold
#check DkMath.NumberTheory.Legendre.coarseTown_rightMissing_le_product_threshold
#print axioms DkMath.NumberTheory.Legendre.coarseTown_rightMissing_le_product_threshold
#check DkMath.NumberTheory.Legendre.coarseTown_product_threshold_loss_upper_ge_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_product_threshold_loss_upper_ge_excess
#check DkMath.NumberTheory.Legendre.coarseTown_right_product_threshold_loss_upper_ge_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_right_product_threshold_loss_upper_ge_excess
#check DkMath.NumberTheory.Legendre.coarseTown_better_product_threshold_upper_ge_excess
#print axioms DkMath.NumberTheory.Legendre.coarseTown_better_product_threshold_upper_ge_excess
#check DkMath.NumberTheory.Legendre.coarseTown_capacity_frontier_implies_better_deficit
#print axioms DkMath.NumberTheory.Legendre.coarseTown_capacity_frontier_implies_better_deficit
#check DkMathTest.LegendreTerminalProductCalibration.support11_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.support11_checked
#check DkMathTest.LegendreTerminalProductCalibration.terminal11_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.terminal11_checked
#check DkMathTest.LegendreTerminalProductCalibration.continuing11_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.continuing11_checked
#check DkMathTest.LegendreTerminalProductCalibration.partition11_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.partition11_checked
#check DkMathTest.LegendreTerminalProductCalibration.products11_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.products11_checked
#check DkMathTest.LegendreTerminalProductCalibration.divisibility11_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.divisibility11_checked
#check DkMathTest.LegendreTerminalProductCalibration.power11_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.power11_checked
#check DkMathTest.LegendreTerminalProductCalibration.support297_shared_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.support297_shared_checked
#check DkMathTest.LegendreTerminalProductCalibration.terminal297_shared_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.terminal297_shared_checked
#check DkMathTest.LegendreTerminalProductCalibration.continuing297_shared_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.continuing297_shared_checked
#check DkMathTest.LegendreTerminalProductCalibration.products297_shared_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.products297_shared_checked
#check DkMathTest.LegendreTerminalProductCalibration.partition297_shared_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.partition297_shared_checked
#check DkMathTest.LegendreTerminalProductCalibration.divisibility297_shared_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.divisibility297_shared_checked
#check DkMathTest.LegendreTerminalProductCalibration.power297_shared_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.power297_shared_checked
#check DkMathTest.LegendreTerminalProductCalibration.support297_branch_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.support297_branch_checked
#check DkMathTest.LegendreTerminalProductCalibration.terminal297_branch_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.terminal297_branch_checked
#check DkMathTest.LegendreTerminalProductCalibration.continuing297_branch_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.continuing297_branch_checked
#check DkMathTest.LegendreTerminalProductCalibration.products297_branch_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.products297_branch_checked
#check DkMathTest.LegendreTerminalProductCalibration.partition297_branch_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.partition297_branch_checked
#check DkMathTest.LegendreTerminalProductCalibration.divisibility297_branch_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.divisibility297_branch_checked
#check DkMathTest.LegendreTerminalProductCalibration.power297_branch_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.power297_branch_checked
#check DkMathTest.LegendreTerminalProductCalibration.support1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.support1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.terminal1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.terminal1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.continuing1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.continuing1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.products1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.products1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.partition1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.partition1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.divisibility1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.divisibility1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.power1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.power1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.terminal_sums297_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.terminal_sums297_checked
#check DkMathTest.LegendreTerminalProductCalibration.terminal_sums1031_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.terminal_sums1031_checked
#check DkMathTest.LegendreTerminalProductCalibration.smallest_weaker_budget_checked
#print axioms DkMathTest.LegendreTerminalProductCalibration.smallest_weaker_budget_checked
#check DkMathTest.LegendreTerminalProductCalibration.one_base_no_exponent_bound
#print axioms DkMathTest.LegendreTerminalProductCalibration.one_base_no_exponent_bound
#check DkMathTest.LegendreTerminalProductCalibration.shared_support_not_valuation_one
#print axioms DkMathTest.LegendreTerminalProductCalibration.shared_support_not_valuation_one
#check DkMathTest.LegendreHandoffRegression.uniform_branching_297
#print axioms DkMathTest.LegendreHandoffRegression.uniform_branching_297
#check DkMathTest.LegendreSurvivor297Calibration.exists_prime_squareCell_297_of_right_survivor_deletion
#print axioms DkMathTest.LegendreSurvivor297Calibration.exists_prime_squareCell_297_of_right_survivor_deletion
#check DkMathTest.LegendreSurvivor1031Calibration.exists_prime_squareCell_1031_of_survivor_deletion
#print axioms DkMathTest.LegendreSurvivor1031Calibration.exists_prime_squareCell_1031_of_survivor_deletion
