/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreResidueCoverCalibration

#print "file: DkMathTest.NumberTheory.LegendreResidueCoverAxiomAudit"

#check DkMath.NumberTheory.Legendre.open_shell_card_add_one_eq_oddGnomon
#print axioms DkMath.NumberTheory.Legendre.open_shell_card_add_one_eq_oddGnomon
#check DkMath.NumberTheory.Legendre.three_consecutive_odd_gnomons
#print axioms DkMath.NumberTheory.Legendre.three_consecutive_odd_gnomons
#check DkMath.NumberTheory.Legendre.squareResidueCoverFiber
#print axioms DkMath.NumberTheory.Legendre.squareResidueCoverFiber
#check DkMath.NumberTheory.Legendre.mem_squareResidueCoverFiber
#print axioms DkMath.NumberTheory.Legendre.mem_squareResidueCoverFiber
#check DkMath.NumberTheory.Legendre.coveredSquareOffsets_eq_residue_union
#print axioms DkMath.NumberTheory.Legendre.coveredSquareOffsets_eq_residue_union
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_residue_union
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_residue_union
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_pointwise_forbidden_residue
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_pointwise_forbidden_residue
#check DkMath.NumberTheory.Legendre.squareShellWheelImage
#print axioms DkMath.NumberTheory.Legendre.squareShellWheelImage
#check DkMath.NumberTheory.Legendre.mem_squareShellWheelImage
#print axioms DkMath.NumberTheory.Legendre.mem_squareShellWheelImage
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_wheel_image_reserved
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_wheel_image_reserved
#check DkMath.NumberTheory.Legendre.not_fullyCovered_iff_wheel_image_survivor
#print axioms DkMath.NumberTheory.Legendre.not_fullyCovered_iff_wheel_image_survivor
#check DkMath.NumberTheory.Legendre.SquareAnchorWheelFullyReserved
#print axioms DkMath.NumberTheory.Legendre.SquareAnchorWheelFullyReserved
#check DkMath.NumberTheory.Legendre.squareAnchorWheelFullyReserved_iff_full
#print axioms DkMath.NumberTheory.Legendre.squareAnchorWheelFullyReserved_iff_full
#check DkMath.NumberTheory.Legendre.squareResidueCoverOwner
#print axioms DkMath.NumberTheory.Legendre.squareResidueCoverOwner
#check DkMath.NumberTheory.Legendre.squareResidueCoverOwner_eq_two_iff
#print axioms DkMath.NumberTheory.Legendre.squareResidueCoverOwner_eq_two_iff
#check DkMath.NumberTheory.Legendre.squareResidueCoverOwner_packet
#print axioms DkMath.NumberTheory.Legendre.squareResidueCoverOwner_packet
#check DkMath.NumberTheory.Legendre.squareResidueOwnerFiber
#print axioms DkMath.NumberTheory.Legendre.squareResidueOwnerFiber
#check DkMath.NumberTheory.Legendre.residue_owner_fibers_disjoint
#print axioms DkMath.NumberTheory.Legendre.residue_owner_fibers_disjoint
#check DkMath.NumberTheory.Legendre.coveredSquareOffsets_eq_owner_union
#print axioms DkMath.NumberTheory.Legendre.coveredSquareOffsets_eq_owner_union
#check DkMath.NumberTheory.Legendre.residue_owner_fiber_sum
#print axioms DkMath.NumberTheory.Legendre.residue_owner_fiber_sum
#check DkMath.NumberTheory.Legendre.squareShellWheelProjection_eq_iff_modEq
#print axioms DkMath.NumberTheory.Legendre.squareShellWheelProjection_eq_iff_modEq
#check DkMath.NumberTheory.Legendre.squareShellWheelProjection_injOn_iff
#print axioms DkMath.NumberTheory.Legendre.squareShellWheelProjection_injOn_iff
#check DkMath.NumberTheory.Legendre.squareShell_period_exceeds_width
#print axioms DkMath.NumberTheory.Legendre.squareShell_period_exceeds_width
#check DkMath.NumberTheory.Legendre.squareShellWheelProjection_injOn_classification
#print axioms DkMath.NumberTheory.Legendre.squareShellWheelProjection_injOn_classification
#check DkMath.NumberTheory.Legendre.squareShellWheelImage_card_of_injective
#print axioms DkMath.NumberTheory.Legendre.squareShellWheelImage_card_of_injective
#check DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_eq_activeSupport
#print axioms DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_eq_activeSupport
#check DkMath.NumberTheory.Legendre.escapingSquareOffsets_eq_paritySafeUncovered
#print axioms DkMath.NumberTheory.Legendre.escapingSquareOffsets_eq_paritySafeUncovered
#check DkMath.NumberTheory.Legendre.squareShellWheelSurvivorImage
#print axioms DkMath.NumberTheory.Legendre.squareShellWheelSurvivorImage
#check DkMath.NumberTheory.Legendre.squareShell_survivor_filter_eq_image_escaping
#print axioms DkMath.NumberTheory.Legendre.squareShell_survivor_filter_eq_image_escaping
#check DkMath.NumberTheory.Legendre.squareShell_survivor_card_eq_uncovered
#print axioms DkMath.NumberTheory.Legendre.squareShell_survivor_card_eq_uncovered
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_uncovered_empty
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_uncovered_empty
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_rough_zero_card
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_rough_zero_card
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_no_wheel_image_survivor
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_no_wheel_image_survivor
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_all_support_nonempty
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_all_support_nonempty
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_collapsed_census
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_collapsed_census
#check DkMath.NumberTheory.Legendre.sqrt_counterexample_balance_with_uncovered
#print axioms DkMath.NumberTheory.Legendre.sqrt_counterexample_balance_with_uncovered
#check DkMath.NumberTheory.Legendre.fullyCovered_iff_corrected_balance
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_iff_corrected_balance
#check DkMath.NumberTheory.Legendre.prime_squareCell_of_corrected_counterexample_gap
#print axioms DkMath.NumberTheory.Legendre.prime_squareCell_of_corrected_counterexample_gap
#check DkMath.NumberTheory.Legendre.squareAnchor_counterexample_packet
#print axioms DkMath.NumberTheory.Legendre.squareAnchor_counterexample_packet
#check DkMath.NumberTheory.Legendre.squareResidueCoverOwner_eq_paritySafeCanonical
#print axioms DkMath.NumberTheory.Legendre.squareResidueCoverOwner_eq_paritySafeCanonical
#check DkMath.NumberTheory.Legendre.squareResidueCoverOwner_eq_of_least_active
#print axioms DkMath.NumberTheory.Legendre.squareResidueCoverOwner_eq_of_least_active
#check DkMath.NumberTheory.Legendre.sqrt_cube_residue_owner
#print axioms DkMath.NumberTheory.Legendre.sqrt_cube_residue_owner
#check DkMath.NumberTheory.Legendre.sqrt_cross_residue_owner
#print axioms DkMath.NumberTheory.Legendre.sqrt_cross_residue_owner
#check DkMath.NumberTheory.Legendre.sqrt_repeated_residue_owner
#print axioms DkMath.NumberTheory.Legendre.sqrt_repeated_residue_owner
#check DkMath.NumberTheory.Legendre.sqrt_triple_residue_owner
#print axioms DkMath.NumberTheory.Legendre.sqrt_triple_residue_owner
#check DkMath.NumberTheory.Legendre.sqrt_small_prime_dvd_product_iff_quotient
#print axioms DkMath.NumberTheory.Legendre.sqrt_small_prime_dvd_product_iff_quotient
#check DkMath.NumberTheory.Legendre.sqrt_small_basis_reservation_product_iff
#print axioms DkMath.NumberTheory.Legendre.sqrt_small_basis_reservation_product_iff
#check DkMath.NumberTheory.Legendre.sqrt_rejected_iff_quotient_wheel_reserved
#print axioms DkMath.NumberTheory.Legendre.sqrt_rejected_iff_quotient_wheel_reserved
#check DkMath.NumberTheory.Legendre.sqrt_two_level_reservation_packet
#print axioms DkMath.NumberTheory.Legendre.sqrt_two_level_reservation_packet
#check DkMath.NumberTheory.Legendre.squareAnchor_old_basis_succ
#print axioms DkMath.NumberTheory.Legendre.squareAnchor_old_basis_succ
#check DkMath.NumberTheory.Legendre.squareAnchor_prime_threshold_projects_old
#print axioms DkMath.NumberTheory.Legendre.squareAnchor_prime_threshold_projects_old
#check DkMath.NumberTheory.Legendre.successorThresholdInsert_squareOffset
#print axioms DkMath.NumberTheory.Legendre.successorThresholdInsert_squareOffset
#check DkMath.NumberTheory.Legendre.residue_owner_persistence_mem_inter
#print axioms DkMath.NumberTheory.Legendre.residue_owner_persistence_mem_inter
#check DkMath.NumberTheory.Legendre.residue_owner_persistence_lower
#print axioms DkMath.NumberTheory.Legendre.residue_owner_persistence_lower
#check DkMath.NumberTheory.Legendre.residue_owner_changes_lower
#print axioms DkMath.NumberTheory.Legendre.residue_owner_changes_lower
#check DkMath.NumberTheory.Legendre.residue_owner_persistence_upper
#print axioms DkMath.NumberTheory.Legendre.residue_owner_persistence_upper
#check DkMath.NumberTheory.Legendre.residue_owner_persistence_prime_upper
#print axioms DkMath.NumberTheory.Legendre.residue_owner_persistence_prime_upper
#check DkMath.NumberTheory.Legendre.residue_owner_changes_prime_upper_odd
#print axioms DkMath.NumberTheory.Legendre.residue_owner_changes_prime_upper_odd
#check DkMath.NumberTheory.Legendre.residue_owner_no_three_lower
#print axioms DkMath.NumberTheory.Legendre.residue_owner_no_three_lower
#check DkMath.NumberTheory.Legendre.fullyCovered_three_lower_owner_change
#print axioms DkMath.NumberTheory.Legendre.fullyCovered_three_lower_owner_change
#check DkMath.NumberTheory.Legendre.primorial_sqrt_address
#print axioms DkMath.NumberTheory.Legendre.primorial_sqrt_address
#check DkMathTest.LegendreResidueCoverRegression.small_periods
#print axioms DkMathTest.LegendreResidueCoverRegression.small_periods
#check DkMathTest.LegendreResidueCoverRegression.small_collisions
#print axioms DkMathTest.LegendreResidueCoverRegression.small_collisions
#check DkMathTest.LegendreResidueCoverRegression.three_width_equal_period_injective
#print axioms DkMathTest.LegendreResidueCoverRegression.three_width_equal_period_injective
#check DkMathTest.LegendreResidueCoverRegression.four_basis_and_image
#print axioms DkMathTest.LegendreResidueCoverRegression.four_basis_and_image
#check DkMathTest.LegendreResidueCoverRegression.four_survivor_filter
#print axioms DkMathTest.LegendreResidueCoverRegression.four_survivor_filter
#check DkMathTest.LegendreResidueCoverRegression.four_multiplicity
#print axioms DkMathTest.LegendreResidueCoverRegression.four_multiplicity
#check DkMathTest.LegendreResidueCoverRegression.four_one_residue_and_survivor
#print axioms DkMathTest.LegendreResidueCoverRegression.four_one_residue_and_survivor
#check DkMathTest.LegendreResidueCoverRegression.one_carrier_boundary
#print axioms DkMathTest.LegendreResidueCoverRegression.one_carrier_boundary
#check DkMathTest.LegendreResidueCoverRegression.repeated_eight_owner
#print axioms DkMathTest.LegendreResidueCoverRegression.repeated_eight_owner
#check DkMathTest.LegendreResidueCoverRegression.repeated_prime_twentyNine_owner
#print axioms DkMathTest.LegendreResidueCoverRegression.repeated_prime_twentyNine_owner
#check DkMathTest.LegendreResidueCoverRegression.repeated_thirteen_owner
#print axioms DkMathTest.LegendreResidueCoverRegression.repeated_thirteen_owner
#check DkMathTest.LegendreResidueCoverRegression.triple_nineteen_owner
#print axioms DkMathTest.LegendreResidueCoverRegression.triple_nineteen_owner
#check DkMathTest.LegendreResidueCoverRegression.cube_cross_owner
#print axioms DkMathTest.LegendreResidueCoverRegression.cube_cross_owner
#check DkMathTest.LegendreResidueCoverRegression.rejected_eleven_two_levels
#print axioms DkMathTest.LegendreResidueCoverRegression.rejected_eleven_two_levels
#check DkMathTest.LegendreResidueCoverRegression.three_lower_owners
#print axioms DkMathTest.LegendreResidueCoverRegression.three_lower_owners
#check DkMathTest.LegendreResidueCoverRegression.lower_support_persists_without_owner
#print axioms DkMathTest.LegendreResidueCoverRegression.lower_support_persists_without_owner
#check DkMathTest.LegendreResidueCoverRegression.sqrt_primorial_address_not_above_anchor
#print axioms DkMathTest.LegendreResidueCoverRegression.sqrt_primorial_address_not_above_anchor
#check DkMathTest.LegendreResidueCoverCalibration.near_miss_five_escape
#print axioms DkMathTest.LegendreResidueCoverCalibration.near_miss_five_escape
#check DkMathTest.LegendreResidueCoverCalibration.near_miss_five_survivors
#print axioms DkMathTest.LegendreResidueCoverCalibration.near_miss_five_survivors
#check DkMathTest.LegendreResidueCoverCalibration.near_miss_five_uncovered
#print axioms DkMathTest.LegendreResidueCoverCalibration.near_miss_five_uncovered
#check DkMathTest.LegendreResidueCoverCalibration.near_miss_five_anchor_image
#print axioms DkMathTest.LegendreResidueCoverCalibration.near_miss_five_anchor_image
#check DkMathTest.LegendreResidueCoverCalibration.residue1031_not_full
#print axioms DkMathTest.LegendreResidueCoverCalibration.residue1031_not_full
#check DkMathTest.LegendreResidueCoverCalibration.residue1031_wheel_survivor
#print axioms DkMathTest.LegendreResidueCoverCalibration.residue1031_wheel_survivor
#check DkMathTest.LegendreResidueCoverCalibration.residue1031_projected_survivor_lower
#print axioms DkMathTest.LegendreResidueCoverCalibration.residue1031_projected_survivor_lower
#check DkMathTest.LegendreResidueCoverCalibration.residue1031_corrected_balance_fails
#print axioms DkMathTest.LegendreResidueCoverCalibration.residue1031_corrected_balance_fails
#check DkMathTest.LegendreResidueCoverCalibration.residue1031_preserved_endpoint
#print axioms DkMathTest.LegendreResidueCoverCalibration.residue1031_preserved_endpoint
