/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreHybridClassification

#print "file: DkMathTest.NumberTheory.LegendreHybridProviderAxiomAudit"

#check DkMath.NumberTheory.card_le_sub_two_exclusions
#print axioms DkMath.NumberTheory.card_le_sub_two_exclusions
#check DkMath.NumberTheory.Legendre.paritySafeOddQuotientUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeOddQuotientUpper
#check DkMath.NumberTheory.Legendre.paritySafeDivisorWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeDivisorWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeQuotientWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeQuotientWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeIncidenceUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeIncidenceUpper
#check DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_spacing
#print axioms DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_spacing
#check DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_oddUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_oddUpper
#check DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_divisorUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_divisorUpper
#check DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_quotientUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_quotientUpper
#check DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_waveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_waveUpper
#check DkMath.NumberTheory.Legendre.paritySafeWaveUpper_le_oddUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeWaveUpper_le_oddUpper
#check DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_upper
#print axioms DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_upper
#check DkMath.NumberTheory.Legendre.paritySafePairDivisorWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafePairDivisorWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeTwoPrimeWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeTwoPrimeWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper
#check DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_pairDivisorUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_pairDivisorUpper
#check DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_twoPrimeWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_twoPrimeWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeTwoPrimeWaveUpper_le_waveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeTwoPrimeWaveUpper_le_waveUpper
#check DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_twoPrimeUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_twoPrimeUpper
#check DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper_le_upper
#print axioms DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper_le_upper
#check DkMath.NumberTheory.Legendre.paritySafeTwoPrimeWaveUpper_eq_waveUpper_of_card_le_one
#print axioms DkMath.NumberTheory.Legendre.paritySafeTwoPrimeWaveUpper_eq_waveUpper_of_card_le_one
#check DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper_eq_upper_of_card_le_one
#print axioms DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper_eq_upper_of_card_le_one
#check DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper_eq_upper_two_pow_mul_prime_pow
#print axioms DkMath.NumberTheory.Legendre.paritySafeTwoPrimeIncidenceUpper_eq_upper_two_pow_mul_prime_pow
#check DkMath.NumberTheory.Legendre.paritySafeActiveSupport_subset_pointPrimeFactors
#print axioms DkMath.NumberTheory.Legendre.paritySafeActiveSupport_subset_pointPrimeFactors
#check DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_pointPrimeFactors_sum
#print axioms DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_pointPrimeFactors_sum
#check DkMath.NumberTheory.Legendre.block_candidateSupportSum_eq_reducedQuotientSum
#print axioms DkMath.NumberTheory.Legendre.block_candidateSupportSum_eq_reducedQuotientSum
#check DkMath.NumberTheory.Legendre.block_incidenceCount_le_upper
#print axioms DkMath.NumberTheory.Legendre.block_incidenceCount_le_upper
#check DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_upper_lt_candidate_add_freshBound
#print axioms DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_upper_lt_candidate_add_freshBound
#check DkMath.NumberTheory.Legendre.paritySafeUncovered_card_ge_candidate_add_excess_sub_upper
#print axioms DkMath.NumberTheory.Legendre.paritySafeUncovered_card_ge_candidate_add_excess_sub_upper
#check DkMath.NumberTheory.Legendre.block_uncovered_ge_candidate_add_excess_sub_upper
#print axioms DkMath.NumberTheory.Legendre.block_uncovered_ge_candidate_add_excess_sub_upper
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_candidate_add_excess_gt_upper
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_candidate_add_excess_gt_upper
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_block_candidate_add_excess_gt_upper
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_block_candidate_add_excess_gt_upper
#check DkMath.NumberTheory.Legendre.local_support_excess_ge_of_card_ge
#print axioms DkMath.NumberTheory.Legendre.local_support_excess_ge_of_card_ge
#check DkMath.NumberTheory.Legendre.sum_local_cost_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.sum_local_cost_le_supportExcess
#check DkMath.NumberTheory.Legendre.sum_witness_support_excess_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.sum_witness_support_excess_le_supportExcess
#check DkMath.NumberTheory.Legendre.two_seat_support_card_lower_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.two_seat_support_card_lower_le_supportExcess
#check DkMath.NumberTheory.Legendre.paritySafeUncovered_card_ge_candidate_add_excess_sub_twoPrimeUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeUncovered_card_ge_candidate_add_excess_sub_twoPrimeUpper
#check DkMath.NumberTheory.Legendre.paritySafeUncovered_nonempty_of_twoPrimeUpper_lt_candidate_add_excess
#print axioms DkMath.NumberTheory.Legendre.paritySafeUncovered_nonempty_of_twoPrimeUpper_lt_candidate_add_excess
#check DkMath.NumberTheory.Legendre.paritySafeUncovered_nonempty_of_local_witnesses
#print axioms DkMath.NumberTheory.Legendre.paritySafeUncovered_nonempty_of_local_witnesses
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_local_witnesses
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_local_witnesses
#check DkMathTest.LegendreHybridProvider.twoPrimeUpper_eq_finite
#print axioms DkMathTest.LegendreHybridProvider.twoPrimeUpper_eq_finite
#check DkMathTest.LegendreHybridProvider.mainBlock_pair_upper
#print axioms DkMathTest.LegendreHybridProvider.mainBlock_pair_upper
#check DkMathTest.LegendreHybridProvider.mainBlock_pair_upper_strict_gain
#print axioms DkMathTest.LegendreHybridProvider.mainBlock_pair_upper_strict_gain
#check DkMathTest.LegendreHybridProvider.shell21_pair_upper_strict_gain
#print axioms DkMathTest.LegendreHybridProvider.shell21_pair_upper_strict_gain
#check DkMathTest.LegendreHybridProvider.six_residual_waves_pair_corrected
#print axioms DkMathTest.LegendreHybridProvider.six_residual_waves_pair_corrected
#check DkMathTest.LegendreHybridProvider.six_residual_waves_pair_exact_diagnostic
#print axioms DkMathTest.LegendreHybridProvider.six_residual_waves_pair_exact_diagnostic
#check DkMathTest.LegendreHybridProvider.incomplete_pair_exclusion_not_exact
#print axioms DkMathTest.LegendreHybridProvider.incomplete_pair_exclusion_not_exact
#check DkMathTest.LegendreHybridProvider.missing_intersection_credit_not_upper
#print axioms DkMathTest.LegendreHybridProvider.missing_intersection_credit_not_upper
#check DkMathTest.LegendreHybridProvider.shell29_point_factorizations
#print axioms DkMathTest.LegendreHybridProvider.shell29_point_factorizations
#check DkMathTest.LegendreHybridProvider.shell29_candidate_seats
#print axioms DkMathTest.LegendreHybridProvider.shell29_candidate_seats
#check DkMathTest.LegendreHybridProvider.shell29_support_witnesses
#print axioms DkMathTest.LegendreHybridProvider.shell29_support_witnesses
#check DkMathTest.LegendreHybridProvider.shell29_local_card_lower
#print axioms DkMathTest.LegendreHybridProvider.shell29_local_card_lower
#check DkMathTest.LegendreHybridProvider.shell29_local_excess_lower
#print axioms DkMathTest.LegendreHybridProvider.shell29_local_excess_lower
#check DkMathTest.LegendreHybridProvider.shell29_supportExcess_ge_four
#print axioms DkMathTest.LegendreHybridProvider.shell29_supportExcess_ge_four
#check DkMathTest.LegendreHybridProvider.shell29_pair_cap_and_candidate
#print axioms DkMathTest.LegendreHybridProvider.shell29_pair_cap_and_candidate
#check DkMathTest.LegendreHybridProvider.shell29_uncovered_ge_one
#print axioms DkMathTest.LegendreHybridProvider.shell29_uncovered_ge_one
#check DkMathTest.LegendreHybridProvider.shell29_uncovered_nonempty
#print axioms DkMathTest.LegendreHybridProvider.shell29_uncovered_nonempty
#check DkMathTest.LegendreHybridProvider.shell29_prime
#print axioms DkMathTest.LegendreHybridProvider.shell29_prime
#check DkMathTest.LegendreHybridClassification.classZeroData
#print axioms DkMathTest.LegendreHybridClassification.classZeroData
#check DkMathTest.LegendreHybridClassification.classOneData
#print axioms DkMathTest.LegendreHybridClassification.classOneData
#check DkMathTest.LegendreHybridClassification.classTwoData
#print axioms DkMathTest.LegendreHybridClassification.classTwoData
#check DkMathTest.LegendreHybridClassification.classOneCertificates
#print axioms DkMathTest.LegendreHybridClassification.classOneCertificates
#check DkMathTest.LegendreHybridClassification.classification_caps_checked
#print axioms DkMathTest.LegendreHybridClassification.classification_caps_checked
#check DkMathTest.LegendreHybridClassification.classification_partition_checked
#print axioms DkMathTest.LegendreHybridClassification.classification_partition_checked
#check DkMathTest.LegendreHybridClassification.class_one_certificates_checked
#print axioms DkMathTest.LegendreHybridClassification.class_one_certificates_checked
#check DkMathTest.LegendreHybridClassification.class_one_certified_excess
#print axioms DkMathTest.LegendreHybridClassification.class_one_certified_excess
#check DkMathTest.LegendreHybridClassification.class_one_gap_checked
#print axioms DkMathTest.LegendreHybridClassification.class_one_gap_checked
#check DkMathTest.LegendreHybridClassification.class_one_uncovered
#print axioms DkMathTest.LegendreHybridClassification.class_one_uncovered
#check DkMathTest.LegendreHybridClassification.class_one_prime
#print axioms DkMathTest.LegendreHybridClassification.class_one_prime
#check DkMathTest.LegendreHybridClassification.class_zero_uncovered
#print axioms DkMathTest.LegendreHybridClassification.class_zero_uncovered
#check DkMathTest.LegendreHybridClassification.class_zero_prime
#print axioms DkMathTest.LegendreHybridClassification.class_zero_prime
#check DkMathTest.LegendreHybridClassification.gainShellData
#print axioms DkMathTest.LegendreHybridClassification.gainShellData
#check DkMathTest.LegendreHybridClassification.gain_shells_checked
#print axioms DkMathTest.LegendreHybridClassification.gain_shells_checked
#check DkMathTest.LegendreHybridClassification.class_two_budget_obstruction
#print axioms DkMathTest.LegendreHybridClassification.class_two_budget_obstruction
#check DkMathTest.LegendreHybridClassification.two_odd_anchor_primes_zero_excess_counterexample
#print axioms DkMathTest.LegendreHybridClassification.two_odd_anchor_primes_zero_excess_counterexample
#check DkMathTest.LegendreHybridClassification.two_odd_anchor_primes_small_certificate_counterexample
#print axioms DkMathTest.LegendreHybridClassification.two_odd_anchor_primes_small_certificate_counterexample
