/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreBlockLocalization

#print "file: DkMathTest.NumberTheory.LegendreBlockLocalizationAxiomAudit"

#check DkMath.NumberTheory.Legendre.activeSupport_excess_le_pair
#print axioms DkMath.NumberTheory.Legendre.activeSupport_excess_le_pair
#check DkMath.NumberTheory.Legendre.paritySafeSupportExcess_le_pairOverlap
#print axioms DkMath.NumberTheory.Legendre.paritySafeSupportExcess_le_pairOverlap
#check DkMath.NumberTheory.Legendre.paritySafeSupportExcess_le_outsidePair_add_collisionSupportCost
#print axioms DkMath.NumberTheory.Legendre.paritySafeSupportExcess_le_outsidePair_add_collisionSupportCost
#check DkMath.NumberTheory.Legendre.paritySafeSupportExcess_le_outsidePair_add_collisionSupport_add_baseline_add_depthResidual
#print axioms DkMath.NumberTheory.Legendre.paritySafeSupportExcess_le_outsidePair_add_collisionSupport_add_baseline_add_depthResidual
#check DkMath.NumberTheory.Legendre.sum_supportExcess_eq_outsideSupport_add_collisionSupport
#print axioms DkMath.NumberTheory.Legendre.sum_supportExcess_eq_outsideSupport_add_collisionSupport
#check DkMath.NumberTheory.Legendre.block_freshBound_le_outsideSupport_add_collisionSupport
#print axioms DkMath.NumberTheory.Legendre.block_freshBound_le_outsideSupport_add_collisionSupport
#check DkMath.NumberTheory.Legendre.block_freshBound_le_outsidePair_add_collisionSupport
#print axioms DkMath.NumberTheory.Legendre.block_freshBound_le_outsidePair_add_collisionSupport
#check DkMath.NumberTheory.Legendre.block_candidate_add_supportExcess_eq_incidence
#print axioms DkMath.NumberTheory.Legendre.block_candidate_add_supportExcess_eq_incidence
#check DkMath.NumberTheory.Legendre.block_incidence_add_uncovered_eq_candidate_add_supportExcess
#print axioms DkMath.NumberTheory.Legendre.block_incidence_add_uncovered_eq_candidate_add_supportExcess
#check DkMath.NumberTheory.Legendre.block_readable_frontier_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.block_readable_frontier_of_fullyCovered
#check DkMath.NumberTheory.Legendre.block_readable_frontier_iff_support_frontier
#print axioms DkMath.NumberTheory.Legendre.block_readable_frontier_iff_support_frontier
#check DkMath.NumberTheory.Legendre.block_secondCancellation_iff_reducedSupportCharge
#print axioms DkMath.NumberTheory.Legendre.block_secondCancellation_iff_reducedSupportCharge
#check DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_localized_capacity_lt_freshBound
#print axioms DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_localized_capacity_lt_freshBound
#check DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_incidence_lt_candidate_add_freshBound
#print axioms DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_incidence_lt_candidate_add_freshBound
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_not_block_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_not_block_fullyCovered
#check DkMathTest.LegendreBlockLocalization.candidate_eq_filter_Icc
#print axioms DkMathTest.LegendreBlockLocalization.candidate_eq_filter_Icc
#check DkMathTest.LegendreBlockLocalization.mainBlock_candidate_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_candidate_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_incidence_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_incidence_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_supportExcess_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_supportExcess_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_pairOverlap_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_pairOverlap_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_residualPair_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_residualPair_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_support_card_le_three
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_support_card_le_three
#check DkMathTest.LegendreBlockLocalization.mainBlock_collision_empty
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_collision_empty
#check DkMathTest.LegendreBlockLocalization.mainBlock_fifth_empty
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_fifth_empty
#check DkMathTest.LegendreBlockLocalization.mainBlock_collisionSupport_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_collisionSupport_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_outsidePair_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_outsidePair_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_outsideSupport_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_outsideSupport_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_localized_38
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_localized_38
#check DkMathTest.LegendreBlockLocalization.mainBlock_not_fullyCovered
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_not_fullyCovered
#check DkMathTest.LegendreBlockLocalization.mainBlock_not_fullyCovered_without_freshBound
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_not_fullyCovered_without_freshBound
#check DkMathTest.LegendreBlockLocalization.mainBlock_exists_prime_squareCell
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_exists_prime_squareCell
#check DkMathTest.LegendreBlockLocalization.oddActive_eq_filter_range
#print axioms DkMathTest.LegendreBlockLocalization.oddActive_eq_filter_range
#check DkMathTest.LegendreBlockLocalization.coprimeSeats_eq_filter_Icc
#print axioms DkMathTest.LegendreBlockLocalization.coprimeSeats_eq_filter_Icc
#check DkMathTest.LegendreBlockLocalization.nearFirst_eq_finite
#print axioms DkMathTest.LegendreBlockLocalization.nearFirst_eq_finite
#check DkMathTest.LegendreBlockLocalization.nearPairs_eq_finite
#print axioms DkMathTest.LegendreBlockLocalization.nearPairs_eq_finite
#check DkMathTest.LegendreBlockLocalization.mainBlock_nearPairs_empty
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_nearPairs_empty
#check DkMathTest.LegendreBlockLocalization.mainBlock_nearBudget_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_nearBudget_sum
#check DkMathTest.LegendreBlockLocalization.depthBudget_eq_finite
#print axioms DkMathTest.LegendreBlockLocalization.depthBudget_eq_finite
#check DkMathTest.LegendreBlockLocalization.mainBlock_depthBudget_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_depthBudget_sum
#check DkMathTest.LegendreBlockLocalization.fourthCapacity_eq_finite
#print axioms DkMathTest.LegendreBlockLocalization.fourthCapacity_eq_finite
#check DkMathTest.LegendreBlockLocalization.mainBlock_fourthCapacity_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_fourthCapacity_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_lowCostCapacity_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_lowCostCapacity_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_collision_terms
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_collision_terms
#check DkMathTest.LegendreBlockLocalization.mainBlock_support_frontier_slack
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_support_frontier_slack
#check DkMathTest.LegendreBlockLocalization.mainBlock_fullCover_frontier_deficit
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_fullCover_frontier_deficit
#check DkMathTest.LegendreBlockLocalization.mainBlock_not_fullyCovered_from_readable_frontier
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_not_fullyCovered_from_readable_frontier
#check DkMathTest.LegendreBlockLocalization.mainBlock_uncovered_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_uncovered_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_excess_not_bounded_by_collisionCost
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_excess_not_bounded_by_collisionCost
#check DkMathTest.LegendreBlockLocalization.fresh_charge_without_collision
#print axioms DkMathTest.LegendreBlockLocalization.fresh_charge_without_collision
#check DkMathTest.LegendreBlockLocalization.lower_bound_substitution_false
#print axioms DkMathTest.LegendreBlockLocalization.lower_bound_substitution_false
#check DkMathTest.LegendreBlockLocalization.terminalKeys_eq_finite
#print axioms DkMathTest.LegendreBlockLocalization.terminalKeys_eq_finite
#check DkMathTest.LegendreBlockLocalization.mainBlock_terminalKeys_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_terminalKeys_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_lowCostAfterUnused_sum
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_lowCostAfterUnused_sum
#check DkMathTest.LegendreBlockLocalization.mainBlock_secondCancellation_slack
#print axioms DkMathTest.LegendreBlockLocalization.mainBlock_secondCancellation_slack
