import DkMath.NumberTheory.Legendre.ParitySafePersistence
import DkMathTest.NumberTheory.LegendreCyclotomicPersistence

-- Complete source-extracted coverage of new production and named regression declarations.
#check DkMath.NumberTheory.Legendre.cyclotomicShiftedEval_two_eq_oddGnomon
#print axioms DkMath.NumberTheory.Legendre.cyclotomicShiftedEval_two_eq_oddGnomon
#check DkMath.NumberTheory.Legendre.mem_lower_commonSupport_iff_cyclotomic
#print axioms DkMath.NumberTheory.Legendre.mem_lower_commonSupport_iff_cyclotomic
#check DkMath.NumberTheory.Legendre.not_dvd_coordinates_of_dvd_oddGnomon
#print axioms DkMath.NumberTheory.Legendre.not_dvd_coordinates_of_dvd_oddGnomon
#check DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_primeOrder_eq_two
#print axioms DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_primeOrder_eq_two
#check DkMath.NumberTheory.Legendre.dvd_cyclotomic_lower_iff_primeOrder_eq_two
#print axioms DkMath.NumberTheory.Legendre.dvd_cyclotomic_lower_iff_primeOrder_eq_two
#check DkMath.NumberTheory.Legendre.mem_lower_commonSupport_iff_primeOrder_eq_two
#print axioms DkMath.NumberTheory.Legendre.mem_lower_commonSupport_iff_primeOrder_eq_two
#check DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_modEq_half
#print axioms DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_modEq_half
#check DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_eq_half_add_mul
#print axioms DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_eq_half_add_mul
#check DkMath.NumberTheory.Legendre.modEq_of_dvd_oddGnomon
#print axioms DkMath.NumberTheory.Legendre.modEq_of_dvd_oddGnomon
#check DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_modEq_of_dvd
#print axioms DkMath.NumberTheory.Legendre.dvd_oddGnomon_iff_modEq_of_dvd
#check DkMath.NumberTheory.Legendre.dvd_four_mul_offset_add_one_of_lower_persistence
#print axioms DkMath.NumberTheory.Legendre.dvd_four_mul_offset_add_one_of_lower_persistence
#check DkMath.NumberTheory.Legendre.not_dvd_oddGnomon_succ
#print axioms DkMath.NumberTheory.Legendre.not_dvd_oddGnomon_succ
#check DkMath.NumberTheory.Legendre.lowerPrimeAddressOffsets
#print axioms DkMath.NumberTheory.Legendre.lowerPrimeAddressOffsets
#check DkMath.NumberTheory.Legendre.shellFrequencyCap
#print axioms DkMath.NumberTheory.Legendre.shellFrequencyCap
#check DkMath.NumberTheory.Legendre.lowerPrimeAddressOffsets_card_le
#print axioms DkMath.NumberTheory.Legendre.lowerPrimeAddressOffsets_card_le
#check DkMath.NumberTheory.Legendre.lowerPrimeAddressOffsets_period_card_le_one
#print axioms DkMath.NumberTheory.Legendre.lowerPrimeAddressOffsets_period_card_le_one
#check DkMath.NumberTheory.Legendre.lower_successor_not_paritySafeCandidate_of_odd
#print axioms DkMath.NumberTheory.Legendre.lower_successor_not_paritySafeCandidate_of_odd
#check DkMath.NumberTheory.Legendre.disjoint_upper_oldSupport_paritySafeActiveSupport
#print axioms DkMath.NumberTheory.Legendre.disjoint_upper_oldSupport_paritySafeActiveSupport
#check DkMath.NumberTheory.Legendre.lowerParitySafeCandidates
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeCandidates
#check DkMath.NumberTheory.Legendre.lowerParitySafeCandidates_eq_filter_Icc
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeCandidates_eq_filter_Icc
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport
#check DkMath.NumberTheory.Legendre.lowerParitySafeFreshSupport
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeFreshSupport
#check DkMath.NumberTheory.Legendre.lowerParitySafeIncidenceCount
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeIncidenceCount
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistentCount
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistentCount
#check DkMath.NumberTheory.Legendre.lowerParitySafeFreshCount
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeFreshCount
#check DkMath.NumberTheory.Legendre.lowerParitySafeIncidenceCount_eq_persistent_add_fresh
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeIncidenceCount_eq_persistent_add_fresh
#check DkMath.NumberTheory.Legendre.lowerParitySafeIncidenceCount_le_incidence
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeIncidenceCount_le_incidence
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport_subset_addresses
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport_subset_addresses
#check DkMath.NumberTheory.Legendre.lowerParitySafeCandidates_card_le
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeCandidates_card_le
#check DkMath.NumberTheory.Legendre.lowerPersistentSeatPool
#print axioms DkMath.NumberTheory.Legendre.lowerPersistentSeatPool
#check DkMath.NumberTheory.Legendre.lowerPersistentSeatPool_card_le
#print axioms DkMath.NumberTheory.Legendre.lowerPersistentSeatPool_card_le
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistentCount_le_seatWeighted_addresses
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistentCount_le_seatWeighted_addresses
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistentCount_le_weighted_addresses
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistentCount_le_weighted_addresses
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistenceCap
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistenceCap
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistenceCap_le_crude
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistenceCap_le_crude
#check DkMath.NumberTheory.Legendre.sum_lowerParitySafePersistentCount_le_cap
#print axioms DkMath.NumberTheory.Legendre.sum_lowerParitySafePersistentCount_le_cap
#check DkMath.NumberTheory.Legendre.sum_lowerParitySafeIncidenceCount_sub_cap_le_fresh
#print axioms DkMath.NumberTheory.Legendre.sum_lowerParitySafeIncidenceCount_sub_cap_le_fresh
#check DkMath.NumberTheory.Legendre.lowerParitySafeCandidates_card_le_incidence_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeCandidates_card_le_incidence_of_fullyCovered
#check DkMath.NumberTheory.Legendre.sum_lowerParitySafeCandidates_sub_cap_le_fresh_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.sum_lowerParitySafeCandidates_sub_cap_le_fresh_of_fullyCovered
#check DkMathTest.LegendreCyclotomicPersistence.three_shell_addresses
#print axioms DkMathTest.LegendreCyclotomicPersistence.three_shell_addresses
#check DkMathTest.LegendreCyclotomicPersistence.three_order_two_at_shell_ten
#print axioms DkMathTest.LegendreCyclotomicPersistence.three_order_two_at_shell_ten
#check DkMathTest.LegendreCyclotomicPersistence.three_no_next_shell
#print axioms DkMathTest.LegendreCyclotomicPersistence.three_no_next_shell
#check DkMathTest.LegendreCyclotomicPersistence.three_run_regression
#print axioms DkMathTest.LegendreCyclotomicPersistence.three_run_regression
#check DkMathTest.LegendreCyclotomicPersistence.frequency_boundaries
#print axioms DkMathTest.LegendreCyclotomicPersistence.frequency_boundaries
#check DkMathTest.LegendreCyclotomicPersistence.shell_ten_two_persistent_three_seats
#print axioms DkMathTest.LegendreCyclotomicPersistence.shell_ten_two_persistent_three_seats
#check DkMathTest.LegendreCyclotomicPersistence.unweighted_single_prime_frequency_bound_false
#print axioms DkMathTest.LegendreCyclotomicPersistence.unweighted_single_prime_frequency_bound_false
#check DkMathTest.LegendreCyclotomicPersistence.lower_parity_reversal_regression
#print axioms DkMathTest.LegendreCyclotomicPersistence.lower_parity_reversal_regression
#check DkMathTest.LegendreCyclotomicPersistence.seat_weight_capacity_regression
#print axioms DkMathTest.LegendreCyclotomicPersistence.seat_weight_capacity_regression
#check DkMathTest.LegendreCyclotomicPersistence.fresh_incidence_without_support_excess
#print axioms DkMathTest.LegendreCyclotomicPersistence.fresh_incidence_without_support_excess
#check DkMathTest.LegendreCyclotomicPersistence.twenty_transition_fresh_lower_bound
#print axioms DkMathTest.LegendreCyclotomicPersistence.twenty_transition_fresh_lower_bound
