/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreDeletionRegression
import DkMathTest.NumberTheory.LegendreCapacity297Calibration
import DkMathTest.NumberTheory.LegendreDeletionProvenance
import DkMathTest.NumberTheory.LegendreCapacity1031Calibration
import DkMathTest.NumberTheory.LegendreDeletion1031Strictness

#print "file: DkMathTest.NumberTheory.LegendreDeletionAxiomAudit"

#check DkMath.Combinatorics.supportCollisionEdges
#print axioms DkMath.Combinatorics.supportCollisionEdges
#check DkMath.Combinatorics.mem_supportCollisionEdges
#print axioms DkMath.Combinatorics.mem_supportCollisionEdges
#check DkMath.Combinatorics.supportCollisionDeletionVertices
#print axioms DkMath.Combinatorics.supportCollisionDeletionVertices
#check DkMath.Combinatorics.supportPackingRemainder
#print axioms DkMath.Combinatorics.supportPackingRemainder
#check DkMath.Combinatorics.mem_supportCollisionDeletionVertices
#print axioms DkMath.Combinatorics.mem_supportCollisionDeletionVertices
#check DkMath.Combinatorics.mem_supportPackingRemainder
#print axioms DkMath.Combinatorics.mem_supportPackingRemainder
#check DkMath.Combinatorics.supportCollisionDeletionVertices_subset
#print axioms DkMath.Combinatorics.supportCollisionDeletionVertices_subset
#check DkMath.Combinatorics.supportPackingRemainder_subset
#print axioms DkMath.Combinatorics.supportPackingRemainder_subset
#check DkMath.Combinatorics.disjoint_supportPackingRemainder_deletion
#print axioms DkMath.Combinatorics.disjoint_supportPackingRemainder_deletion
#check DkMath.Combinatorics.supportPackingRemainder_union_deletion
#print axioms DkMath.Combinatorics.supportPackingRemainder_union_deletion
#check DkMath.Combinatorics.card_supportPacking_partition
#print axioms DkMath.Combinatorics.card_supportPacking_partition
#check DkMath.Combinatorics.card_supportCollisionDeletionVertices_le_edges
#print axioms DkMath.Combinatorics.card_supportCollisionDeletionVertices_le_edges
#check DkMath.Combinatorics.supportPackingRemainder_pairwiseDisjoint
#print axioms DkMath.Combinatorics.supportPackingRemainder_pairwiseDisjoint
#check DkMath.Combinatorics.supportPacking_exact_packet
#print axioms DkMath.Combinatorics.supportPacking_exact_packet
#check DkMath.Combinatorics.supportCollisionRightDeletionVertices
#print axioms DkMath.Combinatorics.supportCollisionRightDeletionVertices
#check DkMath.Combinatorics.supportPackingRightRemainder
#print axioms DkMath.Combinatorics.supportPackingRightRemainder
#check DkMath.Combinatorics.mem_supportCollisionRightDeletionVertices
#print axioms DkMath.Combinatorics.mem_supportCollisionRightDeletionVertices
#check DkMath.Combinatorics.supportCollisionRightDeletionVertices_subset
#print axioms DkMath.Combinatorics.supportCollisionRightDeletionVertices_subset
#check DkMath.Combinatorics.card_supportPackingRight_partition
#print axioms DkMath.Combinatorics.card_supportPackingRight_partition
#check DkMath.Combinatorics.supportPackingRightRemainder_pairwiseDisjoint
#print axioms DkMath.Combinatorics.supportPackingRightRemainder_pairwiseDisjoint
#check DkMath.Combinatorics.exists_supportPacking
#print axioms DkMath.Combinatorics.exists_supportPacking
#check DkMath.NumberTheory.Legendre.boundedSquareSupport
#print axioms DkMath.NumberTheory.Legendre.boundedSquareSupport
#check DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_eq_boundedSquareSupport
#print axioms DkMath.NumberTheory.Legendre.squareOffsetPrimeSupport_eq_boundedSquareSupport
#check DkMath.NumberTheory.Legendre.oldSupportSeatFiber
#print axioms DkMath.NumberTheory.Legendre.oldSupportSeatFiber
#check DkMath.NumberTheory.Legendre.pairwiseDisjoint_squareSupport_iff_fiber_card
#print axioms DkMath.NumberTheory.Legendre.pairwiseDisjoint_squareSupport_iff_fiber_card
#check DkMath.NumberTheory.Legendre.OldSupportCapacityCertificate
#print axioms DkMath.NumberTheory.Legendre.OldSupportCapacityCertificate
#check DkMath.NumberTheory.Legendre.checkOldSupportCapacityCertificate
#print axioms DkMath.NumberTheory.Legendre.checkOldSupportCapacityCertificate
#check DkMath.NumberTheory.Legendre.checkOldSupportCapacityCertificate_eq_true_iff
#print axioms DkMath.NumberTheory.Legendre.checkOldSupportCapacityCertificate_eq_true_iff
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_oldSupportCapacityCertificate
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_oldSupportCapacityCertificate
#check DkMath.NumberTheory.Legendre.coarseTownDeletionVertices
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionVertices
#check DkMath.NumberTheory.Legendre.coarseTownPackingRemainder
#print axioms DkMath.NumberTheory.Legendre.coarseTownPackingRemainder
#check DkMath.NumberTheory.Legendre.mem_coarseTownDeletionVertices
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownDeletionVertices
#check DkMath.NumberTheory.Legendre.mem_coarseTownPackingRemainder
#print axioms DkMath.NumberTheory.Legendre.mem_coarseTownPackingRemainder
#check DkMath.NumberTheory.Legendre.coarseTownDeletionVertices_subset
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionVertices_subset
#check DkMath.NumberTheory.Legendre.coarseTownPackingRemainder_subset
#print axioms DkMath.NumberTheory.Legendre.coarseTownPackingRemainder_subset
#check DkMath.NumberTheory.Legendre.disjoint_coarseTownRemainder_deletion
#print axioms DkMath.NumberTheory.Legendre.disjoint_coarseTownRemainder_deletion
#check DkMath.NumberTheory.Legendre.coarseTownRemainder_union_deletion
#print axioms DkMath.NumberTheory.Legendre.coarseTownRemainder_union_deletion
#check DkMath.NumberTheory.Legendre.coarseTownPackingRemainder_family
#print axioms DkMath.NumberTheory.Legendre.coarseTownPackingRemainder_family
#check DkMath.NumberTheory.Legendre.card_coarseTownDeletion_partition
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownDeletion_partition
#check DkMath.NumberTheory.Legendre.card_coarseTownPackingRemainder
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownPackingRemainder
#check DkMath.NumberTheory.Legendre.coarseTownDeletion_period_partition
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletion_period_partition
#check DkMath.NumberTheory.Legendre.card_coarseTownDeletionVertices_le_edges
#print axioms DkMath.NumberTheory.Legendre.card_coarseTownDeletionVertices_le_edges
#check DkMath.NumberTheory.Legendre.coarseTown_deletion_deficit_of_edge_deficit
#print axioms DkMath.NumberTheory.Legendre.coarseTown_deletion_deficit_of_edge_deficit
#check DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_deletion_deficit
#print axioms DkMath.NumberTheory.Legendre.not_fullyCovered_of_coarseTown_deletion_deficit
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_deletion_deficit
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_coarseTown_deletion_deficit
#check DkMath.NumberTheory.Legendre.coarseTownDivisibilityFiber
#print axioms DkMath.NumberTheory.Legendre.coarseTownDivisibilityFiber
#check DkMath.NumberTheory.Legendre.coarseTownDeletionByFibers
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionByFibers
#check DkMath.NumberTheory.Legendre.coarseTownDeletionVertices_eq_fibers
#print axioms DkMath.NumberTheory.Legendre.coarseTownDeletionVertices_eq_fibers
#check DkMathTest.LegendreDeletionRegression.tiny_collision_free
#print axioms DkMathTest.LegendreDeletionRegression.tiny_collision_free
#check DkMathTest.LegendreDeletionRegression.six_shared_first_endpoints
#print axioms DkMathTest.LegendreDeletionRegression.six_shared_first_endpoints
#check DkMathTest.LegendreDeletionRegression.six_strict_deletion_vs_edge
#print axioms DkMathTest.LegendreDeletionRegression.six_strict_deletion_vs_edge
#check DkMathTest.LegendreDeletionRegression.six_prime_via_exact_deletion
#print axioms DkMathTest.LegendreDeletionRegression.six_prime_via_exact_deletion
#check DkMathTest.LegendreDeletionRegression.eleven_edge_endpoint_preserved
#print axioms DkMathTest.LegendreDeletionRegression.eleven_edge_endpoint_preserved
#check DkMathTest.LegendreDeletionRegression.invalid_three_certificate
#print axioms DkMathTest.LegendreDeletionRegression.invalid_three_certificate
#check DkMathTest.LegendreDeletionRegression.invalid_three_certificate_semantic
#print axioms DkMathTest.LegendreDeletionRegression.invalid_three_certificate_semantic
#check DkMathTest.LegendreCapacity297Calibration.seats297
#print axioms DkMathTest.LegendreCapacity297Calibration.seats297
#check DkMathTest.LegendreCapacity297Calibration.certificate297_checked
#print axioms DkMathTest.LegendreCapacity297Calibration.certificate297_checked
#check DkMathTest.LegendreCapacity297Calibration.certificate297_semantic
#print axioms DkMathTest.LegendreCapacity297Calibration.certificate297_semantic
#check DkMathTest.LegendreCapacity297Calibration.certificate297_cards
#print axioms DkMathTest.LegendreCapacity297Calibration.certificate297_cards
#check DkMathTest.LegendreCapacity297Calibration.exists_prime_squareCell_297_of_explicitCapacityCertificate
#print axioms DkMathTest.LegendreCapacity297Calibration.exists_prime_squareCell_297_of_explicitCapacityCertificate
#check DkMathTest.LegendreDeletion1031Data.town1031SeatsList
#print axioms DkMathTest.LegendreDeletion1031Data.town1031SeatsList
#check DkMathTest.LegendreDeletion1031Data.town1031Seats
#print axioms DkMathTest.LegendreDeletion1031Data.town1031Seats
#check DkMathTest.LegendreDeletion1031Data.mem_town1031Seats
#print axioms DkMathTest.LegendreDeletion1031Data.mem_town1031Seats
#check DkMathTest.LegendreDeletion1031Data.oldPrimes1031List
#print axioms DkMathTest.LegendreDeletion1031Data.oldPrimes1031List
#check DkMathTest.LegendreDeletion1031Data.oldPrimes1031
#print axioms DkMathTest.LegendreDeletion1031Data.oldPrimes1031
#check DkMathTest.LegendreDeletion1031Data.mem_oldPrimes1031
#print axioms DkMathTest.LegendreDeletion1031Data.mem_oldPrimes1031
#check DkMathTest.LegendreDeletion1031Data.base1031SeatsList
#print axioms DkMathTest.LegendreDeletion1031Data.base1031SeatsList
#check DkMathTest.LegendreDeletion1031Data.base1031Seats
#print axioms DkMathTest.LegendreDeletion1031Data.base1031Seats
#check DkMathTest.LegendreDeletion1031Data.mem_base1031Seats
#print axioms DkMathTest.LegendreDeletion1031Data.mem_base1031Seats
#check DkMathTest.LegendreDeletion1031Data.base1031_geometry_checked
#print axioms DkMathTest.LegendreDeletion1031Data.base1031_geometry_checked
#check DkMathTest.LegendreDeletion1031Data.town1031_list_expansion
#print axioms DkMathTest.LegendreDeletion1031Data.town1031_list_expansion
#check DkMathTest.LegendreDeletion1031Data.town1031Seats_eq_production
#print axioms DkMathTest.LegendreDeletion1031Data.town1031Seats_eq_production
#check DkMathTest.LegendreDeletion1031Data.oldPrimes1031_eq_production
#print axioms DkMathTest.LegendreDeletion1031Data.oldPrimes1031_eq_production
#check DkMathTest.LegendreDeletion1031Data.oldPrimes1031_card
#print axioms DkMathTest.LegendreDeletion1031Data.oldPrimes1031_card
#check DkMathTest.LegendreDeletion1031Calibration.deletion1031_card_checked
#print axioms DkMathTest.LegendreDeletion1031Calibration.deletion1031_card_checked
#check DkMathTest.LegendreDeletion1031Calibration.deletion1031_symbolic_card
#print axioms DkMathTest.LegendreDeletion1031Calibration.deletion1031_symbolic_card
#check DkMathTest.LegendreDeletion1031Calibration.oldPrimes1031_card_checked
#print axioms DkMathTest.LegendreDeletion1031Calibration.oldPrimes1031_card_checked
#check DkMathTest.LegendreDeletion1031Calibration.remainder1031_card
#print axioms DkMathTest.LegendreDeletion1031Calibration.remainder1031_card
#check DkMathTest.LegendreDeletion1031Calibration.exists_prime_squareCell_1031_of_coarseTownDeletion
#print axioms DkMathTest.LegendreDeletion1031Calibration.exists_prime_squareCell_1031_of_coarseTownDeletion
#check DkMathTest.LegendreDeletionProvenance.both1031_named_routes
#print axioms DkMathTest.LegendreDeletionProvenance.both1031_named_routes
#check DkMathTest.LegendreCapacity1031Calibration.seats1031List
#print axioms DkMathTest.LegendreCapacity1031Calibration.seats1031List
#check DkMathTest.LegendreCapacity1031Calibration.seats1031
#print axioms DkMathTest.LegendreCapacity1031Calibration.seats1031
#check DkMathTest.LegendreCapacity1031Calibration.certificate1031_checked
#print axioms DkMathTest.LegendreCapacity1031Calibration.certificate1031_checked
#check DkMathTest.LegendreCapacity1031Calibration.certificate1031_semantic
#print axioms DkMathTest.LegendreCapacity1031Calibration.certificate1031_semantic
#check DkMathTest.LegendreCapacity1031Calibration.certificate1031_cards
#print axioms DkMathTest.LegendreCapacity1031Calibration.certificate1031_cards
#check DkMathTest.LegendreCapacity1031Calibration.exists_prime_squareCell_1031_of_explicitCapacityCertificate
#print axioms DkMathTest.LegendreCapacity1031Calibration.exists_prime_squareCell_1031_of_explicitCapacityCertificate
#check DkMathTest.LegendreDeletion1031Strictness.fiber11_card1031
#print axioms DkMathTest.LegendreDeletion1031Strictness.fiber11_card1031
#check DkMathTest.LegendreDeletion1031Strictness.strict_deletion_vs_edge1031
#print axioms DkMathTest.LegendreDeletion1031Strictness.strict_deletion_vs_edge1031
