/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre
import DkMathTest.NumberTheory.LegendreCanonicalTailRegression
import DkMathTest.NumberTheory.LegendreCanonicalTailDiagnostics
import DkMathTest.NumberTheory.LegendreCanonicalPrimeCapCalibration

#print "file: DkMathTest.NumberTheory.LegendreCanonicalTailAxiomAudit"

#check DkMath.NumberTheory.Legendre.canonicalRootHead
#print axioms DkMath.NumberTheory.Legendre.canonicalRootHead
#check DkMath.NumberTheory.Legendre.canonicalRootTail
#print axioms DkMath.NumberTheory.Legendre.canonicalRootTail
#check DkMath.NumberTheory.Legendre.canonicalRoughCandidates
#print axioms DkMath.NumberTheory.Legendre.canonicalRoughCandidates
#check DkMath.NumberTheory.Legendre.supportExcess_eq_head_add_tail
#print axioms DkMath.NumberTheory.Legendre.supportExcess_eq_head_add_tail
#check DkMath.NumberTheory.Legendre.canonicalRootHead_card_eq_root_sum
#print axioms DkMath.NumberTheory.Legendre.canonicalRootHead_card_eq_root_sum
#check DkMath.NumberTheory.Legendre.canonicalRoot_gt_iff_rough
#print axioms DkMath.NumberTheory.Legendre.canonicalRoot_gt_iff_rough
#check DkMath.NumberTheory.Legendre.supportLabel_ne_root_iff_smaller
#print axioms DkMath.NumberTheory.Legendre.supportLabel_ne_root_iff_smaller
#check DkMath.NumberTheory.Legendre.mem_canonicalRootTail_iff
#print axioms DkMath.NumberTheory.Legendre.mem_canonicalRootTail_iff
#check DkMath.NumberTheory.Legendre.canonicalHeadAtQ
#print axioms DkMath.NumberTheory.Legendre.canonicalHeadAtQ
#check DkMath.NumberTheory.Legendre.canonicalTailAtQ
#print axioms DkMath.NumberTheory.Legendre.canonicalTailAtQ
#check DkMath.NumberTheory.Legendre.canonicalRootHead_card_eq_secondary_sum
#print axioms DkMath.NumberTheory.Legendre.canonicalRootHead_card_eq_secondary_sum
#check DkMath.NumberTheory.Legendre.canonicalHeadAtQ_card_eq_pair_sum
#print axioms DkMath.NumberTheory.Legendre.canonicalHeadAtQ_card_eq_pair_sum
#check DkMath.NumberTheory.Legendre.canonicalHeadAtQ_add_tail_le_cap
#print axioms DkMath.NumberTheory.Legendre.canonicalHeadAtQ_add_tail_le_cap
#check DkMath.NumberTheory.Legendre.canonicalTailAtQ_card_le_remaining
#print axioms DkMath.NumberTheory.Legendre.canonicalTailAtQ_card_le_remaining
#check DkMath.NumberTheory.Legendre.canonicalRemainingCap
#print axioms DkMath.NumberTheory.Legendre.canonicalRemainingCap
#check DkMath.NumberTheory.Legendre.canonicalRemainingCap_eq_secondary_sum
#print axioms DkMath.NumberTheory.Legendre.canonicalRemainingCap_eq_secondary_sum
#check DkMath.NumberTheory.Legendre.canonicalRemainingCap_eq_covered_tail_slack
#print axioms DkMath.NumberTheory.Legendre.canonicalRemainingCap_eq_covered_tail_slack
#check DkMath.NumberTheory.Legendre.remainingCap_lt_candidate_iff
#print axioms DkMath.NumberTheory.Legendre.remainingCap_lt_candidate_iff
#check DkMath.NumberTheory.Legendre.uncovered_nonempty_of_remainingCap_lt
#print axioms DkMath.NumberTheory.Legendre.uncovered_nonempty_of_remainingCap_lt
#check DkMath.NumberTheory.Legendre.canonicalRootTail_card_eq_rough_support_sum
#print axioms DkMath.NumberTheory.Legendre.canonicalRootTail_card_eq_rough_support_sum
#check DkMath.NumberTheory.Legendre.activeSupport_prod_dvd_point
#print axioms DkMath.NumberTheory.Legendre.activeSupport_prod_dvd_point
#check DkMath.NumberTheory.Legendre.rough_support_pow_le_point
#print axioms DkMath.NumberTheory.Legendre.rough_support_pow_le_point
#check DkMath.NumberTheory.Legendre.rough_support_card_le
#print axioms DkMath.NumberTheory.Legendre.rough_support_card_le
#check DkMath.NumberTheory.Legendre.canonicalRootTail_card_le_rough_mul
#print axioms DkMath.NumberTheory.Legendre.canonicalRootTail_card_le_rough_mul
#check DkMath.NumberTheory.card_filter_three_exclusions
#print axioms DkMath.NumberTheory.card_filter_three_exclusions
#check DkMath.NumberTheory.Legendre.candidateAvoidThree
#print axioms DkMath.NumberTheory.Legendre.candidateAvoidThree
#check DkMath.NumberTheory.Legendre.candidateAvoidThree_card
#print axioms DkMath.NumberTheory.Legendre.candidateAvoidThree_card
#check DkMath.NumberTheory.Legendre.activePrime_below_eleven
#print axioms DkMath.NumberTheory.Legendre.activePrime_below_eleven
#check DkMath.NumberTheory.Legendre.canonicalRoot11Pair_eq
#print axioms DkMath.NumberTheory.Legendre.canonicalRoot11Pair_eq
#check DkMath.NumberTheory.Legendre.canonicalRoot11Pair_card
#print axioms DkMath.NumberTheory.Legendre.canonicalRoot11Pair_card
#check DkMath.NumberTheory.Legendre.primeAnchorAvoidThreeCount
#print axioms DkMath.NumberTheory.Legendre.primeAnchorAvoidThreeCount
#check DkMath.NumberTheory.Legendre.canonicalRootCharge11
#print axioms DkMath.NumberTheory.Legendre.canonicalRootCharge11
#check DkMath.NumberTheory.Legendre.candidateAvoidThree_card_eq_count
#print axioms DkMath.NumberTheory.Legendre.candidateAvoidThree_card_eq_count
#check DkMath.NumberTheory.Legendre.primeAnchor_root11
#print axioms DkMath.NumberTheory.Legendre.primeAnchor_root11
#check DkMath.NumberTheory.Legendre.canonicalRootCharge11_eq_fiber
#print axioms DkMath.NumberTheory.Legendre.canonicalRootCharge11_eq_fiber
#check DkMath.NumberTheory.Legendre.canonicalFourRootCharges_le_excess
#print axioms DkMath.NumberTheory.Legendre.canonicalFourRootCharges_le_excess
#check DkMath.NumberTheory.Legendre.activePrimes_smallCutoff
#print axioms DkMath.NumberTheory.Legendre.activePrimes_smallCutoff
#check DkMath.NumberTheory.Legendre.canonicalSmallHeads_eq_charges
#print axioms DkMath.NumberTheory.Legendre.canonicalSmallHeads_eq_charges
#check DkMath.NumberTheory.Legendre.mem_uncovered_iff_no_activeSupport
#print axioms DkMath.NumberTheory.Legendre.mem_uncovered_iff_no_activeSupport
#check DkMath.NumberTheory.Legendre.canonicalRoughWave
#print axioms DkMath.NumberTheory.Legendre.canonicalRoughWave
#check DkMath.NumberTheory.Legendre.roughWave_sum_eq_support_sum
#print axioms DkMath.NumberTheory.Legendre.roughWave_sum_eq_support_sum
#check DkMath.NumberTheory.Legendre.roughWave_sum_eq_covered_add_tail
#print axioms DkMath.NumberTheory.Legendre.roughWave_sum_eq_covered_add_tail
#check DkMath.NumberTheory.Legendre.uncovered_nonempty_of_roughWave_sum_lt
#print axioms DkMath.NumberTheory.Legendre.uncovered_nonempty_of_roughWave_sum_lt
#check DkMath.NumberTheory.Legendre.remainingCap_add_rough_eq_candidate_add_roughIncidence
#print axioms DkMath.NumberTheory.Legendre.remainingCap_add_rough_eq_candidate_add_roughIncidence
#check DkMath.NumberTheory.Legendre.remainingCap_lt_iff_rough_currency
#print axioms DkMath.NumberTheory.Legendre.remainingCap_lt_iff_rough_currency
#check DkMath.NumberTheory.Legendre.roughWave_sum_le_card_mul
#print axioms DkMath.NumberTheory.Legendre.roughWave_sum_le_card_mul
#check DkMath.NumberTheory.Legendre.roughCriterion_smallCutoff
#print axioms DkMath.NumberTheory.Legendre.roughCriterion_smallCutoff
#check DkMath.NumberTheory.Legendre.roughCandidates_seven_eq
#print axioms DkMath.NumberTheory.Legendre.roughCandidates_seven_eq
#check DkMath.NumberTheory.Legendre.roughWave_seven_eq
#print axioms DkMath.NumberTheory.Legendre.roughWave_seven_eq
#check DkMath.NumberTheory.Legendre.candidateAvoidThree_filter_dvd
#print axioms DkMath.NumberTheory.Legendre.candidateAvoidThree_filter_dvd
#check DkMath.NumberTheory.Legendre.roughCandidates_eleven_eq
#print axioms DkMath.NumberTheory.Legendre.roughCandidates_eleven_eq
#check DkMath.NumberTheory.Legendre.roughWave_eleven_eq
#print axioms DkMath.NumberTheory.Legendre.roughWave_eleven_eq
#check DkMath.NumberTheory.Legendre.roughCandidates_eleven_card
#print axioms DkMath.NumberTheory.Legendre.roughCandidates_eleven_card
#check DkMath.NumberTheory.Legendre.roughWave_eleven_card
#print axioms DkMath.NumberTheory.Legendre.roughWave_eleven_card
#check DkMath.NumberTheory.Legendre.primeAnchorRoughElevenIncidenceCount
#print axioms DkMath.NumberTheory.Legendre.primeAnchorRoughElevenIncidenceCount
#check DkMath.NumberTheory.Legendre.roughWave_eleven_sum_eq_count
#print axioms DkMath.NumberTheory.Legendre.roughWave_eleven_sum_eq_count
#check DkMath.NumberTheory.Legendre.prime_squareCell_of_roughEleven_count
#print axioms DkMath.NumberTheory.Legendre.prime_squareCell_of_roughEleven_count
#check DkMath.NumberTheory.Legendre.primeAnchorTwoPrimeWaveUpper_eq_count
#print axioms DkMath.NumberTheory.Legendre.primeAnchorTwoPrimeWaveUpper_eq_count
#check DkMath.NumberTheory.Legendre.primeAnchorTwoPrimeWaveUpper_eq_card
#print axioms DkMath.NumberTheory.Legendre.primeAnchorTwoPrimeWaveUpper_eq_card
#check DkMath.NumberTheory.Legendre.primeAnchorTwoPrimeUpper_eq_incidence
#print axioms DkMath.NumberTheory.Legendre.primeAnchorTwoPrimeUpper_eq_incidence
#check DkMath.NumberTheory.Legendre.primeAnchorRemainingCap_eq_covered_tail
#print axioms DkMath.NumberTheory.Legendre.primeAnchorRemainingCap_eq_covered_tail
#check DkMath.NumberTheory.Legendre.primeAnchorRemainingCap_lt_iff_rough
#print axioms DkMath.NumberTheory.Legendre.primeAnchorRemainingCap_lt_iff_rough
#check DkMath.NumberTheory.Legendre.primeAnchorHead_gap_iff_rough
#print axioms DkMath.NumberTheory.Legendre.primeAnchorHead_gap_iff_rough
#check DkMath.NumberTheory.Legendre.sqrtCutoff_power_four_gt
#print axioms DkMath.NumberTheory.Legendre.sqrtCutoff_power_four_gt
#check DkMath.NumberTheory.Legendre.sqrtCutoff_support_card_le_three
#print axioms DkMath.NumberTheory.Legendre.sqrtCutoff_support_card_le_three
#check DkMath.NumberTheory.Legendre.sqrtCutoff_tail_card_le_two_mul
#print axioms DkMath.NumberTheory.Legendre.sqrtCutoff_tail_card_le_two_mul
#check DkMathTest.LegendreCanonicalTailCalibration.RootRow
#print axioms DkMathTest.LegendreCanonicalTailCalibration.RootRow
#check DkMathTest.LegendreCanonicalTailCalibration.rootData
#print axioms DkMathTest.LegendreCanonicalTailCalibration.rootData
#check DkMathTest.LegendreCanonicalTailCalibration.roughData
#print axioms DkMathTest.LegendreCanonicalTailCalibration.roughData
#check DkMathTest.LegendreCanonicalTailCalibration.cutoffData
#print axioms DkMathTest.LegendreCanonicalTailCalibration.cutoffData
#check DkMathTest.LegendreCanonicalTailCalibration.root11UnionFloorLower
#print axioms DkMathTest.LegendreCanonicalTailCalibration.root11UnionFloorLower
#check DkMathTest.LegendreCanonicalTailCalibration.unionData
#print axioms DkMathTest.LegendreCanonicalTailCalibration.unionData
#check DkMathTest.LegendreCanonicalTailCalibration.root_charges_checked
#print axioms DkMathTest.LegendreCanonicalTailCalibration.root_charges_checked
#check DkMathTest.LegendreCanonicalTailCalibration.caps_checked
#print axioms DkMathTest.LegendreCanonicalTailCalibration.caps_checked
#check DkMathTest.LegendreCanonicalTailCalibration.rough_floor_counts_checked
#print axioms DkMathTest.LegendreCanonicalTailCalibration.rough_floor_counts_checked
#check DkMathTest.LegendreCanonicalTailCalibration.union_credit_checked
#print axioms DkMathTest.LegendreCanonicalTailCalibration.union_credit_checked
#check DkMathTest.LegendreCanonicalTailCalibration.head_charges_checked
#print axioms DkMathTest.LegendreCanonicalTailCalibration.head_charges_checked
#check DkMathTest.LegendreCanonicalTailCalibration.cutoff_checked
#print axioms DkMathTest.LegendreCanonicalTailCalibration.cutoff_checked
#check DkMathTest.LegendreCanonicalTailCalibration.checkpoints_uncovered_from_head
#print axioms DkMathTest.LegendreCanonicalTailCalibration.checkpoints_uncovered_from_head
#check DkMathTest.LegendreCanonicalTailCalibration.checkpoints_prime_from_rough
#print axioms DkMathTest.LegendreCanonicalTailCalibration.checkpoints_prime_from_rough
#check DkMathTest.LegendreCanonicalTailCalibration.shell1009_uncovered
#print axioms DkMathTest.LegendreCanonicalTailCalibration.shell1009_uncovered
#check DkMathTest.LegendreCanonicalTailCalibration.shell1013_uncovered
#print axioms DkMathTest.LegendreCanonicalTailCalibration.shell1013_uncovered
#check DkMathTest.LegendreCanonicalTailCalibration.shell1009_prime
#print axioms DkMathTest.LegendreCanonicalTailCalibration.shell1009_prime
#check DkMathTest.LegendreCanonicalTailCalibration.shell1013_prime
#print axioms DkMathTest.LegendreCanonicalTailCalibration.shell1013_prime
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_support_eq
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_support_eq
#check DkMathTest.LegendreCanonicalTailDiagnostics.excess_eq_diagnostic
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.excess_eq_diagnostic
#check DkMathTest.LegendreCanonicalTailDiagnostics.rough_covered_eq_diagnostic
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.rough_covered_eq_diagnostic
#check DkMathTest.LegendreCanonicalTailDiagnostics.actual_excess_checked
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.actual_excess_checked
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_excess_checked
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_excess_checked
#check DkMathTest.LegendreCanonicalTailDiagnostics.actual_tail_cards_checked
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.actual_tail_cards_checked
#check DkMathTest.LegendreCanonicalTailDiagnostics.actual_rough_seat_cards_checked
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.actual_rough_seat_cards_checked
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticActivePrimes
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticActivePrimes
#check DkMathTest.LegendreCanonicalTailDiagnostics.excessData
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.excessData
#check DkMathTest.LegendreCanonicalTailDiagnostics.tailData
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.tailData
#check DkMathTest.LegendreCanonicalTailDiagnostics.prime_inventory_checked
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.prime_inventory_checked
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticExcess
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticExcess
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticRoughSeats
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticRoughSeats
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticCoveredEleven
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnosticCoveredEleven
#check DkMathTest.LegendreCanonicalTailDiagnostics.coveredElevenData
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.coveredElevenData
#check DkMathTest.LegendreCanonicalTailDiagnostics.covered_eleven_checked
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.covered_eleven_checked
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_excess_inputs
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_excess_inputs
#check DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_rough_seats_checked
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.diagnostic_rough_seats_checked
#check DkMathTest.LegendreCanonicalTailDiagnostics.tail_tables_consistent
#print axioms DkMathTest.LegendreCanonicalTailDiagnostics.tail_tables_consistent
#check DkMathTest.LegendreCanonicalTailRegression.erased_root_counterexample
#print axioms DkMathTest.LegendreCanonicalTailRegression.erased_root_counterexample
#check DkMathTest.LegendreCanonicalTailRegression.empty_support_counterexample
#print axioms DkMathTest.LegendreCanonicalTailRegression.empty_support_counterexample
#check DkMathTest.LegendreCanonicalTailRegression.termwise_cancellation_counterexample
#print axioms DkMathTest.LegendreCanonicalTailRegression.termwise_cancellation_counterexample
#check DkMathTest.LegendreCanonicalTailRegression.rough_seat_multiplicity_counterexample
#print axioms DkMathTest.LegendreCanonicalTailRegression.rough_seat_multiplicity_counterexample
#check DkMathTest.LegendreCanonicalTailRegression.sequential_three_exclusion_counterexample
#print axioms DkMathTest.LegendreCanonicalTailRegression.sequential_three_exclusion_counterexample
#check DkMathTest.LegendreCanonicalTailRegression.root11_sieve_eq_floor_union
#print axioms DkMathTest.LegendreCanonicalTailRegression.root11_sieve_eq_floor_union
#check DkMathTest.LegendreCanonicalTailRegression.rough_seats_three_floor
#print axioms DkMathTest.LegendreCanonicalTailRegression.rough_seats_three_floor
#check DkMathTest.LegendreCanonicalTailRegression.rough_seats_five_floor
#print axioms DkMathTest.LegendreCanonicalTailRegression.rough_seats_five_floor
#check DkMathTest.LegendreCanonicalTailRegression.sqrt_multiplicity_bound_sharp
#print axioms DkMathTest.LegendreCanonicalTailRegression.sqrt_multiplicity_bound_sharp
#check DkMathTest.LegendreCanonicalPrimeCapCalibration.cap_probe
#print axioms DkMathTest.LegendreCanonicalPrimeCapCalibration.cap_probe
#check DkMathTest.LegendreCanonicalPrimeCapCalibration.old_sieve_credit_checked
#print axioms DkMathTest.LegendreCanonicalPrimeCapCalibration.old_sieve_credit_checked
