/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMathTest.NumberTheory.LegendreIncidenceUpper
import DkMath.NumberTheory.Legendre

#print "file: DkMathTest.NumberTheory.LegendreIncidenceUpperAxiomAudit"

#check DkMath.NumberTheory.Legendre.card_filter_odd_dvd_Ioc_eq_paritySafeDelta
#print axioms DkMath.NumberTheory.Legendre.card_filter_odd_dvd_Ioc_eq_paritySafeDelta
#check DkMath.NumberTheory.Legendre.paritySafeOddQuotientUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeOddQuotientUpper
#check DkMath.NumberTheory.Legendre.paritySafeDivisorWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeDivisorWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeQuotientWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeQuotientWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeWaveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeWaveUpper
#check DkMath.NumberTheory.Legendre.paritySafeIncidenceUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeIncidenceUpper
#check DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_spacing
#print axioms DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_spacing
#check DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_oddUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_oddUpper
#check DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_divisorUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_divisorUpper
#check DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_quotientUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeReducedQuotient_card_le_quotientUpper
#check DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_waveUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeActiveWave_card_le_waveUpper
#check DkMath.NumberTheory.Legendre.paritySafeWaveUpper_le_oddUpper
#print axioms DkMath.NumberTheory.Legendre.paritySafeWaveUpper_le_oddUpper
#check DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_upper
#print axioms DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_upper
#check DkMath.NumberTheory.Legendre.paritySafeActiveSupport_subset_pointPrimeFactors
#print axioms DkMath.NumberTheory.Legendre.paritySafeActiveSupport_subset_pointPrimeFactors
#check DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_pointPrimeFactors_sum
#print axioms DkMath.NumberTheory.Legendre.paritySafeIncidenceCount_le_pointPrimeFactors_sum
#check DkMath.NumberTheory.Legendre.block_candidateSupportSum_eq_reducedQuotientSum
#print axioms DkMath.NumberTheory.Legendre.block_candidateSupportSum_eq_reducedQuotientSum
#check DkMath.NumberTheory.Legendre.block_incidenceCount_le_upper
#print axioms DkMath.NumberTheory.Legendre.block_incidenceCount_le_upper
#check DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_upper_lt_candidate_add_freshBound
#print axioms DkMath.NumberTheory.Legendre.not_block_fullyCovered_of_upper_lt_candidate_add_freshBound
#check DkMath.NumberTheory.Legendre.paritySafeUncovered_card_ge_candidate_add_excess_sub_upper
#print axioms DkMath.NumberTheory.Legendre.paritySafeUncovered_card_ge_candidate_add_excess_sub_upper
#check DkMath.NumberTheory.Legendre.block_uncovered_ge_candidate_add_excess_sub_upper
#print axioms DkMath.NumberTheory.Legendre.block_uncovered_ge_candidate_add_excess_sub_upper
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_candidate_add_excess_gt_upper
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_candidate_add_excess_gt_upper
#check DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_block_candidate_add_excess_gt_upper
#print axioms DkMath.NumberTheory.Legendre.exists_prime_squareCell_of_block_candidate_add_excess_gt_upper
#check DkMathTest.LegendreIncidenceUpper.incidenceUpper_eq_finite
#print axioms DkMathTest.LegendreIncidenceUpper.incidenceUpper_eq_finite
#check DkMathTest.LegendreIncidenceUpper.mainBlock_structural_upper
#print axioms DkMathTest.LegendreIncidenceUpper.mainBlock_structural_upper
#check DkMathTest.LegendreIncidenceUpper.mainBlock_odd_endpoint_upper
#print axioms DkMathTest.LegendreIncidenceUpper.mainBlock_odd_endpoint_upper
#check DkMathTest.LegendreIncidenceUpper.mainBlock_uniform_spacing_upper
#print axioms DkMathTest.LegendreIncidenceUpper.mainBlock_uniform_spacing_upper
#check DkMathTest.LegendreIncidenceUpper.uniform_spacing_main_threshold_false
#print axioms DkMathTest.LegendreIncidenceUpper.uniform_spacing_main_threshold_false
#check DkMathTest.LegendreIncidenceUpper.mainBlock_structural_not_fullyCovered
#print axioms DkMathTest.LegendreIncidenceUpper.mainBlock_structural_not_fullyCovered
#check DkMathTest.LegendreIncidenceUpper.mainBlock_uncovered_ge_sixtyFive
#print axioms DkMathTest.LegendreIncidenceUpper.mainBlock_uncovered_ge_sixtyFive
#check DkMathTest.LegendreIncidenceUpper.widthCalibration
#print axioms DkMathTest.LegendreIncidenceUpper.widthCalibration
#check DkMathTest.LegendreIncidenceUpper.width_cap_and_candidate_calibration
#print axioms DkMathTest.LegendreIncidenceUpper.width_cap_and_candidate_calibration
#check DkMathTest.LegendreIncidenceUpper.widths_uncovered_lower_bound
#print axioms DkMathTest.LegendreIncidenceUpper.widths_uncovered_lower_bound
#check DkMathTest.LegendreIncidenceUpper.widths_structural_prime
#print axioms DkMathTest.LegendreIncidenceUpper.widths_structural_prime
#check DkMathTest.LegendreIncidenceUpper.widths_structural_not_fullyCovered
#print axioms DkMathTest.LegendreIncidenceUpper.widths_structural_not_fullyCovered
#check DkMathTest.LegendreIncidenceUpper.shell21_cap_and_candidate
#print axioms DkMathTest.LegendreIncidenceUpper.shell21_cap_and_candidate
#check DkMathTest.LegendreIncidenceUpper.shell21_uncovered_ge_five
#print axioms DkMathTest.LegendreIncidenceUpper.shell21_uncovered_ge_five
#check DkMathTest.LegendreIncidenceUpper.shell21_not_fullyCovered
#print axioms DkMathTest.LegendreIncidenceUpper.shell21_not_fullyCovered
#check DkMathTest.LegendreIncidenceUpper.shell21_structural_prime
#print axioms DkMathTest.LegendreIncidenceUpper.shell21_structural_prime
#check DkMathTest.LegendreIncidenceUpper.shell29_zero_excess_threshold_fails
#print axioms DkMathTest.LegendreIncidenceUpper.shell29_zero_excess_threshold_fails
#check DkMathTest.LegendreIncidenceUpper.activeWave_eq_finite
#print axioms DkMathTest.LegendreIncidenceUpper.activeWave_eq_finite
#check DkMathTest.LegendreIncidenceUpper.sameWave_exact_adjacency_false
#print axioms DkMathTest.LegendreIncidenceUpper.sameWave_exact_adjacency_false
#check DkMathTest.LegendreIncidenceUpper.single_divisor_upper_not_exact
#print axioms DkMathTest.LegendreIncidenceUpper.single_divisor_upper_not_exact
#check DkMathTest.LegendreIncidenceUpper.mainBlock_upper_slack_diagnostic
#print axioms DkMathTest.LegendreIncidenceUpper.mainBlock_upper_slack_diagnostic
#check DkMathTest.LegendreIncidenceUpper.residualWaveCalibration
#print axioms DkMathTest.LegendreIncidenceUpper.residualWaveCalibration
#check DkMathTest.LegendreIncidenceUpper.residual_wave_slack_calibration
#print axioms DkMathTest.LegendreIncidenceUpper.residual_wave_slack_calibration
#check DkMathTest.LegendreIncidenceUpper.mainBlock_low_prime_upper_diagnostic
#print axioms DkMathTest.LegendreIncidenceUpper.mainBlock_low_prime_upper_diagnostic
#check DkMathTest.LegendreIncidenceUpper.shell21_seat_upper_diagnostic
#print axioms DkMathTest.LegendreIncidenceUpper.shell21_seat_upper_diagnostic
#check DkMathTest.LegendreIncidenceUpper.shell21_odd_endpoint_upper_diagnostic
#print axioms DkMathTest.LegendreIncidenceUpper.shell21_odd_endpoint_upper_diagnostic
