/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.Legendre.ParitySafeFreshCost
import DkMathTest.NumberTheory.LegendreFreshCost

#print "file: "

-- Complete coverage of new public production and named regression declarations.
#check DkMath.NumberTheory.Legendre.lowerParitySafeActiveSupport_card_eq
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeActiveSupport_card_eq
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport_subset_primeFactors
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport_subset_primeFactors
#check DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport_card_le_primeFactors
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafePersistentSupport_card_le_primeFactors
#check DkMath.NumberTheory.Legendre.lowerParitySafeActiveSupport_sub_primeFactors_le_fresh
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeActiveSupport_sub_primeFactors_le_fresh
#check DkMath.NumberTheory.Legendre.sum_fixedSeat_persistentSupport_le_frequency
#print axioms DkMath.NumberTheory.Legendre.sum_fixedSeat_persistentSupport_le_frequency
#check DkMath.NumberTheory.Legendre.lower_candidate_modEq_two
#print axioms DkMath.NumberTheory.Legendre.lower_candidate_modEq_two
#check DkMath.NumberTheory.Legendre.lowerCandidatePrimeAddressOffsets
#print axioms DkMath.NumberTheory.Legendre.lowerCandidatePrimeAddressOffsets
#check DkMath.NumberTheory.Legendre.lowerCandidatePrimeAddressOffsets_card_le
#print axioms DkMath.NumberTheory.Legendre.lowerCandidatePrimeAddressOffsets_card_le
#check DkMath.NumberTheory.Legendre.sum_fixedSeat_persistentSupport_le_parity_frequency
#print axioms DkMath.NumberTheory.Legendre.sum_fixedSeat_persistentSupport_le_parity_frequency
#check DkMath.NumberTheory.Legendre.lowerParitySafeParityPersistenceCap
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeParityPersistenceCap
#check DkMath.NumberTheory.Legendre.sum_lowerPersistentCount_le_parityCap
#print axioms DkMath.NumberTheory.Legendre.sum_lowerPersistentCount_le_parityCap
#check DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_parityCap_le_fresh_of_fullyCovered
#print axioms DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_parityCap_le_fresh_of_fullyCovered
#check DkMath.NumberTheory.Legendre.lowerPersistenceCap_eq_seatSum
#print axioms DkMath.NumberTheory.Legendre.lowerPersistenceCap_eq_seatSum
#check DkMath.NumberTheory.Legendre.shellFrequencyCap_double_le
#print axioms DkMath.NumberTheory.Legendre.shellFrequencyCap_double_le
#check DkMath.NumberTheory.Legendre.lowerParitySafeParityPersistenceCap_le_oldCap
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeParityPersistenceCap_le_oldCap
#check DkMath.NumberTheory.Legendre.lowerSingletonFreshSeats
#print axioms DkMath.NumberTheory.Legendre.lowerSingletonFreshSeats
#check DkMath.NumberTheory.Legendre.lowerMultiFreshCount
#print axioms DkMath.NumberTheory.Legendre.lowerMultiFreshCount
#check DkMath.NumberTheory.Legendre.lowerFreshWithoutPersistentSeats
#print axioms DkMath.NumberTheory.Legendre.lowerFreshWithoutPersistentSeats
#check DkMath.NumberTheory.Legendre.lowerFreshSupportExcessCharge
#print axioms DkMath.NumberTheory.Legendre.lowerFreshSupportExcessCharge
#check DkMath.NumberTheory.Legendre.lowerFreshSupportExcessChargeCount
#print axioms DkMath.NumberTheory.Legendre.lowerFreshSupportExcessChargeCount
#check DkMath.NumberTheory.Legendre.lower_active_excess_eq_persistent_excess_add_fresh_charge
#print axioms DkMath.NumberTheory.Legendre.lower_active_excess_eq_persistent_excess_add_fresh_charge
#check DkMath.NumberTheory.Legendre.lower_singleton_fresh_has_zero_excess
#print axioms DkMath.NumberTheory.Legendre.lower_singleton_fresh_has_zero_excess
#check DkMath.NumberTheory.Legendre.mem_lowerSingletonFreshSeats_iff_zero_excess
#print axioms DkMath.NumberTheory.Legendre.mem_lowerSingletonFreshSeats_iff_zero_excess
#check DkMath.NumberTheory.Legendre.lowerFreshSupportExcessCharge_pos_of_multi
#print axioms DkMath.NumberTheory.Legendre.lowerFreshSupportExcessCharge_pos_of_multi
#check DkMath.NumberTheory.Legendre.lowerParitySafeFreshCount_eq_singleton_add_multi
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeFreshCount_eq_singleton_add_multi
#check DkMath.NumberTheory.Legendre.lowerMultiFreshCount_le_two_supportExcess
#print axioms DkMath.NumberTheory.Legendre.lowerMultiFreshCount_le_two_supportExcess
#check DkMath.NumberTheory.Legendre.lowerParitySafeFreshCount_eq_firstSlots_add_excessCharge
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeFreshCount_eq_firstSlots_add_excessCharge
#check DkMath.NumberTheory.Legendre.lowerFreshSupportExcessChargeCount_le_supportExcess
#print axioms DkMath.NumberTheory.Legendre.lowerFreshSupportExcessChargeCount_le_supportExcess
#check DkMath.NumberTheory.Legendre.lowerFreshCharge_onCollision_le_collisionSupportCost
#print axioms DkMath.NumberTheory.Legendre.lowerFreshCharge_onCollision_le_collisionSupportCost
#check DkMath.NumberTheory.Legendre.lowerSingletonFreshSeats_subset_firstSlots
#print axioms DkMath.NumberTheory.Legendre.lowerSingletonFreshSeats_subset_firstSlots
#check DkMath.NumberTheory.Legendre.lowerFreshCount_le_singleton_add_two_supportExcess
#print axioms DkMath.NumberTheory.Legendre.lowerFreshCount_le_singleton_add_two_supportExcess
#check DkMath.NumberTheory.Legendre.lowerFreshCount_le_firstSlots_add_supportExcess
#print axioms DkMath.NumberTheory.Legendre.lowerFreshCount_le_firstSlots_add_supportExcess
#check DkMath.NumberTheory.Legendre.lowerParitySafeFreshPairs
#print axioms DkMath.NumberTheory.Legendre.lowerParitySafeFreshPairs
#check DkMath.NumberTheory.Legendre.mem_lowerParitySafeFreshPairs_iff
#print axioms DkMath.NumberTheory.Legendre.mem_lowerParitySafeFreshPairs_iff
#check DkMath.NumberTheory.Legendre.lower_persistent_upperPairs_subset
#print axioms DkMath.NumberTheory.Legendre.lower_persistent_upperPairs_subset
#check DkMath.NumberTheory.Legendre.lower_active_pair_eq_persistent_pair_add_fresh_pairs
#print axioms DkMath.NumberTheory.Legendre.lower_active_pair_eq_persistent_pair_add_fresh_pairs
#check DkMath.NumberTheory.Legendre.lowerFreshPairs_card_eq_mixed_add_choose_fresh
#print axioms DkMath.NumberTheory.Legendre.lowerFreshPairs_card_eq_mixed_add_choose_fresh
#check DkMath.NumberTheory.Legendre.lowerFreshPairs_card_pos_of_multi
#print axioms DkMath.NumberTheory.Legendre.lowerFreshPairs_card_pos_of_multi
#check DkMath.NumberTheory.Legendre.lowerFreshPairOverlapCount
#print axioms DkMath.NumberTheory.Legendre.lowerFreshPairOverlapCount
#check DkMath.NumberTheory.Legendre.lowerFreshPairOverlapCount_le_pairOverlap
#print axioms DkMath.NumberTheory.Legendre.lowerFreshPairOverlapCount_le_pairOverlap
#check DkMath.NumberTheory.Legendre.lowerFreshPairs_outsideCollision_le_outsidePairOverlap
#print axioms DkMath.NumberTheory.Legendre.lowerFreshPairs_outsideCollision_le_outsidePairOverlap
#check DkMath.NumberTheory.Legendre.lower_singleton_not_collision
#print axioms DkMath.NumberTheory.Legendre.lower_singleton_not_collision
#check DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_persistenceCap_sub_singletons_le_two_excess
#print axioms DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_persistenceCap_sub_singletons_le_two_excess
#check DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_persistenceCap_sub_firstSlots_le_excess
#print axioms DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_persistenceCap_sub_firstSlots_le_excess
#check DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_parityCap_sub_firstSlots_le_excess
#print axioms DkMath.NumberTheory.Legendre.sum_lowerCandidates_sub_parityCap_sub_firstSlots_le_excess
#check DkMath.NumberTheory.Legendre.sum_fullCandidate_add_freshChargeBound_le_incidence
#print axioms DkMath.NumberTheory.Legendre.sum_fullCandidate_add_freshChargeBound_le_incidence
#check DkMathTest.LegendreFreshCost.activeSupport_eq_filter_range
#print axioms DkMathTest.LegendreFreshCost.activeSupport_eq_filter_range
#check DkMathTest.LegendreFreshCost.oldSupport_eq_filter_range
#print axioms DkMathTest.LegendreFreshCost.oldSupport_eq_filter_range
#check DkMathTest.LegendreFreshCost.freshSupport_eq_filter_range
#print axioms DkMathTest.LegendreFreshCost.freshSupport_eq_filter_range
#check DkMathTest.LegendreFreshCost.mainBlock_singleton_capacity
#print axioms DkMathTest.LegendreFreshCost.mainBlock_singleton_capacity
#check DkMathTest.LegendreFreshCost.mainBlock_first_slot_capacity
#print axioms DkMathTest.LegendreFreshCost.mainBlock_first_slot_capacity
#check DkMathTest.LegendreFreshCost.mainBlock_parity_capacity
#print axioms DkMathTest.LegendreFreshCost.mainBlock_parity_capacity
#check DkMathTest.LegendreFreshCost.mainBlock_required_seats
#print axioms DkMathTest.LegendreFreshCost.mainBlock_required_seats
#check DkMathTest.LegendreFreshCost.old_fresh_bound_below_singleton_capacity
#print axioms DkMathTest.LegendreFreshCost.old_fresh_bound_below_singleton_capacity
#check DkMathTest.LegendreFreshCost.mainBlock_fresh_lower_bound
#print axioms DkMathTest.LegendreFreshCost.mainBlock_fresh_lower_bound
#check DkMathTest.LegendreFreshCost.mainBlock_support_excess_lower_bound
#print axioms DkMathTest.LegendreFreshCost.mainBlock_support_excess_lower_bound
#check DkMathTest.LegendreFreshCost.mainBlock_fullCover_balance_with_positive_charge
#print axioms DkMathTest.LegendreFreshCost.mainBlock_fullCover_balance_with_positive_charge
#check DkMathTest.LegendreFreshCost.singletonFresh_not_bounded_by_persistent_prime_labels
#print axioms DkMathTest.LegendreFreshCost.singletonFresh_not_bounded_by_persistent_prime_labels
#check DkMathTest.LegendreFreshCost.fresh_with_persistent_has_cost_without_residual
#print axioms DkMathTest.LegendreFreshCost.fresh_with_persistent_has_cost_without_residual
#check DkMathTest.LegendreFreshCost.fresh_pairs_not_bounded_by_local_residual
#print axioms DkMathTest.LegendreFreshCost.fresh_pairs_not_bounded_by_local_residual
#check DkMathTest.LegendreFreshCost.candidate_period_regression
#print axioms DkMathTest.LegendreFreshCost.candidate_period_regression
