/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.FLT.Five.CleanChannel

#print "file: DkMath.FLT.Five.BranchB"

namespace DkMath.FLT.Five

/-- The exponent-five body in local gap coordinates. -/
def Body5 (g y : ℕ) : ℕ :=
  g * GN5 g y

/-- `Body5` is the fifth-power difference generated by the gap. -/
theorem body5_eq_add_pow_sub (g y : ℕ) :
    Body5 g y = (g + y) ^ 5 - y ^ 5 := by
  symm
  exact add_pow_five_sub_eq_mul_GN5 g y

/-- A Fermat-five equation turns the body at `z-y` into the fifth power `x^5`. -/
theorem body5_eq_fifth_power_of_fermat
    {x y z : ℕ}
    (hyz : y ≤ z)
    (hEq : Fermat5Equation x y z) :
    Body5 (z - y) y = x ^ 5 := by
  calc
    Body5 (z - y) y = z ^ 5 - y ^ 5 := by
      symm
      exact pow_five_sub_pow_five_eq_gap_mul_GN5 hyz
    _ = x ^ 5 := fifth_sub_eq_of_add_eq hEq

/--
Next checkpoint target:

A clean channel at `GN5 (z-y) y` should refute the candidate equation by a direct
square-divisibility argument, and then independently by a `padicValNat` argument.
-/

end DkMath.FLT.Five
