/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import Mathlib.Data.Finset.Basic
import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Tactic
import DkMath.NumberTheory.Primitive.PeriodicPrimeWorld
import DkMath.NumberTheory.Primitive.PrimeWorldRefinement

#print "file: DkMath.NumberTheory.Primitive.PHZ30"

/-!
## The concrete `{2, 3, 5}` period-30 observer

The first concrete finite prime world is `{2, 3, 5}`.  Its product modulus is
`30`, and exactly eight residues in one period avoid divisibility by the old
prime directions:
`{1, 7, 11, 13, 17, 19, 23, 29}`.

This module lifts that finite classification to all natural positions using
the generic periodic observer.  The surviving positions are candidate seats:
PHZ30 records only that they are not divisible by `2`, `3`, or `5`; it makes
no primality claim and does not provide a Legendre theorem.
-/

namespace DkMath.NumberTheory.Primitive

open DkMath.NumberTheory.StructuralArithmetic

/-- The concrete finite prime world generated by the directions `2`, `3`, and `5`. -/
def primeWorld235 : Finset ℕ := {2, 3, 5}

/-- Every direction in `primeWorld235` is certified to be prime. -/
theorem knownPrimeScales_primeWorld235 :
    KnownPrimeScales primeWorld235 := by
  intro p hp
  simp only [primeWorld235, Finset.mem_insert, Finset.mem_singleton] at hp
  rcases hp with rfl | rfl | rfl <;> norm_num

/-- The product modulus of `primeWorld235` is exactly `30`. -/
@[simp] theorem primeWorldModulus_primeWorld235 :
    primeWorldModulus primeWorld235 = 30 := by
  norm_num [primeWorldModulus, primeWorld235]

/-- The eight support-disjoint candidate residues in one period modulo `30`. -/
def phzResidues30 : Finset ℕ := {1, 7, 11, 13, 17, 19, 23, 29}

/-
The bound below is used to turn the finite residue statement into a complete
case split.  It is deliberately separate from the global modulo theorem so
that the latter visibly reuses the generic period normalization.
-/

/--
Below `30`, support disjointness from the concrete world is exactly membership
in the explicit eight-element PHZ residue set.

This is a candidate-seat classification, not a primality characterization.
-/
theorem supportDisjointFrom_primeWorld235_iff_mem_phzResidues30
    {r : ℕ} (hr : r < 30) :
    SupportDisjointFrom primeWorld235 r ↔
      r ∈ phzResidues30 := by
  rw [supportDisjointFrom_iff_coprime_primeWorldModulus
    knownPrimeScales_primeWorld235]
  simp only [primeWorldModulus_primeWorld235]
  interval_cases r <;> norm_num [phzResidues30]

/--
For every natural position, the concrete support observer is classified by
the residue modulo `30`.

The proof factors through the generic modulo theorem and the complete
one-period certificate above.
-/
theorem supportDisjointFrom_primeWorld235_iff_mod_mem_phzResidues30
    {m : ℕ} :
    SupportDisjointFrom primeWorld235 m ↔
      m % 30 ∈ phzResidues30 := by
  calc
    SupportDisjointFrom primeWorld235 m ↔
        SupportDisjointFrom primeWorld235
          (m % primeWorldModulus primeWorld235) :=
      (supportDisjointFrom_mod_primeWorldModulus_iff
        (S := primeWorld235) (m := m)).symm
    _ ↔ SupportDisjointFrom primeWorld235 (m % 30) := by
      rw [primeWorldModulus_primeWorld235]
    _ ↔ m % 30 ∈ phzResidues30 :=
      supportDisjointFrom_primeWorld235_iff_mem_phzResidues30
        (Nat.mod_lt m (by norm_num))

/--
The concrete PHZ30 world is the canonical bounded prime world at `P = 5`.
This identifies the named example with the existing finite-world constructor.
-/
theorem primeWorld235_eq_primeScalesUpTo_five :
    primeWorld235 = primeScalesUpTo 5 := by
  ext p
  constructor
  · intro hp
    simp only [primeWorld235, Finset.mem_insert, Finset.mem_singleton] at hp
    rcases hp with rfl | rfl | rfl
    · exact (mem_primeScalesUpTo).2 ⟨by norm_num, by norm_num⟩
    · exact (mem_primeScalesUpTo).2 ⟨by norm_num, by norm_num⟩
    · exact (mem_primeScalesUpTo).2 ⟨by norm_num, by norm_num⟩
  · intro hp
    have hp' := (mem_primeScalesUpTo.mp hp)
    have hp5 : p ≤ 5 := hp'.2
    interval_cases p <;> norm_num at hp' <;>
      simp [primeWorld235, Finset.mem_insert, Finset.mem_singleton]

/-- The `{2,3,5}` world grows to modulus `210` after inserting the fresh direction `7`. -/
@[simp] theorem primeWorldModulus_insert_seven_primeWorld235 :
    primeWorldModulus (insert 7 primeWorld235) = 210 := by
  have h7 : 7 ∉ primeWorld235 := by
    simp [primeWorld235]
  rw [primeWorldModulus_insert h7, primeWorldModulus_primeWorld235]

/--
Every explicit PHZ30 residue is a valid representative of the old period.
-/
theorem lt_thirty_of_mem_phzResidues30
    {r : ℕ} (hr : r ∈ phzResidues30) :
    r < 30 := by
  simp only [phzResidues30, Finset.mem_insert, Finset.mem_singleton] at hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  all_goals norm_num

/--
Each PHZ30 candidate seat has exactly six surviving child indices after the
fresh direction `7` is inserted.  This is a count certificate only; the
individual PHZ210 residues are intentionally not enumerated.
-/
theorem card_seven_refinement_survivors_of_mem_phzResidues30
    {r : ℕ} (hr : r ∈ phzResidues30) :
    (survivingChildIndices primeWorld235 7 r).card = 6 := by
  have hr30 : r < 30 := lt_thirty_of_mem_phzResidues30 hr
  have hrPeriod : r < primeWorldModulus primeWorld235 := by
    simpa [primeWorldModulus_primeWorld235] using hr30
  have h7 : 7 ∉ primeWorld235 := by
    simp [primeWorld235]
  have hcard := card_survivingChildIndices
    (S := primeWorld235) (q := 7) (r := r)
    knownPrimeScales_primeWorld235 (by norm_num) h7 hrPeriod
  simpa using hcard

/-
The global PHZ210 construction is kept as an image of the generic refinement.
This gives a compact constructive certificate instead of an enumerated list of
the forty-eight representatives.
-/

/-- The PHZ30 candidate seats refined by the fresh direction `7`. -/
def phzResidues210 : Finset ℕ :=
  refinedSurvivingSeats primeWorld235 7 phzResidues30

/-- The PHZ210 refinement contains exactly `8 * (7 - 1) = 48` candidate seats. -/
theorem card_phzResidues210 :
    phzResidues210.card = 48 := by
  have h7 : 7 ∉ primeWorld235 := by
    simp [primeWorld235]
  have hR : ∀ r ∈ phzResidues30,
      r < primeWorldModulus primeWorld235 := by
    intro r hr
    simpa [primeWorldModulus_primeWorld235] using
      lt_thirty_of_mem_phzResidues30 hr
  have hcard := card_refinedSurvivingSeats
    (S := primeWorld235) (q := 7) (R := phzResidues30)
    knownPrimeScales_primeWorld235 (by norm_num) h7 hR
  have hRcard : phzResidues30.card = 8 := by
    norm_num [phzResidues30]
  simpa [phzResidues210, hRcard] using hcard

/-- Every constructed PHZ210 candidate is support-disjoint from `2, 3, 5, 7`. -/
theorem supportDisjointFrom_of_mem_phzResidues210
    {n : ℕ} (hn : n ∈ phzResidues210) :
    SupportDisjointFrom (insert 7 primeWorld235) n := by
  apply supportDisjointFrom_of_mem_refinedSurvivingSeats
    (S := primeWorld235) (q := 7) (R := phzResidues30)
    (by norm_num)
  · intro r hr
    exact (supportDisjointFrom_primeWorld235_iff_mem_phzResidues30
    (lt_thirty_of_mem_phzResidues30 hr)).2 hr
  exact hn

/--
The concrete observer inherits the generic period theorem in `r + 30 * k`
coordinates.
-/
theorem supportDisjointFrom_primeWorld235_add_thirty_mul_iff
    {k r : ℕ} :
    SupportDisjointFrom primeWorld235 (r + 30 * k) ↔
      SupportDisjointFrom primeWorld235 r := by
  simpa [primeWorldModulus_primeWorld235, Nat.mul_comm] using
    (supportDisjointFrom_add_mul_primeWorldModulus_iff
      (S := primeWorld235) (m := r) (k := k))

/--
The generic centered mirror theorem specializes to reflection around one
period of the concrete modulus.  The bound is retained because subtraction
on `ℕ` is truncated.
-/
theorem supportDisjointFrom_primeWorld235_mirror_iff
    {r : ℕ} (hr : r ≤ 30) :
    SupportDisjointFrom primeWorld235 (30 - r) ↔
      SupportDisjointFrom primeWorld235 (30 + r) := by
  have hr' : r ≤ 1 * primeWorldModulus primeWorld235 := by
    simpa [primeWorldModulus_primeWorld235] using hr
  simpa [primeWorldModulus_primeWorld235] using
    (supportDisjointFrom_centered_mirror_iff
      (S := primeWorld235) (k := 1) (r := r) hr')

/--
The explicit PHZ residue list is invariant under one-period residue
negation, for the nonzero representatives below `30`.
-/
theorem mem_phzResidues30_sub_iff
    {r : ℕ} (hr0 : 0 < r) (hr30 : r < 30) :
    (30 - r ∈ phzResidues30) ↔ (r ∈ phzResidues30) := by
  interval_cases r <;> norm_num [phzResidues30] at hr0 hr30 ⊢

end DkMath.NumberTheory.Primitive
