/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/
import DkMath.NumberTheory.Primitive.SquareBody

#print "file: DkMath.NumberTheory.Primitive.PrimitiveConservationKernel"

/-!
## Primitive Conservation Kernel

This module is a semantic facade over the already-proved square-Body
decomposition. It proves no new factorization theorem and introduces no
generic `PrimitiveKernel` abstraction.

The complete old world is `primeScalesUpTo P`. If `q ≤ P`,
`squareBody_mono` nests the fine square window inside the coarse one. Every
positive point in that bounded window is either entirely generated by the old
world, or is an old-generated bounded cofactor times exactly one unique fresh
prime direction above `P`. Here “primitive” means a finite-world fresh prime
direction relative to canonical old support, not a Zsigmondy primitive
divisor, `PrimitiveBeam` origin, or RH/analytic primitive. The result is finite
and bounded and does not say that a fresh branch occurs for every `m`.
-/
namespace DkMath.NumberTheory.Primitive

open DkMath.NumberTheory.StructuralArithmetic

/--
Primitive Conservation Kernel for nested square worlds.

A positive point in a fine square world `q ≤ P` is either entirely generated
by the complete old prime world through `P`, or has exactly one fresh prime
direction `p > P`; after removing that direction, the remaining cofactor is
positive, at most `P`, old-generated, and coprime to `p`.
-/
theorem primitiveConservationKernel_dichotomy_of_le_fine_squareBody
    {q P m : ℕ}
    (hqP : q ≤ P)
    (hm : 0 < m)
    (hmUpper : m ≤ squareBody q) :
    PrimeScaleGeneratedBy (primeScalesUpTo P) m ∨
      ∃ p k,
        Nat.Prime p ∧
        P < p ∧
        0 < k ∧
        k ≤ P ∧
        FreshPrimeDirection (primeScalesUpTo P) m p ∧
        p * k = m ∧
        PrimeScaleGeneratedBy (primeScalesUpTo P) k ∧
        Nat.Coprime p k ∧
        (∀ ⦃r : ℕ⦄,
          FreshPrimeDirection (primeScalesUpTo P) m r → r = p) := by
  have hmUpperCoarse : m ≤ squareBody P :=
    hmUpper.trans (squareBody_mono hqP)
  exact
    primeScaleGeneratedBy_or_uniqueFresh_small_split_of_le_squareBody
      hm hmUpperCoarse

end DkMath.NumberTheory.Primitive
