/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.FLT.Seven

set_option linter.style.longLine false

namespace DkMath.FLT.Seven

#print axioms RamifiedSignedRootRoutingPacket.ActiveUnitBoard.cycleRatio12_div_cycleRatio23_eq
#print axioms RamifiedSignedRootRoutingPacket.ActiveUnitBoard.cyclePhaseTwist_cycles
#print axioms RamifiedSignedRootRoutingPacket.ActiveUnitBoard.hiddenRowTwist_cycles
#print axioms RamifiedSignedRootRoutingPacket.ActiveUnitBoard.margins_do_not_determine_cycles
#print axioms RamifiedSignedRootRoutingPacket.ActiveUnitBoard.margins_and_cycles_do_not_determine_board

#print axioms RamifiedSecondCoordinateRoutingPacket.nonempty_canonicalSplit
#print axioms RamifiedSecondCoordinateCanonicalSplit.cubicGap_natAbs_eq
#print axioms RamifiedSecondCoordinateCanonicalSplit.receiver_iff_cubicGap_seventh_shape
#print axioms RamifiedSecondCoordinateCanonicalSplit.receiver_iff_independent_seventh_powers

#print axioms AwaySevenBaseTerminalUnitSectorPacket.terminalRamifiedSummit
#print axioms TerminalPrimitiveRamifiedSummitPacket.rootSnd_depth_eq_five
#print axioms TerminalPrimitiveRamifiedSummitPacket.rootSnd_mul_sndCore_eq
#print axioms TerminalPrimitiveRamifiedSummitPacket.nonempty_secondCoordinateRouting
#print axioms TerminalPrimitiveRamifiedSummitPacket.receiver_of_compensationCore_eq_one

#print axioms AwaySevenBaseTerminalUnitSectorPacket.ramifiedSummit
#print axioms PrimitiveRamifiedSummitPacket.rootSnd_padicValNat
#print axioms ramifiedSeventhSnd_factorization

#print axioms PrimitiveRamifiedSummitPacket.cubicGap_mul_sndCore_eq_endpointGap_mul_bridge
#print axioms RamifiedGapUnitBridgePacket.cubicGap_eq_endpointGap_mul_explicitUnit

#print axioms PrimitiveRamifiedSummitPacket.root_gcd_conj_isUnit
#print axioms RamifiedSecondCoordinateCanonicalSplit.nonempty_quadraticInnerRoot
#print axioms RamifiedQuadraticInnerRootPacket.coordinate_eq_fortyNine
#print axioms RamifiedQuadraticInnerRootPacket.innerRoot_coordinates_isCoprime
#print axioms RamifiedQuadraticInnerRootPacket.innerRoot_norm_eq
#print axioms RamifiedQuadraticInnerRootPacket.innerRootSnd_depth_eq_four
#print axioms RamifiedQuadraticInnerRootPacket.exists_inner_secondCoordinate_split
#print axioms RamifiedQuadraticInnerRootPacket.exists_inner_cubic_factor_signed_seventh_powers

#print axioms RamifiedQuadraticInnerRootPacket.exists_signed_innerSndRoot
#print axioms RamifiedQuadraticInnerRootPacket.nonempty_realCubicNorm
#print axioms RamifiedRealCubicNormPacket.norm_leftSource_eq
#print axioms RamifiedRealCubicNormPacket.norm_rightSource_eq
#print axioms RamifiedRealCubicNormPacket.signedRootGap_seventhPower_eq
#print axioms RamifiedRealCubicNormPacket.sourceDifference_eq_normalizedAxis_pow_six_mul_pow_seven

#print axioms PrimitiveRamifiedSummitPacket.explicitUnit_mod49_eq
#print axioms PrimitiveRamifiedSummitPacket.residualRoot_mod49_classifier
#print axioms PrimitiveRamifiedSummitPacket.isSeventhPowerMod49_iff_residualRoot_eq_one
#print axioms PrimitiveRamifiedSummitPacket.isSeventhPowerMod49_iff_three_residues

#print axioms AwaySevenBaseTerminalUnitSectorPacket.ramifiedCubicRouting
#print axioms PrimitiveRamifiedSummitPacket.cubicGap_depth_eq_endpointGap_depth

#print axioms RamifiedGapUnitBridgePacket.explicitUnit_reduction
#print axioms RamifiedGapUnitBridgePacket.isSeventhPowerMod49_iff
#print axioms RamifiedGapUnitBridgePacket.isSeventhPowerMod49_iff_residue

#print axioms RamifiedSignedRootRoutingPacket.DegreeSixLocalRatioProvider.oriented_mul_conjugate_eq_realPairCarrier
#print axioms RamifiedSignedRootRoutingPacket.DegreeSixLocalRatioProvider.localEval_orientedLinearCarrier_zero
#print axioms RamifiedSignedRootRoutingPacket.DegreeSixLocalRatioProvider.localEval_conjugateLinearCarrier_ne_zero
#print axioms RamifiedSignedRootRoutingPacket.DegreeSixLocalRatioProvider.orientedPair_associated_loadedCore
#print axioms RamifiedSignedRootRoutingPacket.nonempty_additiveChartFrontierPacket
#print axioms RamifiedSignedRootRoutingPacket.AdditiveChartFrontierPacket.orientedLoadedFactor_chartReadyAt

#print axioms RamifiedSignedRootRoutingPacket.cycleRatio_div_eq_absoluteFusionSlope
#print axioms RamifiedFusionRoutingAuditPacket.cycleRatio_square_div_eq_fusionSlope_sq

#print axioms SevenCyclotomicDegreeSixInt.sixPhaseProduct_eq_ofReal_cyclotomicNorm
#print axioms SevenCyclotomicDegreeSixInt.no_ringHom_to_int
#print axioms RamifiedSignedRootDepthPacket.cyclotomicNorm_cyclotomicDegreeSixCarrier
#print axioms RamifiedSignedRootDepthPacket.ramifiedElementEquation_boundary
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.orientedElementLevelPower_additiveBoundary
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.orientedResidualRoot_muSevenGaugeBoundary

#print axioms SevenCyclotomicDegreeSixInt.star_zeta
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.evalKernel_ne_conjugateEvalKernel
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.evalKernel_sup_conjugateEvalKernel
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.conjugateEvalKernel_comap_ofReal
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.conjugateEvalKernel_comap_intCast
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.conjugateEvalKernel_cardQuot
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.realPrimeFiberIdeal_le_conjugateProduct
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.conjugatePrimeProduct_le_realPrimeFiberIdeal
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.realPrimeFiberIdeal_eq_conjugateProduct
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.conjugatePrimeFiberProductEqualityObligation_holds
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.conjugatePrimePair_packet

#print axioms SevenCyclotomicDegreeSixInt.ringIsDomain

#print axioms SevenCyclotomicDegreeSixInt.zetaInv_eq_pow_six
#print axioms SevenCyclotomicDegreeSixInt.adjoin_zeta_eq_top
#print axioms SevenCyclotomicDegreeSixInt.ringOfIntegersToRing_surjective
#print axioms SevenCyclotomicDegreeSixInt.ringIsPrincipalIdealRing
#print axioms SevenCyclotomicDegreeSixInt.unitMulPowOfSpanEqPow

#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.eval_cyclotomicDegreeSixCarrier_zero
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.eval_cyclotomicDegreeSixCarrierConj_ne_zero
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.evalKernel_isMaximal
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.evalKernel_comap_ofReal
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.evalKernel_comap_intCast
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.evalKernel_cardQuot
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.linearPrimeAddress_packet

#print axioms SevenCyclotomicDegreeSixInt.ramifiedPrime_eq_span_uniformizer
#print axioms RamifiedSignedRootDepthPacket.cyclotomicDegreeSixCarrier_not_mem_ramifiedPrime_sq
#print axioms RamifiedSignedRootDepthPacket.cyclotomicDegreeSixCarrierConj_not_mem_ramifiedPrime_sq
#print axioms RamifiedSignedRootDepthPacket.ramifiedPrime_ownership_packet

#print axioms CyclotomicSeven.minkowskiFloor_le_four
#print axioms CyclotomicSeven.orderOf_two_zmodSeven
#print axioms CyclotomicSeven.orderOf_three_zmodSeven
#print axioms CyclotomicSeven.ringOfIntegers_isPrincipalIdealRing
#print axioms CyclotomicSeven.classNumber_eq_one

#print axioms RamifiedFusionRow2LoadFamily.PrimeSupport.map_kernelPower_eq_orientedPairPower
#print axioms RamifiedFusionRow2LoadFamily.PrimeSupport.orientedPairPowers_pairwise_isCoprime
#print axioms RamifiedFusionRow2LoadFamily.globalDegreeSixOrientedFactorIdeal_eq_span_ofReal_load
#print axioms RamifiedFusionRow2LoadFamily.degreeSixOrientedLoadFactorizationPacket

#print axioms RamifiedSignedRootDepthPacket.signedRoot_seventhPowerDifference_eq
#print axioms RamifiedSignedRootDepthPacket.sevenPowSix_not_dvd_signedRoot_seventhPowerDifference
#print axioms RamifiedSignedRootDepthPacket.not_exists_signedRoot_seventhPowerDifference_eq_pow
#print axioms RamifiedSignedRootDepthPacket.no_direct_signedFermatSevenChart

#print axioms SevenCyclotomicDegreeSixInt.exists_mul_pow_of_span_eq_mul_pow
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.cyclotomicDegreeSixCarrier_eq_load_mul_residualRoot_pow
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.cyclotomicDegreeSixCarrierConj_eq_load_mul_residualRoot_pow
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.elementLevelOrientedPowerPacket
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.elementLevelOrientedConjugatePowerPacket

#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeGCDLoadAddress.map_rotate_galoisKernel_zero_eq_one
#print axioms RamifiedSignedRootRoutingPacket.CyclotomicLinearPrimeAddress.map_star_evalKernel_eq_conjugateEvalKernel
#print axioms RamifiedFusionRow2LoadFamily.map_star_globalDegreeSixOrientedFactorIdeal
#print axioms RamifiedFusionRow2LoadFamily.globalOrientedPrimeFactorizationPacket

#print axioms RamifiedSignedRootRoutingPacket.RealPairLoadedPowerSplit.span_realPairCore_eq_loads_mul_residual_pow
#print axioms RamifiedSignedRootRoutingPacket.RealPairLoadedPowerSplit.carrierIdealPair_eq_ramified_sq_mul_loadHalves_mul_residualPair_pow

#print axioms RamifiedFusionRow2LoadFamily.PrimeSupport.orientedKernelPower_dvd_span_carrier
#print axioms RamifiedFusionRow2LoadFamily.PrimeSupport.conjugateKernelPower_dvd_span_conjugateCarrier
#print axioms RamifiedFusionRow2LoadFamily.PrimeSupport.carrier_mem_orientedKernelPower
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.carrier_mem_orientedKernelPower_iff
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.globalRealCoreFactorIdeal_eq_span_realPairCore
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.globalCarrierFactorIdeal_pair_exact
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.globalCarrierValuationOwnershipPacket

#print axioms RamifiedSignedRootDepthPacket.realPairCores_pairwiseCoprime
#print axioms RamifiedSignedRootDepthPacket.norm_realPairCore
#print axioms RamifiedSignedRootDepthPacket.nonempty_realPairCoreAssociatedPowerSplit
#print axioms RamifiedSignedRootRoutingPacket.nonempty_col3SeventhPowerSplit
#print axioms RamifiedSignedRootRoutingPacket.quotientRoot_signedSeventhPower_iff_row2_cells

#print axioms RamifiedPairedThetaRootJetPacket.relativeRealIndex_eq_one_iff

#print axioms SevenRealCubicInt.rotate_depthTen_thetaResidue
#print axioms RamifiedPairedThetaRootJetPacket.rotatedGapCoreResidues

#print axioms AwaySevenBaseTerminalUnitSectorPacket.ramifiedSummitWithProvenance
#print axioms RamifiedSignedRootRoutingPacket.activeCells_not_seven_dvd
#print axioms RamifiedPairedThetaRootJetPacket.nonempty_fusionRoutingAudit
#print axioms RamifiedPairedThetaRootJetPacket.relativeCyclotomicIndex_eq_one_iff

#print axioms sevenUnitSectorEquiv
#print axioms RamifiedPairedThetaRootJetPacket.left_binarySector_eq_neg_right

#print axioms SevenCyclotomicDegreeSixInt.map_star_ramifiedPrime
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.span_carrier_eq_loadedCarrier_mul_residual_pow
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.globalSeventhPowerResidualIdealExtractionPacket

#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.internalDepthFourCarrier_strictly_decreases
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.internalDepthFourCounterexampleReconstructionObligation_iff_strictDescentCandidate
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.exists_strict_awayCounterexample_of_internalDepthFourReconstruction
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.strictDescentFailureBoundary

#print axioms RamifiedSignedRootDepthPacket.quotientRoot_modSeven_eq_one
#print axioms RamifiedSignedRootDepthPacket.gapRoot_modSeven_eq

#print axioms RamifiedSignedRootDepthPacket.nonempty_pairedThetaRootJet
#print axioms RamifiedPairedThetaRootJetPacket.gapCore_thetaResidue_eq
#print axioms RamifiedPairedThetaRootJetPacket.left_not_sourcePlane
#print axioms RamifiedPairedThetaRootJetPacket.fusionSlope_eq_gapRoot_div_cube

#print axioms RamifiedRealCubicBalancedAxisSplitPacket.nonempty_signedRootDepth
#print axioms RamifiedSignedRootDepthPacket.gapRoot_isCoprime_quotientRoot

#print axioms RamifiedSignedRootDepthPacket.nonempty_coherent_signedRootRouting
#print axioms RamifiedSignedRootDepthPacket.nonempty_signedRootRouting

#print axioms triangularJet_depth_step
#print axioms triangularJet_depth_three_six
#print axioms nonempty_triangularThetaJetExact
#print axioms triangularJetJacobianDet_ne_zero

#print axioms SevenRealCubicInt.eisensteinAxis_prime
#print axioms RamifiedRealCubicExactPowerPacket.roots_isCoprime
#print axioms RamifiedRealCubicExactPowerPacket.nonempty_depthLedger
#print axioms RamifiedRealCubicDepthLedgerPacket.normalizedFactors_isCoprime
#print axioms RamifiedRealCubicDepthLedgerPacket.exists_gapCore_associated_pow_seven
#print axioms RamifiedRealCubicDepthLedgerPacket.exists_quotientCore_associated_pow_seven
#print axioms RamifiedRealCubicDepthLedgerPacket.nonempty_balancedAxisSplit
#print axioms RamifiedRealCubicExactPowerPacket.nonempty_axisDrop
#print axioms RamifiedRealCubicNormPacket.nonempty_axisDrop

#print axioms SevenRealCubicInt.linearSource_isCoprime_rotateEquiv
#print axioms SevenRealCubicInt.linearSource_cyclic_pairwiseCoprime
#print axioms SevenRealCubicInt.exists_unit_mul_pow_seven_of_linearSource_norm_eq
#print axioms RamifiedRealCubicNormPacket.nonempty_upToUnit
#print axioms RamifiedRealCubicUpToUnitPacket.unitWeightedPowerDifference_eq

#print axioms SevenRealCubicInt.eisensteinAxis_relation
#print axioms SevenRealCubicInt.eisensteinAxis_cube
#print axioms SevenRealCubicInt.eisensteinPolynomial_isEisensteinAt
#print axioms SevenRealCubicInt.eisensteinPolynomial_irreducible
#print axioms SevenRealCubicInt.eisensteinAxisUnit_isUnit
#print axioms SevenRealCubicInt.ramifiedAxis_associated_eisensteinAxis
#print axioms SevenRealCubicInt.rotateEquiv_alpha
#print axioms SevenRealCubicInt.rotateEquiv_three

#print axioms SevenRealCubicInt.norm_mul
#print axioms SevenRealCubicInt.norm_leftSource
#print axioms SevenRealCubicInt.norm_rightSource
#print axioms SevenRealCubicInt.ramifiedAxis_cube
#print axioms SevenRealCubicInt.ramifiedUnit_isUnit
#print axioms SevenRealCubicInt.ramifiedAxis_mul_seven_pow_four_mul_pow_seven

#print axioms SevenRealCubicInt.norm_add_seven_cube_axis_mul
#print axioms RamifiedRealCubicDepthLedgerPacket.exists_normVariationCore
#print axioms RamifiedSignedRootDepthPacket.nonempty_normFirstVariation

#print axioms SevenRealCubic.powerBasis_discr
#print axioms SevenRealCubic.adjoin_isIntegralClosure
#print axioms SevenRealCubic.field_discr
#print axioms SevenRealCubic.nrComplexPlaces_eq_zero
#print axioms SevenRealCubic.minkowskiClassBound_eq
#print axioms SevenRealCubic.classNumber_eq_one
#print axioms SevenRealCubic.modelToRingOfIntegers_surjective
#print axioms SevenRealCubic.modelToRingOfIntegers_injective
#print axioms SevenRealCubic.ringOfIntegersRotateEquiv_three

#print axioms SevenRealCubicInt.thd_pow_seven
#print axioms SevenRealCubicInt.pow_seven_isSourcePlane_iff

#print axioms SevenRealCubicInt.theta_coordinate_decomposition

#print axioms SevenRealCubicInt.thetaLinear_pow_seven
#print axioms SevenRealCubicInt.thetaSquare_pow_seven

#print axioms SevenRealCubicInt.thetaConstModSeven_mul
#print axioms SevenRealCubicInt.projectiveLog_pow_seven
#print axioms SevenRealCubicInt.projectiveLog_alpha
#print axioms SevenRealCubicInt.projectiveLog_alphaAddOne
#print axioms SevenRealCubicInt.projectiveLog_eq_zero_of_linearSource_eq_unit_mul_pow_seven

#print axioms RamifiedRealCubicUpToUnitPacket.leftUnit_projectiveLog_eq_zero
#print axioms RamifiedRealCubicUpToUnitPacket.nonempty_exactPower
#print axioms RamifiedRealCubicNormPacket.nonempty_exactPower

end DkMath.FLT.Seven
