import DkMath.FLT.Seven.PrimeTraceOneClosureBridge

open DkMath.FLT.Seven

#print axioms traceOnePowCoords_negTwo_seven_fst
#print axioms traceOnePowCoords_negTwo_seven_snd
#print axioms not_seven_dvd_natAbs_norm_of_primeTraceOne_residual_axis_terminal
#print axioms not_seven_dvd_norm_of_primeTraceOne_residual_axis_terminal
#print axioms exists_seventhPowerCoords_of_primeTraceOneImaginaryStrippedIdealPacket_seven
#print axioms exists_seventhPowerRoot_not_seven_dvd_norm_of_primeTraceOnePacket
#print axioms exists_seventhPowerCoords_and_root_not_seven_dvd_norm_of_primeTraceOnePacket
#print axioms exists_seventhPowerCoords_residual_sndCore_not_dvd_seven_of_primeTraceOnePacket
