#!/usr/bin/env bash
set -euo pipefail

tts_dir="$(cd "$(dirname "$0")" && pwd)"
repo_root="$(cd "$tts_dir/../../../../../../../" && pwd)"
factory_tts="$tts_dir/../../../cosmic-formula-inversion-260715/tts"
kokoro="$repo_root/venv/bin/kokoro-tts"
model="$factory_tts/models/kokoro-v1.0.onnx"
voices="$factory_tts/models/voices-v1.0.bin"
raw_dir="$tts_dir/output/raw"
timed_dir="$tts_dir/output/timed"
timing="$tts_dir/output/timing.tsv"
concat_file="$tts_dir/output/concat.txt"
timed_master="$tts_dir/output/narration-timed.wav"
normalized_master="$tts_dir/output/narration-normalized.wav"

test -x "$kokoro"
test -f "$model"
test -f "$voices"
mkdir -p "$raw_dir" "$timed_dir"

printf 'cue\tstart\tend\tslot_seconds\traw_seconds\tatempo\ttext_file\n' > "$timing"
printf '%s\n' '# generated by build_narration.sh' > "$concat_file"

start="0.000"
while IFS='|' read -r cue text_file; do
  case "$cue" in
    ''|'#'*) continue ;;
  esac
  text_path="$tts_dir/$text_file"
  raw_wav="$raw_dir/cue_${cue}.wav"
  timed_wav="$timed_dir/cue_${cue}.wav"

  "$kokoro" "$text_path" "$raw_wav" \
    --lang en-us --voice af_sarah --model "$model" --voices "$voices"

  raw="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$raw_wav")"
  slot="$(awk -v raw="$raw" 'BEGIN { printf "%.3f", raw + 0.8 }')"
  end="$(awk -v start="$start" -v slot="$slot" 'BEGIN { printf "%.3f", start + slot }')"

  ffmpeg -nostdin -y -v error -i "$raw_wav" \
    -filter:a "apad=pad_dur=$slot,atrim=duration=$slot" \
    -ar 48000 -ac 1 -c:a pcm_s16le "$timed_wav"

  printf "file '%s'\n" "$timed_wav" >> "$concat_file"
  printf '%s\t%s\t%s\t%s\t%s\t1.000000\t%s\n' \
    "$cue" "$start" "$end" "$slot" "$raw" "$text_file" >> "$timing"
  start="$end"
done < "$tts_dir/cues.tsv"

ffmpeg -nostdin -y -v error -f concat -safe 0 -i "$concat_file" \
  -ar 48000 -ac 1 -c:a pcm_s16le "$timed_master"
ffmpeg -nostdin -y -v error -i "$timed_master" \
  -filter:a "loudnorm=I=-16:TP=-1.5:LRA=11" \
  -ar 48000 -ac 1 -c:a pcm_s16le "$normalized_master"

"$repo_root/venv/bin/python" "$tts_dir/../visual/generate_timeline.py" \
  "$timing" "$tts_dir" "$tts_dir/../visual/timeline.ass" \
  "$tts_dir/narration-en.srt" "$tts_dir/../visual/timeline.json"

ffprobe -v error -show_entries format=duration -of default=nw=1:nk=1 \
  "$normalized_master"
