/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.Lib.NumberTheory.GTailSevenResidueIdeal
import Mathlib.RingTheory.Ideal.Operations

#print "file: DkMath.Lib.NumberTheory.GTailSevenSplitIdeal"

/-!
# Split scalar-prime ideals in the existing Eisenstein ring

Two separated conjugate residue slots recover scalar divisibility of both
integral coordinates. All factorization statements require an actual root
and separation; no cyclotomic transfer or descent is asserted.
-/

namespace DkMath.Lib.NumberTheory

open DkMath.NumberTheory.TraceOneQuadratic

/-- A supplied root is separated from its conjugate at a prime away from three. -/
theorem eisensteinResidue_root_ne_conjugate {q : ℕ} (hq : Nat.Prime q)
    (hq3 : q ≠ 3) (t : ZMod q) (ht : t ^ 2 - t + 1 = 0) : t ≠ 1 - t := by
  intro heq
  have hlin : 2 * t - 1 = 0 := by linear_combination heq
  have hid : 4 * (t ^ 2 - t + 1) = (2 * t - 1) ^ 2 + 3 := by ring
  rw [ht, hlin] at hid
  have hthree : (3 : ZMod q) = 0 := by simpa using hid.symm
  have hqthree := (ZMod.natCast_eq_zero_iff 3 q).mp hthree
  exact hq3 ((Nat.prime_dvd_prime_iff_eq hq (by decide : Nat.Prime 3)).mp hqthree)

/-- Scalar element divisibility for every integral pair, including negative coordinates. -/
theorem scalar_dvd_traceOne_neg_one_iff (n : ℤ) (z : TraceOneInt (-1)) :
    ofInt (-1) n ∣ z ↔ n ∣ z.fst ∧ n ∣ z.snd := by
  constructor
  · rintro ⟨w, hw⟩
    have hf := congrArg TraceOneInt.fst hw
    have hs := congrArg TraceOneInt.snd hw
    exact ⟨⟨w.fst, by simpa [ofInt] using hf⟩,
      ⟨w.snd, by simpa [ofInt] using hs⟩⟩
  · rintro ⟨⟨r, hr⟩, ⟨s, hs⟩⟩
    refine ⟨⟨r, s⟩, ?_⟩
    apply traceOne_ext <;> simp [ofInt, hr, hs]

/-- The principal ideal generated by the embedded scalar modulus. -/
def eisensteinScalarIdeal (q : ℕ) : Ideal (TraceOneInt (-1)) :=
  Ideal.span ({ofInt (-1) (q : ℤ)} : Set (TraceOneInt (-1)))

/-- Principal scalar ideal membership is exactly divisibility of the two integral coordinates. -/
theorem mem_eisensteinScalarIdeal_iff (q : ℕ) (z : TraceOneInt (-1)) :
    z ∈ eisensteinScalarIdeal q ↔ (q : ℤ) ∣ z.fst ∧ (q : ℤ) ∣ z.snd := by
  rw [eisensteinScalarIdeal, Ideal.mem_span_singleton, scalar_dvd_traceOne_neg_one_iff]

/-- Two separated residue slots recover both integral coordinate divisors. -/
theorem mem_eisensteinResidueIdeals_iff_coordinates {q : ℕ} (hq : Nat.Prime q)
    (t : ZMod q) (ht : t ^ 2 - t + 1 = 0) (htdiff : t ≠ 1 - t)
    (z : TraceOneInt (-1)) :
    (z ∈ eisensteinResidueIdeal t ht ∧
      z ∈ eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht)) ↔
      (q : ℤ) ∣ z.fst ∧ (q : ℤ) ∣ z.snd := by
  let : Fact (Nat.Prime q) := ⟨hq⟩
  rw [mem_eisensteinResidueIdeal_iff, mem_eisensteinResidueIdeal_iff,
    ← CharP.intCast_eq_zero_iff (ZMod q) q z.fst,
    ← CharP.intCast_eq_zero_iff (ZMod q) q z.snd]
  simp only [eisensteinResidueEval]
  constructor
  · rintro ⟨hfirst, hsecond⟩
    have hmul : (z.snd : ZMod q) * (t - (1 - t)) = 0 := by
      linear_combination hfirst - hsecond
    have hs := (mul_eq_zero.mp hmul).resolve_right (sub_ne_zero.mpr htdiff)
    have hf : (z.fst : ZMod q) = 0 := by simpa [hs] using hfirst
    exact ⟨hf, hs⟩
  · rintro ⟨hf, hs⟩
    simp [hf, hs]

/-- Exact intersection in the existing integral ring, for every element of the ideal. -/
theorem eisensteinResidueIdeals_inf_eq_scalar {q : ℕ} (hq : Nat.Prime q)
    (t : ZMod q) (ht : t ^ 2 - t + 1 = 0) (htdiff : t ≠ 1 - t) :
    eisensteinResidueIdeal t ht ⊓
      eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht) =
        eisensteinScalarIdeal q := by
  ext z
  rw [Ideal.mem_inf, mem_eisensteinResidueIdeals_iff_coordinates hq t ht htdiff,
    mem_eisensteinScalarIdeal_iff]

/-- A lifted root gives a membership witness distinguishing the two kernels. -/
theorem eisensteinResidueIdeals_ne_of_root_ne_conjugate {q : ℕ}
    (t : ZMod q) (ht : t ^ 2 - t + 1 = 0) (htdiff : t ≠ 1 - t) :
    eisensteinResidueIdeal t ht ≠
      eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht) := by
  obtain ⟨n, hn⟩ := ZMod.intCast_surjective t
  have hm : tau (-1) - ofInt (-1) n ∈ eisensteinResidueIdeal t ht := by
    rw [mem_eisensteinResidueIdeal_iff]
    change eisensteinResidueRingHom t ht (tau (-1) - ofInt (-1) n) = 0
    rw [map_sub, eisensteinResidueRingHom_tau, eisensteinResidueRingHom_ofInt, hn, sub_self]
  have hnot : tau (-1) - ofInt (-1) n ∉
      eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht) := by
    rw [mem_eisensteinResidueIdeal_iff]
    change eisensteinResidueRingHom (1 - t) (eisensteinResidue_conjugate_root t ht)
      (tau (-1) - ofInt (-1) n) ≠ 0
    rw [map_sub, eisensteinResidueRingHom_tau, eisensteinResidueRingHom_ofInt, hn]
    exact sub_ne_zero.mpr htdiff.symm
  intro heq
  exact hnot (heq ▸ hm)

/-- Separated root kernels at a prime are distinct maximal, hence comaximal, ideals. -/
theorem eisensteinResidueIdeals_sup_eq_top {q : ℕ} (hq : Nat.Prime q)
    (t : ZMod q) (ht : t ^ 2 - t + 1 = 0) (htdiff : t ≠ 1 - t) :
    eisensteinResidueIdeal t ht ⊔
      eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht) = ⊤ := by
  let : (eisensteinResidueIdeal t ht).IsMaximal := eisensteinResidueIdeal_isMaximal hq t ht
  let : (eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht)).IsMaximal :=
    eisensteinResidueIdeal_isMaximal hq _ _
  exact (Ideal.isCoprime_of_isMaximal
    (eisensteinResidueIdeals_ne_of_root_ne_conjugate t ht htdiff)).sup_eq

/-- Checked split-prime product in the degree-two integral ring. -/
theorem eisensteinResidueIdeals_mul_eq_scalar {q : ℕ} (hq : Nat.Prime q)
    (t : ZMod q) (ht : t ^ 2 - t + 1 = 0) (htdiff : t ≠ 1 - t) :
    eisensteinResidueIdeal t ht *
      eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht) =
        eisensteinScalarIdeal q := by
  exact (Ideal.mul_eq_inf_of_coprime (eisensteinResidueIdeals_sup_eq_top hq t ht htdiff)).trans
    (eisensteinResidueIdeals_inf_eq_scalar hq t ht htdiff)

/-- The characteristic-three exception supplies root separation for the product receiver. -/
theorem eisensteinResidueIdeals_mul_eq_scalar_of_ne_three {q : ℕ} (hq : Nat.Prime q)
    (hq3 : q ≠ 3) (t : ZMod q) (ht : t ^ 2 - t + 1 = 0) :
    eisensteinResidueIdeal t ht *
      eisensteinResidueIdeal (1 - t) (eisensteinResidue_conjugate_root t ht) =
        eisensteinScalarIdeal q :=
  eisensteinResidueIdeals_mul_eq_scalar hq t ht (eisensteinResidue_root_ne_conjugate hq hq3 t ht)

end DkMath.Lib.NumberTheory
