import DkMath.FLT.Seven.PrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJet

namespace DkMathTest.FLT.SevenPrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJetApi

open DkMath.FLT.Seven
open DkMath.FLT.Seven.SevenRealCubic

#check directOrbitPairedDeepJetY
#check directOrbitPairedDeepJetZ
#check directOrbitPairedDeepJet_fixed_unit_identity
#check directOrbitPairedDeepJet_quotientCore_eq
#check directOrbitPairedDeepJet_quotientCore_eq_theta_mul_Z_pow_seven
#check directOrbitPairedDeepJet_gapCore_eq
#check directOrbitPairedDeepJet_cores_product_unit_eq
#check directOrbitPairedDeepJet_same_v_unit_identity
#check directOrbitPairedDeepJet_quotientCore_eq_canonical_depth32
#check directOrbitPairedDeepJet_quotientCore_sub_leading_axis_pow32_dvd
#check directOrbitPairedDeepJet_rotate_gap_theta_coordinates
#check directOrbitPairedDeepJet_ofInt_dvd_theta_coordinates
#check directOrbit_axis_pow_six_dvd_imp_natCast49
#check directOrbit_axis_pow_nine_dvd_imp_natCast343
#check directOrbitPairedDeepJet_source_root_mod49_scalar
#check directOrbitPairedDeepJet_source_root_sub_scalar_dvd49
#check directOrbitPairedDeepJet_source_root_pow_six_mod49_scalar
#check directOrbitPairedDeepJet_quotient_remainder_cancel_theta
#check directOrbitPairedDeepJet_z_pow_seven_square_mod49
#check directOrbitPairedDeepJet_not_seven_v
#check directOrbitPairedDeepJet_z_local_unit_and_linear
#check directOrbitPairedDeepJet_z_square_mod_seven
#check directOrbitPairedDeepJet_inverse_linear_mod_seven
#check directOrbitPairedDeepJet_inverse_square_mod_seven
#check directOrbitPairedDeepJet_v_square_mod_seven
#check directOrbitPairedDeepJet_v_projective_log_zero
#check directOrbitPairedDeepJet_v_seventh_power
#check directOrbitPairedDeepJet_49th_power_correction

end DkMathTest.FLT.SevenPrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJetApi
