import DkMath.FLT.Seven.PrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJet

open DkMath.FLT.Seven
open DkMath.FLT.Seven.SevenRealCubic

#print axioms directOrbitPairedDeepJet_fixed_unit_identity
#print axioms directOrbitPairedDeepJet_same_v_unit_identity
#print axioms directOrbitPairedDeepJet_quotientCore_eq
#print axioms directOrbitPairedDeepJet_quotientCore_eq_theta_mul_Z_pow_seven
#print axioms directOrbitPairedDeepJet_gapCore_eq
#print axioms directOrbitPairedDeepJet_cores_product_unit_eq
#print axioms directOrbitPairedDeepJet_quotientCore_eq_canonical_depth32
#print axioms directOrbitPairedDeepJet_quotientCore_sub_leading_axis_pow32_dvd
#print axioms directOrbitPairedDeepJet_rotate_gap_theta_coordinates
#print axioms directOrbitPairedDeepJet_ofInt_dvd_theta_coordinates
#print axioms directOrbitPairedDeepJet_source_root_mod49_scalar
#print axioms directOrbit_axis_pow_six_dvd_imp_natCast49
#print axioms directOrbit_axis_pow_nine_dvd_imp_natCast343
