import DkMath.FLT.Seven.PrimeTraceOnePrimitiveRamifiedProvenance

open DkMath.FLT.Seven

#print axioms nonempty_primitiveCounterexampleRamifiedProvenance
#print axioms PrimitiveCounterexampleRamifiedProvenance.toResolution
#print axioms PrimitiveCounterexampleRamifiedProvenance.toResolution_summit
#print axioms PrimitiveCounterexampleRamifiedProvenance.gap_residual_coprime
#print axioms PrimitiveCounterexampleRamifiedProvenance.endpointLeft_not_seven_dvd
#print axioms PrimitiveCounterexampleRamifiedProvenance.endpointRight_not_seven_dvd
#print axioms PrimitiveCounterexampleRamifiedProvenance.endpointSum_not_seven_dvd
#print axioms PrimitiveCounterexampleRamifiedProvenance.terminalizable_iff_gapRoot_not_seven_dvd
#print axioms PrimitiveCounterexampleRamifiedProvenance.terminalizable_iff_endpoint_depth_eq_one
#print axioms PrimitiveCounterexampleRamifiedProvenance.endpoint_depth_eq_one_or_two_le
#print axioms PrimitiveCounterexampleRamifiedProvenance.seven_dvd_gapRoot_of_two_le_endpoint_depth
#print axioms PrimitiveCounterexampleRamifiedProvenance.not_terminalizable_of_two_le_endpoint_depth
#print axioms PrimitiveCounterexampleRamifiedProvenance.nonempty_secondCoordinateRouting_of_endpoint_depth_eq_one
