import DkMath.FLT.Seven.PrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJet

namespace DkMathTest.FLT.SevenPrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJetApi

open DkMath.FLT.Seven
open DkMath.FLT.Seven.SevenRealCubic

#check directOrbitPairedDeepJetY
#check directOrbitPairedDeepJetZ
#check directOrbitPairedDeepJet_fixed_unit_identity
#check directOrbitPairedDeepJet_quotientCore_eq
#check directOrbitPairedDeepJet_quotientCore_eq_theta_mul_Z_pow_seven
#check directOrbitPairedDeepJet_gapCore_eq
#check directOrbitPairedDeepJet_cores_product_unit_eq
#check directOrbitPairedDeepJet_same_v_unit_identity
#check directOrbitPairedDeepJet_quotientCore_eq_canonical_depth32
#check directOrbitPairedDeepJet_quotientCore_sub_leading_axis_pow32_dvd
#check directOrbitPairedDeepJet_rotate_gap_theta_coordinates
#check directOrbitPairedDeepJet_ofInt_dvd_theta_coordinates
#check directOrbit_axis_pow_six_dvd_imp_natCast49
#check directOrbit_axis_pow_nine_dvd_imp_natCast343
#check directOrbitPairedDeepJet_source_root_mod49_scalar

end DkMathTest.FLT.SevenPrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJetApi
