import DkMath.FLT.Seven.PrimeTraceOnePrimitiveRamifiedResolutionU16

open DkMath.FLT.Seven

#print axioms primitiveSevenDivisibleEndpoint_of_counterexample
#print axioms seven_dvd_some_endpoint_of_counterexample
#print axioms seven_dvd_gap_of_seven_dvd_first
#print axioms PrimitiveCounterexampleRamifiedResolution.rootSnd_padicValNat_add_two_eq_seven_mul_endpoint_depth
#print axioms nonempty_primitiveCounterexampleRamifiedResolution
#print axioms nonempty_primitiveCounterexampleRamifiedSummit
#print axioms PrimitiveRamifiedSummitPacket.distinguished_padicValNat
#print axioms PrimitiveRamifiedSummitPacket.rootSnd_padicValNat_add_two_eq
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.internalDepthFourPrescribedCarrierRamifiedSummit_depths
