import DkMath.FLT.Seven.PrimeTraceOneHigherDepthRamifiedCanonicalReceiver

open DkMath.FLT.Seven

#check PrimitiveRamifiedSummitPacket.ramifiedPrimaryCompensationCore
#check RamifiedPrimarySecondCoordinateCanonicalSplit
#check RamifiedPrimarySecondCoordinateCanonicalSplit.nonempty
#check PrimitiveRamifiedSummitPacket.primaryCanonicalSplit
#check RamifiedPrimarySecondCoordinateCanonicalSplit.cubicGap_natAbs_eq
#check RamifiedPrimarySecondCoordinateCanonicalSplit.CubicGapSeventhShape
#check RamifiedPrimarySecondCoordinateCanonicalSplit.CubicGapSeventhShapeReceiver
#check RamifiedPrimarySecondCoordinateCanonicalSplit.vertical_coprime_compensation_residual
#check RamifiedPrimarySecondCoordinateCanonicalSplit.receiver_iff_cubicGap_seventh_shape
#check RamifiedPrimarySecondCoordinateCanonicalSplit.receiver_iff_independent_seventh_powers
#check RamifiedPrimarySecondCoordinateCanonicalSplit.depth_zero_compensation_core_eq_terminal
#check RamifiedPrimarySecondCoordinateCanonicalSplit.depth_zero_receiver_iff_terminal_receiver
#check RamifiedPrimaryQuadraticInnerRootPacket
#check RamifiedPrimarySecondCoordinateCanonicalSplit.nonempty_primaryQuadraticInnerRoot
#check RamifiedPrimaryQuadraticInnerRootPacket.innerRoot_coordinates_isCoprime
#check RamifiedPrimaryQuadraticInnerRootPacket.innerRoot_norm_eq
#check RamifiedPrimaryQuadraticInnerRootPacket.inner_secondCoordinate_product_eq
#check RamifiedPrimaryQuadraticInnerRootPacket.innerRootSnd_depth_eq_four_add_seven_mul
#check RamifiedPrimaryQuadraticInnerRootPacket.exists_inner_secondCoordinate_split
#check PrimitiveCounterexampleRamifiedProvenance.innerRootSnd_depth_add_three_eq_distinguished_depth

example (p : PrimitiveRamifiedSummitPacket) :
    Nonempty (RamifiedPrimarySecondCoordinateCanonicalSplit p) :=
  RamifiedPrimarySecondCoordinateCanonicalSplit.nonempty
    (Classical.choice p.nonempty_primarySecondCoordinateRouting)
