import DkMath.FLT.Seven.PrimeTraceOneReconstructionRamifiedResolutionU16

open DkMath.FLT.Seven

#print axioms no_counterexample_of_seven_dvd_y_add_z
#print axioms AwayCarrierFermatChart.sum_impossible
#print axioms nonempty_ramified_of_seven_dvd_second
#print axioms nonempty_prescribedCarrierAlternatingPowerSplit
#print axioms nonempty_prescribedCarrierSignedResidualCore
#print axioms PrescribedCarrierSignedResidualCore.exists_residualCore_eq_seventh_power
#print axioms nonempty_prescribedCarrierRamifiedSummit_of_right_chart
#print axioms nonempty_prescribedCarrierRamifiedSummit_of_left_chart
#print axioms nonempty_prescribedCarrierRamifiedSummit_of_fermatChart
#print axioms nonempty_prescribedCarrierRamifiedSummit_of_awayCarrierReconstruction
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.internalDepthFourPrescribedCarrierRamifiedSummit
