import DkMath.FLT.Seven.PrimeTraceOneHigherDepthRamifiedRouting

open DkMath.FLT.Seven

#print axioms RamifiedGapRootPrimaryDecomposition.ofSummit
#print axioms PrimitiveRamifiedSummitPacket.rootSnd_mul_sndCore_eq
#print axioms PrimitiveRamifiedSummitPacket.rootSnd_sndCore_coprime
#print axioms PrimitiveRamifiedSummitPacket.rootNorm_rootSnd_coprime
#print axioms PrimitiveRamifiedSummitPacket.rootNorm_sndCore_coprime
#print axioms PrimitiveRamifiedSummitPacket.gapRoot_endpointRight_coprime
#print axioms PrimitiveRamifiedSummitPacket.gapRoot_gapQuotient_coprime
#print axioms PrimitiveRamifiedSummitPacket.secondCoordinate_natAbs_product_eq
#print axioms PrimitiveRamifiedSummitPacket.nonempty_primarySecondCoordinateRouting
#print axioms PrimitiveRamifiedSummitPacket.primarySecondCoordinateRouting_depth_zero_calibration
#print axioms PrimitiveCounterexampleRamifiedProvenance.primary_depth_add_one_eq_distinguished_depth
