import DkMath.FLT.Seven.PrimeTraceOneHigherDepthRamifiedCanonicalReceiver

open DkMath.FLT.Seven

#print axioms RamifiedPrimarySecondCoordinateCanonicalSplit.nonempty
#print axioms PrimitiveRamifiedSummitPacket.primaryCanonicalSplit
#print axioms RamifiedPrimarySecondCoordinateCanonicalSplit.cubicGap_natAbs_eq
#print axioms RamifiedPrimarySecondCoordinateCanonicalSplit.receiver_iff_cubicGap_seventh_shape
#print axioms RamifiedPrimarySecondCoordinateCanonicalSplit.receiver_iff_independent_seventh_powers
#print axioms RamifiedPrimarySecondCoordinateCanonicalSplit.depth_zero_receiver_iff_terminal_receiver
#print axioms RamifiedPrimarySecondCoordinateCanonicalSplit.nonempty_primaryQuadraticInnerRoot
#print axioms RamifiedPrimaryQuadraticInnerRootPacket.innerRoot_coordinates_isCoprime
#print axioms RamifiedPrimaryQuadraticInnerRootPacket.innerRoot_norm_eq
#print axioms RamifiedPrimaryQuadraticInnerRootPacket.inner_secondCoordinate_product_eq
#print axioms RamifiedPrimaryQuadraticInnerRootPacket.innerRootSnd_depth_eq_four_add_seven_mul
#print axioms RamifiedPrimaryQuadraticInnerRootPacket.exists_inner_secondCoordinate_split
#print axioms PrimitiveCounterexampleRamifiedProvenance.innerRootSnd_depth_add_three_eq_distinguished_depth
