import DkMath.FLT.Seven.PrimeTraceOneReconstructionKernelU16

open DkMath.FLT.Seven

#print axioms awayCarrierReconstruction_iff_nonempty_descentClosureProvider
#print axioms AwayCarrierReconstruction.carrier_pos
#print axioms AwayCarrierReconstruction.one_le_carrier_depth
#print axioms AwayCarrierReconstruction.seven_dvd_carrier
#print axioms AwayValuationTransferPacket.root_snd_depth_eq_carrier_depth_sub_one
#print axioms AwayValuationTransferPacket.no_reconstruction_at_depth_one
#print axioms AwayValuationTransferPacket.no_descentClosureProvider_at_depth_one
#print axioms AwayValuationTransferPacket.seven_dvd_root_snd_of_two_le_carrier_depth
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.internalDepthFourReconstruction_iff_awayCarrierReconstruction
#print axioms RamifiedSignedRootRoutingPacket.QuotientPrimeSupport.internalDepthFourCarrier_admissible
