import DkMath.FLT.Seven.PrimeTraceOneDirectRealCubicTrivialCommonFactorPairedDeepJet

open DkMath.FLT.Seven
open DkMath.FLT.Seven.SevenRealCubic

#print axioms directOrbitPairedDeepJet_fixed_unit_identity
#print axioms directOrbitPairedDeepJet_same_v_unit_identity
#print axioms directOrbitPairedDeepJet_quotientCore_eq
#print axioms directOrbitPairedDeepJet_quotientCore_eq_theta_mul_Z_pow_seven
#print axioms directOrbitPairedDeepJet_gapCore_eq
#print axioms directOrbitPairedDeepJet_cores_product_unit_eq
#print axioms directOrbitPairedDeepJet_quotientCore_eq_canonical_depth32
#print axioms directOrbitPairedDeepJet_quotientCore_sub_leading_axis_pow32_dvd
#print axioms directOrbitPairedDeepJet_rotate_gap_theta_coordinates
#print axioms directOrbitPairedDeepJet_ofInt_dvd_theta_coordinates
#print axioms directOrbitPairedDeepJet_source_root_mod49_scalar
#print axioms directOrbitPairedDeepJet_source_root_pow_six_mod49_scalar
#print axioms directOrbitPairedDeepJet_source_root_depth9
#print axioms directOrbitPairedDeepJet_z_pow_seven_depth9
#print axioms directOrbitPairedDeepJet_z_depth8
#print axioms directOrbitPairedDeepJet_inverse_depth8
#print axioms directOrbitPairedDeepJet_7pow9_correction
#print axioms directOrbitPairedDeepJet_current_depth9_wrapper
#print axioms directOrbitPairedDeepJet_quotient_remainder_cancel_theta
#print axioms directOrbitPairedDeepJet_z_pow_seven_square_mod49
#print axioms directOrbitPairedDeepJet_z_square_mod_seven
#print axioms directOrbitPairedDeepJet_inverse_linear_mod_seven
#print axioms directOrbitPairedDeepJet_v_square_mod_seven
#print axioms directOrbitPairedDeepJet_v_projective_log_zero
#print axioms directOrbitPairedDeepJet_v_seventh_power
#print axioms directOrbitPairedDeepJet_49th_power_correction
#print axioms directOrbit_axis_pow_six_dvd_imp_natCast49
#print axioms directOrbit_axis_pow_nine_dvd_imp_natCast343
