"""Bounded arithmetic exploration; generated data are independently checked in Lean.

Search budget: at most two distinct candidate seats, each using at most three
distinct active primes. Do not treat this finite scan as a uniform provider.
Run from lean/dk_math. No actual whole-shell incidence or excess sum is used.
"""
from pathlib import Path
from collections import Counter
from itertools import combinations
from math import gcd, isqrt
import json

base = Path(__file__).resolve().parent.parent
root = base.parents[2]
primes = [p for p in range(2, 101) if all(p % d for d in range(2, isqrt(p) + 1))]

def factors(n):
    return [p for p in primes if n % p == 0]

def wave_cap(n, q, pairs):
    lo, hi = n*n // q, (n*n + 2*n) // q
    odd = (hi+1)//2 - (lo+1)//2
    def delta(d):
        return hi//d - lo//d - (hi//(2*d) - lo//(2*d))
    ds = [d for d in factors(n) if d != 2]
    caps = [(n+q-1)//q, odd] + [odd-delta(d) for d in ds]
    if pairs:
        caps += [odd+delta(d*e)-delta(d)-delta(e) for d, e in combinations(ds, 2)]
    return min(caps)

rows = []
for n in range(2, 101):
    active = [p for p in primes if 2 < p <= n and n % p != 0]
    candidates = [r for r in range(1, 2*n+1) if gcd(n, r) == 1 and (n*n+r) % 2 == 1]
    upper = sum(wave_cap(n, q, True) for q in active)
    old = sum(wave_cap(n, q, False) for q in active)
    witnesses = []
    for r in candidates:
        ps = [p for p in active if (n*n+r) % p == 0][:3]
        if len(ps) >= 2:
            witnesses.append({'seat': r, 'primes': ps, 'cost': len(ps)-1})
    witnesses.sort(key=lambda w: (-w['cost'], w['seat']))
    witnesses = witnesses[:2]
    local = sum(w['cost'] for w in witnesses)
    cls = 0 if upper < len(candidates) else 1 if upper < len(candidates)+local else 2
    rows.append({'n': n, 'class': cls, 'candidate': len(candidates), 'upper': upper,
                 'old_upper': old, 'local_cost': local, 'witnesses': witnesses,
                 'anchor_prime_factors': factors(n)})
(base / 'logs/classification-008.json').write_text(json.dumps(rows, indent=2)+'\n')

def finite(items):
    items = list(items)
    separator = ',\n    ' if len(items) > 3 else ', '
    return '{' + separator.join(items) + '}'

def triples(cls):
    return finite(f"({r['n']}, {r['upper']}, {r['candidate']})" for r in rows if r['class'] == cls)

certs = []
for row in rows:
    if row['class'] == 1:
        a, b = row['witnesses']
        assert a['cost'] == b['cost'] == 2
        certs.append(f"({row['n']}, ({a['seat']}, {finite(map(str,a['primes']))}), "
                     f"({b['seat']}, {finite(map(str,b['primes']))}))")
data = '''/- Bounded calibration data, regenerated by checks/classify-008.py. -/
import DkMathTest.NumberTheory.LegendreHybridProvider

namespace DkMathTest.LegendreHybridClassification

def classZeroData : Finset (ℕ × ℕ × ℕ) :=
  ZERO

def classOneData : Finset (ℕ × ℕ × ℕ) :=
  ONE

def classTwoData : Finset (ℕ × ℕ × ℕ) :=
  TWO

def classOneCertificates : Finset (ℕ × (ℕ × Finset ℕ) × (ℕ × Finset ℕ)) :=
  CERTS

end DkMathTest.LegendreHybridClassification
'''
for token, replacement in [('ZERO', triples(0)), ('ONE', triples(1)), ('TWO', triples(2)),
                           ('CERTS', finite(certs))]:
    data = data.replace(token, replacement)
(root / 'DkMathTest/NumberTheory/LegendreHybridClassificationData.lean').write_text(data)
counts = Counter(r['class'] for r in rows)
old_unresolved = [r['n'] for r in rows if r['old_upper'] >= r['candidate']+r['local_cost']]
summary = (f'Range 2..100; counts {dict(sorted(counts.items()))}.\n'
           f'Unresolved: {[r["n"] for r in rows if r["class"] == 2]}.\n'
           f'Old cap with same local budget unresolved: {old_unresolved}.\n')
(base / 'logs/classification-summary-008.txt').write_text(summary)
print(summary, end='')
