"""Search only008's thirty Class2 shells under a three-seat/three-prime budget.

Generated data are independently proved in Lean. This script never evaluates
whole-shell incidence/excess. A charge5 certificate truncates one triple to a
two-prime subset; mandatory41/91 separately retain their full charge6 witness.
"""
from pathlib import Path
from math import gcd, isqrt
import json

base = Path(__file__).resolve().parent.parent
root = base.parents[2]
old = json.loads((base/'logs/classification-008.json').read_text())
rows = []
witness_data = []
for entry in old:
    if entry['class'] != 2:
        continue
    n = entry['n']
    primes = [p for p in range(3, n+1) if n % p and
              all(p % d for d in range(2, isqrt(p)+1))]
    candidates = []
    for r in range(1, 2*n+1):
        if gcd(n, r) != 1 or (n*n+r) % 2 != 1:
            continue
        qs = [q for q in primes if (n*n+r) % q == 0][:3]
        if len(qs) >= 2:
            candidates.append({'seat': r, 'primes': qs, 'cost': len(qs)-1})
    candidates.sort(key=lambda w: (-w['cost'], w['seat']))
    chosen = candidates[:3]
    available = sum(w['cost'] for w in chosen)
    required = entry['upper'] - entry['candidate'] + 1
    target = min(required, available)
    witnesses = []
    remaining = target
    for witness in chosen:
        cost = min(remaining, witness['cost'])
        if cost:
            ps = witness['primes'][:cost+1]
            witnesses.append({'seat': witness['seat'], 'primes': ps, 'cost': cost})
            witness_data.append((n, witness['seat'], ps))
            remaining -= cost
    assert remaining == 0 and available == 6
    row = {'n': n, 'upper': entry['upper'], 'candidate': entry['candidate'],
           'required': required, 'available_charge': available, 'certified_charge': target,
           'solved': target >= required, 'witnesses': witnesses,
           'anchor_prime_factors': entry['anchor_prime_factors']}
    rows.append(row)
(base/'logs/classification-009.json').write_text(json.dumps(rows, indent=2)+'\n')

def finite(items):
    items = list(items)
    return '{' + (',\n    ' if len(items) > 3 else ', ').join(items) + '}'

header = '''/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

'''
data = header + '''import DkMathTest.NumberTheory.LegendreCRTSeat

#print "file: DkMathTest.NumberTheory.LegendreAdaptiveClassificationData"

/- Generated by checks/classify-009.py; every dataset assertion is kernel checked. -/

namespace DkMathTest.LegendreAdaptiveClassification

def diagnosticData : Finset (ℕ × ℕ × ℕ × ℕ) :=
  ROWS

def diagnosticWitnessData : Finset (ℕ × ℕ × Finset ℕ) :=
  WITNESSES

def solvedUpToFive : Finset ℕ := SOLVED5

def solvedAtSix : Finset ℕ := SOLVED6

def unresolvedShells : Finset ℕ := OPEN

end DkMathTest.LegendreAdaptiveClassification
'''
replacement = {
    'ROWS': finite(f"({r['n']}, {r['upper']}, {r['candidate']}, {r['certified_charge']})" for r in rows),
    'WITNESSES': finite(f"({n}, {r}, {finite(map(str, qs))})" for n, r, qs in witness_data),
    'SOLVED5': finite(str(r['n']) for r in rows if r['solved'] and r['certified_charge'] <= 5),
    'SOLVED6': finite(str(r['n']) for r in rows if r['solved'] and r['certified_charge'] == 6),
    'OPEN': finite(str(r['n']) for r in rows if not r['solved']),
}
for token, value in replacement.items():
    data = data.replace(token, value)
(root/'DkMathTest/NumberTheory/LegendreAdaptiveClassificationData.lean').write_text(data)
summary = (f'Previous Class2: {len(rows)} shells.\n'
           f'Charge<=5 solved: {[r["n"] for r in rows if r["solved"] and r["certified_charge"]<=5]}.\n'
           f'Charge6 solved: {[r["n"] for r in rows if r["solved"] and r["certified_charge"]==6]}.\n'
           f'Unresolved: {[r["n"] for r in rows if not r["solved"]]}.\n'
           'Every survivor has an explicit charge6 certificate; the budget, not missing seats, fails.\n')
(base/'logs/classification-summary-009.txt').write_text(summary)
print(summary, end='')
