/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.CosmicFormula.Rotation.CF2D.RegularOrbit
import DkMath.NumberTheory.EuclideanGeometry.FermatForm

#print "file: DkMath.NumberTheory.EuclideanGeometry.QuadraticConstructible"

/-!
# Algebraic quadratic constructibility

This module defines a finite expression language generated by rational
constants, ring operations, valid inverses, and valid nonnegative square
roots.  It is an algebraic model for quadratic construction, not yet a theorem
about straightedge-and-compass incidence geometry.

The syntax is total.  Side conditions for inverse and square-root nodes are
recorded separately by `QuadraticExpr.Valid`; this keeps recursive evaluation
simple while retaining the mathematical domain restrictions.
-/

namespace DkMath.NumberTheory.EuclideanGeometry

open DkMath.CosmicFormula.Rotation.CF2D

/-- Finite expressions generated by rational arithmetic and square roots. -/
inductive QuadraticExpr where
  | rat : ℚ → QuadraticExpr
  | add : QuadraticExpr → QuadraticExpr → QuadraticExpr
  | neg : QuadraticExpr → QuadraticExpr
  | mul : QuadraticExpr → QuadraticExpr → QuadraticExpr
  | inv : QuadraticExpr → QuadraticExpr
  | sqrt : QuadraticExpr → QuadraticExpr
deriving Repr

namespace QuadraticExpr

/-- Real semantics of a quadratic expression. -/
noncomputable def eval : QuadraticExpr → ℝ
  | rat q => (q : ℝ)
  | add x y => eval x + eval y
  | neg x => -eval x
  | mul x y => eval x * eval y
  | inv x => (eval x)⁻¹
  | sqrt x => Real.sqrt (eval x)

/--
Semantic validity: every inverse has a nonzero input and every square root has
a nonnegative radicand, recursively throughout the expression.
-/
noncomputable def Valid : QuadraticExpr → Prop
  | rat _ => True
  | add x y => x.Valid ∧ y.Valid
  | neg x => x.Valid
  | mul x y => x.Valid ∧ y.Valid
  | inv x => x.Valid ∧ x.eval ≠ 0
  | sqrt x => x.Valid ∧ 0 ≤ x.eval

end QuadraticExpr

/-- A real scalar represented by a valid finite quadratic expression. -/
def QuadraticallyConstructibleScalar (x : ℝ) : Prop :=
  ∃ e : QuadraticExpr, e.Valid ∧ e.eval = x

namespace QuadraticallyConstructibleScalar

/-- Every rational scalar is quadratically constructible. -/
theorem rat (q : ℚ) : QuadraticallyConstructibleScalar (q : ℝ) := by
  exact ⟨.rat q, trivial, rfl⟩

/-- Zero is quadratically constructible. -/
theorem zero : QuadraticallyConstructibleScalar 0 := by
  simpa using rat 0

/-- One is quadratically constructible. -/
theorem one : QuadraticallyConstructibleScalar 1 := by
  simpa using rat 1

/-- Quadratic constructibility is closed under addition. -/
theorem add {x y : ℝ} (hx : QuadraticallyConstructibleScalar x)
    (hy : QuadraticallyConstructibleScalar y) :
    QuadraticallyConstructibleScalar (x + y) := by
  rcases hx with ⟨ex, hex, rfl⟩
  rcases hy with ⟨ey, hey, rfl⟩
  exact ⟨.add ex ey, ⟨hex, hey⟩, rfl⟩

/-- Quadratic constructibility is closed under negation. -/
theorem neg {x : ℝ} (hx : QuadraticallyConstructibleScalar x) :
    QuadraticallyConstructibleScalar (-x) := by
  rcases hx with ⟨e, he, rfl⟩
  exact ⟨.neg e, he, rfl⟩

/-- Quadratic constructibility is closed under subtraction. -/
theorem sub {x y : ℝ} (hx : QuadraticallyConstructibleScalar x)
    (hy : QuadraticallyConstructibleScalar y) :
    QuadraticallyConstructibleScalar (x - y) := by
  simpa [sub_eq_add_neg] using hx.add hy.neg

/-- Quadratic constructibility is closed under multiplication. -/
theorem mul {x y : ℝ} (hx : QuadraticallyConstructibleScalar x)
    (hy : QuadraticallyConstructibleScalar y) :
    QuadraticallyConstructibleScalar (x * y) := by
  rcases hx with ⟨ex, hex, rfl⟩
  rcases hy with ⟨ey, hey, rfl⟩
  exact ⟨.mul ex ey, ⟨hex, hey⟩, rfl⟩

/-- A nonzero quadratically constructible scalar has constructible inverse. -/
theorem inv {x : ℝ} (hx : QuadraticallyConstructibleScalar x) (hx0 : x ≠ 0) :
    QuadraticallyConstructibleScalar x⁻¹ := by
  rcases hx with ⟨e, he, rfl⟩
  exact ⟨.inv e, ⟨he, hx0⟩, rfl⟩

/-- A nonnegative constructible scalar has constructible nonnegative root. -/
theorem sqrt {x : ℝ} (hx : QuadraticallyConstructibleScalar x) (hx0 : 0 ≤ x) :
    QuadraticallyConstructibleScalar (Real.sqrt x) := by
  rcases hx with ⟨e, he, rfl⟩
  exact ⟨.sqrt e, ⟨he, hx0⟩, rfl⟩

/-- Natural powers preserve quadratic constructibility. -/
theorem pow {x : ℝ} (hx : QuadraticallyConstructibleScalar x) (n : ℕ) :
    QuadraticallyConstructibleScalar (x ^ n) := by
  induction n with
  | zero => simpa using one
  | succ n ih => simpa [pow_succ] using ih.mul hx

end QuadraticallyConstructibleScalar

/-- Both coordinates of a CF2D state are quadratically constructible. -/
def QuadraticallyConstructibleVec (z : Vec ℝ) : Prop :=
  QuadraticallyConstructibleScalar z.core ∧
    QuadraticallyConstructibleScalar z.beam

namespace QuadraticallyConstructibleVec

/-- The neutral CF2D state has rational coordinates. -/
theorem one : QuadraticallyConstructibleVec (Vec.one ℝ) := by
  exact ⟨QuadraticallyConstructibleScalar.one,
    QuadraticallyConstructibleScalar.zero⟩

/-- The CF2D star product preserves coordinate constructibility. -/
theorem star {r z : Vec ℝ} (hr : QuadraticallyConstructibleVec r)
    (hz : QuadraticallyConstructibleVec z) :
    QuadraticallyConstructibleVec (Vec.star r z) := by
  constructor
  · simpa using (hr.1.mul hz.1).sub (hr.2.mul hz.2)
  · simpa using (hr.1.mul hz.2).add (hr.2.mul hz.1)

end QuadraticallyConstructibleVec

/-- A real unit kernel whose two coordinates are quadratically constructible. -/
def QuadraticallyConstructibleUnitKernel (r : UnitKernel ℝ) : Prop :=
  QuadraticallyConstructibleVec (r : Vec ℝ)

namespace QuadraticallyConstructibleUnitKernel

/-- The neutral unit kernel is quadratically constructible. -/
theorem one : QuadraticallyConstructibleUnitKernel (1 : UnitKernel ℝ) := by
  exact QuadraticallyConstructibleVec.one

/-- Unit-kernel multiplication preserves quadratic constructibility. -/
theorem mul {r s : UnitKernel ℝ} (hr : QuadraticallyConstructibleUnitKernel r)
    (hs : QuadraticallyConstructibleUnitKernel s) :
    QuadraticallyConstructibleUnitKernel (r * s) := by
  exact QuadraticallyConstructibleVec.star hr hs

/-- Every natural power of a constructible unit kernel is constructible. -/
theorem pow {r : UnitKernel ℝ} (hr : QuadraticallyConstructibleUnitKernel r)
    (n : ℕ) : QuadraticallyConstructibleUnitKernel (r ^ n) := by
  induction n with
  | zero => simpa using one
  | succ n ih => simpa [pow_succ] using ih.mul hr

end QuadraticallyConstructibleUnitKernel

/-- Constructible kernels carry constructible states to constructible states. -/
theorem quadraticallyConstructibleVec_act {r : UnitKernel ℝ} {z : Vec ℝ}
    (hr : QuadraticallyConstructibleUnitKernel r)
    (hz : QuadraticallyConstructibleVec z) :
    QuadraticallyConstructibleVec (UnitKernel.act r z) := by
  exact QuadraticallyConstructibleVec.star hr hz

/-- Every state in a constructible neutral-base kernel orbit is constructible. -/
theorem quadraticallyConstructible_kernelOrbitVertex
    {r : UnitKernel ℝ} (hr : QuadraticallyConstructibleUnitKernel r) (j : ℕ) :
    QuadraticallyConstructibleVec
      (kernelOrbitVertex r (Vec.one ℝ) j) := by
  exact quadraticallyConstructibleVec_act (hr.pow j)
    QuadraticallyConstructibleVec.one

/-- Every vertex in the finite regular orbit has constructible coordinates. -/
def QuadraticallyConstructibleRegularOrbit (k : ℕ) : Prop :=
  ∀ j : Fin k, QuadraticallyConstructibleVec (regularVertex k j)

/--
Constructibility of the one-step regular kernel is sufficient for coordinate
constructibility of the entire finite regular orbit.
-/
theorem quadraticallyConstructibleRegularOrbit_of_regularKernel {k : ℕ}
    (hkernel : QuadraticallyConstructibleUnitKernel (regularKernel k)) :
    QuadraticallyConstructibleRegularOrbit k := by
  intro j
  exact quadraticallyConstructible_kernelOrbitVertex hkernel j.val

section InterfaceChecks

#check QuadraticExpr
#check QuadraticExpr.Valid
#check QuadraticallyConstructibleScalar
#check QuadraticallyConstructibleScalar.sqrt
#check QuadraticallyConstructibleUnitKernel.pow
#check QuadraticallyConstructibleRegularOrbit
#check quadraticallyConstructibleRegularOrbit_of_regularKernel
#check IsGaussWantzelIndex

end InterfaceChecks

end DkMath.NumberTheory.EuclideanGeometry
