/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.FLT.Seven.PrimeTraceOneDirectCyclotomicChosenTail

#print "file: DkMath.FLT.Seven.PrimeTraceOneDirectCyclotomicUnitCongruence"

namespace DkMath.FLT.Seven

noncomputable section

set_option linter.style.longLine false

local instance : Fact (Nat.Prime 7) := ⟨by norm_num⟩

open SevenRealCubicInt
open SevenCyclotomicDegreeSixInt

/-- The principal ideal generated by seven in the concrete degree-six carrier. -/
def sevenIdeal : Ideal SevenCyclotomicDegreeSixInt.Ring :=
  Ideal.span ({(7 : SevenCyclotomicDegreeSixInt.Ring)} : Set _)

/-- An element-level extraction of the chosen quotient from the R11 ideal
identity.  The unit is intentionally retained as a separate datum. -/
structure DirectCyclotomicChosenQuotientPowerPacket
    {x y z : ℕ} (source : CounterexamplePack x y z)
    (r : PrimitiveCounterexampleRamifiedProvenance source) where
  idealRoot : Ideal SevenCyclotomicDegreeSixInt.Ring
  beta : SevenCyclotomicDegreeSixInt.Ring
  unit : SevenCyclotomicDegreeSixInt.Ring
  unit_isUnit : IsUnit unit
  span_beta : Ideal.span ({beta} : Set SevenCyclotomicDegreeSixInt.Ring) = idealRoot
  quotient_eq :
    directCyclotomicPhaseQuotient r 1 = unit * beta ^ 7

private def ScalarModSeven
    (a : SevenCyclotomicDegreeSixInt.Ring) : Prop :=
  ∃ n : ℤ, a ^ 7 - (n : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal

private theorem seven_mem_sevenIdeal :
    (7 : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal := by
  rw [sevenIdeal, Ideal.mem_span_singleton]

private theorem intCast_pow_seven_sub_self_mem_sevenIdeal
    (n : ℤ) :
    (n : SevenCyclotomicDegreeSixInt.Ring) ^ 7 -
        (n : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal := by
  have hmod : ((n ^ 7 - n : ℤ) : ZMod 7) = 0 := by
    rw [Int.cast_sub, Int.cast_pow, ZMod.pow_card, sub_self]
  have hdvd : (7 : ℤ) ∣ n ^ 7 - n := by
    exact (ZMod.intCast_zmod_eq_zero_iff_dvd (n ^ 7 - n) 7).mp hmod
  rcases hdvd with ⟨k, hk⟩
  rw [sevenIdeal, Ideal.mem_span_singleton]
  refine ⟨(k : SevenCyclotomicDegreeSixInt.Ring), ?_⟩
  calc
    (n : SevenCyclotomicDegreeSixInt.Ring) ^ 7 -
        (n : SevenCyclotomicDegreeSixInt.Ring) =
      ((n ^ 7 - n : ℤ) : SevenCyclotomicDegreeSixInt.Ring) := by
        norm_cast
    _ = ((7 * k : ℤ) : SevenCyclotomicDegreeSixInt.Ring) := by rw [hk]
    _ = (7 : SevenCyclotomicDegreeSixInt.Ring) * (k : _) := by norm_num

private theorem ScalarModSeven.add
    {x y : SevenCyclotomicDegreeSixInt.Ring}
    (hx : ScalarModSeven x) (hy : ScalarModSeven y) :
    ScalarModSeven (x + y) := by
  rcases hx with ⟨m, hm⟩
  rcases hy with ⟨n, hn⟩
  refine ⟨m + n, ?_⟩
  let c : SevenCyclotomicDegreeSixInt.Ring :=
    x ^ 6 * y + 3 * x ^ 5 * y ^ 2 + 5 * x ^ 4 * y ^ 3 +
      5 * x ^ 3 * y ^ 4 + 3 * x ^ 2 * y ^ 5 + x * y ^ 6
  have hpow : (x + y) ^ 7 = x ^ 7 + y ^ 7 + 7 * c := by
    dsimp [c]
    ring
  have hcross : 7 * c ∈ sevenIdeal :=
    sevenIdeal.mul_mem_right c seven_mem_sevenIdeal
  have hsum :
      (x ^ 7 - (m : SevenCyclotomicDegreeSixInt.Ring)) +
          (y ^ 7 - (n : SevenCyclotomicDegreeSixInt.Ring)) +
          7 * c ∈ sevenIdeal :=
    sevenIdeal.add_mem (sevenIdeal.add_mem hm hn) hcross
  rw [hpow]
  rw [Int.cast_add]
  convert hsum using 1
  ring

private theorem ScalarModSeven.mul
    {x y : SevenCyclotomicDegreeSixInt.Ring}
    (hx : ScalarModSeven x) (hy : ScalarModSeven y) :
    ScalarModSeven (x * y) := by
  rcases hx with ⟨m, hm⟩
  rcases hy with ⟨n, hn⟩
  refine ⟨m * n, ?_⟩
  have hmem :
      y ^ 7 * (x ^ 7 - (m : SevenCyclotomicDegreeSixInt.Ring)) +
          (m : SevenCyclotomicDegreeSixInt.Ring) *
            (y ^ 7 - (n : SevenCyclotomicDegreeSixInt.Ring)) ∈ sevenIdeal :=
    sevenIdeal.add_mem
      (sevenIdeal.mul_mem_left (y ^ 7) hm)
      (sevenIdeal.mul_mem_left (m : SevenCyclotomicDegreeSixInt.Ring) hn)
  rw [mul_pow]
  rw [Int.cast_mul]
  convert hmem using 1
  ring

private theorem ScalarModSeven.zeta : ScalarModSeven zeta := by
  refine ⟨1, ?_⟩
  rw [zeta_pow_seven]
  simp

theorem degreeSix_pow_seven_scalarized_mod_seven
    (a : SevenCyclotomicDegreeSixInt.Ring) :
    ∃ n : ℤ,
      a ^ 7 - (n : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal := by
  have ha : a ∈ Algebra.adjoin ℤ ({zeta} : Set SevenCyclotomicDegreeSixInt.Ring) := by
    rw [adjoin_zeta_eq_top]
    trivial
  induction ha using Algebra.adjoin_induction with
  | mem x hx =>
      have hx' : x = zeta := by simpa only [Set.mem_singleton_iff] using hx
      subst x
      exact ScalarModSeven.zeta
  | algebraMap n =>
      refine ⟨n, ?_⟩
      exact intCast_pow_seven_sub_self_mem_sevenIdeal n
  | add x y hx hy hpx hpy =>
      exact ScalarModSeven.add hpx hpy
  | mul x y hx hy hpx hpy =>
      exact ScalarModSeven.mul hpx hpy

/-- The unit congruence that is needed for the p=7 Kummer step. -/
def DegreeSixUnitCongruentToRationalModSeven
    (u : SevenCyclotomicDegreeSixInt.Ring) : Prop :=
  ∃ m : ℤ,
    ¬ (7 : ℤ) ∣ m ∧
    u - (m : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal

/-- The remaining concrete Kummer-unit target.  This is a specification of
the missing bridge, not an asserted theorem. -/
def DegreeSixKummerUnitLemmaAtSeven : Prop :=
  ∀ u : SevenCyclotomicDegreeSixInt.Ringˣ,
    DegreeSixUnitCongruentToRationalModSeven (u : SevenCyclotomicDegreeSixInt.Ring) →
      ∃ v : SevenCyclotomicDegreeSixInt.Ringˣ, u = v ^ 7

private theorem sevenIdeal_le_ramifiedPrime :
    sevenIdeal ≤ ramifiedPrime := by
  rw [sevenIdeal, Ideal.span_le]
  intro x hx
  simp only [Set.mem_singleton_iff] at hx
  subst x
  change ramifiedEval (7 : SevenCyclotomicDegreeSixInt.Ring) = 0
  change ramifiedEval ((7 : ℕ) : SevenCyclotomicDegreeSixInt.Ring) = 0
  rw [map_natCast]
  decide

private theorem directCyclotomicChosenQuotient_not_mem_ramifiedPrime
    {x y z : ℕ} {source : CounterexamplePack x y z}
    (r : PrimitiveCounterexampleRamifiedProvenance source) :
    directCyclotomicPhaseQuotient r 1 ∉ ramifiedPrime := by
  exact directCyclotomicPhaseQuotient_not_mem_ramifiedPrime_of_lt_seven
    r (by norm_num) (by norm_num)

theorem DirectCyclotomicChosenQuotientPowerPacket.beta_not_mem_ramifiedPrime
    {x y z : ℕ} {source : CounterexamplePack x y z}
    {r : PrimitiveCounterexampleRamifiedProvenance source}
    (p : DirectCyclotomicChosenQuotientPowerPacket source r) :
    p.beta ∉ ramifiedPrime := by
  intro hbeta
  have hbeta' : ramifiedEval p.beta = 0 := hbeta
  have hq' : ramifiedEval (directCyclotomicPhaseQuotient r 1) = 0 := by
    rw [p.quotient_eq, map_mul, map_pow, hbeta']
    simp
  exact directCyclotomicChosenQuotient_not_mem_ramifiedPrime r hq'

private theorem exists_integer_unit_congruence_of_nonzero_scalar
    {n e : ℤ} (hn : (n : ZMod 7) ≠ 0) (he : (e : ZMod 7) ≠ 0)
    {u : SevenCyclotomicDegreeSixInt.Ring}
    (hunit : u * (n : SevenCyclotomicDegreeSixInt.Ring) -
        (e : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal) :
    ∃ m : ℤ,
      ¬ (7 : ℤ) ∣ m ∧
      u - (m : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal := by
  let s : ℤ := Int.ofNat ((n : ZMod 7)⁻¹).val
  have hsmod : (s : ZMod 7) = (n : ZMod 7)⁻¹ := by
    dsimp [s]
    exact ZMod.natCast_zmod_val ((n : ZMod 7)⁻¹)
  have hsnmod : ((s * n - 1 : ℤ) : ZMod 7) = 0 := by
    rw [Int.cast_sub, Int.cast_mul, hsmod]
    simp [hn]
  have hsndvd : (7 : ℤ) ∣ s * n - 1 := by
    exact (ZMod.intCast_zmod_eq_zero_iff_dvd (s * n - 1) 7).mp hsnmod
  have hsnmem :
      ((s * n - 1 : ℤ) : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal := by
    rw [sevenIdeal, Ideal.mem_span_singleton]
    rcases hsndvd with ⟨k, hk⟩
    refine ⟨(k : SevenCyclotomicDegreeSixInt.Ring), ?_⟩
    calc
      ((s * n - 1 : ℤ) : SevenCyclotomicDegreeSixInt.Ring) =
          ((7 * k : ℤ) : SevenCyclotomicDegreeSixInt.Ring) := by rw [hk]
      _ = (7 : SevenCyclotomicDegreeSixInt.Ring) * (k : _) := by norm_num
  let m : ℤ := s * e
  have hmnmem :
      ((s : SevenCyclotomicDegreeSixInt.Ring) *
          (u * (n : SevenCyclotomicDegreeSixInt.Ring) -
            (e : SevenCyclotomicDegreeSixInt.Ring))) ∈ sevenIdeal :=
    sevenIdeal.mul_mem_left (s : SevenCyclotomicDegreeSixInt.Ring) hunit
  have hsnmem' :
      (u * ((s * n - 1 : ℤ) : SevenCyclotomicDegreeSixInt.Ring)) ∈ sevenIdeal :=
    sevenIdeal.mul_mem_left u hsnmem
  have hdiff :
      u - (m : SevenCyclotomicDegreeSixInt.Ring) ∈ sevenIdeal := by
    have htmp := sevenIdeal.neg_mem (sevenIdeal.sub_mem hsnmem' hmnmem)
    convert htmp using 1
    simp only [m, Int.cast_sub, Int.cast_mul, Int.cast_one]
    ring
  refine ⟨m, ?_, hdiff⟩
  intro hm
  have hmzero : (m : ZMod 7) = 0 :=
    (ZMod.intCast_zmod_eq_zero_iff_dvd m 7).mpr hm
  have hmn : (m : ZMod 7) = (n : ZMod 7)⁻¹ * (e : ZMod 7) := by
    simp [m, hsmod]
  rw [hmn] at hmzero
  exact (mul_ne_zero (inv_ne_zero hn) he) hmzero

theorem DirectCyclotomicChosenQuotientPowerPacket.unit_congruentToRationalModSeven
    {x y z : ℕ} {source : CounterexamplePack x y z}
    {r : PrimitiveCounterexampleRamifiedProvenance source}
    (p : DirectCyclotomicChosenQuotientPowerPacket source r) :
    DegreeSixUnitCongruentToRationalModSeven p.unit := by
  obtain ⟨n, hn⟩ := degreeSix_pow_seven_scalarized_mod_seven p.beta
  have htail : directRamifiedGapTail r ∈ sevenIdeal := by
    rw [sevenIdeal, Ideal.mem_span_singleton]
    refine ⟨ramifiedUniformizer ^ 29 * ramifiedSevenUnit ^ 5 *
        ofReal (r.summit.gapRoot : SevenRealCubicInt) ^ 7, ?_⟩
    change directRamifiedGapTail r =
      ofReal (7 : SevenRealCubicInt) *
        (ramifiedUniformizer ^ 29 * ramifiedSevenUnit ^ 5 *
          ofReal (r.summit.gapRoot : SevenRealCubicInt) ^ 7)
    rw [ofReal_seven_eq_uniformizer_pow_six_mul_unit]
    simp only [directRamifiedGapTail]
    ring
  have hqsub :
      directCyclotomicPhaseQuotient r 1 -
          ofReal (r.summit.endpointRight : SevenRealCubicInt) ∈ sevenIdeal := by
    rw [directCyclotomicPhaseQuotient_one]
    simpa [directRamifiedQuotient, sub_eq_add_neg] using htail
  have hqsub' :
      directCyclotomicPhaseQuotient r 1 -
          p.unit * p.beta ^ 7 ∈ sevenIdeal := by
    rw [p.quotient_eq]
    simp [sevenIdeal.zero_mem]
  have hun :
      p.unit * (n : SevenCyclotomicDegreeSixInt.Ring) -
          ofReal (r.summit.endpointRight : SevenRealCubicInt) ∈ sevenIdeal := by
    have hmul := sevenIdeal.mul_mem_left p.unit hn
    have hdiff := sevenIdeal.sub_mem hqsub hqsub'
    have hresult := sevenIdeal.sub_mem hdiff hmul
    convert hresult using 1
    ring
  have hbeta_ne := p.beta_not_mem_ramifiedPrime
  have hbeta_eval : ramifiedEval p.beta ≠ 0 := by
    intro hzero
    exact hbeta_ne hzero
  have hnmod : (n : ZMod 7) ≠ 0 := by
    intro hzero
    have hscalar := sevenIdeal_le_ramifiedPrime hn
    change ramifiedEval (p.beta ^ 7 -
      (n : SevenCyclotomicDegreeSixInt.Ring)) = 0 at hscalar
    rw [map_sub, map_pow, map_intCast] at hscalar
    rw [hzero] at hscalar
    exact hbeta_eval
      ((pow_eq_zero_iff (by norm_num : 7 ≠ 0)).mp (by simpa using hscalar))
  have hendpoint :
      (r.summit.endpointRight : ZMod 7) ≠ 0 := by
    intro hzero
    exact r.summit.endpointRight_not_seven_dvd
      ((ZMod.intCast_zmod_eq_zero_iff_dvd _ 7).mp hzero)
  apply exists_integer_unit_congruence_of_nonzero_scalar hnmod hendpoint
  have hof :
      ofReal (r.summit.endpointRight : SevenRealCubicInt) =
        (r.summit.endpointRight : SevenCyclotomicDegreeSixInt.Ring) := by
    ext <;> simp [ofReal, SevenRealCubicInt.ofInt,
      QuadraticAlgebra.algebraMap_eq]
  simpa only [hof, mul_comm] using hun

/-- The direct chosen-quotient ideal identity gives the honest element packet. -/
theorem exists_directCyclotomicChosenQuotientPowerPacket
    {x y z : ℕ} {source : CounterexamplePack x y z}
    (r : PrimitiveCounterexampleRamifiedProvenance source) :
    Nonempty (DirectCyclotomicChosenQuotientPowerPacket source r) := by
  obtain ⟨I, hI⟩ := directCyclotomicChosenQuotient_ideal_is_seventh_power r
  obtain ⟨u, hu, hq⟩ :=
    SevenCyclotomicDegreeSixInt.unitMulPowOfSpanEqPow hI
  let beta := Submodule.IsPrincipal.generator I
  have hbeta :
      Ideal.span ({beta} : Set SevenCyclotomicDegreeSixInt.Ring) = I := by
    exact Ideal.span_singleton_generator I
  exact ⟨{
    idealRoot := I
    beta := beta
    unit := u
    unit_isUnit := hu
    span_beta := hbeta
    quotient_eq := hq }⟩

theorem DirectCyclotomicChosenQuotientPowerPacket.directLinearFactor_eq
    {x y z : ℕ} {source : CounterexamplePack x y z}
    {r : PrimitiveCounterexampleRamifiedProvenance source}
    (p : DirectCyclotomicChosenQuotientPowerPacket source r) :
    directLinearFactor r = ramifiedUniformizer * p.unit * p.beta ^ 7 := by
  have hq := p.quotient_eq
  rw [directCyclotomicPhaseQuotient_one] at hq
  rw [directLinearFactor_eq_uniformizer_mul_quotient, hq]
  ring

/-- The explicit R11 tail is already a multiple of seven, not merely an
element of the ramified prime. -/
theorem directRamifiedGapTail_mem_sevenIdeal
    {x y z : ℕ} {source : CounterexamplePack x y z}
    (r : PrimitiveCounterexampleRamifiedProvenance source) :
    directRamifiedGapTail r ∈ sevenIdeal := by
  rw [sevenIdeal, Ideal.mem_span_singleton]
  refine ⟨ramifiedUniformizer ^ 29 * ramifiedSevenUnit ^ 5 *
      ofReal (r.summit.gapRoot : SevenRealCubicInt) ^ 7, ?_⟩
  change directRamifiedGapTail r =
    ofReal (7 : SevenRealCubicInt) *
      (ramifiedUniformizer ^ 29 * ramifiedSevenUnit ^ 5 *
        ofReal (r.summit.gapRoot : SevenRealCubicInt) ^ 7)
  rw [ofReal_seven_eq_uniformizer_pow_six_mul_unit]
  simp only [directRamifiedGapTail]
  ring

/-- The chosen quotient is congruent to its rational endpoint modulo `(7)`. -/
theorem directCyclotomicChosenQuotient_sub_endpointRight_mem_sevenIdeal
    {x y z : ℕ} {source : CounterexamplePack x y z}
    (r : PrimitiveCounterexampleRamifiedProvenance source) :
    directCyclotomicPhaseQuotient r 1 -
        ofReal (r.summit.endpointRight : SevenRealCubicInt) ∈ sevenIdeal := by
  rw [directCyclotomicPhaseQuotient_one]
  simpa [directRamifiedQuotient, sub_eq_add_neg] using
    directRamifiedGapTail_mem_sevenIdeal r

/-- The real-cubic source left by taking the relative quadratic norm of the
chosen quotient. -/
def directChosenQuotientRealSource
    {x y z : ℕ} {source : CounterexamplePack x y z}
    (r : PrimitiveCounterexampleRamifiedProvenance source) :
    SevenRealCubicInt :=
  (r.summit.endpointLeft : SevenRealCubicInt) *
      (r.summit.endpointRight : SevenRealCubicInt) -
    eisensteinAxis ^ 35 * thetaSevenUnit ^ 12 *
      (r.summit.gapRoot : SevenRealCubicInt) ^ 14

theorem directCyclotomicChosenQuotient_quadraticNorm
    {x y z : ℕ} {source : CounterexamplePack x y z}
    (r : PrimitiveCounterexampleRamifiedProvenance source) :
    QuadraticAlgebra.norm (directCyclotomicPhaseQuotient r 1) =
      directChosenQuotientRealSource r := by
  have hgap :
      ((r.summit.endpointLeft : ℤ) : SevenRealCubicInt) -
          (r.summit.endpointRight : SevenRealCubicInt) =
        (7 : SevenRealCubicInt) ^ 6 *
          (r.summit.gapRoot : SevenRealCubicInt) ^ 7 := by
    have h := congrArg
      (fun q : ℤ => (q : SevenRealCubicInt)) r.summit.gap_eq
    simp only [Int.cast_sub, Int.cast_mul, Int.cast_pow] at h
    norm_num only [Int.cast_ofNat] at h
    norm_num at h ⊢
    simpa using h
  have hgapSq :
      (((r.summit.endpointLeft : ℤ) : SevenRealCubicInt) -
          (r.summit.endpointRight : SevenRealCubicInt)) ^ 2 =
        eisensteinAxis ^ 36 * thetaSevenUnit ^ 12 *
          (r.summit.gapRoot : SevenRealCubicInt) ^ 14 := by
    rw [hgap, seven_eq_eisensteinAxis_cube_mul_unit]
    ring
  have hsource :
      directRelativeNorm r.summit.endpointLeft
          r.summit.endpointRight =
        eisensteinAxis *
          (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12 *
              (r.summit.gapRoot : SevenRealCubicInt) ^ 14 -
            (r.summit.endpointLeft : SevenRealCubicInt) *
              (r.summit.endpointRight : SevenRealCubicInt)) := by
    rw [directRelativeNorm]
    calc
      ((r.summit.endpointLeft : ℤ) : SevenRealCubicInt) ^ 2 -
          (alpha - 1) * (r.summit.endpointLeft : SevenRealCubicInt) *
            (r.summit.endpointRight : SevenRealCubicInt) +
          (r.summit.endpointRight : SevenRealCubicInt) ^ 2 =
        (((r.summit.endpointLeft : ℤ) : SevenRealCubicInt) -
            (r.summit.endpointRight : SevenRealCubicInt)) ^ 2 -
          eisensteinAxis * (r.summit.endpointLeft : SevenRealCubicInt) *
            (r.summit.endpointRight : SevenRealCubicInt) := by
              rw [eisensteinAxis_eq]
              ring
      _ = eisensteinAxis *
          (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12 *
              (r.summit.gapRoot : SevenRealCubicInt) ^ 14 -
            (r.summit.endpointLeft : SevenRealCubicInt) *
              (r.summit.endpointRight : SevenRealCubicInt)) := by
            rw [hgapSq]
            ring
  have hnormF :
      QuadraticAlgebra.norm (directLinearFactor r) =
        directRelativeNorm r.summit.endpointLeft
          r.summit.endpointRight := by
    apply ofReal_injective
    change algebraMap SevenRealCubicInt
      SevenCyclotomicDegreeSixInt.Ring
        (QuadraticAlgebra.norm (directLinearFactor r)) = _
    rw [QuadraticAlgebra.algebraMap_norm_eq_mul_star]
    simpa [directLinearFactor] using
      directLinearFactor_mul_star
        r.summit.endpointLeft r.summit.endpointRight
  have hfactor :
      QuadraticAlgebra.norm (directLinearFactor r) =
    QuadraticAlgebra.norm ramifiedUniformizer *
          QuadraticAlgebra.norm (directCyclotomicPhaseQuotient r 1) := by
    rw [directLinearFactor_eq_uniformizer_mul_quotient,
      directCyclotomicPhaseQuotient_one,
      QuadraticAlgebra.norm.map_mul]
  have hpi := quadraticNorm_ramifiedUniformizer
  apply mul_left_cancel₀ eisensteinAxis_prime.ne_zero
  calc
    eisensteinAxis * QuadraticAlgebra.norm
        (directCyclotomicPhaseQuotient r 1) =
        -QuadraticAlgebra.norm (directLinearFactor r) := by
          rw [hfactor, hpi]
          ring
    _ = -directRelativeNorm r.summit.endpointLeft
          r.summit.endpointRight := by rw [hnormF]
    _ = eisensteinAxis * directChosenQuotientRealSource r := by
      rw [hsource]
      simp only [directChosenQuotientRealSource]
      ring

/-- The unit obtained by taking the relative quadratic norm of the packet
unit. -/
def directChosenQuotientNormUnit
    {x y z : ℕ} {source : CounterexamplePack x y z}
    {r : PrimitiveCounterexampleRamifiedProvenance source}
    (p : DirectCyclotomicChosenQuotientPowerPacket source r) :
    SevenRealCubicIntˣ :=
  (p.unit_isUnit.map QuadraticAlgebra.norm).unit

theorem DirectCyclotomicChosenQuotientPowerPacket.realSource_eq_normUnit_mul_normBeta_pow
    {x y z : ℕ} {source : CounterexamplePack x y z}
    {r : PrimitiveCounterexampleRamifiedProvenance source}
    (p : DirectCyclotomicChosenQuotientPowerPacket source r) :
    directChosenQuotientRealSource r =
      (directChosenQuotientNormUnit p : SevenRealCubicInt) *
        QuadraticAlgebra.norm p.beta ^ 7 := by
  have hq := congrArg QuadraticAlgebra.norm p.quotient_eq
  rw [directCyclotomicChosenQuotient_quadraticNorm] at hq
  rw [QuadraticAlgebra.norm.map_mul, map_pow] at hq
  change directChosenQuotientRealSource r =
    ((p.unit_isUnit.map QuadraticAlgebra.norm).unit : SevenRealCubicInt) *
      QuadraticAlgebra.norm p.beta ^ 7 at hq
  exact hq

private theorem projectiveLog_eq_zero_of_source_eq_unit_mul_pow_seven
    (source root : SevenRealCubicInt) (u : SevenRealCubicIntˣ)
    (hconst : thetaConstModSeven source ≠ 0)
    (hlinear : thetaLinearModSeven source = 0)
    (hsquare : thetaSquareModSeven source = 0)
    (hsource : source = (u : SevenRealCubicInt) * root ^ 7) :
    projectiveLog (Additive.ofMul u) = 0 := by
  have hA :
      thetaConstModSeven source =
        thetaConstModSeven (u : SevenRealCubicInt) *
          thetaConstModSeven root ^ 7 := by
    rw [hsource, thetaConstModSeven_mul, thetaConstModSeven_pow]
  have hrootA : thetaConstModSeven root ≠ 0 := by
    intro hzero
    apply hconst
    rw [hA, hzero]
    simp
  have huB : thetaLinearModSeven (u : SevenRealCubicInt) = 0 := by
    have hproduct :
        thetaLinearModSeven (u : SevenRealCubicInt) *
            thetaConstModSeven root ^ 7 = 0 := by
      calc
        _ = thetaLinearModSeven
              ((u : SevenRealCubicInt) * root ^ 7) := by
          rw [thetaLinearModSeven_mul,
            thetaLinearModSeven_pow_seven,
            thetaConstModSeven_pow]
          ring
        _ = thetaLinearModSeven source := by rw [← hsource]
        _ = 0 := hlinear
    exact (mul_eq_zero.mp hproduct).resolve_right
      (pow_ne_zero 7 hrootA)
  have huC : thetaSquareModSeven (u : SevenRealCubicInt) = 0 := by
    have hproduct :
        thetaSquareModSeven (u : SevenRealCubicInt) *
            thetaConstModSeven root ^ 7 = 0 := by
      calc
        _ = thetaSquareModSeven
              ((u : SevenRealCubicInt) * root ^ 7) := by
          rw [thetaSquareModSeven_mul,
            thetaSquareModSeven_pow_seven,
            thetaLinearModSeven_pow_seven,
            thetaConstModSeven_pow]
          ring
        _ = thetaSquareModSeven source := by rw [← hsource]
        _ = 0 := hsquare
    exact (mul_eq_zero.mp hproduct).resolve_right
      (pow_ne_zero 7 hrootA)
  rw [projectiveLog_apply]
  ext
  · simp [unitNilpotentX, huB]
  · simp [unitNilpotentX, unitNilpotentY, huB, huC]

private theorem directChosenQuotientRealSource_theta_coordinates
    {x y z : ℕ} {source : CounterexamplePack x y z}
    (r : PrimitiveCounterexampleRamifiedProvenance source) :
    thetaConstModSeven (directChosenQuotientRealSource r) ≠ 0 ∧
      thetaLinearModSeven (directChosenQuotientRealSource r) = 0 ∧
      thetaSquareModSeven (directChosenQuotientRealSource r) = 0 := by
  have hEconst : thetaConstModSeven eisensteinAxis = 0 := by
    norm_num [thetaConstModSeven, eisensteinAxis]
  have hE7const : thetaConstModSeven (eisensteinAxis ^ 7) = 0 := by
    rw [thetaConstModSeven_pow, hEconst]
    simp
  have hE7linear : thetaLinearModSeven (eisensteinAxis ^ 7) = 0 :=
    thetaLinearModSeven_pow_seven eisensteinAxis
  have hE7square : thetaSquareModSeven (eisensteinAxis ^ 7) = 0 :=
    thetaSquareModSeven_pow_seven eisensteinAxis
  have hE35const : thetaConstModSeven (eisensteinAxis ^ 35) = 0 := by
    rw [show 35 = 7 * 5 by norm_num, pow_mul, thetaConstModSeven_pow,
      hE7const]
    simp
  have hE35linear : thetaLinearModSeven (eisensteinAxis ^ 35) = 0 := by
    rw [show 35 = 7 + 28 by norm_num, pow_add,
      thetaLinearModSeven_mul, hE7const, hE7linear]
    simp
  have hE35square : thetaSquareModSeven (eisensteinAxis ^ 35) = 0 := by
    rw [show 35 = 7 + 28 by norm_num, pow_add,
      thetaSquareModSeven_mul, hE7const, hE7linear, hE7square]
    simp
  have htermlinear :
      thetaLinearModSeven
        (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12 *
          (r.summit.gapRoot : SevenRealCubicInt) ^ 14) = 0 := by
    have hfirst :
        thetaLinearModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) = 0 := by
      rw [thetaLinearModSeven_mul, hE35const, hE35linear]
      simp
    have hfirstConst :
        thetaConstModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) = 0 := by
      rw [thetaConstModSeven_mul, hE35const]
      simp
    have hfirstLinear :
        thetaLinearModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) = 0 := by
      rw [thetaLinearModSeven_mul, hE35const, hE35linear]
      simp
    calc
      thetaLinearModSeven
          ((eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) *
            (r.summit.gapRoot : SevenRealCubicInt) ^ 14) =
        thetaConstModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) *
            thetaLinearModSeven ((r.summit.gapRoot : SevenRealCubicInt) ^ 14) +
          thetaLinearModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) *
            thetaConstModSeven ((r.summit.gapRoot : SevenRealCubicInt) ^ 14) :=
        thetaLinearModSeven_mul _ _
      _ = 0 := by
        simp only [hfirstConst, hfirstLinear, zero_mul, add_zero]
  have htermsquare :
      thetaSquareModSeven
        (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12 *
          (r.summit.gapRoot : SevenRealCubicInt) ^ 14) = 0 := by
    have hfirst :
        thetaSquareModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) = 0 := by
      rw [thetaSquareModSeven_mul, hE35const, hE35linear, hE35square]
      simp
    have hfirstConst :
        thetaConstModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) = 0 := by
      rw [thetaConstModSeven_mul, hE35const]
      simp
    have hfirstLinear :
        thetaLinearModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) = 0 := by
      rw [thetaLinearModSeven_mul, hE35const, hE35linear]
      simp
    calc
      thetaSquareModSeven
          ((eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) *
            (r.summit.gapRoot : SevenRealCubicInt) ^ 14) =
        thetaConstModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) *
            thetaSquareModSeven ((r.summit.gapRoot : SevenRealCubicInt) ^ 14) +
          thetaLinearModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) *
            thetaLinearModSeven ((r.summit.gapRoot : SevenRealCubicInt) ^ 14) +
          thetaSquareModSeven (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12) *
            thetaConstModSeven ((r.summit.gapRoot : SevenRealCubicInt) ^ 14) :=
        thetaSquareModSeven_mul _ _
      _ = 0 := by
        simp only [hfirstConst, hfirstLinear, hfirst, zero_mul, add_zero]
  have htermconst :
      thetaConstModSeven
        (eisensteinAxis ^ 35 * thetaSevenUnit ^ 12 *
          (r.summit.gapRoot : SevenRealCubicInt) ^ 14) = 0 := by
    rw [thetaConstModSeven_mul, thetaConstModSeven_mul, hE35const]
    simp
  have hLRconst :
      thetaConstModSeven
          ((r.summit.endpointLeft : SevenRealCubicInt) *
            (r.summit.endpointRight : SevenRealCubicInt)) =
        (r.summit.endpointLeft : ZMod 7) *
          (r.summit.endpointRight : ZMod 7) := by
    simp [thetaConstModSeven]
  have hLRlinear :
      thetaLinearModSeven
          ((r.summit.endpointLeft : SevenRealCubicInt) *
            (r.summit.endpointRight : SevenRealCubicInt)) = 0 := by
    simp [thetaLinearModSeven]
  have hLRsquare :
      thetaSquareModSeven
          ((r.summit.endpointLeft : SevenRealCubicInt) *
            (r.summit.endpointRight : SevenRealCubicInt)) = 0 := by
    simp [thetaSquareModSeven]
  have hconst_sub (a b : SevenRealCubicInt) :
      thetaConstModSeven (a - b) =
        thetaConstModSeven a - thetaConstModSeven b := by
    rcases a with ⟨a₁, b₁, c₁⟩
    rcases b with ⟨a₂, b₂, c₂⟩
    simp [thetaConstModSeven]
    ring
  have hlinear_sub (a b : SevenRealCubicInt) :
      thetaLinearModSeven (a - b) =
        thetaLinearModSeven a - thetaLinearModSeven b := by
    rcases a with ⟨a₁, b₁, c₁⟩
    rcases b with ⟨a₂, b₂, c₂⟩
    simp [thetaLinearModSeven]
    ring
  have hsquare_sub (a b : SevenRealCubicInt) :
      thetaSquareModSeven (a - b) =
      thetaSquareModSeven a - thetaSquareModSeven b := by
    simp [thetaSquareModSeven]
  constructor
  · rw [directChosenQuotientRealSource, hconst_sub,
      hLRconst, htermconst]
    intro hzero
    have hzero' :
        (r.summit.endpointLeft : ZMod 7) *
            (r.summit.endpointRight : ZMod 7) = 0 := by
      simpa using hzero
    exact (mul_ne_zero
      (by
        intro hleft
        have hleft' : (7 : ℤ) ∣ r.summit.endpointLeft :=
          (ZMod.intCast_zmod_eq_zero_iff_dvd _ 7).mp hleft
        have hgap' : (7 : ℤ) ∣
            r.summit.endpointLeft - r.summit.endpointRight := by
          rw [r.summit.gap_eq]
          exact dvd_mul_of_dvd_left (by norm_num) _
        rcases hleft' with ⟨l, hl⟩
        rcases hgap' with ⟨k, hk⟩
        apply r.summit.endpointRight_not_seven_dvd
        refine ⟨l - k, ?_⟩
        linear_combination hl - hk)
      (by
        intro h
        exact r.summit.endpointRight_not_seven_dvd
          ((ZMod.intCast_zmod_eq_zero_iff_dvd _ 7).mp h))) hzero'
  · constructor
    · rw [directChosenQuotientRealSource, hlinear_sub,
        hLRlinear, htermlinear, sub_zero]
    · rw [directChosenQuotientRealSource, hsquare_sub,
        hLRsquare, htermsquare, sub_zero]

theorem DirectCyclotomicChosenQuotientPowerPacket.realUnit_projectiveLog_eq_zero
    {x y z : ℕ} {source : CounterexamplePack x y z}
    {r : PrimitiveCounterexampleRamifiedProvenance source}
    (p : DirectCyclotomicChosenQuotientPowerPacket source r) :
    projectiveLog (Additive.ofMul (directChosenQuotientNormUnit p)) = 0 := by
  have hcoords := directChosenQuotientRealSource_theta_coordinates r
  apply projectiveLog_eq_zero_of_source_eq_unit_mul_pow_seven
    (directChosenQuotientRealSource r) (QuadraticAlgebra.norm p.beta)
    (directChosenQuotientNormUnit p)
    hcoords.1 hcoords.2.1 hcoords.2.2
  exact p.realSource_eq_normUnit_mul_normBeta_pow

theorem DirectCyclotomicChosenQuotientPowerPacket.exists_realNormUnit_seventhPower
    {x y z : ℕ} {source : CounterexamplePack x y z}
    {r : PrimitiveCounterexampleRamifiedProvenance source}
    (p : DirectCyclotomicChosenQuotientPowerPacket source r) :
    ∃ v : SevenRealCubicIntˣ,
      directChosenQuotientNormUnit p = v ^ 7 :=
  (SevenRealCubic.unit_isSeventhPower_iff_projectiveLog_eq_zero
    (directChosenQuotientNormUnit p)).mpr
      p.realUnit_projectiveLog_eq_zero

end
end DkMath.FLT.Seven
