/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.FLT.Seven.SevenRealCubicEisenstein
import Mathlib.NumberTheory.NumberField.ClassNumber
import Mathlib.NumberTheory.NumberField.InfinitePlace.TotallyRealComplex
import Mathlib.RingTheory.Discriminant
import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral

#print "file: DkMath.FLT.Seven.SevenRealCubicNumberField"

namespace DkMath.FLT.Seven

open Algebra Polynomial
open NumberField.InfinitePlace

open scoped NumberField nonZeroDivisors

noncomputable section

namespace SevenRealCubic

open SevenRealCubicInt

/-- The rational Eisenstein polynomial defining the real cubic field. -/
def polynomialQ : ℚ[X] :=
  eisensteinPolynomial.map (algebraMap ℤ ℚ)

theorem polynomialQ_irreducible :
    Irreducible polynomialQ := by
  exact eisensteinPolynomial_map_rat_irreducible

instance polynomialQ_irreducibleFact :
    Fact (Irreducible polynomialQ) :=
  ⟨polynomialQ_irreducible⟩

/-- The degree-three number field attached to the RAMIFIED real cubic order. -/
abbrev Field : Type :=
  AdjoinRoot polynomialQ

theorem polynomialQ_monic :
    polynomialQ.Monic := by
  exact eisensteinPolynomial_monic.map (algebraMap ℤ ℚ)

theorem polynomialQ_ne_zero :
    polynomialQ ≠ 0 :=
  polynomialQ_monic.ne_zero

/-- The canonical power basis generated by the translated root `theta`. -/
def powerBasis : PowerBasis ℚ Field :=
  AdjoinRoot.powerBasis polynomialQ_ne_zero

@[simp] theorem powerBasis_gen :
    powerBasis.gen = AdjoinRoot.root polynomialQ := rfl

theorem powerBasis_minpoly :
    minpoly ℚ powerBasis.gen = polynomialQ :=
  AdjoinRoot.minpoly_powerBasis_gen_of_monic polynomialQ_monic

theorem finrank_eq_three :
    Module.finrank ℚ Field = 3 := by
  rw [PowerBasis.finrank powerBasis]
  change polynomialQ.natDegree = 3
  rw [polynomialQ,
    Polynomial.natDegree_map_eq_of_injective
      (algebraMap ℤ ℚ).injective_int]
  exact eisensteinPolynomial_natDegree

/-- The translated generator is integral over the integers. -/
theorem powerBasis_gen_isIntegral :
    IsIntegral ℤ powerBasis.gen := by
  refine ⟨eisensteinPolynomial, eisensteinPolynomial_monic, ?_⟩
  rw [← aeval_def, ← aeval_map_algebraMap ℚ]
  change aeval powerBasis.gen polynomialQ = 0
  rw [powerBasis_gen]
  calc
    aeval (AdjoinRoot.root polynomialQ) polynomialQ =
        AdjoinRoot.mk polynomialQ polynomialQ :=
      AdjoinRoot.aeval_eq polynomialQ
    _ = 0 := AdjoinRoot.mk_self

set_option linter.unnecessarySeqFocus false in
/-- The rational power basis retains the discriminant `49`. -/
theorem powerBasis_discr :
    Algebra.discr ℚ powerBasis.basis = 49 := by
  rw [Algebra.discr_powerBasis_eq_norm, finrank_eq_three,
    powerBasis_minpoly]
  norm_num [polynomialQ, eisensteinPolynomial, Algebra.norm_eq_matrix_det
    powerBasis.basis]
  simp only [map_ofNat]
  rw [← powerBasis_gen, powerBasis.leftMulMatrix]
  have hdim : powerBasis.dim = 3 := by
    rw [← PowerBasis.finrank powerBasis]
    exact finrank_eq_three
  rw [PowerBasis.minpolyGen_eq, powerBasis_minpoly]
  rw [hdim]
  norm_num [polynomialQ,
    eisensteinPolynomial, coeff_X, coeff_C, coeff_natCast_ite,
    pow_two, Matrix.ofNat_apply, Matrix.natCast_apply,
    Matrix.mul_apply, Fin.sum_univ_three,
    Matrix.det_fin_three]
  split_ifs <;> simp_all <;> norm_num

theorem powerBasis_minpoly_int :
    minpoly ℤ powerBasis.gen = eisensteinPolynomial := by
  have h :=
    minpoly.isIntegrallyClosed_eq_field_fractions' ℚ
      powerBasis_gen_isIntegral
  rw [powerBasis_minpoly] at h
  change
    eisensteinPolynomial.map (algebraMap ℤ ℚ) =
      (minpoly ℤ powerBasis.gen).map (algebraMap ℤ ℚ) at h
  exact
    (Polynomial.map_injective (algebraMap ℤ ℚ)
      (algebraMap ℤ ℚ).injective_int h).symm

theorem powerBasis_minpoly_int_isEisensteinAt :
    (minpoly ℤ powerBasis.gen).IsEisensteinAt
      (Ideal.span ({(7 : ℤ)} : Set ℤ)) := by
  rw [powerBasis_minpoly_int]
  exact eisensteinPolynomial_isEisensteinAt

/-- Every algebraic integer of the cubic field lies in `ℤ[theta]`.  Thus the
Eisenstein power-basis order is the maximal order. -/
theorem adjoin_isIntegralClosure :
    IsIntegralClosure
      (Algebra.adjoin ℤ ({powerBasis.gen} : Set Field)) ℤ Field := by
  refine ⟨Subtype.val_injective, @fun x => ⟨fun hx => ⟨⟨x, ?_⟩, rfl⟩, ?_⟩⟩
  · have H :=
      Algebra.discr_mul_isIntegral_mem_adjoin ℚ
        powerBasis_gen_isIntegral hx
    rw [powerBasis_discr] at H
    have Hseven :
        (7 : ℤ) ^ 2 • x ∈
          Algebra.adjoin ℤ ({powerBasis.gen} : Set Field) := by
      simpa [Algebra.smul_def, zsmul_eq_mul] using H
    exact
      mem_adjoin_of_smul_prime_pow_smul_of_minpoly_isEisensteinAt
        (n := 2) (by norm_num : Prime (7 : ℤ))
        powerBasis_gen_isIntegral hx Hseven
        powerBasis_minpoly_int_isEisensteinAt
  · rintro ⟨y, rfl⟩
    exact
      IsIntegral.algebraMap
        ((le_integralClosure_iff_isIntegral.1
          (adjoin_le_integralClosure powerBasis_gen_isIntegral)).isIntegral y)

/-- The canonical comparison from the Eisenstein order to the ring of
integers. -/
def adjoinEquivRingOfIntegers :
    Algebra.adjoin ℤ ({powerBasis.gen} : Set Field) ≃ₐ[ℤ] 𝓞 Field :=
  @IsIntegralClosure.equiv ℤ
    (Algebra.adjoin ℤ ({powerBasis.gen} : Set Field)) Field
    _ _ _ _ _ adjoin_isIntegralClosure (𝓞 Field)
    _ _ (integralClosure.isIntegralClosure ℤ Field) _ _
    (IsScalarTower.of_algebraMap_eq fun _ => rfl)
    (IsScalarTower.of_algebraMap_eq fun _ => rfl)

private instance fieldIntTorsionFree :
    Module.IsTorsionFree ℤ Field :=
  inferInstance

/-- The integral power basis of the maximal order. -/
def integralPowerBasis : PowerBasis ℤ (𝓞 Field) :=
  (@Algebra.adjoin.powerBasis' ℤ Field _ _ _ _ _ _
      fieldIntTorsionFree powerBasis.gen powerBasis_gen_isIntegral).map
    adjoinEquivRingOfIntegers

@[simp] theorem integralPowerBasis_gen :
    integralPowerBasis.gen =
      ⟨powerBasis.gen, powerBasis_gen_isIntegral⟩ := by
  apply NumberField.RingOfIntegers.coe_injective
  change algebraMap (𝓞 Field) Field
      ((@Algebra.adjoin.powerBasis' ℤ Field _ _ _ _ _ _
        fieldIntTorsionFree powerBasis.gen powerBasis_gen_isIntegral).map
          adjoinEquivRingOfIntegers).gen = powerBasis.gen
  rw [PowerBasis.map_gen,
    @Algebra.adjoin.powerBasis'_gen ℤ Field _ _ _ _ _ _
      fieldIntTorsionFree powerBasis.gen powerBasis_gen_isIntegral]
  exact
    @IsIntegralClosure.algebraMap_equiv ℤ
      (Algebra.adjoin ℤ ({powerBasis.gen} : Set Field)) Field
      _ _ _ _ _ adjoin_isIntegralClosure (𝓞 Field)
      _ _ (integralClosure.isIntegralClosure ℤ Field) _ _
      (IsScalarTower.of_algebraMap_eq fun _ => rfl)
      (IsScalarTower.of_algebraMap_eq fun _ => rfl)
      ⟨powerBasis.gen,
        Algebra.subset_adjoin (Set.mem_singleton powerBasis.gen)⟩

theorem integralPowerBasis_dim :
    integralPowerBasis.dim = 3 := by
  change (minpoly ℤ powerBasis.gen).natDegree = 3
  rw [powerBasis_minpoly_int,
    eisensteinPolynomial_natDegree]

set_option maxHeartbeats 800000 in
-- Reindexing the localized integral basis unfolds two power bases and needs
-- more elaboration time than the project default.
/-- The field discriminant is the order discriminant `49`, since the
Eisenstein order is already maximal. -/
theorem field_discr :
    NumberField.discr Field = 49 := by
  let pB := integralPowerBasis
  have hloc :=
    @Algebra.discr_localizationLocalization ℤ (𝓞 Field) _ _ _
      ℚ _ _ ℤ⁰ _ Field _ _ _ _
      (IsScalarTower.of_algebraMap_eq fun _ => rfl)
      (IsScalarTower.of_algebraMap_eq fun _ => rfl)
      _ _ _ _ pB.basis
  apply (algebraMap ℤ ℚ).injective_int
  rw [← NumberField.discr_eq_discr _ pB.basis, ← hloc]
  convert powerBasis_discr using 1
  · have hdim : pB.dim = powerBasis.dim := by
      rw [← PowerBasis.finrank, ← PowerBasis.finrank]
      exact NumberField.RingOfIntegers.rank Field
    rw [← Algebra.discr_reindex _ _ (finCongr hdim)]
    congr 1
    ext i
    simp_rw [Function.comp_apply, Module.Basis.localizationLocalization_apply,
      PowerBasis.coe_basis, pB, integralPowerBasis_gen]
    simp
  · norm_num

/-- The cubic field has no complex places.  Positivity of its discriminant
forces an even number of complex places, while degree three bounds that
number by one. -/
theorem nrComplexPlaces_eq_zero :
    nrComplexPlaces Field = 0 := by
  have hsignature :=
    card_add_two_mul_card_eq_rank Field
  rw [finrank_eq_three] at hsignature
  have hrange :
      nrComplexPlaces Field = 0 ∨
        nrComplexPlaces Field = 1 := by
    omega
  rcases hrange with hzero | hone
  · exact hzero
  · have hsign := NumberField.sign_discr Field
    rw [field_discr, hone] at hsign
    norm_num at hsign

/-- The discriminant-49 cubic field is totally real. -/
theorem isTotallyReal :
    NumberField.IsTotallyReal Field :=
  NumberField.nrComplexPlaces_eq_zero_iff.mp
    nrComplexPlaces_eq_zero

/-- The class-group form of the Minkowski bound. -/
noncomputable def minkowskiClassBound : ℝ :=
  (4 / Real.pi) ^ nrComplexPlaces Field *
    (((Module.finrank ℚ Field).factorial : ℝ) /
      (Module.finrank ℚ Field : ℝ) ^ Module.finrank ℚ Field *
      Real.sqrt |(NumberField.discr Field : ℝ)|)

theorem minkowskiClassBound_eq :
    minkowskiClassBound = 14 / 9 := by
  rw [minkowskiClassBound, nrComplexPlaces_eq_zero,
    finrank_eq_three, field_discr]
  norm_num

theorem minkowskiClassBound_lt_two :
    minkowskiClassBound < 2 := by
  rw [minkowskiClassBound_eq]
  norm_num

/-- The exact discriminant bound makes the maximal order a PID. -/
theorem ringOfIntegers_isPrincipalIdealRing :
    IsPrincipalIdealRing (𝓞 Field) := by
  apply
    RingOfIntegers.isPrincipalIdealRing_of_abs_discr_lt
  rw [field_discr, nrComplexPlaces_eq_zero, finrank_eq_three]
  norm_num

/-- The real cubic field has class number one. -/
theorem classNumber_eq_one :
    NumberField.classNumber Field = 1 :=
  NumberField.classNumber_eq_one_iff.mpr
    ringOfIntegers_isPrincipalIdealRing

/-- The original generator `alpha = theta + 3`, now inside the maximal
order. -/
def alphaInteger : 𝓞 Field :=
  integralPowerBasis.gen + 3

theorem thetaInteger_relation :
    integralPowerBasis.gen ^ 3 +
        7 * integralPowerBasis.gen ^ 2 +
        14 * integralPowerBasis.gen + 7 = 0 := by
  apply NumberField.RingOfIntegers.coe_injective
  simp only [map_add, map_mul, map_pow, map_ofNat, map_zero,
    integralPowerBasis_gen, NumberField.RingOfIntegers.map_mk]
  have h := minpoly.aeval ℚ powerBasis.gen
  rw [powerBasis_minpoly] at h
  simpa [polynomialQ, eisensteinPolynomial, map_ofNat] using h

theorem alphaInteger_cube :
    alphaInteger ^ 3 =
      2 * alphaInteger ^ 2 + alphaInteger - 1 := by
  rw [alphaInteger]
  linear_combination thetaInteger_relation

/-- The concrete three-coordinate order maps into the full ring of integers
by sending its generator `alpha` to `theta + 3`. -/
def modelToRingOfIntegers :
    SevenRealCubicInt →+* 𝓞 Field where
  toFun x :=
    x.fst + x.snd * alphaInteger + x.thd * alphaInteger ^ 2
  map_zero' := by simp
  map_one' := by simp
  map_add' x y := by
    simp only [SevenRealCubicInt.fst_add, SevenRealCubicInt.snd_add,
      SevenRealCubicInt.thd_add, Int.cast_add]
    ring
  map_mul' x y := by
    simp only [SevenRealCubicInt.fst_mul, SevenRealCubicInt.snd_mul,
      SevenRealCubicInt.thd_mul, Int.cast_sub, Int.cast_add,
      Int.cast_mul, Int.cast_ofNat]
    linear_combination
      -(x.thd * y.thd * (alphaInteger + 2) +
        (x.snd * y.thd + x.thd * y.snd)) * alphaInteger_cube

@[simp] theorem modelToRingOfIntegers_ofInt (z : ℤ) :
    modelToRingOfIntegers (SevenRealCubicInt.ofInt z) = z := by
  simp [modelToRingOfIntegers, SevenRealCubicInt.ofInt]

@[simp] theorem modelToRingOfIntegers_two :
    modelToRingOfIntegers (2 : SevenRealCubicInt) =
      (2 : 𝓞 Field) := by
  exact map_ofNat modelToRingOfIntegers 2

@[simp] theorem modelToRingOfIntegers_alpha :
    modelToRingOfIntegers SevenRealCubicInt.alpha =
      alphaInteger := by
  simp [modelToRingOfIntegers, SevenRealCubicInt.alpha]

@[simp] theorem modelToRingOfIntegers_eisensteinAxis :
    modelToRingOfIntegers SevenRealCubicInt.eisensteinAxis =
      integralPowerBasis.gen := by
  norm_num [modelToRingOfIntegers, SevenRealCubicInt.eisensteinAxis,
    alphaInteger]

theorem modelToRingOfIntegers_surjective :
    Function.Surjective modelToRingOfIntegers := by
  intro y
  obtain ⟨f, _, rfl⟩ := integralPowerBasis.exists_eq_aeval' y
  refine ⟨aeval SevenRealCubicInt.eisensteinAxis f, ?_⟩
  calc
    modelToRingOfIntegers
        (aeval SevenRealCubicInt.eisensteinAxis f) =
        aeval
          (modelToRingOfIntegers SevenRealCubicInt.eisensteinAxis) f :=
      (Polynomial.aeval_algHom_apply
        modelToRingOfIntegers.toIntAlgHom
        SevenRealCubicInt.eisensteinAxis f).symm
    _ = aeval integralPowerBasis.gen f := by
      rw [modelToRingOfIntegers_eisensteinAxis]

theorem modelToRingOfIntegers_eq_thetaCoordinates
    (x : SevenRealCubicInt) :
    modelToRingOfIntegers x =
      (x.fst + 3 * x.snd + 9 * x.thd : ℤ) +
        (x.snd + 6 * x.thd : ℤ) * integralPowerBasis.gen +
        x.thd * integralPowerBasis.gen ^ 2 := by
  change
    (x.fst : 𝓞 Field) +
        (x.snd : 𝓞 Field) * (integralPowerBasis.gen + 3) +
        (x.thd : 𝓞 Field) * (integralPowerBasis.gen + 3) ^ 2 =
      _
  push_cast
  ring

theorem modelToRingOfIntegers_injective :
    Function.Injective modelToRingOfIntegers := by
  intro x y hxy
  rw [modelToRingOfIntegers_eq_thetaCoordinates,
    modelToRingOfIntegers_eq_thetaCoordinates] at hxy
  let i0 : Fin integralPowerBasis.dim :=
    ⟨0, by rw [integralPowerBasis_dim]; omega⟩
  let i1 : Fin integralPowerBasis.dim :=
    ⟨1, by rw [integralPowerBasis_dim]; omega⟩
  let i2 : Fin integralPowerBasis.dim :=
    ⟨2, by rw [integralPowerBasis_dim]; omega⟩
  have hlinear :
      (x.fst + 3 * x.snd + 9 * x.thd) •
            integralPowerBasis.basis i0 +
          (x.snd + 6 * x.thd) •
            integralPowerBasis.basis i1 +
          x.thd • integralPowerBasis.basis i2 =
        (y.fst + 3 * y.snd + 9 * y.thd) •
            integralPowerBasis.basis i0 +
          (y.snd + 6 * y.thd) •
            integralPowerBasis.basis i1 +
          y.thd • integralPowerBasis.basis i2 := by
    simpa [i0, i1, i2, Algebra.smul_def,
      integralPowerBasis.basis_eq_pow] using hxy
  have hrepr :=
    congr_arg integralPowerBasis.basis.repr hlinear
  simp only [map_add, LinearEquiv.map_smul,
    integralPowerBasis.basis.repr_self] at hrepr
  have h0 := DFunLike.congr_fun hrepr i0
  have h1 := DFunLike.congr_fun hrepr i1
  have h2 := DFunLike.congr_fun hrepr i2
  simp only [Finsupp.coe_add, Finsupp.coe_smul, Pi.add_apply,
    Pi.smul_apply, smul_eq_mul] at h0 h1 h2
  simp [i0, i1, i2] at h0 h1 h2
  apply SevenRealCubicInt.ext <;> omega

/-- The coordinate order from RAMIFIED-009 is exactly the full ring of
integers of the discriminant-49 cubic field. -/
noncomputable def modelEquivRingOfIntegers :
    SevenRealCubicInt ≃+* 𝓞 Field :=
  RingEquiv.ofBijective modelToRingOfIntegers
    ⟨modelToRingOfIntegers_injective,
      modelToRingOfIntegers_surjective⟩

noncomputable instance modelIsDomain :
    IsDomain SevenRealCubicInt :=
  (modelEquivRingOfIntegers :
    SevenRealCubicInt ≃* 𝓞 Field).isDomain

@[simp] theorem modelEquivRingOfIntegers_apply
    (x : SevenRealCubicInt) :
    modelEquivRingOfIntegers x = modelToRingOfIntegers x := rfl

@[simp] theorem modelEquivRingOfIntegers_symm_alphaInteger :
    modelEquivRingOfIntegers.symm alphaInteger =
      SevenRealCubicInt.alpha := by
  apply modelEquivRingOfIntegers.injective
  simp

/-- The cyclic order-three automorphism transported to the full ring of
integers. -/
noncomputable def ringOfIntegersRotateEquiv :
    𝓞 Field ≃+* 𝓞 Field :=
  modelEquivRingOfIntegers.symm.trans
    (SevenRealCubicInt.rotateEquiv.trans
      modelEquivRingOfIntegers)

theorem ringOfIntegersRotateEquiv_apply (x : 𝓞 Field) :
    ringOfIntegersRotateEquiv x =
      modelEquivRingOfIntegers
        (SevenRealCubicInt.rotateEquiv
          (modelEquivRingOfIntegers.symm x)) := rfl

theorem ringOfIntegersRotateEquiv_alpha :
    ringOfIntegersRotateEquiv alphaInteger =
      alphaInteger ^ 2 - 2 * alphaInteger := by
  rw [ringOfIntegersRotateEquiv_apply,
    modelEquivRingOfIntegers_symm_alphaInteger,
    SevenRealCubicInt.rotateEquiv_alpha]
  simp

theorem ringOfIntegersRotateEquiv_sq_alpha :
    ringOfIntegersRotateEquiv
        (ringOfIntegersRotateEquiv alphaInteger) =
      -alphaInteger ^ 2 + alphaInteger + 2 := by
  rw [ringOfIntegersRotateEquiv_apply,
    ringOfIntegersRotateEquiv_apply,
    modelEquivRingOfIntegers.symm_apply_apply,
    modelEquivRingOfIntegers_symm_alphaInteger,
    SevenRealCubicInt.rotateEquiv_sq_alpha]
  simp

theorem ringOfIntegersRotateEquiv_three (x : 𝓞 Field) :
    ringOfIntegersRotateEquiv
        (ringOfIntegersRotateEquiv
          (ringOfIntegersRotateEquiv x)) = x := by
  rw [ringOfIntegersRotateEquiv_apply,
    ringOfIntegersRotateEquiv_apply,
    ringOfIntegersRotateEquiv_apply,
    modelEquivRingOfIntegers.symm_apply_apply,
    modelEquivRingOfIntegers.symm_apply_apply,
    SevenRealCubicInt.rotateEquiv_three,
    modelEquivRingOfIntegers.apply_symm_apply]


end SevenRealCubic

end

end DkMath.FLT.Seven
