/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.CFBRC.Bridge
import DkMath.CFBRC.CyclotomicNorm
import Mathlib.RingTheory.Ideal.Norm.AbsNorm

#print "file: DkMath.CFBRC.CyclotomicIdeal"

/-!
# CFBRC cyclotomic principal ideal and global norm bridge

This module attaches the canonical principal ideal to the generic cyclotomic
linear factor.  It transports only absolute ideal norms and global rational
prime valuations; it does not choose a prime ideal above a rational prime.
-/

namespace DkMath.CFBRC

open DkMath.CosmicFormulaBinom
open NumberField

noncomputable section

/-- The principal ideal generated by the canonical cyclotomic linear factor. -/
def cyclotomicLinearFactorIdeal
    {K : Type*} [Field K] [NumberField K] [CharZero K]
    {p : ℕ} [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) (x u : ℕ) : Ideal (𝓞 K) :=
  Ideal.span
    ({cyclotomicLinearFactorInRingOfIntegers hζ x u} : Set (𝓞 K))

/-- The absolute norm of the canonical principal ideal is the `GN` kernel.

The ideal is principal, generated by the cyclotomic linear factor, so its
absolute ideal norm is the absolute value of the algebraic norm of that
generator.  The norm bridge from `CyclotomicNorm` identifies this scalar with
the cancellation-free `GN` value.  This is a global rational norm statement;
it does not select or split a prime ideal above a rational prime. -/
theorem cyclotomicLinearFactorIdeal_absNorm_eq_GN
    {K : Type*} [Field K] [NumberField K] [CharZero K]
    {p x u : ℕ} [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    Ideal.absNorm (cyclotomicLinearFactorIdeal hζ x u) =
      DkMath.CosmicFormulaBinom.GN p x u := by
  rw [cyclotomicLinearFactorIdeal, Ideal.absNorm_span_singleton,
    cyclotomicLinearFactor_norm_eq_GN hζ]
  simp only [Int.natAbs_natCast]

/-- The complete gap factor is retained after passing to the ideal norm.

This is a rational/integer norm identity.  It is not the field norm of the
element `x * alpha`; that field norm would carry the degree-`p - 1` factor
`x ^ (p - 1)` instead.
-/
theorem gap_mul_cyclotomicLinearFactorIdeal_absNorm_eq_sub_pow
    {K : Type*} [Field K] [NumberField K] [CharZero K]
    {p x u : ℕ} [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    x * Ideal.absNorm (cyclotomicLinearFactorIdeal hζ x u) =
      (x + u) ^ p - u ^ p := by
  rw [cyclotomicLinearFactorIdeal_absNorm_eq_GN hζ]
  change x * DkMath.CosmicFormula.GTail p 1 x u =
    (x + u) ^ p - u ^ p
  have hbig :=
    DkMath.CosmicFormula.add_pow_eq_mul_GTail_one_add_gap
      (R := ℕ) p x u
  have hpow : u ^ p ≤ (x + u) ^ p :=
    Nat.pow_le_pow_left (Nat.le_add_left u x) p
  omega

/-- Rational-prime divisibility is unchanged by the ideal-norm bridge. -/
theorem dvd_cyclotomicLinearFactorIdeal_absNorm_iff_dvd_GN
    {K : Type*} [Field K] [NumberField K] [CharZero K]
    {p x u q : ℕ} [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    q ∣ Ideal.absNorm (cyclotomicLinearFactorIdeal hζ x u) ↔
      q ∣ DkMath.CosmicFormulaBinom.GN p x u := by
  rw [cyclotomicLinearFactorIdeal_absNorm_eq_GN hζ]

/-- Divisibility of the complete power difference is transported to the ideal norm. -/
theorem dvd_sub_pow_iff_dvd_gap_mul_cyclotomicLinearFactorIdeal_absNorm
    {K : Type*} [Field K] [NumberField K] [CharZero K]
    {p x u q : ℕ} [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    q ∣ ((x + u) ^ p - u ^ p) ↔
      q ∣ x * Ideal.absNorm (cyclotomicLinearFactorIdeal hζ x u) := by
  rw [gap_mul_cyclotomicLinearFactorIdeal_absNorm_eq_sub_pow hζ]

/-- The global rational-prime valuation is exactly the `GN` valuation.

This equality transports `padicValNat` through the scalar ideal-norm bridge;
it must not be read as ownership of that valuation by one prime ideal above
`q`. -/
theorem padicValNat_cyclotomicLinearFactorIdeal_absNorm_eq_GN
    {K : Type*} [Field K] [NumberField K] [CharZero K]
    {p x u q : ℕ} [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ p) :
    padicValNat q (Ideal.absNorm (cyclotomicLinearFactorIdeal hζ x u)) =
      padicValNat q (DkMath.CosmicFormulaBinom.GN p x u) := by
  rw [cyclotomicLinearFactorIdeal_absNorm_eq_GN hζ]

/-- Under the existing boundary hypotheses, the ideal norm has the valuation
of the complete power difference. -/
theorem padicValNat_cyclotomicLinearFactorIdeal_absNorm_eq_sub_pow_of_not_dvd_boundary
    {K : Type*} [Field K] [NumberField K] [CharZero K]
    {p x u q : ℕ} [Fact p.Prime] [IsCyclotomicExtension {p} ℚ K]
    {ζ : K} (hζ : IsPrimitiveRoot ζ p)
    (hp2 : 2 ≤ p) (hx : 0 < x) (hu : 0 < u)
    (hqP : Nat.Prime q) (hq_not_dvd_x : ¬ q ∣ x) :
    padicValNat q (Ideal.absNorm (cyclotomicLinearFactorIdeal hζ x u)) =
      padicValNat q ((x + u) ^ p - u ^ p) := by
  calc
    padicValNat q (Ideal.absNorm (cyclotomicLinearFactorIdeal hζ x u)) =
        padicValNat q (DkMath.CosmicFormulaBinom.GN p x u) :=
      padicValNat_cyclotomicLinearFactorIdeal_absNorm_eq_GN hζ
    _ = padicValNat q ((x + u) ^ p - u ^ p) :=
      (padicValNat_sub_pow_eq_padicValNat_GN_of_not_dvd_boundary
        (d := p) (x := x) (u := u) (q := q) hp2 hx hu hqP hq_not_dvd_x).symm

end

end DkMath.CFBRC
