/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.Analysis.MellinMultiplicativeApproxIdentity
import Mathlib.Tactic

/-!
# A fixed-ε quadratic Gram-kernel candidate

This module records the positive finite-family energy suggested by the
logarithmic average for the centered Mellin box.  It is deliberately kept
separate from the one-variable second-difference weight: the Gram diagonal
has argument `z + conj z`, while the latter has argument `z`.

Only fixed-ε identities are asserted here.  No limit, contour exchange,
finite-cutoff conjugate provider, or implication from Gram positivity to the
prime-side excess is supplied.
-/

namespace DkMath.Analysis

open MeasureTheory
open scoped Interval Topology

/-- The centered Mellin logarithmic multiplier at a fixed box width. -/
noncomputable def mellinQuadraticBoxMultiplier (ε : ℝ) (z : ℂ) : ℂ :=
  centeredMellinSpectralWeight (centeredMellinBoxApprox ε) z

/-- The current one-variable quadratic weight, retained as a separate surface. -/
noncomputable def mellinQuadraticBoxWeight (ε : ℝ) (z : ℂ) : ℂ :=
  z ^ 2 * mellinQuadraticBoxMultiplier ε z

/-- The Hermitian Gram-kernel candidate suggested by the logarithmic average. -/
noncomputable def mellinQuadraticBoxGramKernel (ε : ℝ) (z w : ℂ) : ℂ :=
  z * starRingEnd ℂ w *
    mellinQuadraticBoxMultiplier ε (z + starRingEnd ℂ w)

theorem mellinQuadraticBoxMultiplier_eq_logAverage
    {ε : ℝ} (hε : 0 < ε) (z : ℂ) :
    mellinQuadraticBoxMultiplier ε z =
      ((2 * ε : ℝ)⁻¹ : ℂ) *
        (∫ t in (-ε)..ε, Complex.exp ((t : ℂ) * z)) := by
  exact centeredMellinSpectralWeight_centeredMellinBoxApprox_eq_logAverage hε z

theorem mellinQuadraticBoxGramKernel_eq_logAverage_integral
    {ε : ℝ} (hε : 0 < ε) (z w : ℂ) :
    mellinQuadraticBoxGramKernel ε z w =
      z * starRingEnd ℂ w *
        (((2 * ε : ℝ)⁻¹ : ℂ) *
          (∫ t in (-ε)..ε,
            Complex.exp ((t : ℂ) * (z + starRingEnd ℂ w)))) := by
  unfold mellinQuadraticBoxGramKernel
  rw [mellinQuadraticBoxMultiplier_eq_logAverage hε]

theorem mellinQuadraticBoxWeight_eq_quadratic_mul_multiplier
    (ε : ℝ) (z : ℂ) :
    mellinQuadraticBoxWeight ε z = z ^ 2 * mellinQuadraticBoxMultiplier ε z := by
  rfl

theorem mellinQuadraticBoxGramKernel_diagonal
    (ε : ℝ) (z : ℂ) :
    mellinQuadraticBoxGramKernel ε z z =
      (Complex.normSq z : ℂ) *
        mellinQuadraticBoxMultiplier ε (z + starRingEnd ℂ z) := by
  unfold mellinQuadraticBoxGramKernel
  rw [Complex.mul_conj]

/-- The finite-family Gram energy obtained directly from the exponential
feature map `z ↦ z * exp (t z)`. -/
noncomputable def mellinQuadraticBoxGramEnergy
    {n : ℕ} (ε : ℝ) (z : Fin n → ℂ) (c : Fin n → ℂ) : ℝ :=
  (2 * ε)⁻¹ *
    ∫ t in (-ε)..ε,
      Complex.normSq (∑ j, c j * (z j * Complex.exp ((t : ℂ) * z j)))

theorem mellinQuadraticBoxGramEnergy_nonneg
    {n : ℕ} {ε : ℝ} (hε : 0 < ε) (z : Fin n → ℂ) (c : Fin n → ℂ) :
    0 ≤ mellinQuadraticBoxGramEnergy ε z c := by
  unfold mellinQuadraticBoxGramEnergy
  have hscale : 0 ≤ (2 * ε)⁻¹ := by positivity
  have hinterval : -ε ≤ ε := by linarith
  have hmass :
      0 ≤ ∫ t in (-ε)..ε,
        Complex.normSq (∑ j, c j * (z j * Complex.exp ((t : ℂ) * z j))) := by
    apply intervalIntegral.integral_nonneg_of_ae hinterval
    exact Filter.Eventually.of_forall (fun t => Complex.normSq_nonneg _)
  exact mul_nonneg hscale hmass

/-- The finite complex quadratic form generated by the kernel candidate. -/
noncomputable def mellinQuadraticBoxGramQuadraticForm
    {n : ℕ} (ε : ℝ) (z : Fin n → ℂ) (c : Fin n → ℂ) : ℂ :=
  ∑ i, ∑ j,
    c i * starRingEnd ℂ (c j) *
      mellinQuadraticBoxGramKernel ε (z i) (z j)

theorem mellinQuadraticBoxGram_feature_normSq_eq_double_sum
    {n : ℕ} (z : Fin n → ℂ) (c : Fin n → ℂ) (t : ℝ) :
    (Complex.normSq
      (∑ j, c j * (z j * Complex.exp ((t : ℂ) * z j))) : ℂ) =
      ∑ i, ∑ j,
        c i * starRingEnd ℂ (c j) * z i * starRingEnd ℂ (z j) *
          Complex.exp ((t : ℂ) * (z i + starRingEnd ℂ (z j))) := by
  classical
  simp only [Complex.normSq_eq_conj_mul_self, map_sum, map_mul,
    Finset.mul_sum, Finset.sum_mul, ← Complex.exp_conj, Complex.conj_ofReal]
  apply Finset.sum_congr rfl
  intro i hi
  apply Finset.sum_congr rfl
  intro j hj
  rw [mul_add]
  rw [Complex.exp_add]
  ring

noncomputable def mellinQuadraticBoxGramPairIntegrand
    (z w a b : ℂ) (t : ℝ) : ℂ :=
  a * starRingEnd ℂ b * z * starRingEnd ℂ w *
    Complex.exp ((t : ℂ) * (z + starRingEnd ℂ w))

theorem mellinQuadraticBoxGram_pair_eq_integral
    {ε : ℝ} (hε : 0 < ε) (z w a b : ℂ) :
    a * starRingEnd ℂ b * mellinQuadraticBoxGramKernel ε z w =
      ∫ t in (-ε)..ε,
        ((2 * ε : ℝ)⁻¹ : ℂ) *
          mellinQuadraticBoxGramPairIntegrand z w a b t := by
  unfold mellinQuadraticBoxGramPairIntegrand
  rw [mellinQuadraticBoxGramKernel_eq_logAverage_integral hε]
  calc
    a * starRingEnd ℂ b *
        (z * starRingEnd ℂ w *
          (((2 * ε : ℝ)⁻¹ : ℂ) *
            ∫ t in (-ε)..ε,
              Complex.exp ((t : ℂ) * (z + starRingEnd ℂ w)))) =
      ((2 * ε : ℝ)⁻¹ : ℂ) *
        (a * starRingEnd ℂ b * z * starRingEnd ℂ w) *
          ∫ t in (-ε)..ε,
            Complex.exp ((t : ℂ) * (z + starRingEnd ℂ w)) := by ring
    _ = ∫ t in (-ε)..ε,
          ((2 * ε : ℝ)⁻¹ : ℂ) *
            (a * starRingEnd ℂ b * z * starRingEnd ℂ w) *
              Complex.exp ((t : ℂ) * (z + starRingEnd ℂ w)) := by
      rw [intervalIntegral.integral_const_mul]
    _ = ∫ t in (-ε)..ε,
          ((2 * ε : ℝ)⁻¹ : ℂ) *
            mellinQuadraticBoxGramPairIntegrand z w a b t := by
      apply intervalIntegral.integral_congr_ae
      filter_upwards [] with t
      unfold mellinQuadraticBoxGramPairIntegrand
      intro _
      ring

theorem mellinQuadraticBoxGramPairIntegrand_intervalIntegrable
    {ε : ℝ} (z w a b : ℂ) :
    IntervalIntegrable
      (mellinQuadraticBoxGramPairIntegrand z w a b)
      volume (-ε) ε := by
  unfold mellinQuadraticBoxGramPairIntegrand
  exact (by fun_prop : Continuous (fun t : ℝ =>
    a * starRingEnd ℂ b * z * starRingEnd ℂ w *
      Complex.exp ((t : ℂ) * (z + starRingEnd ℂ w))))
    |>.intervalIntegrable _ _

theorem mellinQuadraticBoxGramEnergy_eq_normalized_integral
    {n : ℕ} {ε : ℝ} (z : Fin n → ℂ) (c : Fin n → ℂ) :
    (mellinQuadraticBoxGramEnergy ε z c : ℂ) =
      ((2 * ε : ℝ)⁻¹ : ℂ) *
        ∫ t in (-ε)..ε,
          (Complex.normSq
            (∑ j, c j * (z j * Complex.exp ((t : ℂ) * z j))) : ℂ) := by
  unfold mellinQuadraticBoxGramEnergy
  push_cast
  rw [← intervalIntegral.integral_ofReal]

theorem mellinQuadraticBoxGramEnergy_eq_normalized_double_sum_integral
    {n : ℕ} {ε : ℝ} (z : Fin n → ℂ) (c : Fin n → ℂ) :
    (mellinQuadraticBoxGramEnergy ε z c : ℂ) =
      ((2 * ε : ℝ)⁻¹ : ℂ) *
        ∫ t in (-ε)..ε,
          ∑ i, ∑ j,
            c i * starRingEnd ℂ (c j) * z i * starRingEnd ℂ (z j) *
              Complex.exp ((t : ℂ) * (z i + starRingEnd ℂ (z j))) := by
  rw [mellinQuadraticBoxGramEnergy_eq_normalized_integral]
  apply congrArg (fun x : ℂ => ((2 * ε : ℝ)⁻¹ : ℂ) * x)
  apply intervalIntegral.integral_congr_ae
  filter_upwards [] with t
  intro _
  exact mellinQuadraticBoxGram_feature_normSq_eq_double_sum z c t

theorem intervalIntegral_sum_univ_eq_sum_intervalIntegral
    {ι : Type*} [Fintype ι] {f : ι → ℝ → ℂ} {a b : ℝ}
    (hf : ∀ i, IntervalIntegrable (f i) volume a b) :
    (∫ t in a..b, ∑ i, f i t) = ∑ i, ∫ t in a..b, f i t := by
  simpa using
    (intervalIntegral.integral_finsetSum (s := (Finset.univ : Finset ι))
      (f := f) (fun i hi => hf i))

theorem sum_intervalIntegral_univ_eq_intervalIntegral_sum
    {ι : Type*} [Fintype ι] {f : ι → ℝ → ℂ} {a b : ℝ}
    (hf : ∀ i, IntervalIntegrable (f i) volume a b) :
    (∑ i, ∫ t in a..b, f i t) = ∫ t in a..b, ∑ i, f i t := by
  symm
  exact intervalIntegral_sum_univ_eq_sum_intervalIntegral hf

theorem mellinQuadraticBoxGramQuadraticForm_eq_normalized_double_sum_integral
    {n : ℕ} {ε : ℝ} (hε : 0 < ε) (z : Fin n → ℂ) (c : Fin n → ℂ) :
    mellinQuadraticBoxGramQuadraticForm ε z c =
      ((2 * ε : ℝ)⁻¹ : ℂ) *
        ∫ t in (-ε)..ε,
          ∑ i, ∑ j,
            c i * starRingEnd ℂ (c j) * z i * starRingEnd ℂ (z j) *
              Complex.exp ((t : ℂ) * (z i + starRingEnd ℂ (z j))) := by
  classical
  let f : Fin n → Fin n → ℝ → ℂ := fun i j t =>
    ((2 * ε : ℝ)⁻¹ : ℂ) *
      mellinQuadraticBoxGramPairIntegrand (z i) (z j) (c i) (c j) t
  have hf : ∀ i j, IntervalIntegrable (f i j) volume (-ε) ε := by
    intro i j
    exact (mellinQuadraticBoxGramPairIntegrand_intervalIntegrable
      (ε := ε) (z i) (z j) (c i) (c j)).const_mul _
  unfold mellinQuadraticBoxGramQuadraticForm
  calc
    ∑ i, ∑ j, c i * starRingEnd ℂ (c j) *
        mellinQuadraticBoxGramKernel ε (z i) (z j) =
      ∑ i, ∑ j, ∫ t in (-ε)..ε, f i j t := by
        apply Finset.sum_congr rfl
        intro i hi
        apply Finset.sum_congr rfl
        intro j hj
        exact mellinQuadraticBoxGram_pair_eq_integral hε
          (z i) (z j) (c i) (c j)
    _ = ∑ i, ∫ t in (-ε)..ε, ∑ j, f i j t := by
      apply Finset.sum_congr rfl
      intro i hi
      symm
      exact intervalIntegral_sum_univ_eq_sum_intervalIntegral (hf i)
    _ = ∫ t in (-ε)..ε, ∑ i, ∑ j, f i j t := by
      symm
      apply intervalIntegral_sum_univ_eq_sum_intervalIntegral
      intro i
      have heq : (∑ j, f i j) = fun t => ∑ j, f i j t :=
        Finset.sum_fn (Finset.univ : Finset (Fin n)) (fun j => f i j)
      rw [← heq]
      exact IntervalIntegrable.sum Finset.univ (fun j hj => hf i j)
    _ = ((2 * ε : ℝ)⁻¹ : ℂ) *
        ∫ t in (-ε)..ε,
          ∑ i, ∑ j,
            c i * starRingEnd ℂ (c j) * z i * starRingEnd ℂ (z j) *
              Complex.exp ((t : ℂ) * (z i + starRingEnd ℂ (z j))) := by
      rw [← intervalIntegral.integral_const_mul]
      apply intervalIntegral.integral_congr_ae
      filter_upwards [] with t
      intro _
      simp only [f, mellinQuadraticBoxGramPairIntegrand]
      simp [mul_comm]
      simp only [Finset.mul_sum]

theorem mellinQuadraticBoxGramQuadraticForm_eq_energy
    {n : ℕ} {ε : ℝ} (hε : 0 < ε) (z : Fin n → ℂ) (c : Fin n → ℂ) :
    mellinQuadraticBoxGramQuadraticForm ε z c =
      (mellinQuadraticBoxGramEnergy ε z c : ℂ) := by
  rw [mellinQuadraticBoxGramQuadraticForm_eq_normalized_double_sum_integral hε,
    mellinQuadraticBoxGramEnergy_eq_normalized_double_sum_integral]

theorem mellinQuadraticBoxGramQuadraticForm_im_eq_zero
    {n : ℕ} {ε : ℝ} (hε : 0 < ε) (z : Fin n → ℂ) (c : Fin n → ℂ) :
    (mellinQuadraticBoxGramQuadraticForm ε z c).im = 0 := by
  rw [mellinQuadraticBoxGramQuadraticForm_eq_energy hε]
  simp

theorem mellinQuadraticBoxGramQuadraticForm_re_eq_energy
    {n : ℕ} {ε : ℝ} (hε : 0 < ε) (z : Fin n → ℂ) (c : Fin n → ℂ) :
    (mellinQuadraticBoxGramQuadraticForm ε z c).re =
      mellinQuadraticBoxGramEnergy ε z c := by
  rw [mellinQuadraticBoxGramQuadraticForm_eq_energy hε]
  simp

theorem mellinQuadraticBoxGramQuadraticForm_re_nonneg
    {n : ℕ} {ε : ℝ} (hε : 0 < ε) (z : Fin n → ℂ) (c : Fin n → ℂ) :
    0 ≤ (mellinQuadraticBoxGramQuadraticForm ε z c).re := by
  rw [mellinQuadraticBoxGramQuadraticForm_re_eq_energy hε]
  exact mellinQuadraticBoxGramEnergy_nonneg hε z c

end DkMath.Analysis
