/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.Hackathon.FinitePrimeEscapeGN5
import DkMath.NumberTheory.StructuralArithmetic.PrimitiveDirection

#print "file: DkMath.NumberTheory.StructuralArithmetic.FinitePrimeEscapeBridge"

/-!
## Bridge from finite-prime escape providers to primitive directions

The Euclidean/product-plus-offset argument and the concrete GN5 witness already
live in `DkMath.Hackathon`.  This module does not duplicate those proofs.  It
consumes `FreshPrimeFactor` and reinterprets it through the StructuralArithmetic
notion of a fresh prime direction and non-generation by a finite prime-scale
world.
-/

namespace DkMath.NumberTheory.StructuralArithmetic

open DkMath.Hackathon

/-- An existing `FreshPrimeFactor` is a StructuralArithmetic fresh direction. -/
theorem freshPrimeFactor_to_freshPrimeDirection
    {S : Finset ℕ} {n q : ℕ}
    (h : FreshPrimeFactor S n q) :
    FreshPrimeDirection S n q :=
  ⟨h.1, h.2.1, h.2.2⟩

/--
Any existing finite-prime escape witness proves that its target is outside the
old prime-scale world.
-/
theorem freshPrimeFactor_not_primeScaleGeneratedBy
    {S : Finset ℕ} {n q : ℕ}
    (h : FreshPrimeFactor S n q) :
    ¬ PrimeScaleGeneratedBy S n :=
  not_primeScaleGeneratedBy_of_freshPrimeDirection
    (freshPrimeFactor_to_freshPrimeDirection h)

/--
An existential finite-prime escape provider lifts to non-generation of its
target without repeating the provider's arithmetic proof.
-/
theorem exists_freshPrimeFactor_not_primeScaleGeneratedBy
    {S : Finset ℕ} {n : ℕ}
    (h : ∃ q, FreshPrimeFactor S n q) :
    ¬ PrimeScaleGeneratedBy S n := by
  obtain ⟨q, hq⟩ := h
  exact freshPrimeFactor_not_primeScaleGeneratedBy hq

/-- The existing `{2, 3, 5}` GN5 escape supplies a fresh direction. -/
theorem GN5_escape_has_freshPrimeDirection :
    ∃ q,
      FreshPrimeDirection
        ({2, 3, 5} : Finset ℕ)
        (DkMath.CosmicFormulaBinom.GN 5 1 1) q := by
  obtain ⟨q, hq⟩ := finitePrimeEscape_hits_GN5
  exact ⟨q, freshPrimeFactor_to_freshPrimeDirection hq⟩

/--
The existing GN5 target is formally outside the multiplicative prime-scale
world generated by `{2, 3, 5}`; this is the new-direction interpretation of
the Hackathon escape example, not a recomputation of `GN 5 1 1 = 31`.
-/
theorem GN5_escape_not_primeScaleGeneratedBy_two_three_five :
    ¬ PrimeScaleGeneratedBy
      ({2, 3, 5} : Finset ℕ)
      (DkMath.CosmicFormulaBinom.GN 5 1 1) :=
  exists_freshPrimeFactor_not_primeScaleGeneratedBy
    finitePrimeEscape_hits_GN5

/-- The concrete known-scale set `{2, 3, 5}` satisfies `KnownPrimeScales`. -/
theorem knownPrimeScales_two_three_five :
    KnownPrimeScales ({2, 3, 5} : Finset ℕ) := by
  intro p hp
  simp only [Finset.mem_insert, Finset.mem_singleton] at hp
  rcases hp with rfl | rfl | rfl <;> norm_num

end DkMath.NumberTheory.StructuralArithmetic
