/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import Mathlib.Data.Nat.Prime.Basic
import Mathlib.Data.Finset.Basic

#print "file: DkMath.NumberTheory.StructuralArithmetic.PrimitiveDirection"

/-!
## Primitive multiplicative directions in a finite prime-scale world

This module introduces a third, deliberately separate meaning of
"primitive".  `PrimitiveSet.PrimitiveOn` is a divisibility antichain, while
`PrimitiveBeam.PrimitivePrimeFactorOfDiffPow` records first occurrence across
power differences.  Here a finite set `S` is a known prime-scale world and a
nonzero natural is generated by `S` when every one of its prime divisors is in
`S`.

The raw direction statement is independent of PowerGauge period projections:
the multiplicative identity `1` contributes no prime direction, while a fresh
prime divisor witnesses escape from the old world.
-/

namespace DkMath.NumberTheory.StructuralArithmetic

/-- A finite set contains only genuine prime directions. -/
def KnownPrimeScales (S : Finset ℕ) : Prop :=
  ∀ ⦃p : ℕ⦄, p ∈ S → Nat.Prime p

namespace KnownPrimeScales

/-- Membership in a known prime-scale set supplies primality of the direction. -/
theorem prime_of_mem {S : Finset ℕ} (hS : KnownPrimeScales S)
    {p : ℕ} (hp : p ∈ S) : Nat.Prime p :=
  hS hp

end KnownPrimeScales

/--
Nonzero naturals generated by a finite prime-scale world `S`: every prime
divisor belongs to `S`.  This is not the Erdos `PrimitiveOn` predicate.
-/
def PrimeScaleGeneratedBy (S : Finset ℕ) (n : ℕ) : Prop :=
  n ≠ 0 ∧ ∀ ⦃q : ℕ⦄, Nat.Prime q → q ∣ n → q ∈ S

/-- A prime direction is fresh when it divides `n` but is absent from `S`. -/
def FreshPrimeDirection (S : Finset ℕ) (n q : ℕ) : Prop :=
  Nat.Prime q ∧ q ∣ n ∧ q ∉ S

/-- The multiplicative identity is generated by every finite prime-scale world. -/
@[simp] theorem primeScaleGeneratedBy_one (S : Finset ℕ) :
    PrimeScaleGeneratedBy S 1 := by
  refine ⟨by decide, ?_⟩
  intro q hq hq1
  exact False.elim (hq.ne_one (Nat.dvd_one.mp hq1))

/--
For a prime `q`, generation by `S` is exactly membership in `S`.  The
nonzero and prime hypotheses are carried by the definition and the theorem;
`KnownPrimeScales S` is the semantic interpretation that `S` lists prime
directions rather than arbitrary composite generators.
-/
theorem primeScaleGeneratedBy_prime_iff_mem
    {S : Finset ℕ} {q : ℕ} (hq : Nat.Prime q) :
    PrimeScaleGeneratedBy S q ↔ q ∈ S := by
  constructor
  · intro h
    exact h.2 hq (dvd_refl q)
  · intro hqS
    refine ⟨hq.ne_zero, ?_⟩
    intro p hp hpd
    have hpq : p = q :=
      (Nat.dvd_prime hq).mp hpd |>.resolve_left hp.ne_one
    simpa [hpq] using hqS

/-- A fresh prime divisor is a new primitive direction relative to `S`. -/
theorem freshPrimeDirection_of_prime_dvd_not_mem
    {S : Finset ℕ} {n q : ℕ}
    (hq : Nat.Prime q) (hqd : q ∣ n) (hqS : q ∉ S) :
    FreshPrimeDirection S n q :=
  ⟨hq, hqd, hqS⟩

/--
Any fresh prime direction forces a nonzero natural outside the old generated
world.  This is the semantic escape theorem used by finite-prime providers.
-/
theorem not_primeScaleGeneratedBy_of_freshPrimeDirection
    {S : Finset ℕ} {n q : ℕ}
    (hfresh : FreshPrimeDirection S n q) :
    ¬ PrimeScaleGeneratedBy S n := by
  intro hgen
  exact hfresh.2.2 (hgen.2 hfresh.1 hfresh.2.1)

end DkMath.NumberTheory.StructuralArithmetic
