#!/usr/bin/env bash
set -euo pipefail

appendix_dir="$(cd "$(dirname "$0")" && pwd)"
base_video="${1:?Usage: $0 BASE_CUT_VIDEO.mp4 [OUTPUT.mp4]}"
output="${2:-$appendix_dir/output/DkMathCosmicPromoFLT5Final.mp4}"

tts_dir="$(cd "$appendix_dir/../../tts" 2>/dev/null && pwd || true)"
if [[ -z "$tts_dir" || ! -d "$tts_dir" ]]; then
  printf 'error: place this directory at submission/flt5_appendix so ../../tts exists\n' >&2
  exit 1
fi
project_root="$(cd "$tts_dir/../../../../../../" && pwd)"
kokoro="$project_root/venv/bin/kokoro-tts"
model="$tts_dir/models/kokoro-v1.0.onnx"
voices="$tts_dir/models/voices-v1.0.bin"

work="$appendix_dir/output/work"
raw_dir="$work/raw"
timed_dir="$work/timed"
mkdir -p "$raw_dir" "$timed_dir" "$(dirname "$output")"

for required in "$base_video" "$kokoro" "$model" "$voices" "$appendix_dir/slides.ass"; do
  test -e "$required" || { printf 'missing: %s\n' "$required" >&2; exit 1; }
done

concat_audio="$work/audio-concat.txt"
timing_file="$work/timing.tsv"
printf '%s\n' '# generated by build_flt5_appendix.sh' > "$concat_audio"
printf 'cue\tstart\tend\ttarget_seconds\traw_seconds\tatempo\n' > "$timing_file"

while IFS='|' read -r cue start end text_file; do
  case "$cue" in ''|'#'*) continue ;; esac
  text_path="$appendix_dir/$text_file"
  raw_wav="$raw_dir/cue_${cue}.wav"
  timed_wav="$timed_dir/cue_${cue}.wav"
  target_seconds=$((end - start))

  "$kokoro" "$text_path" "$raw_wav" \
    --lang en-us --voice af_sarah --model "$model" --voices "$voices"

  raw_seconds="$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$raw_wav")"
  atempo="$(awk -v raw="$raw_seconds" -v target="$target_seconds" 'BEGIN {
    if (raw > target) printf "%.6f", raw / target; else print "1.000000"
  }')"

  awk -v a="$atempo" 'BEGIN { exit !(a <= 2.0) }' || {
    printf 'error: cue %s requires atempo %s (>2.0); shorten its text\n' "$cue" "$atempo" >&2
    exit 1
  }

  ffmpeg -nostdin -y -v error -i "$raw_wav" \
    -filter:a "atempo=$atempo,apad=pad_dur=$target_seconds,atrim=duration=$target_seconds" \
    -ar 48000 -ac 1 -c:a pcm_s16le "$timed_wav"

  printf "file '%s'\n" "$timed_wav" >> "$concat_audio"
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$cue" "$start" "$end" "$target_seconds" "$raw_seconds" "$atempo" >> "$timing_file"
done < "$appendix_dir/cues.tsv"

appendix_wav="$work/flt5-appendix-normalized.wav"
ffmpeg -nostdin -y -v error -f concat -safe 0 -i "$concat_audio" \
  -filter:a "loudnorm=I=-16:TP=-1.5:LRA=11" \
  -ar 48000 -ac 1 -c:a pcm_s16le "$appendix_wav"

appendix_silent="$work/flt5-appendix-silent.mp4"
ffmpeg -nostdin -y -v error \
  -f lavfi -i "color=c=0x0B1020:s=1280x720:r=30:d=55" \
  -vf "ass='$appendix_dir/slides.ass',fade=t=in:st=0:d=0.25,fade=t=out:st=54.55:d=0.45" \
  -c:v libx264 -preset medium -crf 18 -pix_fmt yuv420p -r 30 -t 55 \
  -movflags +faststart "$appendix_silent"

appendix_mp4="$work/flt5-appendix.mp4"
ffmpeg -nostdin -y -v error -i "$appendix_silent" -i "$appendix_wav" \
  -map 0:v:0 -map 1:a:0 -c:v copy -c:a aac -b:a 192k \
  -ar 48000 -ac 1 -shortest -movflags +faststart "$appendix_mp4"

if ! ffprobe -v error -select_streams a:0 -show_entries stream=index \
    -of csv=p=0 "$base_video" | grep -q .; then
  printf 'error: base video has no audio stream\n' >&2
  exit 1
fi

base_norm="$work/base-normalized.mp4"
ffmpeg -nostdin -y -v error -i "$base_video" \
  -map 0:v:0 -map 0:a:0 \
  -vf "scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=30" \
  -af "aresample=48000" \
  -c:v libx264 -preset medium -crf 18 -pix_fmt yuv420p -r 30 \
  -c:a aac -b:a 192k -ar 48000 -ac 1 \
  -movflags +faststart "$base_norm"

appendix_norm="$work/appendix-normalized.mp4"
ffmpeg -nostdin -y -v error -i "$appendix_mp4" \
  -map 0:v:0 -map 0:a:0 \
  -c:v libx264 -preset medium -crf 18 -pix_fmt yuv420p -r 30 \
  -c:a aac -b:a 192k -ar 48000 -ac 1 \
  -movflags +faststart "$appendix_norm"

concat_video="$work/video-concat.txt"
printf "file '%s'\nfile '%s'\n" "$base_norm" "$appendix_norm" > "$concat_video"
ffmpeg -nostdin -y -v error -f concat -safe 0 -i "$concat_video" \
  -c copy -movflags +faststart "$output"

printf 'output: %s\n' "$output"
printf 'duration: '
ffprobe -v error -show_entries format=duration -of csv=p=0 "$output"
