#!/usr/bin/env python3
"""
GNReducedGap の核心: ω を使った g' の構成可能性を探る。

反例文脈: x^p + y^p = z^p
- gap = z - y
- GN(p, gap, y) = (z^p - y^p)/gap = x^p/gap
- q: primitive prime (q∤gap, q|GN, q^p|GN)
- ω^p = 1 in ZMod q, ω ≠ 1
- z ≡ ω^j · y (mod q) for some j ∈ {1,...,p-1}

Goal: ∃ g' such that g' · GN(p, g', y) = gap · GN / q^p = (x/q)^p

つまり: (g'+y)^p - y^p = (x/q)^p
       (g'+y)^p = (x/q)^p + y^p

ω が与える情報:
z ≡ ω^j·y mod q
gap ≡ (ω^j - 1)·y mod q

g' = z' - y where z'^p = (x/q)^p + y^p

z' mod q = ?
z'^p ≡ (x/q)^p + y^p mod q

Since q∣x (in FLT context): x = q·(x/q)
If v_q(x) = 1 (i.e., v_q(s) = 1): (x/q) is coprime to q
  z'^p ≡ (x/q)^p + y^p mod q ≢ y^p mod q (since (x/q)^p ≢ 0)

But z^p ≡ y^p mod q (since q∣x → x^p ≡ 0 → z^p - y^p ≡ 0 → z^p ≡ y^p)

So: z'^p mod q ≠ z^p mod q in general. z' has a DIFFERENT residue mod q.

The key: z' is NOT obtained by simple modification of z.
z' is a fundamentally new value.

Let's study this from the CYCLOTOMIC perspective.
"""

from sympy import binomial, factorint, isprime, gcd, primitive_root
from sympy.ntheory import n_order
from itertools import product as iter_product


def GN(p, u, y):
    return sum(binomial(p, k + 1) * u**k * y ** (p - 1 - k) for k in range(p))


def solve_pth_root_mod(p, rhs_mod, q):
    """Find all x mod q such that x^p ≡ rhs_mod mod q"""
    solutions = []
    for x in range(q):
        if pow(x, p, q) == rhs_mod % q:
            solutions.append(x)
    return solutions


print("=" * 60)
print("ω-BASED CONSTRUCTION: How to find z' from z and ω")
print("=" * 60)

p = 5
for q in [11, 31, 41, 61]:
    if not isprime(q) or (q - 1) % p != 0:
        continue
    g = primitive_root(q)
    omega = pow(g, (q - 1) // p, q)

    print(f"\n{'='*40}")
    print(f"q = {q}, p = {p}, ω = {omega}")
    print(f"ω powers: {[pow(omega, j, q) for j in range(p)]}")
    print(f"{'='*40}")

    for y in [1, 2, 3, 4]:
        if y % q == 0:
            continue
        y_inv = pow(y, q - 2, q)

        print(f"\n  y = {y}")

        for j in range(1, p):
            z_mod_q = (pow(omega, j, q) * y) % q
            gap_mod_q = (z_mod_q - y) % q
            x_mod_q = 0  # since q | x

            print(f"\n  j={j}: z ≡ {z_mod_q}, gap ≡ {gap_mod_q} (mod {q})")

            # In descent: x' = x/q, so v_q(x') = v_q(x) - 1
            # If v_q(x) = 1: x' is coprime to q
            # z'^p ≡ x'^p + y^p (mod q) where x' is coprime to q
            # We don't know x' mod q exactly, but let's parametrize

            # For each possible x' mod q (coprime to q):
            # z'^p ≡ (x')^p + y^p mod q

            print(f"    For each x' mod q (coprime to q):")
            # Just show a few representative cases
            for x_prime_mod in [1, 2, 3]:
                rhs = (pow(x_prime_mod, p, q) + pow(y, p, q)) % q
                z_prime_solutions = solve_pth_root_mod(p, rhs, q)
                g_prime_solutions = [(zp - y) % q for zp in z_prime_solutions]
                print(
                    f"      x'≡{x_prime_mod}: z'^p ≡ {rhs}, z' ≡ {z_prime_solutions}, g' ≡ {g_prime_solutions}"
                )

print("\n" + "=" * 60)
print("CRITICAL ANALYSIS: The cyclotomic factorization approach")
print("=" * 60)

print(
    """
In Z[ζ_p], we have the factorization:
  x^p = z^p - y^p = ∏_{i=0}^{p-1} (z - ζ^i · y)

Each factor z - ζ^i·y is in Z[ζ_p].

KEY PROPERTY: For coprime z, y and p prime:
  gcd(z - ζ^i·y, z - ζ^j·y) divides (ζ^i - ζ^j)·y = ζ^j(ζ^{i-j} - 1)·y
  
  Since ζ^{i-j} - 1 divides p in Z[ζ_p] (the unique prime above p):
  gcd(z - ζ^i·y, z - ζ^j·y) divides p · y · units

  If gcd(x, y) = 1 and p ∤ gap (Case 1 / BranchB):
    The factors are pairwise coprime in Z[ζ_p]
    So each (z - ζ^i·y) = unit · α_i^p for some α_i ∈ Z[ζ_p]

  If p | gap (BranchA / Case 2):
    More careful analysis needed due to ramification at p
    The factor z - y has extra p-divisibility

ELEMENTARY TRANSLATION:
  The factorization in Z[ζ_p] can be projected to ZMod q via ω.

  In ZMod q: z - ζ^i·y becomes z - ω^{ij}·y (evaluating ζ at the embedding ζ → ω^j')

  Since z ≡ ω^j·y mod q:
    z - ω^i·y ≡ (ω^j - ω^i)·y mod q
    = ω^i(ω^{j-i} - 1)·y mod q
  
  This is 0 mod q only when j = i (since ω has order p in (ZMod q)*)
  So EXACTLY ONE factor z - ω^i·y ≡ 0 mod q, namely i = j.

  Since q^p | GN and GN = x^p/gap = ∏_{i=0}^{p-1}(z-ω^i·y)/... :
    All the q-power goes into the single factor z - ω^j·y

  In Z[ζ_p]: (z - ζ^j·y) = unit · α_j^p
  The ideal generated by q in Z[ζ_p] factors as:
    (q) = ∏ Q_i where Q_i are prime ideals
  Since p|(q-1), q splits completely: each Q_i has norm q.
  
  v_{Q_j}(z - ζ^j·y) = p·v_{Q_j}(α_j) ≥ p
  
  The descent: replace α_j by α_j/q_element, reducing the q-part by 1.
  This gives a new z' = g' + y in Z[ζ_p], and the key is to show z' ∈ Z.

ELEMENTARY VERSION OF THE DESCENT:
  We want to construct g' such that:
    g' ≡ gap (mod terms involving removal of one q from the factorization)
  
  The ω provides the "direction" in which q enters the factorization.
  The descent amounts to finding g' such that:
    1. g' · GN(p, g', y) = gap · GN / q^p
    2. g' > 0
    3. g' ∈ ℤ (not just in Z[ζ_p])
"""
)

print("=" * 60)
print("POLYNOMIAL APPROACH: GN as polynomial in gap")
print("=" * 60)

# GN(p, u, y) as a polynomial in u:
# GN = Σ C(p,k+1) u^k y^{p-1-k}
# = C(p,1)y^{p-1} + C(p,2)u·y^{p-2} + ... + C(p,p)u^{p-1}
# = p·y^{p-1} + C(p,2)·u·y^{p-2} + ... + u^{p-1}

# In ZMod q: GN(p, u, y) ≡ 0 when u ≡ (ω^j - 1)·y mod q (for some j ≠ 0)

# The p roots of GN(p, ·, y) = 0 in ZMod q are:
# u_j = (ω^j - 1)·y for j = 1, 2, ..., p-1
# Plus u = 0 (since GN has degree p-1 in u, wait...)

# Actually, deg_u(GN) = p-1 (the u^{p-1} coefficient is C(p,p) = 1)
# So GN has exactly p-1 roots in an algebraically closed field
# The roots in ZMod q are: u_j = (ω^j - 1)·y for j = 1, ..., p-1
# That's p-1 roots for a degree p-1 polynomial → ALL ROOTS FOUND!

# Therefore:
# GN(p, u, y) ≡ ∏_{j=1}^{p-1} (u - (ω^j - 1)·y) mod q
# = ∏_{j=1}^{p-1} (u - ω^j·y + y) mod q

# Verify this!
print("\nVerification: GN(p, u, y) = ∏_{j=1}^{p-1} (u - (ω^j - 1)·y) mod q")

p = 5
for q in [11, 31]:
    if not isprime(q) or (q - 1) % p != 0:
        continue
    g = primitive_root(q)
    omega = pow(g, (q - 1) // p, q)

    print(f"\nq={q}, ω={omega}")

    for y in [1, 2, 3]:
        if y % q == 0:
            continue

        # Leading coefficient: u^{p-1} → 1 (C(p,p) = 1)
        # But wait: GN = Σ_{k=0}^{p-1} C(p,k+1) u^k y^{p-1-k}
        # leading coeff (k=p-1): C(p,p) * y^0 = 1

        matched = True
        for u_test in range(q):
            gn_val = GN(p, u_test, y) % q
            prod_val = 1
            for j in range(1, p):
                root_j = ((pow(omega, j, q) - 1) * y) % q
                prod_val = (prod_val * (u_test - root_j)) % q
            if gn_val != prod_val:
                matched = False
                print(
                    f"  y={y}, u={u_test}: GN mod q = {gn_val}, product = {prod_val} MISMATCH!"
                )
                break
        if matched:
            print(f"  y={y}: GN(p,u,y) ≡ ∏(u - (ω^j-1)y) mod q for ALL u ✓")

print("\n" + "=" * 60)
print("FACTORED GN: Higher q-adic structure")
print("=" * 60)

print(
    """
We have established: 
  GN(p, u, y) ≡ ∏_{j=1}^{p-1} (u - (ω^j - 1)·y) (mod q)

Now for the q-adic valuation. In the FLT context:
  u = gap, z = gap + y, z ≡ ω^j₀·y (mod q) for fixed j₀
  So gap ≡ (ω^{j₀} - 1)·y (mod q)

  v_q(u - (ω^j - 1)·y) for the factor with j = j₀:
    u - (ω^{j₀} - 1)·y = gap - (ω^{j₀} - 1)·y ≡ 0 (mod q)
    This factor absorbs ALL the q-power.

  v_q(u - (ω^j - 1)·y) for j ≠ j₀:
    gap - (ω^j - 1)·y ≡ (ω^{j₀} - 1)·y - (ω^j - 1)·y
    = (ω^{j₀} - ω^j)·y
    = ω^j·(ω^{j₀-j} - 1)·y ≢ 0 (mod q) [since j₀≠j, ω^{j₀-j}≠1]
    
  So v_q(factor j ≠ j₀) = 0.

  Therefore: v_q(GN) = v_q(gap - (ω^{j₀}-1)·y) + 0 + ... + 0
           = v_q(gap - (ω^{j₀}-1)·y)

  And we know v_q(GN) = p·v_q(x)/1 ... actually v_q(gap·GN) = p·v_q(x).
  Since q∤gap: v_q(GN) = p·v_q(x) where q∣x.

  KEY: v_q(gap - (ω^{j₀}-1)·y) = v_q(GN) = p·v_q(x) ≥ p

This means: gap ≡ (ω^{j₀}-1)·y (mod q^p) at least!

Let's verify this numerically.
"""
)

# Numerical verification
p = 5
q = 11
g = primitive_root(q)
omega = pow(g, (q - 1) // p, q)
print(f"p={p}, q={q}, ω={omega}")

for y in [1, 2, 3]:
    print(f"\ny={y}:")
    for j0 in range(1, p):
        # The "root" at ZMod q level
        root_base = ((pow(omega, j0, q) - 1) * y) % q

        # Try various u ≡ root_base (mod q) and check v_q of the factor
        for k in range(0, 20):
            u = root_base + q * k
            if u == 0:
                continue
            factor = u - ((pow(omega, j0, q) - 1) * y) % q
            # Actually, we should compute u - (ω^{j0}-1)*y properly
            # where ω^{j0} is in ZMod q, so (ω^{j0}-1)*y is also mod q

            # The exact factor: u - (ω^{j0}-1)_lift * y
            # We need to lift ω from ZMod q to Z
            # Let's think of it differently: compute GN and check v_q
            gn = GN(p, u, y)
            if gn <= 0:
                continue
            vq_gn = 0
            temp = gn
            while temp % q == 0:
                vq_gn += 1
                temp //= q

            # Also check v_q of the "corresponding factor"
            # factor_j0 = u - (ω^{j0} - 1)*y in ZMod q is 0
            # But as integers: u = root_base + q*k
            # So the factor in some sense has v_q = 1 + ...

            if vq_gn >= 2:
                print(f"  j0={j0}, u={u} (=root+{q}*{k}): v_{q}(GN) = {vq_gn}")

print("\n" + "=" * 60)
print("LIFTING THE FACTORIZATION: Hensel-like approach")
print("=" * 60)

print(
    """
HENSEL'S LEMMA APPROACH:

GN(p, u, y) as polynomial in u, degree p-1.
mod q: GN = ∏_{j=1}^{p-1} (u - r_j) where r_j = (ω^j - 1)·y mod q
These roots are DISTINCT (since ω^j are all different).

By Hensel's lemma (multivariable version):
  GN(p, u, y) = ∏_{j=1}^{p-1} (u - R_j) mod q^k
  where R_j ≡ r_j mod q, and this factorization lifts uniquely to all q^k.

This means: v_q(GN(p, u, y)) = Σ_j v_q(u - R_j)

For our specific u (= gap in FLT context):
  Only the j = j₀ factor has v_q ≥ 1 (the others have v_q = 0).
  So v_q(GN) = v_q(gap - R_{j₀})

  And v_q(GN) = p·v_q(x) ≥ p means: gap ≡ R_{j₀} (mod q^p)

NOW THE DESCENT:
  Define g' such that g' ≡ R_{j₀} (mod q^{p-1}) but NOT (mod q^p)
  Wait, that's not right...

  Actually, let's think more carefully.
  
  In the FLT context:
    gap · GN(p, gap, y) = x^p
    q | x → x = q · x'
    gap · GN = (q·x')^p = q^p · x'^p
    gap · GN / q^p = x'^p
  
  We want: g' · GN(p, g', y) = x'^p
  i.e., (g'+y)^p - y^p = x'^p
  i.e., (g'+y)^p = x'^p + y^p

  From the Hensel factorization:
    GN(p, g', y) = ∏_{j=1}^{p-1} (g' - R_j) mod q^k
    
    g' · GN(p, g', y) should equal x'^p 
    = x^p / q^p = gap · GN / q^p = gap · ∏_j(gap - R_j) / q^p

  Since only the j₀ factor absorbs q-power:
    gap · ∏_j(gap - R_j) / q^p = gap · (gap - R_{j₀})/q^p · ∏_{j≠j₀}(gap - R_j)

  For the descent to work, we need:
    g' · ∏_j(g' - R_j) = gap · (gap - R_{j₀})/q^p · ∏_{j≠j₀}(gap - R_j)

  A natural candidate: g' = gap - (correction term involving q)
  
  But this is still very nonlinear.

  ALTERNATIVE APPROACH: use the fact that the factorization in Z[ζ_p]
  gives a LINEAR structure that can be projected.
"""
)

print("=" * 60)
print("POLYNOMIAL DIVISION APPROACH")
print("=" * 60)

print(
    """
Key observation: 
  gap · GN(p, gap, y) = (gap + y)^p - y^p = z^p - y^p = x^p

We want: ∃ g' s.t. g' · GN(p, g', y) = x'^p where x' = x/q

Note: g' · GN(p, g', y) = (g' + y)^p - y^p

So we need: (g' + y)^p = x'^p + y^p
           z'^p = x'^p + y^p  where z' = g' + y

This is: does x'^p + y^p have a p-th root's complement?

In Z[ζ_p]:
  x'^p + y^p = ∏_{i=0}^{p-1} (x' + ζ^i · y)  ... wait, this is wrong
  
  Actually: as a factorization in Z:
  a^p + b^p = (a+b)(a^{p-1} - a^{p-2}b + ... + b^{p-1})  when p is ODD

  But this doesn't help directly.

  In Z[ζ_p]:
  a^p + b^p = a^p - (-b)^p = ∏_{i=0}^{p-1} (a - ζ^i · (-b)) = ∏_{i=0}^{p-1} (a + ζ^i · b)
  Wait: ζ^i are p-th roots of 1, so ζ^{p/2} = -1 only if p is even.
  For odd p: a^p + b^p = (a+b) · GN(p, a+b-b, b) ... no.
  
  Actually for odd p: a^p + b^p = a^p - (-b)^p = ∏_{i=0}^{p-1} (a + ζ^{2i+1}·b) 
  ... I need to be more careful.

  There IS a factorization: for odd p,
  a^p + b^p = (a + b)(a^{p-1} - a^{p-2}b + a^{p-3}b² - ... + b^{p-1})

  Hmm, we're going in circles. Let me take a completely different approach.
"""
)

# Try a completely new angle: can we construct g' using polynomial GCD?
print("=" * 60)
print("NEW ANGLE: Polynomial resultant / GCD approach")
print("=" * 60)

# defin F(u) = u · GN(p, u, y) - C for a constant C
# We want F(g') = 0 where C = x'^p

# F(u) = (u+y)^p - y^p - C
# This is a degree-p polynomial in u
# Its roots are g' = z' - y where z'^p = C + y^p = x'^p + y^p

# The EXISTENCE of a natural number root is the whole question!

# But here's an idea: F(gap) = gap·GN(p,gap,y) - C' where C' = x'^p = x^p/q^p
# F(gap) = x^p - x^p/q^p = x^p(1 - 1/q^p)
# F is degree p, F(gap) is known

# Other approach: study F mod q^k
# F(u) = (u+y)^p - y^p - x'^p
# mod q: F(u) ≡ (u+y)^p - y^p - (x/q)^p mod q

# If v_q(x) = 1: x' = x/q is coprime to q
# F(u) mod q = (u+y)^p - y^p - (x')^p mod q

# We want F(g') ≡ 0 mod q^k for all k → F(g') = 0

# Step 1: Find g' mod q such that F(g') ≡ 0 mod q
# (g'+y)^p ≡ x'^p + y^p mod q
# Need (g'+y) to be a p-th root of x'^p + y^p mod q

# Since (ZMod q)* is cyclic of order q-1 and p|(q-1):
# Every element has a p-th root (Fermat)
# More precisely: a has a p-th root iff a^{(q-1)/p} = 1
# This is automatically true since a^{q-1} = 1 → (a^{(q-1)/p})^p = a^{q-1} = 1

# Wait no. a^{(q-1)/p} = 1 iff a is in the subgroup of index p.
# Not every element satisfies this.

# But EVERY element of (ZMod q)* has SOME p-th root when gcd(p, q-1) divides something...
# Actually: the map x → x^p is surjective iff gcd(p, q-1) = 1
# Since p | (q-1), the map is NOT surjective.
# x^p hits only (q-1)/p-th of the elements.

# So: not every element of ZMod q is a p-th power!
# x'^p + y^p mod q needs to be a p-th power in ZMod q for a root to exist.

print("Checking: is x'^p + y^p always a p-th power mod q?")
print("(Required for g'+y to exist mod q)")

p = 5
for q in [11, 31, 41, 61]:
    if not isprime(q) or (q - 1) % p != 0:
        continue
    g = primitive_root(q)
    omega = pow(g, (q - 1) // p, q)

    # p-th powers mod q
    pth_powers = set()
    for a in range(q):
        pth_powers.add(pow(a, p, q))

    print(f"\nq={q}: {len(pth_powers)} p-th powers out of {q} elements")
    print(f"  p-th powers: {sorted(pth_powers)}")

    # Check for all x' coprime to q and y coprime to q
    all_ok = True
    failures = []
    for y in range(1, q):
        for xp in range(1, q):
            rhs = (pow(xp, p, q) + pow(y, p, q)) % q
            if rhs not in pth_powers:
                all_ok = False
                failures.append((xp, y, rhs))

    if all_ok:
        print(f"  ✓ x'^p + y^p is ALWAYS a p-th power mod {q}")
    else:
        print(f"  ✗ FAILURES: {len(failures)} cases")
        for xp, y, rhs in failures[:5]:
            print(f"    x'={xp}, y={y}: x'^p+y^p ≡ {rhs} mod {q}, not a p-th power")

print("\n" + "=" * 60)
print("HENSEL LIFTING: From mod q to mod q^k")
print("=" * 60)

print(
    """
Even if z' exists mod q, we need:
1. z' mod q   (initial root)
2. z' mod q²  (Hensel lift)
3. z' mod q^k for all k (converge to p-adic integer)
4. z' is a positive integer (not just p-adic)

Step 1 may FAIL: x'^p + y^p might not be a p-th power mod q.
Let's check if it DOES fail...
"""
)

# The previous check showed some failures!
# Let's analyze more carefully WHICH (x', y) pairs work
p = 5
q = 11
g = primitive_root(q)
omega = pow(g, (q - 1) // p, q)

pth_powers = set()
for a in range(q):
    pth_powers.add(pow(a, p, q))

print(f"q={q}, p={p}")
print(f"p-th powers mod {q}: {sorted(pth_powers)}")
print(f"Non-p-th powers mod {q}: {sorted(set(range(q)) - pth_powers)}")

# In FLT context: x ≡ 0 mod q, so x' = x/q and x' is coprime to q
# z ≡ ω^j · y mod q

# z'^p = x'^p + y^p
# We need x'^p + y^p ≡ (some)^p mod q
# i.e., x'^p + y^p should be a p-th power mod q

# But x' depends on x/q. In FLT context, what is x' mod q?
# x = p*t*s, q|s, s = q*s'. x' = p*t*s' (since x = q*x')
# x' mod q = (p*t*s') mod q

# The constraint: x' is arbitrary (depends on p, t, s')
# So x'^p mod q can be ANY p-th power (nonzero, since gcd(x',q)=1)

# Let's check: for each possible x'^p mod q (nonzero p-th power)
# and each y coprime to q:
# is x'^p + y^p a p-th power mod q?

print(f"\nSystematic check: for each x'^p mod q and y mod q:")
nonzero_pth_powers = sorted(pth_powers - {0})
for xp_pow in nonzero_pth_powers:
    for y in range(1, q):
        rhs = (xp_pow + pow(y, p, q)) % q
        is_pth = rhs in pth_powers
        if not is_pth:
            print(
                f"  FAIL: x'^p ≡ {xp_pow}, y={y}, y^p ≡ {pow(y,p,q)}, sum ≡ {rhs} — NOT a p-th power!"
            )

print("\nIf no FAILs printed, then in FLT context z' always exists mod q ✓")
