/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
-/

import DkMath.RH.CFBRC.CosmicFormulaZetaPrimeAxisRemainderAbelSmoothDiscrepancyAudit
import Mathlib.Tactic

#print "file: DkMath.RH.CFBRC.CosmicFormulaZetaPrimeAxisCombinedDiscrepancyEnvelopeAudit"

/-!
# CFZP-049: a common finite discrepancy envelope

The carrier and prime-axis remainder use two test functions, but both
discrepancy terms are finite Abel functionals of the same exact
prime-counting error.  This module packages their common finite sensitivity
bound without introducing a prime-distribution asymptotic.
-/

noncomputable section

namespace DkMath.RH.CFBRCProjection

open DkMath.NumberTheory
open MeasureTheory
open Set

/-! ## Gates A-B: generic finite Abel discrepancy control -/

/-- The finite Abel functional generated by a test function and the exact
prime-counting discrepancy. -/
noncomputable def cfzp049FiniteAbelDiscrepancyFunctional
    (f : ℝ → ℝ) (a b : ℝ) : ℝ :=
  f b * cfzp040PrimeCountingDiscrepancy b -
    f a * cfzp040PrimeCountingDiscrepancy a -
    ∫ x in Set.Ioc a b,
      deriv f x * cfzp040PrimeCountingDiscrepancy x

/-- The finite sensitivity norm for the Abel functional. -/
noncomputable def cfzp049FiniteAbelSensitivity
    (f : ℝ → ℝ) (a b : ℝ) : ℝ :=
  |f b| + |f a| +
    ∫ x in Set.Ioc a b, |deriv f x|

/-- The sensitivity is nonnegative; no integrability or asymptotic input is
needed for this finite interface. -/
theorem cfzp049FiniteAbelSensitivity_nonneg
    (f : ℝ → ℝ) (a b : ℝ) :
    0 ≤ cfzp049FiniteAbelSensitivity f a b := by
  unfold cfzp049FiniteAbelSensitivity
  positivity

/-- A pointwise discrepancy envelope controls the absolute finite Abel
functional by the corresponding finite sensitivity. -/
theorem cfzp049FiniteAbelDiscrepancyFunctional_abs_le
    {f : ℝ → ℝ} {a b Δ : ℝ}
    (hab : a ≤ b)
    (hΔ : 0 ≤ Δ)
    (hPoint : Cfzp040PrimeCountingDiscrepancyBoundOn a b Δ)
    (hDerivAbsInt : IntegrableOn
      (fun x => |deriv f x|) (Set.Ioc a b))
    (hDerivDiscInt : IntegrableOn
      (fun x => deriv f x * cfzp040PrimeCountingDiscrepancy x)
        (Set.Ioc a b)) :
    |cfzp049FiniteAbelDiscrepancyFunctional f a b| ≤
      Δ * cfzp049FiniteAbelSensitivity f a b := by
  have haPoint := hPoint a ⟨le_rfl, hab⟩
  have hbPoint := hPoint b ⟨hab, le_rfl⟩
  have ha : |f a * cfzp040PrimeCountingDiscrepancy a| ≤ Δ * |f a| := by
    calc
      |f a * cfzp040PrimeCountingDiscrepancy a| =
          |f a| * |cfzp040PrimeCountingDiscrepancy a| := by
            rw [abs_mul]
      _ ≤ |f a| * Δ :=
        mul_le_mul_of_nonneg_left haPoint (abs_nonneg _)
      _ = Δ * |f a| := by ring
  have hb : |f b * cfzp040PrimeCountingDiscrepancy b| ≤ Δ * |f b| := by
    calc
      |f b * cfzp040PrimeCountingDiscrepancy b| =
          |f b| * |cfzp040PrimeCountingDiscrepancy b| := by
            rw [abs_mul]
      _ ≤ |f b| * Δ :=
        mul_le_mul_of_nonneg_left hbPoint (abs_nonneg _)
      _ = Δ * |f b| := by ring
  have hIntegralAbs :
      |∫ x in Set.Ioc a b,
          deriv f x * cfzp040PrimeCountingDiscrepancy x| ≤
        ∫ x in Set.Ioc a b,
          |deriv f x * cfzp040PrimeCountingDiscrepancy x| := by
    simpa only [Real.norm_eq_abs] using
      (norm_integral_le_integral_norm
        (fun x => deriv f x * cfzp040PrimeCountingDiscrepancy x))
  have hProductInt : IntegrableOn
      (fun x => |deriv f x * cfzp040PrimeCountingDiscrepancy x|)
        (Set.Ioc a b) := by
    change Integrable
      (fun x => |deriv f x * cfzp040PrimeCountingDiscrepancy x|)
      (volume.restrict (Set.Ioc a b))
    exact hDerivDiscInt.norm
  have hScaledInt : IntegrableOn
      (fun x => Δ * |deriv f x|) (Set.Ioc a b) :=
    hDerivAbsInt.const_mul Δ
  have hProductBound :
      (∫ x in Set.Ioc a b,
        |deriv f x * cfzp040PrimeCountingDiscrepancy x|) ≤
        ∫ x in Set.Ioc a b, Δ * |deriv f x| := by
    apply setIntegral_mono_on hProductInt hScaledInt measurableSet_Ioc
    intro x hx
    have hPointx := hPoint x ⟨le_of_lt hx.1, hx.2⟩
    calc
      |deriv f x * cfzp040PrimeCountingDiscrepancy x| =
          |deriv f x| * |cfzp040PrimeCountingDiscrepancy x| := by
            rw [abs_mul]
      _ ≤ |deriv f x| * Δ :=
        mul_le_mul_of_nonneg_left hPointx (abs_nonneg _)
      _ = Δ * |deriv f x| := by ring
  have hScaled :
      (∫ x in Set.Ioc a b, Δ * |deriv f x|) =
        Δ * (∫ x in Set.Ioc a b, |deriv f x|) := by
    rw [integral_const_mul]
  have _hRhs_nonneg :
      0 ≤ Δ * cfzp049FiniteAbelSensitivity f a b :=
    mul_nonneg hΔ (cfzp049FiniteAbelSensitivity_nonneg f a b)
  unfold cfzp049FiniteAbelDiscrepancyFunctional
    cfzp049FiniteAbelSensitivity
  calc
    |f b * cfzp040PrimeCountingDiscrepancy b -
        f a * cfzp040PrimeCountingDiscrepancy a -
        ∫ x in Set.Ioc a b,
          deriv f x * cfzp040PrimeCountingDiscrepancy x| ≤
      |f b * cfzp040PrimeCountingDiscrepancy b -
        f a * cfzp040PrimeCountingDiscrepancy a| +
        |∫ x in Set.Ioc a b,
          deriv f x * cfzp040PrimeCountingDiscrepancy x| := by
      simpa [abs_neg] using
        (abs_sub_le
          (f b * cfzp040PrimeCountingDiscrepancy b -
            f a * cfzp040PrimeCountingDiscrepancy a)
          0
          (∫ x in Set.Ioc a b,
            deriv f x * cfzp040PrimeCountingDiscrepancy x))
    _ ≤ (Δ * |f b| + Δ * |f a|) +
        ∫ x in Set.Ioc a b,
          |deriv f x * cfzp040PrimeCountingDiscrepancy x| := by
      have hEndpoint :
          |f b * cfzp040PrimeCountingDiscrepancy b -
              f a * cfzp040PrimeCountingDiscrepancy a| ≤
            Δ * |f b| + Δ * |f a| := by
        calc
          |f b * cfzp040PrimeCountingDiscrepancy b -
              f a * cfzp040PrimeCountingDiscrepancy a| ≤
              |f b * cfzp040PrimeCountingDiscrepancy b| +
                |f a * cfzp040PrimeCountingDiscrepancy a| := by
            simpa using
              (abs_sub_le
                (f b * cfzp040PrimeCountingDiscrepancy b)
                0
                (f a * cfzp040PrimeCountingDiscrepancy a))
          _ ≤ Δ * |f b| + Δ * |f a| := add_le_add hb ha
      exact add_le_add hEndpoint hIntegralAbs
    _ ≤ (Δ * |f b| + Δ * |f a|) +
        ∫ x in Set.Ioc a b, Δ * |deriv f x| := by
      simpa [add_assoc] using
        add_le_add_left hProductBound (Δ * |f b| + Δ * |f a|)
    _ = Δ * (|f b| + |f a| +
        ∫ x in Set.Ioc a b, |deriv f x|) := by
      rw [hScaled]
      ring

/-! ## Gates C-E: carrier, remainder, and combined debts -/

/-- The carrier discrepancy functional is the generic finite Abel functional
for the carrier test function. -/
theorem cfzp049CarrierDiscrepancyFunctional_eq_generic
    (ε : ℝ) (W : PascalCenteredXiResidueTransportWindow)
    (a b : ℝ) :
    cfzp040PrimeCountingDiscrepancyFunctional ε W a b =
      cfzp049FiniteAbelDiscrepancyFunctional
        (cfzp040PrimeAxisCarrierTestFunction ε W) a b := by
  rfl

/-- The finite carrier sensitivity on one exponential cell. -/
noncomputable def cfzp049CarrierDiscrepancyCellSensitivity
    (ε : ℝ) (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) : ℝ :=
  cfzp049FiniteAbelSensitivity
    (cfzp040PrimeAxisCarrierTestFunction ε W)
    (cfzp040CarrierCellExpLeft W c n)
    (cfzp040CarrierCellExpRight W c n)

/-- The carrier discrepancy debt is controlled by the generic sensitivity
bound on the same finite cell. -/
theorem cfzp049CarrierDiscrepancyCellDebt_le
    {ε Δ : ℝ}
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ)
    (hPoint : Cfzp040PrimeCountingDiscrepancyBoundOn
      (cfzp040CarrierCellExpLeft W c n)
      (cfzp040CarrierCellExpRight W c n) Δ)
    (hDerivAbsInt : IntegrableOn
      (fun x => |deriv (cfzp040PrimeAxisCarrierTestFunction ε W) x|)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hDerivDiscInt : IntegrableOn
      (fun x => deriv (cfzp040PrimeAxisCarrierTestFunction ε W) x *
        cfzp040PrimeCountingDiscrepancy x)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n))) :
    cfzp041PrimeCountingDiscrepancyCellDebt ε W c n ≤
      Δ * cfzp049CarrierDiscrepancyCellSensitivity ε W c n := by
  have hΔ : 0 ≤ Δ :=
    (abs_nonneg (cfzp040PrimeCountingDiscrepancy
      (cfzp040CarrierCellExpLeft W c n))).trans
      (hPoint _ ⟨le_rfl, (cfzp040CarrierCellExpLeft_lt_right W c n).le⟩)
  unfold cfzp041PrimeCountingDiscrepancyCellDebt
  exact cfzp049FiniteAbelDiscrepancyFunctional_abs_le
    (cfzp040CarrierCellExpLeft_lt_right W c n).le
    hΔ hPoint hDerivAbsInt hDerivDiscInt

/-- The remainder discrepancy functional is the generic finite Abel
functional for the remainder test function. -/
theorem cfzp049RemainderDiscrepancyFunctional_eq_generic
    (W : PascalCenteredXiResidueTransportWindow)
    (a b : ℝ) :
    cfzp048PrimeRemainderDiscrepancyFunctional W a b =
      cfzp049FiniteAbelDiscrepancyFunctional
        (cfzp048PrimeAxisRemainderTestFunction W) a b := by
  rfl

/-- The finite remainder sensitivity on one exponential cell. -/
noncomputable def cfzp049RemainderDiscrepancyCellSensitivity
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) : ℝ :=
  cfzp049FiniteAbelSensitivity
    (cfzp048PrimeAxisRemainderTestFunction W)
    (cfzp040CarrierCellExpLeft W c n)
    (cfzp040CarrierCellExpRight W c n)

/-- The remainder discrepancy debt is controlled by the same pointwise
envelope, with the finite CFZP-036 remainder constant retained. -/
theorem cfzp049RemainderDiscrepancyCellDebt_le
    {ε Δ : ℝ} (hε : 0 < ε)
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ)
    (hPoint : Cfzp040PrimeCountingDiscrepancyBoundOn
      (cfzp040CarrierCellExpLeft W c n)
      (cfzp040CarrierCellExpRight W c n) Δ)
    (hDerivAbsInt : IntegrableOn
      (fun x => |deriv (cfzp048PrimeAxisRemainderTestFunction W) x|)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hDerivDiscInt : IntegrableOn
      (fun x => deriv (cfzp048PrimeAxisRemainderTestFunction W) x *
        cfzp040PrimeCountingDiscrepancy x)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n))) :
    cfzp048PrimeAxisRemainderDiscrepancyCellDebt ε W c n ≤
      cfzp036PrimeAxisRemainderConstant ε W *
        (Δ * cfzp049RemainderDiscrepancyCellSensitivity W c n) := by
  have hΔ : 0 ≤ Δ :=
    (abs_nonneg (cfzp040PrimeCountingDiscrepancy
      (cfzp040CarrierCellExpLeft W c n))).trans
      (hPoint _ ⟨le_rfl, (cfzp040CarrierCellExpLeft_lt_right W c n).le⟩)
  have hbound := cfzp049FiniteAbelDiscrepancyFunctional_abs_le
    (f := cfzp048PrimeAxisRemainderTestFunction W)
    (a := cfzp040CarrierCellExpLeft W c n)
    (b := cfzp040CarrierCellExpRight W c n)
    (Δ := Δ)
    (cfzp040CarrierCellExpLeft_lt_right W c n).le
    hΔ hPoint hDerivAbsInt hDerivDiscInt
  unfold cfzp048PrimeAxisRemainderDiscrepancyCellDebt
    cfzp048PrimeRemainderCellDiscrepancyFunctional
    cfzp049RemainderDiscrepancyCellSensitivity
  have hK := (cfzp036PrimeAxisRemainderConstant_pos hε W).le
  exact mul_le_mul_of_nonneg_left hbound hK

/-- The total unpaid discrepancy debt is the sum of the carrier and
prime-axis remainder debts. -/
noncomputable def cfzp049CombinedPrimeCountingDiscrepancyCellDebt
    (ε : ℝ) (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) : ℝ :=
  cfzp041PrimeCountingDiscrepancyCellDebt ε W c n +
    cfzp048PrimeAxisRemainderDiscrepancyCellDebt ε W c n

/-- The total finite sensitivity combines the two test-function sensitivities
with the exact CFZP-036 remainder constant. -/
noncomputable def cfzp049CombinedPrimeCountingDiscrepancySensitivity
    (ε : ℝ) (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) : ℝ :=
  cfzp049CarrierDiscrepancyCellSensitivity ε W c n +
    cfzp036PrimeAxisRemainderConstant ε W *
      cfzp049RemainderDiscrepancyCellSensitivity W c n

/-- The combined sensitivity is nonnegative on the safe finite ε-regime. -/
theorem cfzp049CombinedPrimeCountingDiscrepancySensitivity_nonneg
    {ε : ℝ} (hε : 0 < ε)
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) :
    0 ≤ cfzp049CombinedPrimeCountingDiscrepancySensitivity ε W c n := by
  unfold cfzp049CombinedPrimeCountingDiscrepancySensitivity
  exact add_nonneg
    (cfzp049FiniteAbelSensitivity_nonneg _ _ _)
    (mul_nonneg (cfzp036PrimeAxisRemainderConstant_pos hε W).le
      (cfzp049FiniteAbelSensitivity_nonneg _ _ _))

/-- One pointwise discrepancy envelope controls both discrepancy debts and
therefore the combined debt. -/
theorem cfzp049CombinedPrimeCountingDiscrepancyCellDebt_le
    {ε Δ : ℝ} (hε : 0 < ε)
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ)
    (hPoint : Cfzp040PrimeCountingDiscrepancyBoundOn
      (cfzp040CarrierCellExpLeft W c n)
      (cfzp040CarrierCellExpRight W c n) Δ)
    (hCarrierDerivAbsInt : IntegrableOn
      (fun x => |deriv (cfzp040PrimeAxisCarrierTestFunction ε W) x|)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hCarrierDerivDiscInt : IntegrableOn
      (fun x => deriv (cfzp040PrimeAxisCarrierTestFunction ε W) x *
        cfzp040PrimeCountingDiscrepancy x)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hRemainderDerivAbsInt : IntegrableOn
      (fun x => |deriv (cfzp048PrimeAxisRemainderTestFunction W) x|)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hRemainderDerivDiscInt : IntegrableOn
      (fun x => deriv (cfzp048PrimeAxisRemainderTestFunction W) x *
        cfzp040PrimeCountingDiscrepancy x)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n))) :
    cfzp049CombinedPrimeCountingDiscrepancyCellDebt ε W c n ≤
      Δ * cfzp049CombinedPrimeCountingDiscrepancySensitivity ε W c n := by
  have hCarrier := cfzp049CarrierDiscrepancyCellDebt_le
    W c n hPoint hCarrierDerivAbsInt hCarrierDerivDiscInt
  have hRemainder := cfzp049RemainderDiscrepancyCellDebt_le
    hε W c n hPoint hRemainderDerivAbsInt hRemainderDerivDiscInt
  unfold cfzp049CombinedPrimeCountingDiscrepancyCellDebt
    cfzp049CombinedPrimeCountingDiscrepancySensitivity
  calc
    cfzp041PrimeCountingDiscrepancyCellDebt ε W c n +
        cfzp048PrimeAxisRemainderDiscrepancyCellDebt ε W c n ≤
      Δ * cfzp049CarrierDiscrepancyCellSensitivity ε W c n +
        cfzp036PrimeAxisRemainderConstant ε W *
          (Δ * cfzp049RemainderDiscrepancyCellSensitivity W c n) :=
      add_le_add hCarrier hRemainder
    _ = Δ * (cfzp049CarrierDiscrepancyCellSensitivity ε W c n +
        cfzp036PrimeAxisRemainderConstant ε W *
          cfzp049RemainderDiscrepancyCellSensitivity W c n) := by ring

/-! ## Gates F-H: pointwise and relative cell envelopes -/

/-- A pointwise discrepancy provider specialized to one canonical carrier
cell. -/
def Cfzp049PrimeCountingPointwiseDiscrepancyBoundAt
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) (Δ : ℝ) : Prop :=
  Cfzp040PrimeCountingDiscrepancyBoundOn
    (cfzp040CarrierCellExpLeft W c n)
    (cfzp040CarrierCellExpRight W c n) Δ

/-- A relative discrepancy provider specialized to one canonical carrier
cell.  This is only a finite interface and does not assert PNT. -/
def Cfzp049PrimeCountingRelativeDiscrepancyBoundAt
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) (δ : ℝ) : Prop :=
  Cfzp040PrimeCountingRelativeDiscrepancyBoundOn
    (cfzp040CarrierCellExpLeft W c n)
    (cfzp040CarrierCellExpRight W c n) δ

/-- On a late cell, the smooth model retains the useful `1 / U` scale. -/
theorem cfzp049PrimeCountingSmoothModel_le_cellScale
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ)
    (hU : 1 ≤ cfzp039CarrierCellLeft W c n)
    {x : ℝ}
    (hx : x ∈ Set.Icc
      (cfzp040CarrierCellExpLeft W c n)
      (cfzp040CarrierCellExpRight W c n)) :
    cfzp040PrimeCountingSmoothModel x ≤
      Real.exp (cfzp039CarrierCellRight W c n) /
        cfzp039CarrierCellLeft W c n := by
  unfold cfzp040PrimeCountingSmoothModel
  have hxpos : 0 < x :=
    (Real.exp_pos (cfzp039CarrierCellLeft W c n)).trans_le hx.1
  have hlog : cfzp039CarrierCellLeft W c n ≤ Real.log x :=
    (Real.le_log_iff_exp_le hxpos).2 hx.1
  have hUpos : 0 < cfzp039CarrierCellLeft W c n :=
    lt_of_lt_of_le (by norm_num) hU
  have hlogpos : 0 < Real.log x :=
    lt_of_lt_of_le hUpos hlog
  have hnum : x / Real.log x ≤
      Real.exp (cfzp039CarrierCellRight W c n) / Real.log x :=
    div_le_div_of_nonneg_right hx.2 hlogpos.le
  have hden : Real.exp (cfzp039CarrierCellRight W c n) /
      Real.log x ≤ Real.exp (cfzp039CarrierCellRight W c n) /
        cfzp039CarrierCellLeft W c n := by
    apply (div_le_div_iff₀ hlogpos hUpos).2
    exact mul_le_mul_of_nonneg_left hlog
      (Real.exp_pos (cfzp039CarrierCellRight W c n)).le
  exact hnum.trans hden

/-- A relative discrepancy bound yields a uniform cell bound with the
essential `exp R / U` scale. -/
theorem cfzp049RelativeDiscrepancy_implies_pointwiseCellBound
    {δ : ℝ} (hδ : 0 ≤ δ)
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ)
    (hU : 1 ≤ cfzp039CarrierCellLeft W c n)
    (hRel : Cfzp049PrimeCountingRelativeDiscrepancyBoundAt W c n δ) :
    Cfzp049PrimeCountingPointwiseDiscrepancyBoundAt W c n
      (δ * Real.exp (cfzp039CarrierCellRight W c n) /
        cfzp039CarrierCellLeft W c n) := by
  unfold Cfzp049PrimeCountingRelativeDiscrepancyBoundAt at hRel
  unfold Cfzp049PrimeCountingPointwiseDiscrepancyBoundAt
  intro x hx
  calc
    |cfzp040PrimeCountingDiscrepancy x| ≤
        δ * cfzp040PrimeCountingSmoothModel x := hRel x hx
    _ ≤ δ * (Real.exp (cfzp039CarrierCellRight W c n) /
        cfzp039CarrierCellLeft W c n) :=
      mul_le_mul_of_nonneg_left
        (cfzp049PrimeCountingSmoothModel_le_cellScale W c n hU hx) hδ
    _ = δ * Real.exp (cfzp039CarrierCellRight W c n) /
        cfzp039CarrierCellLeft W c n := by ring

/-- The finite combined debt has the uniform relative-discrepancy envelope
obtained from the pointwise-to-functional theorem. -/
noncomputable def cfzp049RelativeCombinedDiscrepancyEnvelope
    (ε δ : ℝ) (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) : ℝ :=
  (δ * Real.exp (cfzp039CarrierCellRight W c n) /
      cfzp039CarrierCellLeft W c n) *
    cfzp049CombinedPrimeCountingDiscrepancySensitivity ε W c n

/-- A relative finite discrepancy provider controls the combined debt while
preserving the logarithmic-cell factor `1 / U`. -/
theorem cfzp049CombinedDebt_le_relativeEnvelope
    {ε δ : ℝ} (hε : 0 < ε) (hδ : 0 ≤ δ)
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ)
    (hU : 1 ≤ cfzp039CarrierCellLeft W c n)
    (hRel : Cfzp049PrimeCountingRelativeDiscrepancyBoundAt W c n δ)
    (hCarrierDerivAbsInt : IntegrableOn
      (fun x => |deriv (cfzp040PrimeAxisCarrierTestFunction ε W) x|)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hCarrierDerivDiscInt : IntegrableOn
      (fun x => deriv (cfzp040PrimeAxisCarrierTestFunction ε W) x *
        cfzp040PrimeCountingDiscrepancy x)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hRemainderDerivAbsInt : IntegrableOn
      (fun x => |deriv (cfzp048PrimeAxisRemainderTestFunction W) x|)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hRemainderDerivDiscInt : IntegrableOn
      (fun x => deriv (cfzp048PrimeAxisRemainderTestFunction W) x *
        cfzp040PrimeCountingDiscrepancy x)
        (Set.Ioc (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n))) :
    cfzp049CombinedPrimeCountingDiscrepancyCellDebt ε W c n ≤
      cfzp049RelativeCombinedDiscrepancyEnvelope ε δ W c n := by
  have hPoint := cfzp049RelativeDiscrepancy_implies_pointwiseCellBound
    hδ W c n hU hRel
  have hCombined := cfzp049CombinedPrimeCountingDiscrepancyCellDebt_le
    hε W c n hPoint hCarrierDerivAbsInt hCarrierDerivDiscInt
      hRemainderDerivAbsInt hRemainderDerivDiscInt
  simpa [cfzp049RelativeCombinedDiscrepancyEnvelope] using hCombined

/-! ## Gate I: combined debt handoff to CFZP-048 -/

/-- The corrected 048 remaining-quarter budget written with the single
combined discrepancy debt. -/
def Cfzp049CombinedRemainingQuarterBudgetAt
    (ε η : ℝ)
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ) : Prop :=
  pascalCenteredXiPrimeSideFiniteRadialContactDeficit ε W
      (cfzp040CarrierCellNaturalLeft W c n) +
    cfzp049CombinedPrimeCountingDiscrepancyCellDebt ε W c n ≤
      cfzp044ExplicitSmoothMargin ε W c n / 4 + η

/-- A combined discrepancy budget is accepted by the corrected CFZP-048
structural adapter.  The finite Abel and smooth-cell certificates remain
explicit, while the carrier functional is supplied to 048 by reflexivity. -/
theorem cfzp049CombinedRemainingQuarterBudget_implies_radialContactDeficit_le
    {ε η : ℝ} (hε : 0 < ε) (hε2 : ε < Real.log 2)
    (W : PascalCenteredXiResidueTransportWindow)
    (c : ℝ) (n : ℕ)
    (hstrip : Cfzp039PrimeAxisInteriorStrip W)
    (hM : 0 < cfzp039ExponentialCarrierPeriodTransform ε W c)
    (hThreshold : cfzp048PrimeAxisRemainderQuarterMarginThreshold ε W c ≤
      cfzp039CarrierCellLeft W c n)
    (hG_int : IntervalIntegrable
      (fun u => Real.exp (cfzp039PrimeAxisGrowthExponent W * u) *
        (1 / u ^ 2 - 1 / u ^ 3)) volume
      (cfzp039CarrierCellLeft W c n)
      (cfzp039CarrierCellRight W c n))
    (hSplit :
      cfzp048PrimeRemainderSumIoc W
          (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n) =
        cfzp048PrimeRemainderSmoothAbelModel W
          (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n) +
        cfzp048PrimeRemainderCellDiscrepancyFunctional W c n)
    (hDebtEq :
      cfzp039PrimeAxisRemainderCellDebt ε W c n
          (cfzp040CarrierCellNaturalLeft W c n)
          (cfzp040CarrierCellNaturalRight W c n) =
        cfzp036PrimeAxisRemainderConstant ε W *
          cfzp048PrimeRemainderSumIoc W
            (cfzp040CarrierCellExpLeft W c n)
            (cfzp040CarrierCellExpRight W c n))
    (hSmoothEq :
      cfzp048PrimeRemainderSmoothAbelModel W
          (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n) =
        cfzp048PrimeRemainderSmoothLogCell W c n)
    (hSmoothLog :
      cfzp040SmoothAbelCarrierModel ε W
          (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n) =
        cfzp042SmoothLogCellIntegral ε W c n)
    (hf_diff : ∀ t ∈ Set.Icc
        (cfzp040CarrierCellExpLeft W c n)
        (cfzp040CarrierCellExpRight W c n),
      DifferentiableAt ℝ (cfzp040PrimeAxisCarrierTestFunction ε W) t)
    (hf_int : IntegrableOn
      (deriv (cfzp040PrimeAxisCarrierTestFunction ε W)) (Set.Icc
        (cfzp040CarrierCellExpLeft W c n)
        (cfzp040CarrierCellExpRight W c n)))
    (hM_int : IntegrableOn
      (fun t => deriv (cfzp040PrimeAxisCarrierTestFunction ε W) t *
        cfzp040PrimeCountingSmoothModel t) (Set.Ioc
          (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hD_int : IntegrableOn
      (fun t => deriv (cfzp040PrimeAxisCarrierTestFunction ε W) t *
        cfzp040PrimeCountingDiscrepancy t) (Set.Ioc
          (cfzp040CarrierCellExpLeft W c n)
          (cfzp040CarrierCellExpRight W c n)))
    (hHigher :
      cfzp034HigherPowerReferenceMass ε W
          (cfzp040CarrierCellNaturalLeft W c n)
          (cfzp040CarrierCellNaturalRight W c n) ≤
        cfzp044ExplicitSmoothMargin ε W c n / 2)
    (hCombined : Cfzp049CombinedRemainingQuarterBudgetAt ε η W c n) :
    pascalCenteredXiPrimeSideFiniteRadialContactDeficit ε W
      (cfzp040CarrierCellNaturalRight W c n) ≤ η := by
  have hD : Cfzp041PrimeCountingDiscrepancyFunctionalBoundAt ε W c n
      (cfzp041PrimeCountingDiscrepancyCellDebt ε W c n) := by
    unfold Cfzp041PrimeCountingDiscrepancyFunctionalBoundAt
      cfzp041PrimeCountingDiscrepancyCellDebt
    exact le_rfl
  have hQuarter : Cfzp048RemainingQuarterMarginBudgetAt ε η
      (cfzp041PrimeCountingDiscrepancyCellDebt ε W c n) W c n := by
    unfold Cfzp049CombinedRemainingQuarterBudgetAt at hCombined
    unfold Cfzp048RemainingQuarterMarginBudgetAt
    simpa [cfzp049CombinedPrimeCountingDiscrepancyCellDebt, add_assoc] using
      hCombined
  exact cfzp048StructuralRemainderRemainingQuarterBudget_implies_radialContactDeficit_le
    hε hε2 W c n hstrip hM hThreshold hG_int hSplit hDebtEq hSmoothEq
      hSmoothLog hf_diff hf_int hM_int hD_int hD hHigher hQuarter

/-! ## Firewall -/

/-- Providers intentionally left outside the finite combined discrepancy
envelope.  In particular, this gap contains no pointwise-to-functional
constructor because that finite bridge is closed above. -/
inductive Cfzp049CombinedPrimeCountingDiscrepancyEnvelopeGap : Prop
  | noExplicitSensitivityAsymptoticEnvelopeProvider
  | noRelativePrimeCountingDiscrepancyDecayProvider
  | noAutomaticPNTRelativeErrorHookup
  | noAutomaticLeadingSmoothAbelLogCellReadinessProvider
  | noAutomaticInteriorStripWindowProvider
  | noCofinalCombinedRemainingQuarterBudgetProvider

end DkMath.RH.CFBRCProjection
