/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.CosmicFormula.ThreeElement.Collision
import DkMath.CosmicFormula.Rotation.CF2D.ThreeElementBridge
import DkMath.RH.CFBRC.EtaCriticalMirrorPairedFrameCompletedZetaTransverseRelativePhase
import DkMath.RH.CFBRC.StandardZetaRealAxisClosure
import Mathlib.Tactic

#print "file: DkMath.RH.CFBRC.EtaCriticalMirrorPairedFrameThreeElementAssimilationBridge"

set_option linter.style.longLine false

noncomputable section

namespace DkMath.RH.CFBRCProjection

open Filter
open scoped Topology
open DkMath.CosmicFormula.ThreeElement
open DkMath.CosmicFormula.Rotation.CF2D

/-- Read one complex carrier as a CF2D `(core, beam)` state. -/
noncomputable def etaComplexCF2DState (z : ℂ) : Vec ℝ :=
  ⟨z.re, z.im⟩

/--
The side-aware dominant endpoint after transport into its local pair-left
frame, read as a CF2D state.
-/
noncomputable def etaCriticalMirrorDominantLocalCF2DCarrier
    (k : ℕ) (s : ℂ) : Vec ℝ :=
  etaComplexCF2DState
    (etaCriticalMirrorDominantLocalRotatedCarrier k s)

/-- The three-element flow generated by the explicit local CF2D carrier. -/
noncomputable def etaCriticalMirrorDominantLocalThreeElementFlow
    (s : ℂ) : ThreeElementFlow ℕ :=
  cf2dThreeElementFlow
    (fun k : ℕ => etaCriticalMirrorDominantLocalCF2DCarrier k s)

/--
The explicit side-aware nonzero real limit of the local dominant carrier.
-/
noncomputable def etaCriticalMirrorDominantLocalCarrierLimit
    (s : ℂ) : ℂ :=
  if s.re ≤ (1 : ℝ) / 2 then
    etaPairIndexNormalizedTailConstant s
  else
    -etaPairIndexNormalizedTailConstant (criticalMirror s)

/-- The local carrier limit is real. -/
theorem etaCriticalMirrorDominantLocalCarrierLimit_im_eq_zero
    (s : ℂ) :
    (etaCriticalMirrorDominantLocalCarrierLimit s).im = 0 := by
  simp [etaCriticalMirrorDominantLocalCarrierLimit,
    etaPairIndexNormalizedTailConstant]

/-- The local carrier limit is nonzero. -/
theorem etaCriticalMirrorDominantLocalCarrierLimit_ne_zero
    (s : ℂ) :
    etaCriticalMirrorDominantLocalCarrierLimit s ≠ 0 := by
  unfold etaCriticalMirrorDominantLocalCarrierLimit
  split_ifs
  · exact etaPairIndexNormalizedTailConstant_ne_zero s
  · exact neg_ne_zero.mpr
      (etaPairIndexNormalizedTailConstant_ne_zero (criticalMirror s))

/-- The real coordinate of the local carrier limit is nonzero. -/
theorem etaCriticalMirrorDominantLocalCarrierLimit_re_ne_zero
    (s : ℂ) :
    (etaCriticalMirrorDominantLocalCarrierLimit s).re ≠ 0 := by
  intro hre
  apply etaCriticalMirrorDominantLocalCarrierLimit_ne_zero s
  apply Complex.ext
  · simpa using hre
  · simpa using etaCriticalMirrorDominantLocalCarrierLimit_im_eq_zero s

/-- The square target carried by the nonzero local asymptotic state. -/
noncomputable def etaCriticalMirrorDominantLocalThreeElementTarget
    (s : ℂ) : ℝ :=
  (etaCriticalMirrorDominantLocalCarrierLimit s).re ^ 2

/-- The local three-element target is nonzero. -/
theorem etaCriticalMirrorDominantLocalThreeElementTarget_ne_zero
    (s : ℂ) :
    etaCriticalMirrorDominantLocalThreeElementTarget s ≠ 0 := by
  exact pow_ne_zero 2
    (etaCriticalMirrorDominantLocalCarrierLimit_re_ne_zero s)

/--
At every hypothetical nonreal off-critical zero, the explicit local dominant
carrier converges to its side-aware nonzero real limit.
-/
theorem etaCriticalMirrorDominantLocalRotatedCarrier_tendsto_explicit_limit
    {s : ℂ}
    (hs : NontrivialRiemannZetaZero s)
    (him : s.im ≠ 0)
    (hre : s.re ≠ (1 : ℝ) / 2) :
    Tendsto
      (fun k : ℕ => etaCriticalMirrorDominantLocalRotatedCarrier k s)
      atTop (nhds (etaCriticalMirrorDominantLocalCarrierLimit s)) := by
  rcases lt_or_gt_of_ne hre with hleft | hright
  · have hrotated :=
      (etaCriticalMirrorLeftNormalizedEvenDefectEndpointAsymptoticCertificate_of_zero
        hs him hleft).rotated_endpoint_tendsto
    have hle : s.re ≤ (1 : ℝ) / 2 := le_of_lt hleft
    have hle' : s.re ≤ 2⁻¹ := by simpa using hle
    simpa [etaCriticalMirrorDominantLocalRotatedCarrier,
      etaCriticalMirrorDominantNormalizedEndpointCarrier,
      etaCriticalMirrorDominantLocalCarrierLimit, hle, hle'] using hrotated
  · have hrotated :=
      (etaCriticalMirrorRightNormalizedEvenDefectEndpointAsymptoticCertificate_of_zero
        hs him hright).rotated_endpoint_tendsto
    have hnotle : ¬ s.re ≤ (1 : ℝ) / 2 := not_le.mpr hright
    have hnotle' : ¬ s.re ≤ 2⁻¹ := by simpa using hnotle
    simpa [etaCriticalMirrorDominantLocalRotatedCarrier,
      etaCriticalMirrorDominantNormalizedEndpointCarrier,
      etaCriticalMirrorDominantLocalCarrierLimit, hnotle, hnotle',
      criticalMirror] using hrotated

/--
A complex carrier converging to a real limit gives pair-whole assimilation of
its associated CF2D three-element flow to the square of that real limit.
-/
theorem pairWholeAssimilation_of_complex_tendsto_real_limit
    {z : ℕ → ℂ} {L : ℂ}
    (hLIm : L.im = 0)
    (hz : Tendsto z atTop (nhds L)) :
    PairWholeAssimilation
      (cf2dThreeElementFlow (fun k : ℕ => etaComplexCF2DState (z k)))
      atTop (L.re ^ 2) := by
  have hre : Tendsto (fun k : ℕ => (z k).re) atTop (nhds L.re) := by
    have h := (Complex.continuous_re.tendsto L).comp hz
    simpa [Function.comp_def] using h
  have him : Tendsto (fun k : ℕ => (z k).im) atTop (nhds 0) := by
    have h := (Complex.continuous_im.tendsto L).comp hz
    simpa [Function.comp_def, hLIm] using h
  constructor
  · change Tendsto
      (fun k : ℕ => ((z k).re + (z k).im) ^ 2)
      atTop (nhds (L.re ^ 2))
    have hsum :
        Tendsto (fun k : ℕ => (z k).re + (z k).im)
          atTop (nhds (L.re + 0)) :=
      hre.add him
    simpa [pow_two] using hsum.mul hsum
  · change Tendsto
      (fun k : ℕ => ((z k).re - (z k).im) ^ 2)
      atTop (nhds (L.re ^ 2))
    have hsub :
        Tendsto (fun k : ℕ => (z k).re - (z k).im)
          atTop (nhds (L.re - 0)) :=
      hre.sub him
    simpa [pow_two] using hsub.mul hsub

/--
The same real-limit input forces the interaction observation to converge to
zero. This is the already-proved pair-assimilation side of the future
same-object collision.
-/
theorem interaction_tendsto_zero_of_complex_tendsto_real_limit
    {z : ℕ → ℂ} {L : ℂ}
    (hLIm : L.im = 0)
    (hz : Tendsto z atTop (nhds L)) :
    Tendsto
      (fun k : ℕ =>
        (cf2dThreeElementFlow
          (fun n : ℕ => etaComplexCF2DState (z n))).interaction k)
      atTop (nhds 0) := by
  have hre : Tendsto (fun k : ℕ => (z k).re) atTop (nhds L.re) := by
    have h := (Complex.continuous_re.tendsto L).comp hz
    simpa [Function.comp_def] using h
  have him : Tendsto (fun k : ℕ => (z k).im) atTop (nhds 0) := by
    have h := (Complex.continuous_im.tendsto L).comp hz
    simpa [Function.comp_def, hLIm] using h
  change Tendsto
    (fun k : ℕ => 2 * (z k).re * (z k).im)
    atTop (nhds 0)
  have htwore :
      Tendsto (fun k : ℕ => 2 * (z k).re) atTop (nhds (2 * L.re)) :=
    hre.const_mul 2
  simpa using htwore.mul him

/--
The pair-whole assimilation provider is unconditional on every nonreal
off-critical zero: it follows from the existing local endpoint asymptotic.
-/
def EtaCriticalMirrorThreeElementPairAssimilationProvider : Prop :=
  ∀ {s : ℂ},
    NontrivialRiemannZetaZero s →
    s.im ≠ 0 →
    s.re ≠ (1 : ℝ) / 2 →
    PairWholeAssimilation
      (etaCriticalMirrorDominantLocalThreeElementFlow s)
      atTop (etaCriticalMirrorDominantLocalThreeElementTarget s)

/-- The explicit CFBRC local carrier supplies pair-whole assimilation. -/
theorem etaCriticalMirrorThreeElementPairAssimilationProvider :
    EtaCriticalMirrorThreeElementPairAssimilationProvider := by
  intro s hs him hre
  exact pairWholeAssimilation_of_complex_tendsto_real_limit
    (etaCriticalMirrorDominantLocalCarrierLimit_im_eq_zero s)
    (etaCriticalMirrorDominantLocalRotatedCarrier_tendsto_explicit_limit
      hs him hre)

/--
The independent interaction magic-core provider still required by the generic
same-object collision theorem.
-/
def EtaCriticalMirrorThreeElementInteractionAssimilationProvider : Prop :=
  ∀ {s : ℂ},
    NontrivialRiemannZetaZero s →
    s.im ≠ 0 →
    s.re ≠ (1 : ℝ) / 2 →
    InteractionAssimilation
      (etaCriticalMirrorDominantLocalThreeElementFlow s)
      atTop (etaCriticalMirrorDominantLocalThreeElementTarget s)

/-- The nonzero-target provider is already unconditional. -/
def EtaCriticalMirrorThreeElementNonzeroTargetProvider : Prop :=
  ∀ {s : ℂ},
    NontrivialRiemannZetaZero s →
    s.im ≠ 0 →
    s.re ≠ (1 : ℝ) / 2 →
    etaCriticalMirrorDominantLocalThreeElementTarget s ≠ 0

/-- The explicit asymptotic constant supplies target noncollapse. -/
theorem etaCriticalMirrorThreeElementNonzeroTargetProvider :
    EtaCriticalMirrorThreeElementNonzeroTargetProvider := by
  intro s _hs _him _hre
  exact etaCriticalMirrorDominantLocalThreeElementTarget_ne_zero s

/--
A more geometric form of the missing interaction provider: the difference
whole `(core - beam)^2` collapses while square mass retains the same target.
-/
def EtaCriticalMirrorThreeElementDifferenceWholeCollapseProvider : Prop :=
  ∀ {s : ℂ},
    NontrivialRiemannZetaZero s →
    s.im ≠ 0 →
    s.re ≠ (1 : ℝ) / 2 →
    Tendsto
      (etaCriticalMirrorDominantLocalThreeElementFlow s).minusWhole
      atTop (nhds 0)

/-- The local flow square mass converges to its explicit nonzero target. -/
theorem etaCriticalMirrorDominantLocalThreeElementFlow_squareMass_tendsto_target
    {s : ℂ}
    (hs : NontrivialRiemannZetaZero s)
    (him : s.im ≠ 0)
    (hre : s.re ≠ (1 : ℝ) / 2) :
    Tendsto
      (etaCriticalMirrorDominantLocalThreeElementFlow s).squareMass
      atTop (nhds (etaCriticalMirrorDominantLocalThreeElementTarget s)) := by
  have hlocal :=
    etaCriticalMirrorDominantLocalRotatedCarrier_tendsto_explicit_limit
      hs him hre
  have hreLim :
      Tendsto
        (fun k : ℕ =>
          (etaCriticalMirrorDominantLocalRotatedCarrier k s).re)
        atTop
        (nhds (etaCriticalMirrorDominantLocalCarrierLimit s).re) := by
    have h :=
      (Complex.continuous_re.tendsto
        (etaCriticalMirrorDominantLocalCarrierLimit s)).comp hlocal
    simpa [Function.comp_def] using h
  have himLim :
      Tendsto
        (fun k : ℕ =>
          (etaCriticalMirrorDominantLocalRotatedCarrier k s).im)
        atTop (nhds 0) := by
    have h :=
      (Complex.continuous_im.tendsto
        (etaCriticalMirrorDominantLocalCarrierLimit s)).comp hlocal
    simpa [Function.comp_def,
      etaCriticalMirrorDominantLocalCarrierLimit_im_eq_zero] using h
  change Tendsto
    (fun k : ℕ =>
      (etaCriticalMirrorDominantLocalRotatedCarrier k s).re ^ 2 +
        (etaCriticalMirrorDominantLocalRotatedCarrier k s).im ^ 2)
    atTop
    (nhds ((etaCriticalMirrorDominantLocalCarrierLimit s).re ^ 2))
  have hcore := hreLim.mul hreLim
  have hgap := himLim.mul himLim
  simpa [pow_two] using hcore.add hgap

/-- Difference-whole collapse supplies the missing interaction assimilation. -/
theorem etaCriticalMirrorThreeElementInteractionAssimilationProvider_of_differenceWholeCollapse
    (hdiff : EtaCriticalMirrorThreeElementDifferenceWholeCollapseProvider) :
    EtaCriticalMirrorThreeElementInteractionAssimilationProvider := by
  intro s hs him hre
  refine ⟨?_⟩
  have hmass :=
    etaCriticalMirrorDominantLocalThreeElementFlow_squareMass_tendsto_target
      hs him hre
  have hminus := hdiff hs him hre
  have hinteraction :
      Tendsto
        (fun k : ℕ =>
          (etaCriticalMirrorDominantLocalThreeElementFlow s).squareMass k -
            (etaCriticalMirrorDominantLocalThreeElementFlow s).minusWhole k)
        atTop (nhds (etaCriticalMirrorDominantLocalThreeElementTarget s)) := by
    simpa only [sub_zero] using hmass.sub hminus
  refine hinteraction.congr' (Eventually.of_forall fun k => ?_)
  rw [(etaCriticalMirrorDominantLocalThreeElementFlow s).minusWhole_eq]
  ring

/--
The remaining interaction provider, together with the two unconditional
providers above, excludes every off-critical nontrivial zero.
-/
theorem riemannHypothesis_of_threeElementInteractionAssimilation
    (hinteraction :
      EtaCriticalMirrorThreeElementInteractionAssimilationProvider) :
    RiemannHypothesis := by
  rw [riemannHypothesis_iff_nontrivialZero_re_eq_half]
  intro s hs
  by_contra hre
  have him : s.im ≠ 0 := nontrivialRiemannZetaZero_im_ne_zero hs
  exact
    false_of_nonzero_pairWhole_and_interaction_assimilation
      (etaCriticalMirrorThreeElementPairAssimilationProvider hs him hre)
      (hinteraction hs him hre)
      (etaCriticalMirrorThreeElementNonzeroTargetProvider hs him hre)

/-- The difference-whole collapse form implies RH through interaction magic-core assimilation. -/
theorem riemannHypothesis_of_threeElementDifferenceWholeCollapse
    (hdiff : EtaCriticalMirrorThreeElementDifferenceWholeCollapseProvider) :
    RiemannHypothesis :=
  riemannHypothesis_of_threeElementInteractionAssimilation
    (etaCriticalMirrorThreeElementInteractionAssimilationProvider_of_differenceWholeCollapse
      hdiff)

/--
Audit: the missing interaction-assimilation provider is logically equivalent
to RH.  The three-element bridge isolates the provider but does not weaken the
remaining mathematical obligation.
-/
theorem etaCriticalMirrorThreeElementInteractionAssimilationProvider_iff_riemannHypothesis :
    EtaCriticalMirrorThreeElementInteractionAssimilationProvider ↔
      RiemannHypothesis := by
  constructor
  · exact riemannHypothesis_of_threeElementInteractionAssimilation
  · intro hRH s hs _him hre
    have hhalf : s.re = (1 : ℝ) / 2 :=
      (riemannHypothesis_iff_nontrivialZero_re_eq_half.mp hRH) s hs
    exact (hre hhalf).elim

/--
Audit: the difference-whole collapse provider is likewise exactly RH-equivalent.
It is therefore a normalized research boundary, not an independently proved
consequence of the current local asymptotic package.
-/
theorem etaCriticalMirrorThreeElementDifferenceWholeCollapseProvider_iff_riemannHypothesis :
    EtaCriticalMirrorThreeElementDifferenceWholeCollapseProvider ↔
      RiemannHypothesis := by
  constructor
  · exact riemannHypothesis_of_threeElementDifferenceWholeCollapse
  · intro hRH s hs _him hre
    have hhalf : s.re = (1 : ℝ) / 2 :=
      (riemannHypothesis_iff_nontrivialZero_re_eq_half.mp hRH) s hs
    exact (hre hhalf).elim

#print axioms etaCriticalMirrorThreeElementPairAssimilationProvider
#print axioms etaCriticalMirrorThreeElementNonzeroTargetProvider
#print axioms etaCriticalMirrorThreeElementInteractionAssimilationProvider_of_differenceWholeCollapse
#print axioms riemannHypothesis_of_threeElementInteractionAssimilation
#print axioms riemannHypothesis_of_threeElementDifferenceWholeCollapse
#print axioms etaCriticalMirrorThreeElementInteractionAssimilationProvider_iff_riemannHypothesis
#print axioms etaCriticalMirrorThreeElementDifferenceWholeCollapseProvider_iff_riemannHypothesis

end DkMath.RH.CFBRCProjection
