/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.RH.CFBRC.EtaCriticalMirrorPairedFrameConjugationAsymptoticAudit
import Mathlib.Tactic

#print "file: DkMath.RH.CFBRC.EtaCriticalMirrorPairedFrameFunctionalEquationOrbitAsymptoticAudit"

set_option linter.style.longLine false

noncomputable section

namespace DkMath.RH.CFBRCProjection

open Filter
open ComplexConjugate
open scoped Topology

/-- The functional-equation reflection is conjugation after critical reflection. -/
theorem one_sub_eq_conj_criticalMirror
    (s : ℂ) :
    1 - s = conj (criticalMirror s) := by
  apply Complex.ext <;> simp [criticalMirror]

/-- The standard nontrivial-zero predicate is closed under `s ↦ 1 - s`. -/
theorem nontrivialRiemannZetaZero_one_sub
    {s : ℂ} (hs : NontrivialRiemannZetaZero s) :
    NontrivialRiemannZetaZero (1 - s) := by
  rw [one_sub_eq_conj_criticalMirror]
  exact
    nontrivialRiemannZetaZero_conj
      (criticalMirror_nontrivialRiemannZetaZero hs)

/--
The functional-equation reflected normalized rotating endpoint is exactly the
negative conjugate of the original endpoint.
-/
theorem etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_one_sub_eq_neg_conj
    (a : ℝ) (s : ℂ) (k : ℕ) :
    etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
        a (1 - s) k =
      -conj
        (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint a s k) := by
  rw [one_sub_eq_conj_criticalMirror]
  rw [etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_conj]
  rw [etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_criticalMirror_eq_neg]
  simp

/--
The functional-equation reflection transports every rotating endpoint limit
to the negative conjugate limit.
-/
theorem etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_one_sub_tendsto_neg_conj
    {a : ℝ} {s C : ℂ}
    (hendpoint :
      Tendsto
        (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint a s)
        atTop (nhds C)) :
    Tendsto
      (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
        a (1 - s))
      atTop (nhds (-conj C)) := by
  have hconj :
      Tendsto
        (fun k : ℕ =>
          conj
            (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
              a s k))
        atTop (nhds (conj C)) :=
    (Complex.continuous_conj.tendsto C).comp hendpoint
  have hneg :
      Tendsto
        (fun k : ℕ =>
          -conj
            (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
              a s k))
        atTop (nhds (-conj C)) := by
    simpa using hconj.neg
  refine hneg.congr' (Eventually.of_forall fun k => ?_)
  exact
    (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_one_sub_eq_neg_conj
      a s k).symm

/--
Certificate for the complete four-point symmetry orbit generated by critical
reflection and complex conjugation.  The four endpoint limits are
`C`, `-C`, `conj C`, and `-conj C`, so the functional equation transports the
asymptotic instead of producing a competing limit of one sequence.
-/
structure EtaCriticalMirrorEndpointFunctionalEquationOrbitAsymptoticCertificate
    (a : ℝ) (s C : ℂ) : Prop where
  original_endpoint_tendsto :
    Tendsto
      (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint a s)
      atTop (nhds C)
  mirror_endpoint_tendsto :
    Tendsto
      (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
        a (criticalMirror s))
      atTop (nhds (-C))
  conjugate_endpoint_tendsto :
    Tendsto
      (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
        a (conj s))
      atTop (nhds (conj C))
  one_sub_endpoint_tendsto :
    Tendsto
      (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
        a (1 - s))
      atTop (nhds (-conj C))
  exact_mirror :
    ∀ k : ℕ,
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
          a (criticalMirror s) k =
        -etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint a s k
  exact_conjugate :
    ∀ k : ℕ,
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
          a (conj s) k =
        conj
          (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint a s k)
  exact_one_sub :
    ∀ k : ℕ,
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint
          a (1 - s) k =
        -conj
          (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint a s k)

/-- Build the complete functional-equation orbit certificate from one limit. -/
theorem etaCriticalMirrorEndpointFunctionalEquationOrbitAsymptoticCertificate_of_limit
    {a : ℝ} {s C : ℂ}
    (hendpoint :
      Tendsto
        (etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint a s)
        atTop (nhds C)) :
    EtaCriticalMirrorEndpointFunctionalEquationOrbitAsymptoticCertificate
      a s C :=
  { original_endpoint_tendsto := hendpoint
    mirror_endpoint_tendsto :=
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_criticalMirror_tendsto_neg
        hendpoint
    conjugate_endpoint_tendsto :=
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_conj_tendsto
        hendpoint
    one_sub_endpoint_tendsto :=
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_one_sub_tendsto_neg_conj
        hendpoint
    exact_mirror :=
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_criticalMirror_eq_neg
        a s
    exact_conjugate :=
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_conj a s
    exact_one_sub :=
      etaCriticalMirrorIndexNormalizedRotatedEvenDefectEndpoint_one_sub_eq_neg_conj
        a s }

/-- Right-side off-critical endpoint asymptotics form the compatible four-point orbit. -/
theorem etaCriticalMirrorRightEndpointFunctionalEquationOrbitAsymptoticCertificate_of_zero
    {s : ℂ} (hs : NontrivialRiemannZetaZero s)
    (him : s.im ≠ 0) (hre : (1 : ℝ) / 2 < s.re) :
    EtaCriticalMirrorEndpointFunctionalEquationOrbitAsymptoticCertificate
      (criticalMirror s).re s
      (-etaPairIndexNormalizedTailConstant (criticalMirror s)) := by
  apply
    etaCriticalMirrorEndpointFunctionalEquationOrbitAsymptoticCertificate_of_limit
  exact
    (etaCriticalMirrorRightNormalizedEvenDefectEndpointAsymptoticCertificate_of_zero
      hs him hre).rotated_endpoint_tendsto

/-- Left-side off-critical endpoint asymptotics form the compatible four-point orbit. -/
theorem etaCriticalMirrorLeftEndpointFunctionalEquationOrbitAsymptoticCertificate_of_zero
    {s : ℂ} (hs : NontrivialRiemannZetaZero s)
    (him : s.im ≠ 0) (hre : s.re < (1 : ℝ) / 2) :
    EtaCriticalMirrorEndpointFunctionalEquationOrbitAsymptoticCertificate
      s.re s (etaPairIndexNormalizedTailConstant s) := by
  apply
    etaCriticalMirrorEndpointFunctionalEquationOrbitAsymptoticCertificate_of_limit
  simpa only [neg_neg] using
    (etaCriticalMirrorLeftNormalizedEvenDefectEndpointAsymptoticCertificate_of_zero
      hs him hre).rotated_endpoint_tendsto

end DkMath.RH.CFBRCProjection
