/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.CosmicFormula.Rotation.CF2D.KernelPower
import DkMath.CosmicFormula.Rotation.CF2D.Real
import DkMath.Analysis.DkReal.SemanticCF2DPhaseShift

#print "file: DkMath.CosmicFormula.Rotation.CF2D.CycleDivision"

/-!
# Abstract cycle division for CF2D kernel families

This file turns an additive parameter division into finite kernel and action
return.  Its hypotheses keep the three logical layers explicit:

* `k • step = period` is a statement in the additive parameter;
* `F.kernel period = 1` declares that the period has neutral kernel;
* the conclusions are kernel-power and action-iterate return.

No real number, trigonometric function, angle, circle, or polygon is used.
-/

namespace DkMath.CosmicFormula.Rotation.CF2D

namespace KernelFamily

variable {T : Type u} {R : Type v} [AddMonoid T] [CommRing R]

/--
A step whose `k`-fold additive repetition reaches a neutral-kernel period has
neutral `k`th kernel power.

Positivity of `k` is not required at this abstract layer: once the repetition
equation and neutral-period hypothesis are supplied, the conclusion is purely
algebraic.
-/
theorem kernel_pow_eq_one_of_nsmul_eq_period
    (F : KernelFamily T R) {k : ℕ} {step period : T}
    (hstep : k • step = period)
    (hperiod : F.kernel period = 1) :
    (F.kernel step) ^ k = 1 := by
  rw [← F.kernel_nsmul k step, hstep, hperiod]

/--
Finite iteration of a kernel-family action is action by the kernel at the
corresponding natural additive repetition.
-/
theorem iterate_act_eq_act_nsmul
    (F : KernelFamily T R) (n : ℕ) (t : T) (z : Vec R) :
    (UnitKernel.act (F.kernel t))^[n] z =
      UnitKernel.act (F.kernel (n • t)) z := by
  rw [← UnitKernel.pow_act, F.kernel_nsmul]

/--
An abstract cycle division returns every two-component state after `k`
iterations of the one-step action.
-/
theorem iterate_act_eq_id_of_nsmul_eq_period
    (F : KernelFamily T R) {k : ℕ} {step period : T}
    (hstep : k • step = period)
    (hperiod : F.kernel period = 1) :
    (UnitKernel.act (F.kernel step))^[k] = id := by
  funext z
  rw [← UnitKernel.pow_act,
    F.kernel_pow_eq_one_of_nsmul_eq_period hstep hperiod]
  simp

/--
Finite iteration of the induced action on a square-mass level set is the
level-set action at the naturally repeated parameter.
-/
theorem iterate_actLevel_eq_actLevel_nsmul
    (F : KernelFamily T R) (n : ℕ) (t : T) {rho2 : R}
    (z : LevelSet R rho2) :
    (F.actLevel t)^[n] z = F.actLevel (n • t) z := by
  induction n generalizing z with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply, ih, ← F.actLevel_add, succ_nsmul]

/--
The abstract cycle division returns every point of every square-mass level set
after `k` induced action steps.
-/
theorem iterate_actLevel_eq_id_of_nsmul_eq_period
    (F : KernelFamily T R) {k : ℕ} {step period : T}
    (hstep : k • step = period)
    (hperiod : F.kernel period = 1) {rho2 : R} :
    (F.actLevel step : LevelSet R rho2 → LevelSet R rho2)^[k] = id := by
  funext z
  rw [F.iterate_actLevel_eq_actLevel_nsmul, hstep]
  apply Subtype.ext
  simp [actLevel, hperiod]

end KernelFamily

noncomputable section

/-!
## Normalized real cycle bridge

The normalized phase convention uses `1` for one full cycle.  Only in this
bridge is a normalized phase `p` interpreted as the real angle
`p * (2 * Real.pi)`.
-/

/-- Convert a normalized full-cycle phase to its real-angle representative. -/
def normalizedPhaseAngle (p : ℝ) : ℝ :=
  p * (2 * Real.pi)

/--
The real trigonometric kernel family reparameterized by normalized full-cycle
phase.  Its additive law is inherited from `realTrigKernelFamily`.
-/
def normalizedRealKernelFamily : KernelFamily ℝ ℝ where
  kernel p := realTrigKernelFamily.kernel (normalizedPhaseAngle p)
  map_zero := by
    simpa [normalizedPhaseAngle] using realTrigKernelFamily.map_zero
  map_add := by
    intro p q
    simpa [normalizedPhaseAngle, add_mul] using
      realTrigKernelFamily.map_add
        (p * (2 * Real.pi)) (q * (2 * Real.pi))

/-- One normalized phase step in a positive `k`-division of the full cycle. -/
def regularPhaseStep (k : ℕ) : ℝ :=
  DkMath.Analysis.DkNNRealQ.normalizedCycleStep k

/-- The real unit kernel generated by one normalized `k`-division step. -/
def regularKernel (k : ℕ) : UnitKernel ℝ :=
  normalizedRealKernelFamily.kernel (regularPhaseStep k)

/-- One normalized full cycle has the neutral real unit kernel. -/
@[simp]
theorem normalizedRealKernelFamily_kernel_one :
    normalizedRealKernelFamily.kernel 1 = 1 := by
  apply UnitKernel.ext
  simp [normalizedRealKernelFamily, normalizedPhaseAngle, UnitKernel.one,
    Vec.one, Real.cos_two_pi, Real.sin_two_pi]

/-- A positive normalized `k`-division reaches phase `1` after `k` additions. -/
theorem regularPhaseStep_nsmul_eq_one {k : ℕ} (hk : 0 < k) :
    k • regularPhaseStep k = (1 : ℝ) := by
  simpa [regularPhaseStep, nsmul_eq_mul] using
    DkMath.Analysis.DkNNRealQ.normalizedCycleStep_mul_returnCount hk

/--
A positive normalized `k`-division kernel returns to the neutral kernel after
exactly `k` products as a return statement (without a minimality claim).

The proof explicitly transports the existing scalar equation
`k * normalizedCycleStep k = 1` through `KernelFamily.kernel_nsmul`.
-/
theorem regularKernel_pow_eq_one {k : ℕ} (hk : 0 < k) :
    regularKernel k ^ k = 1 := by
  rw [regularKernel, ← normalizedRealKernelFamily.kernel_nsmul k,
    regularPhaseStep_nsmul_eq_one hk,
    normalizedRealKernelFamily_kernel_one]

/-- Every real two-component state returns after `k` regular-kernel actions. -/
theorem regularKernel_iterate_act_eq_id {k : ℕ} (hk : 0 < k) :
    (UnitKernel.act (regularKernel k))^[k] = id := by
  funext z
  rw [← UnitKernel.pow_act, regularKernel_pow_eq_one hk]
  simp

/--
Every point on every real square-mass level set returns after `k`
regular-kernel actions.
-/
theorem regularKernel_iterate_actLevel_eq_id {k : ℕ} (hk : 0 < k)
    {rho2 : ℝ} :
    (LevelSet.act (regularKernel k) : LevelSet ℝ rho2 → LevelSet ℝ rho2)^[k]
      = id := by
  simpa [regularKernel, KernelFamily.actLevel] using
    (normalizedRealKernelFamily.iterate_actLevel_eq_id_of_nsmul_eq_period
      (regularPhaseStep_nsmul_eq_one hk)
      normalizedRealKernelFamily_kernel_one (rho2 := rho2))

end

section InterfaceChecks

#check KernelFamily.kernel_pow_eq_one_of_nsmul_eq_period
#check KernelFamily.iterate_act_eq_id_of_nsmul_eq_period
#check KernelFamily.iterate_actLevel_eq_id_of_nsmul_eq_period
#check normalizedRealKernelFamily
#check regularKernel
#check regularPhaseStep_nsmul_eq_one
#check regularKernel_pow_eq_one
#check regularKernel_iterate_act_eq_id
#check regularKernel_iterate_actLevel_eq_id

end InterfaceChecks

end DkMath.CosmicFormula.Rotation.CF2D
