/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.CosmicFormula.Rotation.CF2D.CycleDivision

#print "file: DkMath.CosmicFormula.Rotation.CF2D.RegularOrbit"

/-!
# Finite CF2D kernel orbits before polygon geometry

This module packages the states generated by repeatedly applying one unit
kernel.  The resulting structure consists only of a conserved `q2` boundary,
a successor action, periodic return, and distinct states before first return.

No edge, convex hull, angle measure, circle, or regular polygon is part of the
definition.
-/

namespace DkMath.CosmicFormula.Rotation.CF2D

/-- The `j`th state generated by a unit kernel from a base state. -/
def kernelOrbitVertex {R : Type u} [CommRing R]
    (r : UnitKernel R) (z : Vec R) (j : ℕ) : Vec R :=
  UnitKernel.act (r ^ j) z

/-- Every state in a unit-kernel orbit remains on the base state's `q2` level. -/
@[simp]
theorem kernelOrbitVertex_q2 {R : Type u} [CommRing R]
    (r : UnitKernel R) (z : Vec R) (j : ℕ) :
    Vec.q2 (kernelOrbitVertex r z j) = Vec.q2 z :=
  UnitKernel.q2_act (r ^ j) z

/-- One more orbit index is one more action by the generating kernel. -/
theorem kernelOrbitVertex_succ {R : Type u} [CommRing R]
    (r : UnitKernel R) (z : Vec R) (j : ℕ) :
    kernelOrbitVertex r z (j + 1) =
      UnitKernel.act r (kernelOrbitVertex r z j) := by
  rw [kernelOrbitVertex, kernelOrbitVertex, pow_succ', UnitKernel.mul_eq_star,
    UnitKernel.act_star]

/-- A neutral `k`th kernel power makes every generated orbit `k`-periodic. -/
theorem kernelOrbitVertex_add_period {R : Type u} [CommRing R]
    (r : UnitKernel R) (z : Vec R) {k : ℕ} (hperiod : r ^ k = 1)
    (j : ℕ) :
    kernelOrbitVertex r z (j + k) = kernelOrbitVertex r z j := by
  rw [kernelOrbitVertex, kernelOrbitVertex, pow_add, hperiod, mul_one]

namespace UnitKernel

/--
The neutral base vector is faithful for unit kernels: acting on `(1,0)`
recovers the underlying kernel vector.
-/
@[simp]
theorem act_vecOne {R : Type u} [CommRing R] (r : UnitKernel R) :
    act r (Vec.one R) = (r : Vec R) := by
  exact Vec.star_one (r : Vec R)

end UnitKernel

/--
At the faithful neutral base, exact order `k` makes the first `k` orbit states
pairwise distinct.
-/
theorem kernelOrbitVertex_vecOne_injective {R : Type u} [CommRing R]
    {r : UnitKernel R} {k : ℕ} (hk : 0 < k)
    (horder : ExactKernelOrder r k) :
    Function.Injective
      (fun j : Fin k ↦ kernelOrbitVertex r (Vec.one R) j.val) := by
  intro i j hij
  have hpowers : r ^ i.val = r ^ j.val := by
    apply UnitKernel.ext
    simpa [kernelOrbitVertex] using hij
  have hord : orderOf r = k :=
    (exactKernelOrder_iff_orderOf_eq hk).1 horder
  have hi : i.val < orderOf r := by rw [hord]; exact i.isLt
  have hj : j.val < orderOf r := by rw [hord]; exact j.isLt
  exact Fin.ext (pow_injOn_Iio_orderOf hi hj hpowers)

noncomputable section

/-- The finite real orbit generated by one positive regular division kernel. -/
def regularVertex (k : ℕ) (j : Fin k) : Vec ℝ :=
  kernelOrbitVertex (regularKernel k) (Vec.one ℝ) j.val

/-- Every regular finite-orbit state has square mass one. -/
@[simp]
theorem regularVertex_q2 (k : ℕ) (j : Fin k) :
    Vec.q2 (regularVertex k j) = 1 := by
  rw [regularVertex, kernelOrbitVertex_q2]
  norm_num [Vec.q2, Vec.one]

/-- Successive non-wrapping finite indices differ by one regular-kernel action. -/
theorem regularVertex_succ {k : ℕ} (j : Fin k)
    (hj : j.val + 1 < k) :
    regularVertex k ⟨j.val + 1, hj⟩ =
      UnitKernel.act (regularKernel k) (regularVertex k j) := by
  exact kernelOrbitVertex_succ (regularKernel k) (Vec.one ℝ) j.val

/-- Cyclic successor on the positive finite regular-orbit index set. -/
def regularVertexNext {k : ℕ} (hk : 0 < k) (j : Fin k) : Fin k :=
  ⟨(j.val + 1) % k, Nat.mod_lt _ hk⟩

/--
The cyclic successor, including the wrap from the last index to zero, is one
more action by the regular kernel.
-/
theorem regularVertex_next {k : ℕ} (hk : 0 < k) (j : Fin k) :
    regularVertex k (regularVertexNext hk j) =
      UnitKernel.act (regularKernel k) (regularVertex k j) := by
  change
    kernelOrbitVertex (regularKernel k) (Vec.one ℝ) ((j.val + 1) % k) =
      UnitKernel.act (regularKernel k)
        (kernelOrbitVertex (regularKernel k) (Vec.one ℝ) j.val)
  rw [← kernelOrbitVertex_succ]
  unfold kernelOrbitVertex
  simp only [UnitKernel.act_vecOne]
  apply congrArg (fun r : UnitKernel ℝ ↦ (r : Vec ℝ))
  simpa only [orderOf_regularKernel hk] using
    (pow_mod_orderOf (regularKernel k) (j.val + 1))

/-- The natural-number regular orbit is periodic after `k` steps. -/
theorem regularKernelOrbit_add_period {k : ℕ} (hk : 0 < k) (j : ℕ) :
    kernelOrbitVertex (regularKernel k) (Vec.one ℝ) (j + k) =
      kernelOrbitVertex (regularKernel k) (Vec.one ℝ) j :=
  kernelOrbitVertex_add_period (regularKernel k) (Vec.one ℝ)
    (regularKernel_pow_eq_one hk) j

/-- The `Fin k` regular orbit contains no repeated state for positive `k`. -/
theorem regularVertex_injective {k : ℕ} (hk : 0 < k) :
    Function.Injective (regularVertex k) := by
  exact kernelOrbitVertex_vecOne_injective hk (regularKernel_exactOrder hk)

/-- The range of the positive finite regular orbit has exactly `k` states. -/
theorem regularVertex_ncard_range {k : ℕ} (hk : 0 < k) :
    (Set.range (regularVertex k)).ncard = k := by
  rw [Set.ncard_range_of_injective (regularVertex_injective hk), Nat.card_fin]

end

section InterfaceChecks

#check kernelOrbitVertex
#check kernelOrbitVertex_q2
#check kernelOrbitVertex_succ
#check kernelOrbitVertex_add_period
#check regularVertex
#check regularVertex_q2
#check regularVertex_next
#check regularVertex_injective
#check regularVertex_ncard_range

end InterfaceChecks

end DkMath.CosmicFormula.Rotation.CF2D
