/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.Analysis.DkReal.PowBound
import DkMath.Analysis.DkReal.Arithmetic

#print "file: DkMath.Analysis.DkReal.Equiv"

/-!
# Representation equivalence for DkReal

Two `DkReal` approximations are equivalent when the separation between their
stagewise rational intervals tends to zero.

This relation compares represented values rather than the raw Lean structures.
It remains in the computable approximation layer: no evaluation into
Mathlib's `Real` and no choice of a limit point is used.

The transitivity proof is a vanishing-width version of the triangle inequality:

`sep(I,K) ≤ sep(I,J) + width(J) + sep(J,K)`.

Consequently, shrinking uncertainty converts interval separation into an
extensional equivalence relation on representations.

[TODO: totality/overlap] Prove that `Equiv x y` is equivalent to stagewise
overlap of the two nested interval sequences. The forward direction should use
monotonicity of interval separation under refinement: once a positive
separation appears, nestedness prevents it from returning to zero. The reverse
direction is immediate because every stage separation is zero.

[IMPLEMENTED: semantic-forward] `DkReal.semanticValue_eq_of_equiv` proves
`Equiv x y → semanticValue x = semanticValue y`.

[TODO: semantic-reflection] Prove the converse when needed. This is the
representation-level equality-reflection problem and should remain separate
from the computable definition of `Equiv`.
-/

namespace DkMath.Analysis.DkReal

/--
Two `DkReal` approximations represent the same value when their interval
separation vanishes. This is the extensional equality used by quotient
constructions in the nonnegative Route B layer.

In the proposed internal totality proof, this is the Merge branch: if neither
interval universe ever becomes strictly left-separated from the other, the
two nested interval sequences overlap at every precision and collapse to one
quotient Core.
-/
def Equiv (x y : DkMath.Analysis.DkReal) : Prop :=
  Filter.Tendsto
    (fun n => (x.interval n).separation (y.interval n))
    Filter.atTop (nhds 0)

/-- Every approximation is equivalent to itself. -/
theorem equiv_refl (x : DkMath.Analysis.DkReal) : Equiv x x := by
  simp [Equiv]

/-- Representation equivalence is symmetric. -/
theorem equiv_symm
    {x y : DkMath.Analysis.DkReal} (hxy : Equiv x y) :
    Equiv y x := by
  simpa only [Equiv, GapInterval.separation_comm] using hxy

/--
Representation equivalence is transitive.

The width of the middle approximation tends to zero, so the interval
separation triangle estimate becomes an ordinary zero-limit argument.
-/
theorem equiv_trans
    {x y z : DkMath.Analysis.DkReal} (hxy : Equiv x y) (hyz : Equiv y z) :
    Equiv x z := by
  have hupper :
      Filter.Tendsto
        (fun n =>
          (x.interval n).separation (y.interval n) +
            (y.interval n).width +
            (y.interval n).separation (z.interval n))
        Filter.atTop (nhds 0) := by
    simpa only [zero_add, add_zero] using
      (hxy.add y.tendsto_width_zero).add hyz
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le
    tendsto_const_nhds hupper
    (fun n => (x.interval n).separation_nonneg (z.interval n))
    (fun n =>
      (x.interval n).separation_triangle (y.interval n) (z.interval n))

/-- `Equiv` is an equivalence relation on `DkReal` representations. -/
theorem equiv_equivalence : Equivalence Equiv :=
  ⟨equiv_refl, @equiv_symm, @equiv_trans⟩

/-- Setoid generated by vanishing interval separation. -/
def equivSetoid : Setoid DkMath.Analysis.DkReal where
  r := Equiv
  iseqv := equiv_equivalence

/-- Raw equality of approximation structures implies representation equivalence. -/
theorem equiv_of_eq
    {x y : DkMath.Analysis.DkReal} (hxy : x = y) :
    Equiv x y := by
  subst y
  exact equiv_refl x

/-- Pointwise equality of approximation intervals implies representation equivalence. -/
theorem equiv_of_interval_eq
    {x y : DkMath.Analysis.DkReal}
    (hxy : ∀ n, x.interval n = y.interval n) :
    Equiv x y := by
  simp only [Equiv, hxy, GapInterval.separation_self]
  exact tendsto_const_nhds

/-!
## Compatibility with addition

Addition is nonexpansive for interval separation up to summing the two input
separations. Therefore it descends to the quotient constructions defined later
in this package.
-/

/-- Addition preserves representation equivalence in both arguments. -/
theorem equiv_add
    {x x' y y' : DkMath.Analysis.DkReal}
    (hxx' : Equiv x x') (hyy' : Equiv y y') :
    Equiv (add x y) (add x' y') := by
  have hupper :
      Filter.Tendsto
        (fun n =>
          (x.interval n).separation (x'.interval n) +
            (y.interval n).separation (y'.interval n))
        Filter.atTop (nhds 0) := by
    simpa only [zero_add] using hxx'.add hyy'
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le
    tendsto_const_nhds hupper
    (fun n => (add x y).interval n |>.separation_nonneg ((add x' y').interval n))
    (fun n => by
      simpa only [add_interval, addApprox] using
        (x.interval n).separation_add_le
          (y.interval n) (x'.interval n) (y'.interval n))

/-- Addition preserves representation equivalence in the left argument. -/
theorem equiv_add_left
    {x x' : DkMath.Analysis.DkReal} (hxx' : Equiv x x')
    (y : DkMath.Analysis.DkReal) :
    Equiv (add x y) (add x' y) :=
  equiv_add hxx' (equiv_refl y)

/-- Addition preserves representation equivalence in the right argument. -/
theorem equiv_add_right
    (x : DkMath.Analysis.DkReal) {y y' : DkMath.Analysis.DkReal}
    (hyy' : Equiv y y') :
    Equiv (add x y) (add x y') :=
  equiv_add (equiv_refl x) hyy'

/-!
## Endpoint consequences

Vanishing interval separation, together with the vanishing widths of both
representations, forces corresponding rational endpoints to approach one
another.
-/

/-- Equivalent representations have vanishing absolute lower-endpoint difference. -/
theorem equiv_tendsto_abs_lo_sub_zero
    {x y : DkMath.Analysis.DkReal} (hxy : Equiv x y) :
    Filter.Tendsto
      (fun n => |(x.interval n).lo - (y.interval n).lo|)
      Filter.atTop (nhds 0) := by
  have hupper :
      Filter.Tendsto
        (fun n =>
          (x.interval n).separation (y.interval n) +
            (x.interval n).width + (y.interval n).width)
        Filter.atTop (nhds 0) := by
    simpa only [zero_add, add_zero] using
      (hxy.add x.tendsto_width_zero).add y.tendsto_width_zero
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le
    tendsto_const_nhds hupper
    (fun n => abs_nonneg _)
    (fun n => (x.interval n).abs_lo_sub_lo_le (y.interval n))

/-- Equivalent representations have lower-endpoint difference tending to zero. -/
theorem equiv_tendsto_lo_sub_zero
    {x y : DkMath.Analysis.DkReal} (hxy : Equiv x y) :
    Filter.Tendsto
      (fun n => (x.interval n).lo - (y.interval n).lo)
      Filter.atTop (nhds 0) := by
  have habs := equiv_tendsto_abs_lo_sub_zero hxy
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le
    (by simpa using habs.neg) habs
    (fun n => neg_abs_le ((x.interval n).lo - (y.interval n).lo))
    (fun n => le_abs_self ((x.interval n).lo - (y.interval n).lo))

/-!
## Compatibility with nonnegative multiplication

Lower endpoints of nonnegative `DkReal` approximations are bounded. Combining
this boundedness with vanishing endpoint differences proves that the lower
endpoints of equivalent products approach one another. Interval separation is
then bounded by that lower-endpoint distance.
-/

/-- Nonnegative multiplication preserves representation equivalence. -/
theorem equiv_mulNonneg
    {x x' y y' : DkMath.Analysis.DkReal}
    (hx : Nonnegative x) (hx' : Nonnegative x')
    (hy : Nonnegative y) (hy' : Nonnegative y')
    (hxx' : Equiv x x') (hyy' : Equiv y y') :
    Equiv
      (mulNonneg x y hx hy)
      (mulNonneg x' y' hx' hy') := by
  have hylo := equiv_tendsto_lo_sub_zero hyy'
  have hxlo := equiv_tendsto_lo_sub_zero hxx'
  have hleft :
      Filter.Tendsto
        (fun n =>
          (x.interval n).lo *
            ((y.interval n).lo - (y'.interval n).lo))
        Filter.atTop (nhds 0) := by
    simpa only [mul_comm] using
      hylo.zero_mul_isBoundedUnder_le (isBoundedUnder_norm_lo x hx)
  have hright :
      Filter.Tendsto
        (fun n =>
          (y'.interval n).lo *
            ((x.interval n).lo - (x'.interval n).lo))
        Filter.atTop (nhds 0) := by
    simpa only [mul_comm] using
      hxlo.zero_mul_isBoundedUnder_le (isBoundedUnder_norm_lo y' hy')
  have hproductLo :
      Filter.Tendsto
        (fun n =>
          (x.interval n).lo * (y.interval n).lo -
            (x'.interval n).lo * (y'.interval n).lo)
        Filter.atTop (nhds 0) := by
    convert hleft.add hright using 1
    · funext n
      dsimp
      ring
    · simp
  have hproductAbs :
      Filter.Tendsto
        (fun n =>
          |(x.interval n).lo * (y.interval n).lo -
            (x'.interval n).lo * (y'.interval n).lo|)
        Filter.atTop (nhds 0) := by
    simpa using hproductLo.abs
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le
    tendsto_const_nhds hproductAbs
    (fun n =>
      ((mulNonneg x y hx hy).interval n).separation_nonneg
        ((mulNonneg x' y' hx' hy').interval n))
    (fun n => by
      simpa only [mulNonneg_interval, mulNonnegApprox,
        GapInterval.mulNonneg_lo] using
        ((x.interval n).mulNonneg (y.interval n) (hx n) (hy n)).separation_le_abs_lo_sub_lo
          ((x'.interval n).mulNonneg (y'.interval n) (hx' n) (hy' n)))

/-- Nonnegative multiplication preserves equivalence in the left argument. -/
theorem equiv_mulNonneg_left
    {x x' : DkMath.Analysis.DkReal}
    (hx : Nonnegative x) (hx' : Nonnegative x')
    (hxx' : Equiv x x')
    (y : DkMath.Analysis.DkReal) (hy : Nonnegative y) :
    Equiv (mulNonneg x y hx hy) (mulNonneg x' y hx' hy) :=
  equiv_mulNonneg hx hx' hy hy hxx' (equiv_refl y)

/-- Nonnegative multiplication preserves equivalence in the right argument. -/
theorem equiv_mulNonneg_right
    (x : DkMath.Analysis.DkReal) (hx : Nonnegative x)
    {y y' : DkMath.Analysis.DkReal}
    (hy : Nonnegative y) (hy' : Nonnegative y')
    (hyy' : Equiv y y') :
    Equiv (mulNonneg x y hx hy) (mulNonneg x y' hx hy') :=
  equiv_mulNonneg hx hx hy hy' (equiv_refl x) hyy'

/-!
## Compatibility with natural powers

Natural power congruence is obtained from multiplicative congruence by
induction on the exponent. This avoids introducing a signed increment into
`gapGN`: successor powers are stagewise the product of the preceding power and
the original approximation.
-/

/--
The successor power agrees stagewise with multiplying the preceding power by
the original nonnegative approximation.
-/
theorem powNonneg_succ_interval
    (d : ℕ) (x : DkMath.Analysis.DkReal) (hx : Nonnegative x) (n : ℕ) :
    (powNonneg (d + 1) x hx).interval n
      =
    (mulNonneg (powNonneg d x hx) x
        (nonnegative_powNonneg d hx) hx).interval n := by
  apply GapInterval.ext <;>
    simp [powNonneg, powNonnegApprox, mulNonneg, mulNonnegApprox, pow_succ]

/-- Natural powers preserve representation equivalence on the nonnegative domain. -/
theorem equiv_powNonneg
    (d : ℕ) {x x' : DkMath.Analysis.DkReal}
    (hx : Nonnegative x) (hx' : Nonnegative x')
    (hxx' : Equiv x x') :
    Equiv (powNonneg d x hx) (powNonneg d x' hx') := by
  induction d with
  | zero =>
      apply equiv_of_interval_eq
      intro n
      rw [powNonneg_zero_interval, powNonneg_zero_interval]
  | succ d ih =>
      have hmul :
          Equiv
            (mulNonneg (powNonneg d x hx) x
              (nonnegative_powNonneg d hx) hx)
            (mulNonneg (powNonneg d x' hx') x'
              (nonnegative_powNonneg d hx') hx') :=
        equiv_mulNonneg
          (nonnegative_powNonneg d hx) (nonnegative_powNonneg d hx')
          hx hx' ih hxx'
      have hleft :
          Equiv
            (powNonneg (d + 1) x hx)
            (mulNonneg (powNonneg d x hx) x
              (nonnegative_powNonneg d hx) hx) :=
        equiv_of_interval_eq (powNonneg_succ_interval d x hx)
      have hright :
          Equiv
            (mulNonneg (powNonneg d x' hx') x'
              (nonnegative_powNonneg d hx') hx')
            (powNonneg (d + 1) x' hx') :=
        equiv_symm (equiv_of_interval_eq (powNonneg_succ_interval d x' hx'))
      exact equiv_trans (equiv_trans hleft hmul) hright

end DkMath.Analysis.DkReal
