/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.Analysis.DkReal.Arithmetic

#print "file: DkMath.Analysis.DkReal.Equiv"

/-!
# Representation equivalence for DkReal

Two `DkReal` approximations are equivalent when the separation between their
stagewise rational intervals tends to zero.

This relation compares represented values rather than the raw Lean structures.
It remains in the computable approximation layer: no evaluation into
Mathlib's `Real` and no choice of a limit point is used.
-/

namespace DkMath.Analysis.DkReal

/--
Two `DkReal` approximations represent the same value when their interval
separation vanishes.
-/
def Equiv (x y : DkMath.Analysis.DkReal) : Prop :=
  Filter.Tendsto
    (fun n => (x.interval n).separation (y.interval n))
    Filter.atTop (nhds 0)

/-- Every approximation is equivalent to itself. -/
theorem equiv_refl (x : DkMath.Analysis.DkReal) : Equiv x x := by
  simp [Equiv]

/-- Representation equivalence is symmetric. -/
theorem equiv_symm
    {x y : DkMath.Analysis.DkReal} (hxy : Equiv x y) :
    Equiv y x := by
  simpa only [Equiv, GapInterval.separation_comm] using hxy

/--
Representation equivalence is transitive.

The width of the middle approximation tends to zero, so the interval
separation triangle estimate becomes an ordinary zero-limit argument.
-/
theorem equiv_trans
    {x y z : DkMath.Analysis.DkReal} (hxy : Equiv x y) (hyz : Equiv y z) :
    Equiv x z := by
  have hupper :
      Filter.Tendsto
        (fun n =>
          (x.interval n).separation (y.interval n) +
            (y.interval n).width +
            (y.interval n).separation (z.interval n))
        Filter.atTop (nhds 0) := by
    simpa only [zero_add, add_zero] using
      (hxy.add y.tendsto_width_zero).add hyz
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le
    tendsto_const_nhds hupper
    (fun n => (x.interval n).separation_nonneg (z.interval n))
    (fun n =>
      (x.interval n).separation_triangle (y.interval n) (z.interval n))

/-- `Equiv` is an equivalence relation on `DkReal` representations. -/
theorem equiv_equivalence : Equivalence Equiv :=
  ⟨equiv_refl, @equiv_symm, @equiv_trans⟩

/-- Setoid generated by vanishing interval separation. -/
def equivSetoid : Setoid DkMath.Analysis.DkReal where
  r := Equiv
  iseqv := equiv_equivalence

/-- Raw equality of approximation structures implies representation equivalence. -/
theorem equiv_of_eq
    {x y : DkMath.Analysis.DkReal} (hxy : x = y) :
    Equiv x y := by
  subst y
  exact equiv_refl x

/-!
## Compatibility with addition

Addition is nonexpansive for interval separation up to summing the two input
separations. Therefore it descends to any future quotient by `Equiv`.
-/

/-- Addition preserves representation equivalence in both arguments. -/
theorem equiv_add
    {x x' y y' : DkMath.Analysis.DkReal}
    (hxx' : Equiv x x') (hyy' : Equiv y y') :
    Equiv (add x y) (add x' y') := by
  have hupper :
      Filter.Tendsto
        (fun n =>
          (x.interval n).separation (x'.interval n) +
            (y.interval n).separation (y'.interval n))
        Filter.atTop (nhds 0) := by
    simpa only [zero_add] using hxx'.add hyy'
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le
    tendsto_const_nhds hupper
    (fun n => (add x y).interval n |>.separation_nonneg ((add x' y').interval n))
    (fun n => by
      simpa only [add_interval, addApprox] using
        (x.interval n).separation_add_le
          (y.interval n) (x'.interval n) (y'.interval n))

/-- Addition preserves representation equivalence in the left argument. -/
theorem equiv_add_left
    {x x' : DkMath.Analysis.DkReal} (hxx' : Equiv x x')
    (y : DkMath.Analysis.DkReal) :
    Equiv (add x y) (add x' y) :=
  equiv_add hxx' (equiv_refl y)

/-- Addition preserves representation equivalence in the right argument. -/
theorem equiv_add_right
    (x : DkMath.Analysis.DkReal) {y y' : DkMath.Analysis.DkReal}
    (hyy' : Equiv y y') :
    Equiv (add x y) (add x y') :=
  equiv_add (equiv_refl x) hyy'

end DkMath.Analysis.DkReal
