/-
Copyright (c) 2026 D. and Wise Wolf. All rights reserved.
Released under MIT license as described in the file LICENSE.
Authors: D. and Wise Wolf.
-/

import DkMath.NumberTheory.GapFocusing.Successor
import DkMath.NumberTheory.GapFocusing.Degree
import Mathlib.RingTheory.Ideal.Quotient.Operations

#print "file: DkMath.NumberTheory.GapFocusing.PolynomialSuccessor"

/-!
# Adjacent focused polynomials and their quotient rings

At anchor one the successor identity gives an explicit Bézout relation over
any commutative coefficient ring. Over `ℤ`, the nontrivial divisor-index
sets are disjoint. Their ideals are comaximal and give a ring CRT, distinct
from a CRT for power subgroups of a unit group.
-/

namespace DkMath.NumberTheory.GapFocusing

open DkMath.CosmicFormula Polynomial

/-- Adjacent focused polynomials generate the unit ideal over any coefficient ring. -/
theorem GN_polynomial_succ_isCoprime {R : Type*} [CommRing R] (d : ℕ) :
    IsCoprime (GTail d 1 (X : R[X]) 1) (GTail (d + 1) 1 (X : R[X]) 1) :=
  GN_succ_isCoprime_unit_anchor d X

/-- An explicit integral polynomial Bézout identity, including degree zero. -/
theorem kernelPolynomial_succ_bezout (d : ℕ) :
    kernelPolynomial (d + 1) - (X + 1) * kernelPolynomial d = 1 :=
  GN_succ_bezout d X

/-- The integral polynomial relation is stronger than absence of common factors. -/
theorem kernelPolynomial_succ_isCoprime (d : ℕ) :
    IsCoprime (kernelPolynomial d) (kernelPolynomial (d + 1)) :=
  GN_polynomial_succ_isCoprime d

/-- Explicit interpolation between residues of two adjacent kernels. -/
theorem kernelPolynomial_successor_interpolation (d : ℕ) (A B : ℤ[X]) :
    let P := A * kernelPolynomial (d + 1) - B * (X + 1) * kernelPolynomial d
    kernelPolynomial d ∣ P - A ∧ kernelPolynomial (d + 1) ∣ P - B := by
  dsimp only
  have hnext : kernelPolynomial (d + 1) = (X + 1) * kernelPolynomial d + 1 :=
    GN_succ_unit_anchor d X
  constructor
  · refine ⟨(X + 1) * (A - B), ?_⟩
    rw [hnext]
    ring
  · refine ⟨A - B, ?_⟩
    rw [hnext]
    ring

/-- No nontrivial cyclotomic index persists between adjacent degree worlds. -/
theorem successor_divisor_layers_disjoint (d : ℕ) :
    Disjoint (d.divisors.erase 1) ((d + 1).divisors.erase 1) := by
  apply Finset.disjoint_left.mpr
  intro k hk hks
  have hkd : k ∣ d := (Nat.mem_divisors.mp (Finset.mem_erase.mp hk).2).1
  have hkds : k ∣ d + 1 := (Nat.mem_divisors.mp (Finset.mem_erase.mp hks).2).1
  have hcop : Nat.Coprime d (d + 1) := by
    rw [Nat.coprime_self_add_right]
    exact Nat.coprime_one_right d
  have hkone : k = 1 := Nat.eq_one_of_dvd_coprimes hcop hkd hkds
  exact (Finset.mem_erase.mp hk).1 hkone

/-- Adjacent root equations share only the trivial phase, in any monoid. -/
theorem eq_one_of_adjacent_pow_eq_one {M : Type*} [Monoid M] (d : ℕ) (zeta : M)
    (hd : zeta ^ d = 1) (hnext : zeta ^ (d + 1) = 1) : zeta = 1 := by
  simpa only [pow_succ, hd, one_mul] using hnext

open Classical in
/-- Adjacent positive degrees have no common nontrivial phase in a domain. -/
theorem successor_nontrivial_roots_disjoint {R : Type*} [CommRing R] [IsDomain R]
    {d : ℕ} (hd : 0 < d) :
    Disjoint ((nthRootsFinset d (1 : R)).erase 1)
      ((nthRootsFinset (d + 1) (1 : R)).erase 1) := by
  classical
  apply Finset.disjoint_left.mpr
  intro zeta hz hzs
  have hzpow := (mem_nthRootsFinset hd (1 : R)).mp (Finset.mem_erase.mp hz).2
  have hzspow := (mem_nthRootsFinset (by omega : 0 < d + 1) (1 : R)).mp
    (Finset.mem_erase.mp hzs).2
  exact (Finset.mem_erase.mp hz).1 (eq_one_of_adjacent_pow_eq_one d zeta hzpow hzspow)

/-- Every common divisor of adjacent integral kernels is a polynomial unit. -/
theorem kernelPolynomial_common_divisor_isUnit {d : ℕ} {q : ℤ[X]}
    (hleft : q ∣ kernelPolynomial d) (hright : q ∣ kernelPolynomial (d + 1)) :
    IsUnit q :=
  (kernelPolynomial_succ_isCoprime d).isUnit_of_dvd' hleft hright

/-- The ideal generated by one focused integral polynomial. -/
noncomputable def kernelIdeal (d : ℕ) : Ideal ℤ[X] :=
  Ideal.span {kernelPolynomial d}

/-- The explicit Bézout identity gives comaximal adjacent kernel ideals. -/
theorem kernelIdeal_succ_isCoprime (d : ℕ) :
    IsCoprime (kernelIdeal d) (kernelIdeal (d + 1)) := by
  exact (Ideal.isCoprime_span_singleton_iff _ _).mpr (kernelPolynomial_succ_isCoprime d)

/-- Ring CRT for the product of adjacent focused-kernel ideals. It is a
quotient-ring decomposition, not a unit-power-class identification. -/
noncomputable def kernelQuotientSuccessorCRT (d : ℕ) :
    ℤ[X] ⧸ (kernelIdeal d * kernelIdeal (d + 1)) ≃+*
      (ℤ[X] ⧸ kernelIdeal d) × (ℤ[X] ⧸ kernelIdeal (d + 1)) :=
  Ideal.quotientMulEquivQuotientProd _ _ (kernelIdeal_succ_isCoprime d)

/-- The ring CRT sends a polynomial to its two residue classes. -/
theorem kernelQuotientSuccessorCRT_mk (d : ℕ) (P : ℤ[X]) :
    kernelQuotientSuccessorCRT d
      (Ideal.Quotient.mk (kernelIdeal d * kernelIdeal (d + 1)) P) =
        (Ideal.Quotient.mk (kernelIdeal d) P, Ideal.Quotient.mk (kernelIdeal (d + 1)) P) := by
  apply Prod.ext <;> simp [kernelQuotientSuccessorCRT]

end DkMath.NumberTheory.GapFocusing
